doocs/leetcode

solution/035.Search Insertion Location/README.md
solution/035.Search Insertion Location/Solution.java

Add solution 035.Search Insertion Location in Java

---

solution/021.Merge Two Sorted Lists/Solution.rb

Extra busy these days, just making slow progress.

Solution in Ruby 021

---

solution/001.Two Sum/Solution.cpp
solution/019.Remove Nth Node From End of List/Solution.cpp
solution/059.Spiral Matrix II/Solution.cpp
solution/122.Best Time to Buy and Sell Stock II/Solution.cpp
solution/581.Shortest Unsorted Continuous Subarray/Solution.cpp

add 122 cpp version(4ms)

---

solution/172.Factorial Trailing Zeroes/Solution.cpp
solution/190.Reverse Bits/Solution.cpp
solution/434.Number of Segments in a String/Solution.cpp

add 172 folder & cpp, add 190 folder & cpp, add 434 folder & cpp

---

solution/025.Reverse Nodes in k-Group/README.md
solution/025.Reverse Nodes in k-Group/Solution.java

Add Solution 025[Java]

---

solution/013.Roman to Integer/Solution2.py

Create solution2.py to 013.Roman to Integer, 80ms

---

solution/020.Valid Parentheses/README.md

Update solution 020 [README.md]

---

solution/002.Add Two Numbers/README.md
solution/002.Add Two Numbers/Solution.cpp
solution/033.Search in Rotated Sorted Array/README.md
solution/033.Search in Rotated Sorted Array/Solution.cpp

daily code

---

solution/318.Maximum Product of Word Lengths/Solution.cpp
solution/427.Construct Quad Tree/Solution.cpp

add 318 folder & cpp, add 427 folder & cpp

add 318 folder & cpp, add 427 folder & cpp

---

solution/035.Search Insert Position/README.md
solution/035.Search Insert Position/Solution.cpp

Add Solution 035[CPP]

---

solution/029.Divide Two Integers/README.md
solution/030.Substring with Concatenation of All Words/README.md
solution/030.Substring with Concatenation of All Words/Solution.java

Correct my error in Readme.md for 029, and Add Solution and Readme.md for 30[Java]

Add Solution and Readme.md for 30[Java]

---

solution/088.Merge Sorted Array/Solution.js
solution/204.Count Primes/Solution.js
solution/278.First Bad Version/Solution.js

add javaScript solutions

---

solution/056.Merge Intervals/README.md
solution/056.Merge Intervals/Solution.cpp

Create Solution 056[CPP]

---

solution/011.Container With Most Water/Solution.java

011.Container With Most Water (java)

---

solution/066.Plus One/README.md
solution/066.Plus One/Solution.cpp
solution/073.Set Matrix Zeroes/README.md
solution/073.Set Matrix Zeroes/Solution.cpp

Add Solution 066&&073 CPP

---

solution/009.Palindrome Number/Solution.py

009 	Palindrome Number - Python

---

solution/119.Pascal's Triangle II/README.md
solution/119.Pascal's Triangle II/Solution.cpp
solution/120.Triangle/README.md
solution/120.Triangle/Solution.cpp

Add Solution 119[CPP]

---

solution/0036.Valid Sudoku/Solution.java

36. Valid Sudoku (java)

---

solution/0008.String to Integer(atoi)/Solution.py

0008 String to Integer(atoi) - Python

---

solution/0228.Summary Ranges/README.md
solution/0228.Summary Ranges/Solution.cpp
solution/0283.Move Zeroes/README.md
solution/0283.Move Zeroes/Solution.cpp

Add Soutution CPP[228 && 283]

---

solution/0670.Maximum Swap/README.md
solution/0670.Maximum Swap/Solution.py

add solution of 0670-python

---

solution/0073.Set Matrix Zeroes/Solution.py
solution/0074.Search a 2D Matrix/Solution.py

0073 Set Matrix Zeroes - Python

---

solution/0202.Happy Number/README.md
solution/0202.Happy Number/Solution.java

Add the solution of Question 202 .Happy Number

Add solution of 202.Happy Number(java)

---

README.md

Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/leetcode-280❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You already have a manual contributor image, but I added the automated Open Collective contributor image anyways. 
You can also add a postinstall script to let people know after npm|yarn install that …

Update Readme.md for Open Collective

---

solution/0985.Sum of Even Numbers After Queries/Solution.py

第一次尝试使用Git帮助完善仓库，有什么用地不对的地方请多指教哈！

Create Solution 0985 [Solution.py]

---

solution/0168.Excel Sheet Column Title/README.md
solution/0168.Excel Sheet Column Title/Solution.java

Add 0168 solution.java and README.md

Add 0168 solution.java and README.md

---

solution/0005.Longest Palindromic Substring/Solution.go
solution/README.md

This is my first pr for leetcode, and I will provide more solutions of Golang.

Add Solution.go for 0005.Longest Palindromic Substring

---

solution/0002.Add Two Numbers/Solution2.py
solution/README.md

This is a very pythonic solution for 0002 in Python3. You can do what you think easily by python~

A pythonic solution for 0002

---

solution/0191.Number of 1 Bits/Solution.java
solution/README.md

Hello, Doocs! 
Please merge my changes if you think these changes are correct.
1. Add `Solution.java` file to the `0191. Number of 1 Bits` directory.
```java
// Solution.java
public class Solution {
public int hammingWeight(int n) {
return Integer.bitCount(n);
}
}
```
2. Update `README.md`.
```java
...
├── 0191.Number of 1 Bits
│   ├── Solution.java
│   ├── Solution.js
│   └── Solution.py
...
```
Please do not mark this as spam.

Add Java Solution for Problem 191

---

solution/1287. Element Appearing More Than 25% In Sorted Array/README.md
solution/1287. Element Appearing More Than 25% In Sorted Array/Solution.js
solution/README.md

- Add solution on js
- Update Solution Readme

1287. Element Appearing More Than 25% In Sorted Array

---

solution/0500-0599/0500.Keyboard Row/Solution.java
solution/0500-0599/0501.Find Mode in Binary Search Tree/Solution.java

add 0500 and 0501 java version

add 0500 and 0501 java version

---

solution/0500-0599/0520.Detect Capital/Solution.java
solution/0500-0599/0521.Longest Uncommon Subsequence I/Solution.java
solution/0500-0599/0522.Longest Uncommon Subsequence II/Solution.java

add 0520,0521,0522 solution for java

add 0520,0521,0522 solution for java

---

lcof/面试题06. 从尾到头打印链表/README.md
lcof/面试题06. 从尾到头打印链表/Solution.go
lcof/面试题07. 重建二叉树/README.md
lcof/面试题07. 重建二叉树/Solution.go
lcof/面试题09. 用两个栈实现队列/README.md
lcof/面试题09. 用两个栈实现队列/Solution.go

add golang solution for lcof problem 06 07 09

feat:add golang solution for lcof problem 06 07 09

---

lcof/面试题03. 数组中重复的数字/README.md

原方法忘记在交换后更新当前`i`指针对应的`num`，导致测试用例 `nums = [1, 3, 4, 0, 2, 5, 3]` 返回`1`（应该返回`3`）:
```
from typing import List
def findRepeatNumber(nums: List[int]) -> int:
for i, num in enumerate(nums):
while i != num:
if num == nums[num]:
return num
nums[i], nums[num] = nums[num], nums[i]
return -1
nums = [1, 3, 4, 0, 2, 5, 3]
findRepeatNumber(nums)
```
因此，本次提交作出了修正：
```
def findRepeatNumber(nums: List[int]) -> int:
for i, num in enumerate(nums):
while i != num:
if num == nums[num]:
return num
nums[i], nums[num] = nums[num], nums[i]
num = nums[i]
return -1
```
修正后可通过三种边界测试和其他笔者想到的任何符合题目要求情况：
```
nums = [1, 3, 4, 0, 2, 5, 3] # should return 3
nums = [2, 4, 1, 0, 2, 5, 3] # should return 2
nums = [2, 4, 1, 0, 6, 5, 3] # should return -1
findRepeatNumber(nums)
```
另，虽然复杂度相同，但读者更偏爱只使用一个循环表示该过程：
```
def …
```

Fix outdate number error of findRepeatNumber

---

lcof/面试题13. 机器人的运动范围/README.md
lcof/面试题13. 机器人的运动范围/Solution.cpp
lcof/面试题32 - I. 从上到下打印二叉树/Solution.cpp

更新了lcof中cpp版本的两个题目。答案均在leetcode上验证通过，解法基本双优

Chunel feng/lcof cpp

---

lcof/面试题25. 合并两个排序的链表/README.md
lcof/面试题25. 合并两个排序的链表/Solurion.cpp
lcof/面试题26. 树的子结构/README.md
lcof/面试题26. 树的子结构/Sulotion.cpp

更新了[25.合并两个排序的链表]和[26.树的子结构]两题的cpp解法

---

lcof/面试题27. 二叉树的镜像/README.md
lcof/面试题27. 二叉树的镜像/Solution.cpp
lcof/面试题55 - II. 平衡二叉树/Solution.cpp

leetcode上自测双优，其中还修复了lcof-55题目cpp题解的注释错误

更新了[lcof-27.二叉树的镜像]中的cpp版本题解

---

lcof/面试题38. 字符串的排列/README.md
lcof/面试题38. 字符串的排列/Solution.cpp
lcof/面试题52. 两个链表的第一个公共节点/README.md
lcof/面试题52. 两个链表的第一个公共节点/Solution.cpp
solution/1100-1199/1195.Fizz Buzz Multithreaded/README.md
solution/1100-1199/1195.Fizz Buzz Multithreaded/Solution.cpp
solution/1200-1299/1226.The Dining Philosophers/README.md
solution/1200-1299/1226.The Dining Philosophers/Solution.cpp

以上代码均在leetcode上测试通过，除一题添加set结构导致时间复杂度略高外（暂时没好方法解决），基本双优

增加了lcof-38.52和lc-1195.1226的题解

---

lcof/面试题03. 数组中重复的数字/README.md
lcof/面试题03. 数组中重复的数字/Solution.cpp
lcof/面试题06. 从尾到头打印链表/README.md
lcof/面试题06. 从尾到头打印链表/Solution.cpp

更新了[lcof-03.数组中重复的数字]和[lcof-06.从尾到头打印链表]的cpp解法

---

lcof/面试题12. 矩阵中的路径/README.md
lcof/面试题12. 矩阵中的路径/Solution.cpp
lcof/面试题19. 正则表达式匹配/README.md
lcof/面试题19. 正则表达式匹配/Solution.cpp

增加了[lcof-12.矩阵中的路径]和[lcof-19.正则表达式匹配]的cpp版本的题解.其中,lcof-12题解双优,lcof-19主要目的是为了提供新思路

增加了lcof-12和lcof-19的cpp版本题解

---

lcof/面试题18. 删除链表的节点/README.md
lcof/面试题18. 删除链表的节点/Solution.cpp
lcof/面试题40. 最小的k个数/README.md
lcof/面试题40. 最小的k个数/Solution.cpp

增加了[lcof-18.删除链表的节点]和[lcof-40.最小的k个数]的cpp解法

---

lcof/面试题57 - II. 和为s的连续正数序列/README.md
lcof/面试题57 - II. 和为s的连续正数序列/Solution.cpp

更新了[lcof-57.和为s的连续正整数序列]的cpp解法

---

lcof/面试题28. 对称的二叉树/README.md
lcof/面试题28. 对称的二叉树/Solution.cpp

更新了[lcof-28.对称的二叉树]的cpp解法

---

solution/1300-1399/1342.Number of Steps to Reduce a Number to Zero/README.md
solution/1300-1399/1342.Number of Steps to Reduce a Number to Zero/README_EN.md
solution/1300-1399/1342.Number of Steps to Reduce a Number to Zero/Solution.java
solution/1600-1699/1678.Goal Parser Interpretation/README.md
solution/1600-1699/1678.Goal Parser Interpretation/README_EN.md
solution/1600-1699/1678.Goal Parser Interpretation/Solution.java

feat: add java solution to lc problem: No.1342 and No.1678

feat: add java solution to lc problem: No.1342 and No.1678

---

solution/1000-1099/1011.Capacity To Ship Packages Within D Days/README.md
solution/1000-1099/1011.Capacity To Ship Packages Within D Days/README_EN.md
solution/1000-1099/1011.Capacity To Ship Packages Within D Days/Solution.java

feat: add java solution to lc problem: 1011. Capacity To Ship Packages Within D Days

---

basic/sorting/BubbleSort/README.md
basic/sorting/BubbleSort/bubblesort.cpp

新增冒泡排序的c++实现

---

solution/2000-2099/2073.Time Needed to Buy Tickets/README.md
solution/2000-2099/2073.Time Needed to Buy Tickets/README_EN.md
solution/2000-2099/2073.Time Needed to Buy Tickets/Solution.ts

feat: add typescript solution to lc problem: No.2073

---

solution/0100-0199/0188.Best Time to Buy and Sell Stock IV/README.md
solution/0100-0199/0188.Best Time to Buy and Sell Stock IV/README_EN.md
solution/0100-0199/0188.Best Time to Buy and Sell Stock IV/Solution.cpp

feat: add cpp solution to lc problem: No.188

---

solution/0900-0999/0987.Vertical Order Traversal of a Binary Tree/README.md
solution/0900-0999/0987.Vertical Order Traversal of a Binary Tree/README_EN.md
solution/0900-0999/0987.Vertical Order Traversal of a Binary Tree/Solution.ts

No.0987.Vertical Order Traversal of a Binary Tree

feat: add typescript solution to lc problem: No.0987

---

solution/1000-1099/1041.Robot Bounded In Circle/README.md
solution/1000-1099/1041.Robot Bounded In Circle/README_EN.md
solution/1000-1099/1041.Robot Bounded In Circle/Solution.java
solution/1000-1099/1041.Robot Bounded In Circle/Solution.py

feat: add solutions to lc problem: No.1041

---

solution/0300-0399/0365.Water and Jug Problem/README.md
solution/0300-0399/0365.Water and Jug Problem/README_EN.md
solution/0300-0399/0365.Water and Jug Problem/Solution.java
solution/0300-0399/0365.Water and Jug Problem/Solution.py

feat: add solutions to lc problem: No.0365

---

lcof/面试题35. 复杂链表的复制/README.md

feat: add javascript solution to lcof problem: No.35

---

solution/0000-0099/0075.Sort Colors/README.md
solution/0000-0099/0075.Sort Colors/README_EN.md
solution/0000-0099/0075.Sort Colors/Solution.rs

feat: add rust solution to lc problem: No.0075

---

basic/sorting/SelectionSort/README.md
basic/sorting/SelectionSort/SelectionSort.cs

add c# select in SelectionSort

---

solution/0000-0099/0033.Search in Rotated Sorted Array/README.md

No.0033.Search in Rotated Sorted Array

docs: update description to lc problem No.0033

---

solution/0100-0199/0189.Rotate Array/README.md
solution/0100-0199/0189.Rotate Array/README_EN.md

feat: add a JS solution of 189

---

solution/1200-1299/1270.All People Report to the Given Manager/README.md
solution/1200-1299/1270.All People Report to the Given Manager/README_EN.md
solution/1200-1299/1270.All People Report to the Given Manager/Solution.sql

added solution to lc:1270

---

solution/0600-0699/0619.Biggest Single Number/README.md
solution/0600-0699/0619.Biggest Single Number/README_EN.md
solution/0600-0699/0619.Biggest Single Number/Solution.sql

added solution to lc:619

---

solution/1200-1299/1251.Average Selling Price/README.md
solution/1200-1299/1251.Average Selling Price/README_EN.md
solution/1200-1299/1251.Average Selling Price/Solution.sql

added solution to lc:1251

---

lcci/08.05.Recursive Mulitply/README.md

docs: add a description of the solution to lcci problem: No.08.05

---

solution/1400-1499/1495.Friendly Movies Streamed Last Month/README.md
solution/1400-1499/1495.Friendly Movies Streamed Last Month/README_EN.md
solution/1400-1499/1495.Friendly Movies Streamed Last Month/Solution.sql

added solution to lc:1495

---

solution/1300-1399/1337.The K Weakest Rows in a Matrix/README.md
solution/1300-1399/1337.The K Weakest Rows in a Matrix/README_EN.md
solution/1300-1399/1337.The K Weakest Rows in a Matrix/Solution.cpp

✅ update readme ➡️  added cpp solution

added solution to lc:1337

---

solution/0500-0599/0534.Game Play Analysis III/README.md
solution/0500-0599/0534.Game Play Analysis III/README_EN.md
solution/0500-0599/0534.Game Play Analysis III/Solution.sql

added solution to lc:534

---

solution/1100-1199/1105.Filling Bookcase Shelves/README.md
solution/1100-1199/1105.Filling Bookcase Shelves/README_EN.md
solution/1100-1199/1105.Filling Bookcase Shelves/Solution.java
solution/1100-1199/1105.Filling Bookcase Shelves/Solution.py

feat: add solutions to lc problem: No.1105

---

solution/0800-0899/0896.Monotonic Array/README.md
solution/0800-0899/0896.Monotonic Array/README_EN.md
solution/0800-0899/0896.Monotonic Array/Solution.cpp
solution/0800-0899/0896.Monotonic Array/Solution.go
solution/0800-0899/0896.Monotonic Array/Solution.java
solution/0800-0899/0896.Monotonic Array/Solution.js
solution/0800-0899/0896.Monotonic Array/Solution.py
solution/0800-0899/0896.Monotonic Array/Solution.rs

feat: update solutions to lc problem: No.0896

---

solution/0300-0399/0315.Count of Smaller Numbers After Self/README.md

No.0315.Count of Smaller Numbers After Self

feat: add go solution to lc problem: No.0315

---

solution/1200-1299/1201.Ugly Number III/README.md
solution/1200-1299/1201.Ugly Number III/README_EN.md
solution/1200-1299/1201.Ugly Number III/Solution.cpp
solution/1200-1299/1201.Ugly Number III/Solution.go
solution/1200-1299/1201.Ugly Number III/Solution.py

feat: add solutions to lc problem: No.1201

---

solution/1700-1799/1726.Tuple with Same Product/README.md
solution/1700-1799/1726.Tuple with Same Product/README_EN.md
solution/1700-1799/1726.Tuple with Same Product/Solution.go
solution/1700-1799/1726.Tuple with Same Product/Solution.py

No.1726.Tuple with Same Product

feat: add solutions to lc problem: No.1726

---

solution/0200-0299/0202.Happy Number/README.md
solution/0200-0299/0202.Happy Number/README_EN.md
solution/0200-0299/0202.Happy Number/Solution.go

The answer is implemented through a hash table. Both English and Chinese md versions have been added. I'm not sure `Solution.go` its role. But I find it nowhere to be quoted. After looking at the other folders, I decided to replace it and al.

fix(solution/202): lack of golang solution

---

solution/0100-0199/0137.Single Number II/README.md
solution/0100-0199/0137.Single Number II/README_EN.md
solution/0100-0199/0137.Single Number II/Solution.swift

add swift solution to lc problem No. 0137

---

solution/0300-0399/0303.Range Sum Query - Immutable/README.md
solution/0300-0399/0303.Range Sum Query - Immutable/README_EN.md
solution/0300-0399/0303.Range Sum Query - Immutable/Solution.php

feat: add php solution to lc problem: No.0303

---

solution/0100-0199/0100.Same Tree/README.md
solution/0100-0199/0100.Same Tree/README_EN.md
solution/0100-0199/0100.Same Tree/Solution.php

feat: add php solution to lc problem: No.s0100

---

solution/1000-1099/1002.Find Common Characters/README.md
solution/1000-1099/1002.Find Common Characters/README_EN.md
solution/1000-1099/1002.Find Common Characters/Solution.cpp
solution/1000-1099/1002.Find Common Characters/Solution.go
solution/1000-1099/1002.Find Common Characters/Solution.java
solution/1000-1099/1002.Find Common Characters/Solution.py

No.1002.Find Common Characters

feat: update solutions to lc problem: No.1002

---

solution/0300-0399/0349.Intersection of Two Arrays/README.md
solution/0300-0399/0349.Intersection of Two Arrays/README_EN.md
solution/0300-0399/0349.Intersection of Two Arrays/Solution.php

feat: add php solution to lc problem: No.0349

---

solution/0300-0399/0350.Intersection of Two Arrays II/README.md
solution/0300-0399/0350.Intersection of Two Arrays II/README_EN.md
solution/0300-0399/0350.Intersection of Two Arrays II/Solution.php

feat: add php solution to lc problem: No.0350

---

solution/0200-0299/0229.Majority Element II/README.md
solution/0200-0299/0229.Majority Element II/README_EN.md
solution/0200-0299/0229.Majority Element II/Solution.php

feat: add php solution to lc problem: No.0229

---

solution/1500-1599/1507.Reformat Date/README.md
solution/1500-1599/1507.Reformat Date/README_EN.md
solution/1500-1599/1507.Reformat Date/Solution.php

feat: add php solution to lc problem: No.1507

---

solution/1700-1799/1732.Find the Highest Altitude/README.md
solution/1700-1799/1732.Find the Highest Altitude/README_EN.md
solution/1700-1799/1732.Find the Highest Altitude/Solution.php

feat: add php solution to lc problem: No.1732

---

solution/2700-2799/2747.Count Zero Request Servers/README.md
solution/2700-2799/2747.Count Zero Request Servers/README_EN.md
solution/2700-2799/2747.Count Zero Request Servers/Solution.cpp
solution/2700-2799/2747.Count Zero Request Servers/Solution.go
solution/2700-2799/2747.Count Zero Request Servers/Solution.java
solution/2700-2799/2747.Count Zero Request Servers/Solution.py
solution/2700-2799/2747.Count Zero Request Servers/Solution.ts

No.2747.Count Zero Request Servers

feat: add solutions to lc problem: No.2747

---

.prettierrc
solution/2700-2799/2752.Customers with Maximum Number of Transactions on Consecutive Days/README.md
solution/2700-2799/2752.Customers with Maximum Number of Transactions on Consecutive Days/README_EN.md
solution/2700-2799/2752.Customers with Maximum Number of Transactions on Consecutive Days/Solution.sql

No.2752.Customers with Maximum Number of Transactions on Consecutive Days

feat: add sql solution to lc problem: No.2752

---

.prettierrc
solution/0100-0199/0192.Word Frequency/README.md
solution/0100-0199/0192.Word Frequency/README_EN.md
solution/0100-0199/0192.Word Frequency/Solution.sh
solution/1900-1999/1990.Count the Number of Experiments/README.md
solution/1900-1999/1990.Count the Number of Experiments/README_EN.md
solution/1900-1999/1990.Count the Number of Experiments/Solution.sql
solution/2000-2099/2020.Number of Accounts That Did Not Stream/README.md
solution/2000-2099/2020.Number of Accounts That Did Not Stream/README_EN.md
solution/2000-2099/2020.Number of Accounts That Did Not Stream/Solution.sql
solution/2000-2099/2041.Accepted Candidates From the Interviews/README.md
solution/2000-2099/2041.Accepted Candidates From the Interviews/README_EN.md
solution/2000-2099/2041.Accepted Candidates From the Interviews/Solution.sql
solution/2000-2099/2051.The Category of Each Member in the Store/README.md
solution/2000-2099/2051.The Category of Each Member in the Store/README_EN.md
solution/2000-2099/2051.The Category of Each Member in the Store/Solution.sql
solution/2000-2099/2066.Account Balance/README.md
solution/2000-2099/2066.Account Balance/README_EN.md
solution/2000-2099/2066.Account Balance/Solution.sql
solution/2000-2099/2084.Drop Type 1 Orders for Customers With Type 0 Orders/README.md
solution/2000-2099/2084.Drop Type 1 Orders for Customers With Type 0 Orders/README_EN.md
solution/2000-2099/2084.Drop Type 1 Orders for Customers With Type 0 Orders/Solution.sql
solution/2100-2199/2112.The Airport With the Most Traffic/README.md
solution/2100-2199/2112.The Airport With the Most Traffic/README_EN.md
solution/2100-2199/2112.The Airport With the Most Traffic/Solution.sql

* No.1990.Count the Number of Experiments
* No.2020.Number of Accounts That Did Not Stream
* No.2051.The Category of Each Member in the Store
* No.2066.Account Balance
* No.2084.Drop Type 1 Orders for Customers With Type 0 Orders
* No.2112.The Airport With the Most Traffic

feat: add sql solutions to lc problems

---

solution/2100-2199/2159.Order Two Columns Independently/README.md
solution/2100-2199/2159.Order Two Columns Independently/README_EN.md
solution/2100-2199/2159.Order Two Columns Independently/Solution.sql
solution/2200-2299/2228.Users With Two Purchases Within Seven Days/README.md
solution/2200-2299/2228.Users With Two Purchases Within Seven Days/README_EN.md
solution/2200-2299/2228.Users With Two Purchases Within Seven Days/Solution.sql
solution/2200-2299/2298.Tasks Count in the Weekend/README.md
solution/2200-2299/2298.Tasks Count in the Weekend/README_EN.md
solution/2200-2299/2298.Tasks Count in the Weekend/Solution.sql
solution/2300-2399/2308.Arrange Table by Gender/README.md
solution/2300-2399/2308.Arrange Table by Gender/README_EN.md
solution/2300-2399/2308.Arrange Table by Gender/Solution.sql

* No.2159.Order Two Columns Independently
* No.2228.Users With Two Purchases Within Seven Days
* No.2308.Arrange Table by Gender

feat: add sql solutions to lc problems: No.2159,2228,2308

---

solution/1900-1999/1919.Leetcodify Similar Friends/README.md
solution/1900-1999/1919.Leetcodify Similar Friends/README_EN.md
solution/1900-1999/1919.Leetcodify Similar Friends/Solution.sql

No.1919.Leetcodify Similar Friends

feat: add sql solution to lc problem: No.1919

---

basic/README.md
basic/README_EN.md
basic/summary.md

fix readme in basic

---

.prettierignore
solution/0600-0699/0612.Shortest Distance in a Plane/README.md
solution/0600-0699/0612.Shortest Distance in a Plane/README_EN.md
solution/0600-0699/0612.Shortest Distance in a Plane/Solution.sql
solution/2100-2199/2118.Build the Equation/README.md
solution/2100-2199/2118.Build the Equation/README_EN.md
solution/2100-2199/2118.Build the Equation/Solution.sql
solution/2100-2199/2177.Find Three Consecutive Integers That Sum to a Given Number/README.md
solution/2100-2199/2177.Find Three Consecutive Integers That Sum to a Given Number/README_EN.md
solution/2100-2199/2177.Find Three Consecutive Integers That Sum to a Given Number/Solution.cpp
solution/2100-2199/2177.Find Three Consecutive Integers That Sum to a Given Number/Solution.py
solution/2100-2199/2177.Find Three Consecutive Integers That Sum to a Given Number/Solution.ts
solution/2100-2199/2178.Maximum Split of Positive Even Integers/README.md
solution/2100-2199/2178.Maximum Split of Positive Even Integers/README_EN.md
solution/2100-2199/2178.Maximum Split of Positive Even Integers/Solution.cs
solution/2100-2199/2178.Maximum Split of Positive Even Integers/Solution.go
solution/2200-2299/2238.Number of Times a Driver Was a Passenger/README.md
solution/2200-2299/2238.Number of Times a Driver Was a Passenger/README_EN.md
solution/2200-2299/2238.Number of Times a Driver Was a Passenger/Solution.sql

* No.0612.Shortest Distance in a Plane
* No.2118.Build the Equation
* No.2177.Find Three Consecutive Integers That Sum to a Given Number
* No.2178.Maximum Split of Positive Even Integers
* No.2238.Number of Times a Driver Was a Passenger

feat: add solutions to lc problems

---

solution/2700-2799/2728.Count Houses in a Circular Street/README.md
solution/2700-2799/2753.Count Houses in a Circular Street II/README.md
solution/2700-2799/2753.Count Houses in a Circular Street II/README_EN.md
solution/2700-2799/2753.Count Houses in a Circular Street II/Solution.cpp
solution/2700-2799/2753.Count Houses in a Circular Street II/Solution.go
solution/2700-2799/2753.Count Houses in a Circular Street II/Solution.java
solution/2700-2799/2753.Count Houses in a Circular Street II/Solution.py
solution/2700-2799/2753.Count Houses in a Circular Street II/Solution.ts

No.2753.Count Houses in a Circular Street II

feat: add solutions to lc problem: No.2753

---

.github/workflows/black-lint.yml
.github/workflows/clang-format-lint.yml
.github/workflows/pr-checker.yml
solution/0500-0599/0511.Game Play Analysis I/README.md
solution/0500-0599/0511.Game Play Analysis I/README_EN.md
solution/0500-0599/0511.Game Play Analysis I/Solution.sql
solution/0500-0599/0512.Game Play Analysis II/README.md
solution/0500-0599/0512.Game Play Analysis II/README_EN.md
solution/0500-0599/0534.Game Play Analysis III/README.md
solution/0500-0599/0534.Game Play Analysis III/README_EN.md
solution/0500-0599/0534.Game Play Analysis III/Solution.sql

* No.0511.Game Play Analysis I
* No.0512.Game Play Analysis II
* No.0534.Game Play Analysis III

feat: update sql solutions to lc problems: No.0511,0512,0534

---

solution/2700-2799/2798.Number of Employees Who Met the Target/README.md
solution/2700-2799/2798.Number of Employees Who Met the Target/README_EN.md
solution/2700-2799/2798.Number of Employees Who Met the Target/Solution.rs
solution/2700-2799/2799.Count Complete Subarrays in an Array/README.md
solution/2700-2799/2799.Count Complete Subarrays in an Array/README_EN.md
solution/2700-2799/2799.Count Complete Subarrays in an Array/Solution.rs
solution/2800-2899/2800.Shortest String That Contains Three Strings/README.md
solution/2800-2899/2800.Shortest String That Contains Three Strings/README_EN.md
solution/2800-2899/2800.Shortest String That Contains Three Strings/Solution.rs

- 2798.Number of Employees Who Met the Target
- 2799.Count Complete Subarrays in an Array
- 2800.Shortest String That Contains Three Strings

feat: add solutions to lc problems: No.2798~2800

---

lcci/05.02.Binary Number to String/README_EN.md

This pull request fixes some typos in `./lcci/05.02.Binary Number to String/README_EN.md`.
I kindly request the repository maintainers to review and merge it.
Thanks! :heart:

fix typos in './lcci/05.02.Binary Number to String/README_EN.md'

---

solution/3000-3099/3017.Count the Number of Houses at a Certain Distance II/README.md
solution/3000-3099/3017.Count the Number of Houses at a Certain Distance II/README_EN.md
solution/3000-3099/3017.Count the Number of Houses at a Certain Distance II/Solution.cpp
solution/3000-3099/3017.Count the Number of Houses at a Certain Distance II/Solution.go
solution/3000-3099/3017.Count the Number of Houses at a Certain Distance II/Solution.java
solution/3000-3099/3017.Count the Number of Houses at a Certain Distance II/Solution.py

Updated the fully working and all test case passes code of Question No. 3017
Adding the code.

No.3015.Count the Number of Houses at a Certain Distance II

---

solution/3000-3099/3021.Alice and Bob Playing Flower Game/README.md
solution/3000-3099/3021.Alice and Bob Playing Flower Game/README_EN.md
solution/3000-3099/3021.Alice and Bob Playing Flower Game/Solution.cpp
solution/3000-3099/3021.Alice and Bob Playing Flower Game/Solution.go
solution/3000-3099/3021.Alice and Bob Playing Flower Game/Solution.java
solution/3000-3099/3021.Alice and Bob Playing Flower Game/Solution.py

Updated the fully working and all test cases are passed for these codes for Question No. 3021
I am adding the code.

No.3021.Alice and Bob Playing Flower Game

---

solution/3000-3099/3032.Count Numbers With Unique Digits II/README.md
solution/3000-3099/3032.Count Numbers With Unique Digits II/README_EN.md
solution/3000-3099/3032.Count Numbers With Unique Digits II/Solution2.cpp
solution/3000-3099/3032.Count Numbers With Unique Digits II/Solution2.go
solution/3000-3099/3032.Count Numbers With Unique Digits II/Solution2.java
solution/3000-3099/3032.Count Numbers With Unique Digits II/Solution2.py
solution/3000-3099/3032.Count Numbers With Unique Digits II/Solution2.ts

Updated the fully working and all test cases passed codes of Question No. 3032
I am adding the code for my second logic of the question.

feat: add solutions to lc problem: No.3032

---

solution/3000-3099/3033.Modify the Matrix/README.md
solution/3000-3099/3033.Modify the Matrix/README_EN.md
solution/3000-3099/3033.Modify the Matrix/Solution.cpp
solution/3000-3099/3033.Modify the Matrix/Solution.go
solution/3000-3099/3033.Modify the Matrix/Solution.java
solution/3000-3099/3033.Modify the Matrix/Solution.py
solution/3000-3099/3033.Modify the Matrix/Solution.ts

Updated the fully working and all test cases passed codes of Question No. 3033
I am adding the code of the question.

feat: add solutions to lc problem: No.3033

---

solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/README.md
solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/README_EN.md
solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/Solution.cpp
solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/Solution.go
solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/Solution.java
solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/Solution.py
solution/3000-3099/3034.Number of Subarrays That Match a Pattern I/Solution.ts

Updated the fully working and all test cases passed codes of Question No. 3034
I am adding the code of the question.

feat: add solutions to lc problem: No.3034

---

solution/2100-2199/2192.All Ancestors of a Node in a Directed Acyclic Graph/README.md
solution/2100-2199/2192.All Ancestors of a Node in a Directed Acyclic Graph/README_EN.md
solution/2100-2199/2192.All Ancestors of a Node in a Directed Acyclic Graph/Solution.cs
solution/2100-2199/2192.All Ancestors of a Node in a Directed Acyclic Graph/Solution.ts

No.2192.All Ancestors of a Node in a Directed Acyclic Graph

feat: add solutions to lc problem: No.2192

---

solution/1000-1099/1026.Maximum Difference Between Node and Ancestor/README.md
solution/1000-1099/1026.Maximum Difference Between Node and Ancestor/README_EN.md
solution/1000-1099/1026.Maximum Difference Between Node and Ancestor/Solution.cs
solution/1000-1099/1026.Maximum Difference Between Node and Ancestor/Solution.py

No.1026.Maximum Difference Between Node and Ancestor

feat: add solutions to lc problem: No.1026

---

solution/1600-1699/1601.Maximum Number of Achievable Transfer Requests/README.md
solution/1600-1699/1601.Maximum Number of Achievable Transfer Requests/README_EN.md
solution/1600-1699/1601.Maximum Number of Achievable Transfer Requests/Solution.cs
solution/1600-1699/1601.Maximum Number of Achievable Transfer Requests/Solution.ts

No.1601.Maximum Number of Achievable Transfer Requests

feat: add solutions to lc problem: No.1601

---

solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/README.md
solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/README_EN.md
solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/Solution.cpp
solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/Solution.go
solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/Solution.java
solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/Solution.py
solution/3100-3199/3107.Minimum Operations to Make Median of Array Equal to K/Solution.ts

No.3107.Minimum Operations to Make Median of Array Equal to K

feat: add solutions to lc problem: No.3107

---

solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/README.md
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/README_EN.md
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.cpp
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.go
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.java
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.php
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.py
solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.ts

No.1456.Maximum Number of Vowels in a Substring of Given Length

feat: update solutions to lc problem: No.1456

---

solution/0600-0699/0643.Maximum Average Subarray I/README.md
solution/0600-0699/0643.Maximum Average Subarray I/README_EN.md
solution/0600-0699/0643.Maximum Average Subarray I/Solution.cpp
solution/0600-0699/0643.Maximum Average Subarray I/Solution.go
solution/0600-0699/0643.Maximum Average Subarray I/Solution.php
solution/0600-0699/0643.Maximum Average Subarray I/Solution.py
solution/0600-0699/0643.Maximum Average Subarray I/Solution.rs
solution/0600-0699/0643.Maximum Average Subarray I/Solution.ts
solution/0600-0699/0644.Maximum Average Subarray II/README_EN.md
solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/README.md
solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/README_EN.md
solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/Solution.cpp
solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/Solution.php

* No.0643.Maximum Average Subarray I
* No.1984.Minimum Difference Between Highest and Lowest of K Scores

feat: add solutions to lc problems: No.0643,1984

---

solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/README.md
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/README_EN.md
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.cpp
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.cs
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.go
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.java
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.py
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.rs
solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.ts

No.2134.Minimum Swaps to Group All 1's Together II

feat: add solutions to lc problem: No.2134

---

solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/README.md
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/README_EN.md
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution.cpp
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution.go
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution.java
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution.py
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution.ts
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution2.cpp
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution2.go
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution2.java
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution2.py
solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution2.ts
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/README.md
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/README_EN.md
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/Solution.cpp
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/Solution.go
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/Solution.java
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/Solution.py
solution/2700-2799/2730.Find the Longest Semi-Repetitive Substring/Solution.ts

* No.1493.Longest Subarray of 1's After Deleting One Element
* No.2730.Find the Longest Semi-Repetitive Substring

feat: add solutions to lc problems: No.1493,2730

---

solution/2500-2599/2516.Take K of Each Character From Left and Right/README.md
solution/2500-2599/2516.Take K of Each Character From Left and Right/README_EN.md
solution/2500-2599/2516.Take K of Each Character From Left and Right/Solution.cpp
solution/2500-2599/2516.Take K of Each Character From Left and Right/Solution.go
solution/2500-2599/2516.Take K of Each Character From Left and Right/Solution.java
solution/2500-2599/2516.Take K of Each Character From Left and Right/Solution.py
solution/2500-2599/2516.Take K of Each Character From Left and Right/Solution.rs
solution/2500-2599/2516.Take K of Each Character From Left and Right/Solution.ts

No.2516.Take K of Each Character From Left and Right

feat: add solutions to lc problem: No.2516

---

solution/3100-3199/3111.Minimum Rectangles to Cover Points/README.md
solution/3100-3199/3111.Minimum Rectangles to Cover Points/README_EN.md
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.cpp
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.go
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.java
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.py
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.ts
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/README.md
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/README_EN.md
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/Solution.cpp
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/Solution.go
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/Solution.java
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/Solution.py

* No.3111.Minimum Rectangles to Cover Points
* No.3112.Minimum Time to Visit Disappearing Nodes

feat: add solutions to lc problems: No.3111,3112

---

solution/1200-1299/1249.Minimum Remove to Make Valid Parentheses/README_EN.md
solution/2700-2799/2796.Repeat String/README_EN.md
solution/2800-2899/2821.Delay the Resolution of Each Promise/README_EN.md
solution/3000-3099/3096.Minimum Levels to Gain More Points/README_EN.md
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/README_EN.md
solution/3100-3199/3118.Friday Purchase III/README.md
solution/3100-3199/3118.Friday Purchase III/README_EN.md
solution/3100-3199/3118.Friday Purchase III/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

feat: add sql solution to lc problem: No.3118

---

solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/README.md
solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/README_EN.md
solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/Solution.cpp
solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/Solution.go
solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/Solution.java
solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/Solution.py
solution/3100-3199/3116.Kth Smallest Amount With Single Denomination Combination/Solution.ts

No.3116.Kth Smallest Amount With Single Denomination Combination

feat: add solutions to lc problem: No.3116

---

solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/README.md
solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/README_EN.md
solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/Solution.cpp
solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/Solution.go
solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/Solution.java
solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/Solution.py
solution/3100-3199/3117.Minimum Sum of Values by Dividing Array/Solution.ts

No.3117.Minimum Sum of Values by Dividing Array

feat: add solutions to lc problem: No.3117

---

solution/2000-2099/2007.Find Original Array From Doubled Array/README.md
solution/2000-2099/2007.Find Original Array From Doubled Array/README_EN.md
solution/2000-2099/2007.Find Original Array From Doubled Array/Solution.cpp
solution/2000-2099/2007.Find Original Array From Doubled Array/Solution.go
solution/2000-2099/2007.Find Original Array From Doubled Array/Solution.java
solution/2000-2099/2007.Find Original Array From Doubled Array/Solution.py
solution/2000-2099/2007.Find Original Array From Doubled Array/Solution.ts

No.2007.Find Original Array From Doubled Array

feat: update solutions to lc problem: No.2007

---

solution/0900-0999/0923.3Sum With Multiplicity/README.md
solution/0900-0999/0923.3Sum With Multiplicity/README_EN.md
solution/0900-0999/0923.3Sum With Multiplicity/Solution.cpp
solution/0900-0999/0923.3Sum With Multiplicity/Solution.go
solution/0900-0999/0923.3Sum With Multiplicity/Solution.java
solution/0900-0999/0923.3Sum With Multiplicity/Solution.py
solution/0900-0999/0923.3Sum With Multiplicity/Solution.ts

No.0923.3Sum With Multiplicity

feat: add solutions to lc problem: No.0923

---

.github/workflows/pr-labeled.yml

ci(invalid): auto comment

---

solution/0200-0299/0261.Graph Valid Tree/README.md
solution/0200-0299/0261.Graph Valid Tree/README_EN.md
solution/0200-0299/0261.Graph Valid Tree/Solution.cpp
solution/0200-0299/0261.Graph Valid Tree/Solution.go
solution/0200-0299/0261.Graph Valid Tree/Solution.java
solution/0200-0299/0261.Graph Valid Tree/Solution.js
solution/0200-0299/0261.Graph Valid Tree/Solution.py
solution/0200-0299/0261.Graph Valid Tree/Solution2.cpp
solution/0200-0299/0261.Graph Valid Tree/Solution2.go
solution/0200-0299/0261.Graph Valid Tree/Solution2.java
solution/0200-0299/0261.Graph Valid Tree/Solution2.js
solution/0200-0299/0261.Graph Valid Tree/Solution2.py

feat: add solutions to lc problem: No.261

---

lcci/01.08.Zero Matrix/README.md
lcci/01.08.Zero Matrix/README_EN.md
lcci/01.08.Zero Matrix/Solution.swift
lcci/01.09.String Rotation/README.md
lcci/01.09.String Rotation/README_EN.md
lcci/01.09.String Rotation/Solution.swift
lcci/02.01.Remove Duplicate Node/README.md
lcci/02.01.Remove Duplicate Node/README_EN.md
lcci/02.01.Remove Duplicate Node/Solution.swift

Swift implementation for LCCI 01.08, 01.09 & 02.01

---

solution/0400-0499/0404.Sum of Left Leaves/README.md
solution/0400-0499/0404.Sum of Left Leaves/README_EN.md
solution/0400-0499/0404.Sum of Left Leaves/Solution.c
solution/0400-0499/0404.Sum of Left Leaves/Solution.go
solution/0400-0499/0404.Sum of Left Leaves/Solution.java
solution/0400-0499/0404.Sum of Left Leaves/Solution.py
solution/0400-0499/0404.Sum of Left Leaves/Solution2.go
solution/0400-0499/0404.Sum of Left Leaves/Solution2.java
solution/0400-0499/0404.Sum of Left Leaves/Solution2.py
solution/0400-0499/0404.Sum of Left Leaves/Solution2.ts

feat: add solutions to lc problem: No.0404

---

solution/2000-2099/2075.Decode the Slanted Ciphertext/README.md
solution/2000-2099/2075.Decode the Slanted Ciphertext/README_EN.md
solution/2000-2099/2075.Decode the Slanted Ciphertext/Solution.cpp
solution/2000-2099/2075.Decode the Slanted Ciphertext/Solution.go
solution/2000-2099/2075.Decode the Slanted Ciphertext/Solution.ts

No.2075.Decode the Slanted Ciphertext

feat: add solutions to lc problem: No.2075

---

solution/1800-1899/1883.Minimum Skips to Arrive at Meeting On Time/README.md
solution/1800-1899/1883.Minimum Skips to Arrive at Meeting On Time/README_EN.md
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/README.md
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/README_EN.md
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.cpp
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.cs
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.go
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.py
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.rs
solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.ts

* No.1883.Minimum Skips to Arrive at Meeting On Time
* No.3119.Maximum Number of Potholes That Can Be Fixed

feat: update solutions to lc problems: No.1883,3119

---

solution/0800-0899/0875.Koko Eating Bananas/README.md
solution/0800-0899/0875.Koko Eating Bananas/README_EN.md
solution/0800-0899/0875.Koko Eating Bananas/Solution.cpp
solution/0800-0899/0875.Koko Eating Bananas/Solution.cs
solution/0800-0899/0875.Koko Eating Bananas/Solution.go
solution/0800-0899/0875.Koko Eating Bananas/Solution.java
solution/0800-0899/0875.Koko Eating Bananas/Solution.py
solution/0800-0899/0875.Koko Eating Bananas/Solution.rs
solution/0800-0899/0875.Koko Eating Bananas/Solution.ts
solution/CONTEST_README.md
solution/template.md

feat: add solutions to lc problem: No.0875

---

solution/2100-2199/2198.Number of Single Divisor Triplets/README.md
solution/2100-2199/2198.Number of Single Divisor Triplets/README_EN.md
solution/2100-2199/2198.Number of Single Divisor Triplets/Solution.cpp
solution/2100-2199/2198.Number of Single Divisor Triplets/Solution.go
solution/2100-2199/2198.Number of Single Divisor Triplets/Solution.java
solution/2100-2199/2198.Number of Single Divisor Triplets/Solution.py
solution/2100-2199/2198.Number of Single Divisor Triplets/Solution.ts

No.2198.Number of Single Divisor Triplets

feat: add solutions to lc problem: No.2197

---

.github/workflows/black-lint.yml
.github/workflows/clang-format-lint.yml
.github/workflows/compress.yml
.github/workflows/deploy.yml
.github/workflows/pr-add-label.yml
.github/workflows/pr-checker.yml
.github/workflows/prettier.yml

Hey! 🙂
I want to contribute the following changes to your workflow:
- Avoid deploying from forks
- Avoid running CI related actions when no source code has changed
- Stop running workflows when there is a newer commit in PR
- Stop running workflows when there is a newer commit in branch
These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)

Fix potential github action smells

---

solution/0700-0799/0742.Closest Leaf in a Binary Tree/README.md
solution/0700-0799/0742.Closest Leaf in a Binary Tree/README_EN.md
solution/0700-0799/0742.Closest Leaf in a Binary Tree/Solution.cpp
solution/0700-0799/0742.Closest Leaf in a Binary Tree/Solution.go
solution/0700-0799/0742.Closest Leaf in a Binary Tree/Solution.java
solution/0700-0799/0742.Closest Leaf in a Binary Tree/Solution.py

No.0742.Closest Leaf in a Binary Tree

feat: add solutions to lc problem: No.0742

---

solution/2700-2799/2708.Maximum Strength of a Group/README.md
solution/2700-2799/2708.Maximum Strength of a Group/README_EN.md
solution/2700-2799/2708.Maximum Strength of a Group/Solution.cpp
solution/2700-2799/2708.Maximum Strength of a Group/Solution.go
solution/2700-2799/2708.Maximum Strength of a Group/Solution.java
solution/2700-2799/2708.Maximum Strength of a Group/Solution.py
solution/2700-2799/2708.Maximum Strength of a Group/Solution.ts
solution/2700-2799/2708.Maximum Strength of a Group/Solution2.cpp
solution/2700-2799/2708.Maximum Strength of a Group/Solution2.go
solution/2700-2799/2708.Maximum Strength of a Group/Solution2.java
solution/2700-2799/2708.Maximum Strength of a Group/Solution2.py
solution/2700-2799/2708.Maximum Strength of a Group/Solution2.ts
solution/2700-2799/2771.Longest Non-decreasing Subarray From Two Arrays/README.md
solution/2700-2799/2771.Longest Non-decreasing Subarray From Two Arrays/README_EN.md
solution/2700-2799/2773.Height of Special Binary Tree/README_EN.md
solution/3100-3199/3140.Consecutive Available Seats II/README.md
solution/3100-3199/3140.Consecutive Available Seats II/README_EN.md
solution/3100-3199/3140.Consecutive Available Seats II/Solution.sql

No.2708.Maximum Strength of a Group

feat: add solutions to lc problem: No.2708

---

solution/2000-2099/2079.Watering Plants/README.md
solution/2000-2099/2079.Watering Plants/README_EN.md
solution/2000-2099/2079.Watering Plants/Solution.c
solution/2000-2099/2079.Watering Plants/Solution.cpp
solution/2000-2099/2079.Watering Plants/Solution.go
solution/2000-2099/2079.Watering Plants/Solution.java
solution/2000-2099/2079.Watering Plants/Solution.py
solution/2000-2099/2079.Watering Plants/Solution.rs
solution/2000-2099/2079.Watering Plants/Solution.ts

feat: add solutions to lc problem: No.2079

---

solution/0400-0499/0477.Total Hamming Distance/README.md
solution/0400-0499/0477.Total Hamming Distance/README_EN.md
solution/0400-0499/0477.Total Hamming Distance/Solution.cpp
solution/0400-0499/0477.Total Hamming Distance/Solution.go
solution/0400-0499/0477.Total Hamming Distance/Solution.java
solution/0400-0499/0477.Total Hamming Distance/Solution.py
solution/0400-0499/0477.Total Hamming Distance/Solution.rs
solution/0400-0499/0477.Total Hamming Distance/Solution.ts

No.0477.Total Hamming Distance

feat: add solutions to lc problem: No.0477

---

solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/README.md
solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/README_EN.md
solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/Solution.cpp
solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/Solution.py
solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/Solution2.cpp
solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/Solution2.java
solution/2100-2199/2102.Sequentially Ordinal Rank Tracker/Solution2.py
solution/2100-2199/2125.Number of Laser Beams in a Bank/README.md
solution/2100-2199/2125.Number of Laser Beams in a Bank/README_EN.md
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.c
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.cpp
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.go
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.java
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.py
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.rs
solution/2100-2199/2125.Number of Laser Beams in a Bank/Solution.ts

No.2102.Sequentially Ordinal Rank Tracker

feat: add solutions to lc problem: No.2102

---

solution/2100-2199/2191.Sort the Jumbled Numbers/README.md
solution/2100-2199/2191.Sort the Jumbled Numbers/README_EN.md
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.cpp
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.cs
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.go
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.java
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.py
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.rs
solution/2100-2199/2191.Sort the Jumbled Numbers/Solution.ts
solution/2100-2199/2194.Cells in a Range on an Excel Sheet/README.md
solution/2100-2199/2194.Cells in a Range on an Excel Sheet/README_EN.md
solution/2100-2199/2194.Cells in a Range on an Excel Sheet/Solution.cpp
solution/2100-2199/2194.Cells in a Range on an Excel Sheet/Solution.go
solution/2100-2199/2194.Cells in a Range on an Excel Sheet/Solution.ts

* No.2191.Sort the Jumbled Numbers
* No.2194.Cells in a Range on an Excel Sheet

feat: add solutions to lc problems: No.2191,2194

---

solution/0900-0999/0994.Rotting Oranges/README.md
solution/0900-0999/0994.Rotting Oranges/README_EN.md
solution/0900-0999/0994.Rotting Oranges/Solution.cpp
solution/0900-0999/0994.Rotting Oranges/Solution.go
solution/0900-0999/0994.Rotting Oranges/Solution.java
solution/0900-0999/0994.Rotting Oranges/Solution.py
solution/0900-0999/0994.Rotting Oranges/Solution.rs
solution/0900-0999/0994.Rotting Oranges/Solution.ts
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/README.md
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/README_EN.md
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/Solution.cpp
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/Solution.go
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/Solution.java
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/Solution.py
solution/3100-3199/3147.Taking Maximum Energy From the Mystic Dungeon/Solution.ts

* No.0994.Rotting Oranges
* No.3147.Taking Maximum Energy From the Mystic Dungeon

feat: add solutions to lc problems: No.0994,3147

---

solution/3100-3199/3149.Find the Minimum Cost Array Permutation/README.md
solution/3100-3199/3149.Find the Minimum Cost Array Permutation/README_EN.md
solution/3100-3199/3149.Find the Minimum Cost Array Permutation/Solution.cpp
solution/3100-3199/3149.Find the Minimum Cost Array Permutation/Solution.go
solution/3100-3199/3149.Find the Minimum Cost Array Permutation/Solution.java
solution/3100-3199/3149.Find the Minimum Cost Array Permutation/Solution.py
solution/3100-3199/3149.Find the Minimum Cost Array Permutation/Solution.ts

No.3149.Find the Minimum Cost Array Permutation

feat: add solutions to lc problem: No.3149

---

solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/README.md
solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/README_EN.md
solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/Solution.cpp
solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/Solution.go
solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/Solution.java
solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/Solution.py
solution/3100-3199/3144.Minimum Substring Partition of Equal Character Frequency/Solution.ts

No.3144.Minimum Substring Partition of Equal Character Frequency

feat: add solutions to lc problem: No.3144

---

lcp/LCP 34. 二叉树染色/README.md
lcp/LCP 52. 二叉搜索树染色/README.md
lcp/LCP 61. 气温变化趋势/README.md
lcp/LCP 74. 最强祝福力场/README.md
lcp/LCP 80. 生物进化录/README.md
solution/1900-1999/1953.Maximum Number of Weeks for Which You Can Work/README.md
solution/1900-1999/1953.Maximum Number of Weeks for Which You Can Work/README_EN.md
solution/1900-1999/1953.Maximum Number of Weeks for Which You Can Work/Solution.ts

No.1953.Maximum Number of Weeks for Which You Can Work

feat: add solutions to lc problem: No.1953

---

solution/0800-0899/0826.Most Profit Assigning Work/README.md
solution/0800-0899/0826.Most Profit Assigning Work/README_EN.md
solution/0800-0899/0826.Most Profit Assigning Work/Solution.cpp
solution/0800-0899/0826.Most Profit Assigning Work/Solution.go
solution/0800-0899/0826.Most Profit Assigning Work/Solution.java
solution/0800-0899/0826.Most Profit Assigning Work/Solution.py
solution/0800-0899/0826.Most Profit Assigning Work/Solution.ts

No.0826.Most Profit Assigning Work

feat: add solutions to lc problem: No.0826

---

solution/3100-3199/3151.Special Array I/README.md
solution/3100-3199/3151.Special Array I/README_EN.md
solution/3100-3199/3151.Special Array I/Solution.cpp
solution/3100-3199/3151.Special Array I/Solution.go
solution/3100-3199/3151.Special Array I/Solution.java
solution/3100-3199/3151.Special Array I/Solution.py
solution/3100-3199/3151.Special Array I/Solution.ts
solution/3100-3199/3152.Special Array II/README.md
solution/3100-3199/3152.Special Array II/README_EN.md
solution/3100-3199/3152.Special Array II/Solution.cpp
solution/3100-3199/3152.Special Array II/Solution.go
solution/3100-3199/3152.Special Array II/Solution.java
solution/3100-3199/3152.Special Array II/Solution.py
solution/3100-3199/3152.Special Array II/Solution.ts
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/README.md
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/README_EN.md
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/Solution.cpp
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/Solution.go
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/Solution.java
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/Solution.py
solution/3100-3199/3153.Sum of Digit Differences of All Pairs/Solution.ts

* No.3151.Special Array I
* No.3152.Special Array II
* No.3153.Sum of Digit Differences of All Pairs

feat: add solutions to lc problems: No.3151~3153

---

solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/README.md
solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/README_EN.md
solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/Solution.cpp
solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/Solution.go
solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/Solution.java
solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/Solution.py
solution/3100-3199/3154.Find Number of Ways to Reach the K-th Stair/Solution.ts

No.3154.Find Number of Ways to Reach the K-th Stair

feat: add solutions to lc problem: No.3154

---

solution/3100-3199/3152.Special Array II/README_EN.md
solution/3100-3199/3155.Maximum Number of Upgradable Servers/README.md
solution/3100-3199/3155.Maximum Number of Upgradable Servers/README_EN.md
solution/3100-3199/3155.Maximum Number of Upgradable Servers/Solution.cpp
solution/3100-3199/3155.Maximum Number of Upgradable Servers/Solution.go
solution/3100-3199/3155.Maximum Number of Upgradable Servers/Solution.java
solution/3100-3199/3155.Maximum Number of Upgradable Servers/Solution.py
solution/3100-3199/3155.Maximum Number of Upgradable Servers/Solution.ts
solution/README.md
solution/README_EN.md

No.3155.Maximum Number of Upgradable Servers

feat: add solutions to lc problem: No.3155

---

solution/1300-1399/1317.Convert Integer to the Sum of Two No-Zero Integers/README.md
solution/1300-1399/1317.Convert Integer to the Sum of Two No-Zero Integers/README_EN.md
solution/1300-1399/1317.Convert Integer to the Sum of Two No-Zero Integers/Solution.ts
solution/1300-1399/1317.Convert Integer to the Sum of Two No-Zero Integers/Solution2.ts
solution/3000-3099/3068.Find the Maximum Sum of Node Values/README.md
solution/3000-3099/3068.Find the Maximum Sum of Node Values/README_EN.md
solution/3000-3099/3068.Find the Maximum Sum of Node Values/Solution.cpp

No.1317.Convert Integer to the Sum of Two No-Zero Integers

feat: add solutions to lc problem: No.1317

---

solution/2700-2799/2705.Compact Object/README.md
solution/2700-2799/2705.Compact Object/README_EN.md
solution/2700-2799/2705.Compact Object/Solution.js
solution/2700-2799/2705.Compact Object/Solution.ts

feat: update solutions to lc problem: No.2705

---

solution/0600-0699/0691.Stickers to Spell Word/README.md
solution/0600-0699/0691.Stickers to Spell Word/README_EN.md
solution/0600-0699/0691.Stickers to Spell Word/Solution.cpp
solution/0600-0699/0691.Stickers to Spell Word/Solution.go
solution/0600-0699/0691.Stickers to Spell Word/Solution.java
solution/0600-0699/0691.Stickers to Spell Word/Solution.py
solution/0600-0699/0691.Stickers to Spell Word/Solution.ts

No.0691.Stickers to Spell Word

feat: add solutions to lc problem: No.691

---

solution/1900-1999/1971.Find if Path Exists in Graph/README.md
solution/1900-1999/1971.Find if Path Exists in Graph/README_EN.md
solution/1900-1999/1971.Find if Path Exists in Graph/Solution.cpp
solution/1900-1999/1971.Find if Path Exists in Graph/Solution.java
solution/1900-1999/1971.Find if Path Exists in Graph/Solution.py
solution/1900-1999/1971.Find if Path Exists in Graph/Solution.ts
solution/1900-1999/1971.Find if Path Exists in Graph/Solution2.cpp
solution/1900-1999/1971.Find if Path Exists in Graph/Solution2.go
solution/1900-1999/1971.Find if Path Exists in Graph/Solution2.java
solution/1900-1999/1971.Find if Path Exists in Graph/Solution2.py
solution/1900-1999/1971.Find if Path Exists in Graph/Solution2.rs
solution/1900-1999/1971.Find if Path Exists in Graph/Solution2.ts
solution/1900-1999/1971.Find if Path Exists in Graph/Solution3.cpp
solution/1900-1999/1971.Find if Path Exists in Graph/Solution3.go
solution/1900-1999/1971.Find if Path Exists in Graph/Solution3.java
solution/1900-1999/1971.Find if Path Exists in Graph/Solution3.py
solution/1900-1999/1971.Find if Path Exists in Graph/Solution3.ts

I didn't add solution into README.md, because I don't know chinese, and it was hard to understand srtucture of the doc.
PLease did it by yourself

feat: add solutions to lc problem: No.1971

---

solution/2000-2099/2028.Find Missing Observations/README.md
solution/2000-2099/2028.Find Missing Observations/README_EN.md
solution/2000-2099/2028.Find Missing Observations/Solution.cpp
solution/2000-2099/2028.Find Missing Observations/Solution.rs
solution/2000-2099/2028.Find Missing Observations/Solution.ts

No.2028.Find Missing Observations

feat: update solutions to lc problem: No.2028

---

solution/3100-3199/3163.String Compression III/README.md
solution/3100-3199/3163.String Compression III/README_EN.md
solution/3100-3199/3163.String Compression III/Solution.cpp
solution/3100-3199/3163.String Compression III/Solution.go
solution/3100-3199/3163.String Compression III/Solution.java
solution/3100-3199/3163.String Compression III/Solution.py
solution/3100-3199/3163.String Compression III/Solution.ts

No.3163.String Compression III

feat: add solutions to lc problem: No.3163

---

lcof/面试题56 - II. 数组中数字出现的次数 II/README.md
lcof/面试题57 - II. 和为s的连续正数序列/README.md
lcof/面试题57. 和为s的两个数字/README.md
lcof/面试题58 - I. 翻转单词顺序/README.md
lcof/面试题59 - I. 滑动窗口的最大值/README.md
lcof/面试题59 - II. 队列的最大值/README.md
solution/3100-3199/3167.Better Compression of String/README.md
solution/3100-3199/3167.Better Compression of String/README_EN.md
solution/3100-3199/3167.Better Compression of String/Solution.cpp
solution/3100-3199/3167.Better Compression of String/Solution.go
solution/3100-3199/3167.Better Compression of String/Solution.java
solution/3100-3199/3167.Better Compression of String/Solution.py
solution/3100-3199/3167.Better Compression of String/Solution.ts
solution/README.md
solution/README_EN.md

No.3167.Better Compression of String

feat: add solutions to lc problem: No.3167

---

solution/0200-0299/0290.Word Pattern/README.md
solution/0200-0299/0290.Word Pattern/README_EN.md
solution/0200-0299/0290.Word Pattern/Solution2.ts

Hello,
This new TS solution is the same as solution 1, but with a simplified algorithm.
And if it will be just closed, I will not upset too match)
Also if it will be approved, please add description into chinese version of README
Thx :)

feat: add TS solution to lc problem No.290

---

solution/0300-0399/0367.Valid Perfect Square/README.md
solution/0300-0399/0367.Valid Perfect Square/README_EN.md
solution/0300-0399/0367.Valid Perfect Square/Solution.cpp
solution/0300-0399/0367.Valid Perfect Square/Solution.go
solution/0300-0399/0367.Valid Perfect Square/Solution.java
solution/0300-0399/0367.Valid Perfect Square/Solution.py
solution/0300-0399/0367.Valid Perfect Square/Solution.rs
solution/0300-0399/0367.Valid Perfect Square/Solution.ts
solution/0300-0399/0367.Valid Perfect Square/Solution2.cpp

feat: update solutions to lc problem: No.367

---

solution/0300-0399/0379.Design Phone Directory/README.md
solution/0300-0399/0379.Design Phone Directory/README_EN.md
solution/0300-0399/0379.Design Phone Directory/Solution.cpp
solution/0300-0399/0379.Design Phone Directory/Solution.go
solution/0300-0399/0379.Design Phone Directory/Solution.java
solution/0300-0399/0379.Design Phone Directory/Solution.py
solution/0300-0399/0379.Design Phone Directory/Solution.ts

No.0379.Design Phone Directory

feat: add solutions to lc problem: No.379

---

solution/0300-0399/0393.UTF-8 Validation/README.md
solution/0300-0399/0393.UTF-8 Validation/README_EN.md
solution/0300-0399/0393.UTF-8 Validation/Solution.cpp
solution/0300-0399/0393.UTF-8 Validation/Solution.go
solution/0300-0399/0393.UTF-8 Validation/Solution.java
solution/0300-0399/0393.UTF-8 Validation/Solution.py
solution/0300-0399/0393.UTF-8 Validation/Solution.ts

feat: add solutions to lc problem: No.393

---

solution/0400-0499/0424.Longest Repeating Character Replacement/README.md
solution/0400-0499/0424.Longest Repeating Character Replacement/README_EN.md
solution/0400-0499/0424.Longest Repeating Character Replacement/Solution.cpp
solution/0400-0499/0424.Longest Repeating Character Replacement/Solution.go
solution/0400-0499/0424.Longest Repeating Character Replacement/Solution.java
solution/0400-0499/0424.Longest Repeating Character Replacement/Solution.py
solution/0400-0499/0424.Longest Repeating Character Replacement/Solution.ts

No.0424.Longest Repeating Character Replacement

feat: add solutions to lc problem: No.424

---

solution/0400-0499/0436.Find Right Interval/README.md
solution/0400-0499/0436.Find Right Interval/README_EN.md
solution/0400-0499/0436.Find Right Interval/Solution.cpp
solution/0400-0499/0436.Find Right Interval/Solution.go
solution/0400-0499/0436.Find Right Interval/Solution.java
solution/0400-0499/0436.Find Right Interval/Solution.py
solution/0400-0499/0436.Find Right Interval/Solution.ts

feat: update solutions to lc problem: No.436

---

solution/0400-0499/0454.4Sum II/README.md
solution/0400-0499/0454.4Sum II/README_EN.md
solution/0400-0499/0454.4Sum II/Solution.rs
solution/0400-0499/0454.4Sum II/Solution.ts

feat: add solutions to lc problem: No.454

---

lcof2/剑指 Offer II 025. 链表中的两数相加/README.md
lcof2/剑指 Offer II 026. 重排链表/README.md
lcof2/剑指 Offer II 030. 插入、删除和随机访问都是 O(1) 的容器/README.md
lcof2/剑指 Offer II 032. 有效的变位词/README.md
lcof2/剑指 Offer II 033. 变位词组/README.md
lcof2/剑指 Offer II 034. 外星语言是否排序/README.md
lcof2/剑指 Offer II 035. 最小时间差/README.md
solution/0000-0099/0088.Merge Sorted Array/README.md
solution/0000-0099/0088.Merge Sorted Array/README_EN.md
solution/0000-0099/0088.Merge Sorted Array/Solution.rs
solution/0000-0099/0088.Merge Sorted Array/Solution2.ts
solution/0400-0499/0455.Assign Cookies/README_EN.md
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/README.md
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/README_EN.md
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/Solution.cpp
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/Solution.go
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/Solution.java
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/Solution.py
solution/3100-3199/3173.Bitwise OR of Adjacent Elements/Solution.ts
solution/README.md
solution/README_EN.md

No.3173.Bitwise OR of Adjacent Elements

feat: add solutions to lc problem: No.3173

---

solution/2700-2799/2786.Visit Array Positions to Maximize Score/README.md
solution/2700-2799/2786.Visit Array Positions to Maximize Score/README_EN.md
solution/2700-2799/2786.Visit Array Positions to Maximize Score/Solution.cpp
solution/2700-2799/2786.Visit Array Positions to Maximize Score/Solution.go
solution/2700-2799/2786.Visit Array Positions to Maximize Score/Solution.java
solution/2700-2799/2786.Visit Array Positions to Maximize Score/Solution.py
solution/2700-2799/2786.Visit Array Positions to Maximize Score/Solution.ts

No.2786.Visit Array Positions to Maximize Score

feat: update solutions to lc problem: No.2786

---

solution/2000-2099/2037.Minimum Number of Moves to Seat Everyone/README.md
solution/2000-2099/2037.Minimum Number of Moves to Seat Everyone/README_EN.md
solution/2000-2099/2037.Minimum Number of Moves to Seat Everyone/Solution.ts
solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/README.md
solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/README_EN.md
solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/Solution.cpp
solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/Solution.go
solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/Solution.java
solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/Solution.py

No.2040.Kth Smallest Product of Two Sorted Arrays

feat: add solutions to lc problem: No.2040

---

solution/0500-0599/0522.Longest Uncommon Subsequence II/README.md
solution/0500-0599/0522.Longest Uncommon Subsequence II/README_EN.md
solution/0500-0599/0522.Longest Uncommon Subsequence II/Solution.cpp
solution/0500-0599/0522.Longest Uncommon Subsequence II/Solution.go
solution/0500-0599/0522.Longest Uncommon Subsequence II/Solution.java
solution/0500-0599/0522.Longest Uncommon Subsequence II/Solution.py
solution/0500-0599/0522.Longest Uncommon Subsequence II/Solution.ts

No.0522.Longest Uncommon Subsequence II

feat: add solutions to lc problem: No.522

---

solution/0500-0599/0524.Longest Word in Dictionary through Deleting/README.md
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/README_EN.md
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/Solution.cpp
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/Solution.go
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/Solution.java
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/Solution.py
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/Solution.rs
solution/0500-0599/0524.Longest Word in Dictionary through Deleting/Solution.ts
solution/0500-0599/0525.Contiguous Array/README.md
solution/0500-0599/0525.Contiguous Array/README_EN.md
solution/0500-0599/0525.Contiguous Array/Solution.cpp
solution/0500-0599/0525.Contiguous Array/Solution.go
solution/0500-0599/0525.Contiguous Array/Solution.java
solution/0500-0599/0525.Contiguous Array/Solution.py
solution/0500-0599/0525.Contiguous Array/Solution.ts

* No.0524.Longest Word in Dictionary through Deleting
* No.0525.Contiguous Array

feat: add solutions to lc problems: No.524,525

---

solution/2200-2299/2288.Apply Discount to Prices/README.md
solution/2200-2299/2288.Apply Discount to Prices/README_EN.md
solution/2200-2299/2288.Apply Discount to Prices/Solution.ts
solution/3100-3199/3187.Peaks in Array/README.md
solution/3100-3199/3187.Peaks in Array/README_EN.md
solution/3100-3199/3187.Peaks in Array/Solution.cpp
solution/3100-3199/3187.Peaks in Array/Solution.go
solution/3100-3199/3187.Peaks in Array/Solution.java
solution/3100-3199/3187.Peaks in Array/Solution.py
solution/3100-3199/3187.Peaks in Array/Solution.ts

feat: add solutions to lc problem: No.3187

---

solution/0600-0699/0637.Average of Levels in Binary Tree/README.md
solution/0600-0699/0637.Average of Levels in Binary Tree/README_EN.md
solution/0600-0699/0637.Average of Levels in Binary Tree/Solution.cpp
solution/0600-0699/0637.Average of Levels in Binary Tree/Solution.js
solution/0600-0699/0637.Average of Levels in Binary Tree/Solution.rs
solution/0600-0699/0637.Average of Levels in Binary Tree/Solution2.js

No.0637.Average of Levels in Binary Tree

feat: update solutions to lc problem: No.637

---

solution/3100-3199/3188.Find Top Scoring Students II/README.md
solution/3100-3199/3188.Find Top Scoring Students II/README_EN.md
solution/3100-3199/3188.Find Top Scoring Students II/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3188.Find Top Scoring Students II

feat: add solutions to lc problem: No.3188

---

lcp/LCP 61. 气温变化趋势/README.md
lcp/LCP 61. 气温变化趋势/Solution.py
lcp/LCP 61. 气温变化趋势/Solution.rs
lcp/LCP 61. 气温变化趋势/Solution.ts

feat: add solutions to lcp problem: No.61

---

solution/1200-1299/1248.Count Number of Nice Subarrays/README.md
solution/1200-1299/1248.Count Number of Nice Subarrays/README_EN.md
solution/1200-1299/1248.Count Number of Nice Subarrays/Solution.ts
solution/1200-1299/1252.Cells with Odd Values in a Matrix/README.md
solution/1200-1299/1252.Cells with Odd Values in a Matrix/README_EN.md
solution/1200-1299/1252.Cells with Odd Values in a Matrix/Solution.cpp
solution/1200-1299/1252.Cells with Odd Values in a Matrix/Solution2.cpp
solution/1200-1299/1252.Cells with Odd Values in a Matrix/Solution3.cpp

* No.1248.Count Number of Nice Subarrays
* No.1252.Cells with Odd Values in a Matrix

feat: update solutions to lc problems: No.1248,1252

---

.prettierignore
.prettierrc
solution/2100-2199/2101.Detonate the Maximum Bombs/README.md
solution/2100-2199/2101.Detonate the Maximum Bombs/README_EN.md
solution/2100-2199/2101.Detonate the Maximum Bombs/Solution.cpp
solution/2100-2199/2101.Detonate the Maximum Bombs/Solution.go
solution/2100-2199/2101.Detonate the Maximum Bombs/Solution.java
solution/2100-2199/2101.Detonate the Maximum Bombs/Solution.py
solution/2100-2199/2101.Detonate the Maximum Bombs/Solution.ts

No.2101.Detonate the Maximum Bombs

feat: add solutions to lc problem: No.2101

---

solution/2100-2199/2135.Count Words Obtained After Adding a Letter/README.md
solution/2100-2199/2135.Count Words Obtained After Adding a Letter/README_EN.md
solution/2100-2199/2135.Count Words Obtained After Adding a Letter/Solution.cpp
solution/2100-2199/2135.Count Words Obtained After Adding a Letter/Solution.go
solution/2100-2199/2135.Count Words Obtained After Adding a Letter/Solution.java
solution/2100-2199/2135.Count Words Obtained After Adding a Letter/Solution.py
solution/2100-2199/2135.Count Words Obtained After Adding a Letter/Solution.ts
solution/2100-2199/2136.Earliest Possible Day of Full Bloom/README_EN.md
solution/2100-2199/2137.Pour Water Between Buckets to Make Water Levels Equal/README_EN.md

* No.2135.Count Words Obtained After Adding a Letter
* No.2136.Earliest Possible Day of Full Bloom
* No.2137.Pour Water Between Buckets to Make Water Levels Equal

feat: add solutions to lc problems: No.2135~2137

---

solution/2100-2199/2138.Divide a String Into Groups of Size k/README.md
solution/2100-2199/2138.Divide a String Into Groups of Size k/README_EN.md
solution/2100-2199/2138.Divide a String Into Groups of Size k/Solution.cpp
solution/2100-2199/2138.Divide a String Into Groups of Size k/Solution.go
solution/2100-2199/2138.Divide a String Into Groups of Size k/Solution.ts
solution/2100-2199/2140.Solving Questions With Brainpower/README_EN.md
solution/2100-2199/2141.Maximum Running Time of N Computers/README_EN.md
solution/2100-2199/2144.Minimum Cost of Buying Candies With Discount/README_EN.md

* No.2138.Divide a String Into Groups of Size k
* No.2140.Solving Questions With Brainpower
* No.2141.Maximum Running Time of N Computers

feat: add solutions to lc problems: No.2138,2140,2141

---

.prettierignore
solution/3100-3199/3198.Find Cities in Each State/README.md
solution/3100-3199/3198.Find Cities in Each State/README_EN.md
solution/3100-3199/3198.Find Cities in Each State/Solution.py
solution/3100-3199/3198.Find Cities in Each State/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3198.Find Cities in Each State

feat: add solutions to lc problem: No.3198

---

solution/0300-0399/0349.Intersection of Two Arrays/README.md
solution/0300-0399/0349.Intersection of Two Arrays/README_EN.md
solution/0300-0399/0349.Intersection of Two Arrays/Solution.js
solution/0300-0399/0349.Intersection of Two Arrays/Solution.php
solution/0300-0399/0349.Intersection of Two Arrays/Solution.ts
solution/0300-0399/0349.Intersection of Two Arrays/Solution2.js
solution/0300-0399/0349.Intersection of Two Arrays/solution.cs
solution/2200-2299/2285.Maximum Total Importance of Roads/README.md
solution/2200-2299/2285.Maximum Total Importance of Roads/README_EN.md
solution/2200-2299/2285.Maximum Total Importance of Roads/Solution.cpp
solution/2200-2299/2285.Maximum Total Importance of Roads/Solution.go
solution/2200-2299/2285.Maximum Total Importance of Roads/Solution.ts

* No.0349.Intersection of Two Arrays
* No.2285.Maximum Total Importance of Roads

feat: add solutions to lc problems: No.0349,2285

---

solution/0500-0599/0594.Longest Harmonious Subsequence/README.md
solution/0500-0599/0594.Longest Harmonious Subsequence/README_EN.md
solution/0500-0599/0594.Longest Harmonious Subsequence/Solution.cpp
solution/0500-0599/0594.Longest Harmonious Subsequence/Solution.go
solution/0500-0599/0594.Longest Harmonious Subsequence/Solution.java
solution/0500-0599/0594.Longest Harmonious Subsequence/Solution.py
solution/0500-0599/0594.Longest Harmonious Subsequence/Solution.ts
solution/0500-0599/0594.Longest Harmonious Subsequence/Solution2.py

No.0594.Longest Harmonious Subsequence

feat: add solutions to lc problem: No.0594

---

solution/3100-3199/3138.Minimum Length of Anagram Concatenation/README.md
solution/3100-3199/3138.Minimum Length of Anagram Concatenation/README_EN.md
solution/3100-3199/3138.Minimum Length of Anagram Concatenation/Solution.cpp
solution/3100-3199/3138.Minimum Length of Anagram Concatenation/Solution.go
solution/3100-3199/3138.Minimum Length of Anagram Concatenation/Solution.java
solution/3100-3199/3138.Minimum Length of Anagram Concatenation/Solution.py
solution/3100-3199/3138.Minimum Length of Anagram Concatenation/Solution.ts

No.3138. Minimum Length of Anagram Concatenation

feat: add solutions to lc problem: No.3138

---

solution/2000-2099/2065.Maximum Path Quality of a Graph/README.md
solution/2000-2099/2065.Maximum Path Quality of a Graph/README_EN.md
solution/2000-2099/2065.Maximum Path Quality of a Graph/Solution.cpp
solution/2000-2099/2065.Maximum Path Quality of a Graph/Solution.go
solution/2000-2099/2065.Maximum Path Quality of a Graph/Solution.java
solution/2000-2099/2065.Maximum Path Quality of a Graph/Solution.py
solution/2000-2099/2065.Maximum Path Quality of a Graph/Solution.ts

No.2065.Maximum Path Quality of a Graph

feat: add solutions to lc problem: No.2065

---

solution/2200-2299/2295.Replace Elements in an Array/README_EN.md
solution/2200-2299/2296.Design a Text Editor/README.md
solution/2200-2299/2296.Design a Text Editor/README_EN.md
solution/2200-2299/2296.Design a Text Editor/Solution.ts

feat: add solutions to lc problem: No.2296

---

solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/README.md
solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/README_EN.md
solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/Solution.cpp
solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/Solution.go
solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/Solution.java
solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/Solution.py
solution/3200-3299/3201.Find the Maximum Length of Valid Subsequence I/Solution.ts
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/README.md
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/README_EN.md
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/Solution.cpp
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/Solution.go
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/Solution.java
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/Solution.py
solution/3200-3299/3202.Find the Maximum Length of Valid Subsequence II/Solution.ts

* No.3201.Find the Maximum Length of Valid Subsequence I
* No.3202.Find the Maximum Length of Valid Subsequence II

feat: add solutions to lc problems: No.3201,3202

---

solution/3000-3099/3086.Minimum Moves to Pick K Ones/README.md
solution/3000-3099/3086.Minimum Moves to Pick K Ones/README_EN.md
solution/3000-3099/3086.Minimum Moves to Pick K Ones/Solution.cpp
solution/3000-3099/3086.Minimum Moves to Pick K Ones/Solution.go
solution/3000-3099/3086.Minimum Moves to Pick K Ones/Solution.java
solution/3000-3099/3086.Minimum Moves to Pick K Ones/Solution.py
solution/3000-3099/3086.Minimum Moves to Pick K Ones/Solution.ts

No.3086.Minimum Moves to Pick K Ones

feat: add solutions to lc problem: No.3086

---

solution/3200-3299/3205.Maximum Array Hopping Score I/README.md
solution/3200-3299/3205.Maximum Array Hopping Score I/README_EN.md
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution.cpp
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution.go
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution.java
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution.py
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution.ts
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution2.cpp
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution2.go
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution2.java
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution2.py
solution/3200-3299/3205.Maximum Array Hopping Score I/Solution2.ts
solution/README.md
solution/README_EN.md

No.3205.Maximum Array Hopping Score I

feat: add solutions to lc problem: No.3205

---

solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/README.md
solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/README_EN.md
solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/Solution.cpp
solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/Solution.go
solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/Solution.java
solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/Solution.py
solution/2000-2099/2058.Find the Minimum and Maximum Number of Nodes Between Critical Points/Solution.ts

No.2058.Find the Minimum and Maximum Number of Nodes Between Critical Points

feat: update solutions to lc problem: No.2058

---

solution/0900-0999/0942.DI String Match/README.md
solution/0900-0999/0942.DI String Match/README_EN.md
solution/0900-0999/0942.DI String Match/Solution.go
solution/0900-0999/0942.DI String Match/Solution.py
solution/0900-0999/0942.DI String Match/Solution.rs
solution/0900-0999/0942.DI String Match/Solution.ts

feat: update solutions to lc problem: No.0942

---

solution/0900-0999/0944.Delete Columns to Make Sorted/README.md
solution/0900-0999/0944.Delete Columns to Make Sorted/README_EN.md
solution/0900-0999/0944.Delete Columns to Make Sorted/Solution.cpp
solution/0900-0999/0944.Delete Columns to Make Sorted/Solution.go
solution/0900-0999/0944.Delete Columns to Make Sorted/Solution.rs
solution/0900-0999/0944.Delete Columns to Make Sorted/Solution.ts

No.0944.Delete Columns to Make Sorted

feat: add solutions to lc problem: No.0944

---

solution/3200-3299/3207.Maximum Points After Enemy Battles/README.md
solution/3200-3299/3207.Maximum Points After Enemy Battles/README_EN.md
solution/3200-3299/3207.Maximum Points After Enemy Battles/Solution.cpp
solution/3200-3299/3207.Maximum Points After Enemy Battles/Solution.go
solution/3200-3299/3207.Maximum Points After Enemy Battles/Solution.java
solution/3200-3299/3207.Maximum Points After Enemy Battles/Solution.py
solution/3200-3299/3207.Maximum Points After Enemy Battles/Solution.ts

No.3207.Maximum Points After Enemy Battles

feat: add solutions to lc problem: No.3207

---

solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/README.md
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/README_EN.md
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution.cpp
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution.go
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution.java
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution.py
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution.ts
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution2.cpp
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution2.go
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution2.java
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution2.py
solution/3100-3199/3171.Find Subarray With Bitwise OR Closest to K/Solution2.ts
solution/3200-3299/3209.Number of Subarrays With AND Value of K/README.md
solution/3200-3299/3209.Number of Subarrays With AND Value of K/README_EN.md
solution/3200-3299/3209.Number of Subarrays With AND Value of K/Solution.cpp
solution/3200-3299/3209.Number of Subarrays With AND Value of K/Solution.go
solution/3200-3299/3209.Number of Subarrays With AND Value of K/Solution.java
solution/3200-3299/3209.Number of Subarrays With AND Value of K/Solution.py
solution/3200-3299/3209.Number of Subarrays With AND Value of K/Solution.ts

* No.3171.Find Subarray With Bitwise OR Closest to K
* No.3209.Number of Subarrays With AND Value of K

feat: update solutions to lc problems: No.3171,3209

---

lcof2/剑指 Offer II 070. 排序数组中只出现一次的数字/README.md
solution/1800-1899/1823.Find the Winner of the Circular Game/Solution.rs
solution/3200-3299/3214.Year on Year Growth Rate/README.md
solution/3200-3299/3214.Year on Year Growth Rate/README_EN.md
solution/3200-3299/3214.Year on Year Growth Rate/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3214.Year on Year Growth Rate

feat: add solutions to lc problem: No.3214

---

solution/0400-0499/0481.Magical String/README.md
solution/0400-0499/0481.Magical String/README_EN.md
solution/0400-0499/0481.Magical String/Solution.java
solution/0400-0499/0481.Magical String/Solution.py
solution/0400-0499/0481.Magical String/Solution.rs
solution/0400-0499/0481.Magical String/Solution.ts
solution/0400-0499/0482.License Key Formatting/README.md
solution/0400-0499/0482.License Key Formatting/README_EN.md
solution/0400-0499/0482.License Key Formatting/Solution.cpp
solution/0400-0499/0482.License Key Formatting/Solution.go
solution/0400-0499/0482.License Key Formatting/Solution.java
solution/0400-0499/0482.License Key Formatting/Solution.py
solution/0400-0499/0482.License Key Formatting/Solution.ts

* No.0481.Magical String
* No.0482.License Key Formatting

feat: add solutions to lc problems: No.0481,0482

---

solution/0400-0499/0485.Max Consecutive Ones/README.md
solution/0400-0499/0485.Max Consecutive Ones/README_EN.md
solution/0400-0499/0485.Max Consecutive Ones/Solution.cpp
solution/0400-0499/0485.Max Consecutive Ones/Solution.go
solution/0400-0499/0485.Max Consecutive Ones/Solution.java
solution/0400-0499/0485.Max Consecutive Ones/Solution.js
solution/0400-0499/0485.Max Consecutive Ones/Solution.php
solution/0400-0499/0485.Max Consecutive Ones/Solution.py
solution/0400-0499/0485.Max Consecutive Ones/Solution.rs
solution/0400-0499/0485.Max Consecutive Ones/Solution.ts

feat: add solutions to lc problem: No.0485

---

solution/2000-2099/2029.Stone Game IX/README.md
solution/2000-2099/2029.Stone Game IX/README_EN.md
solution/2000-2099/2029.Stone Game IX/Solution.cpp
solution/2000-2099/2029.Stone Game IX/Solution.go
solution/2000-2099/2029.Stone Game IX/Solution.java
solution/2000-2099/2029.Stone Game IX/Solution.py
solution/2000-2099/2029.Stone Game IX/Solution.ts

feat: add solutions to lc problem: No.2029

---

solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/README.md
solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/README_EN.md
solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/Solution.cpp
solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/Solution.go
solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/Solution.java
solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/Solution.py
solution/3200-3299/3215.Count Triplets with Even XOR Set Bits II/Solution.ts
solution/README.md
solution/README_EN.md

feat: add solutions to lc problem: No.3215

---

solution/0800-0899/0877.Stone Game/README.md
solution/0800-0899/0877.Stone Game/README_EN.md
solution/0800-0899/0877.Stone Game/Solution.cpp
solution/1800-1899/1859.Sorting the Sentence/README.md
solution/1800-1899/1859.Sorting the Sentence/README_EN.md
solution/1800-1899/1859.Sorting the Sentence/Solution.py
solution/1800-1899/1859.Sorting the Sentence/Solution2.py

* No.0877.Stone Game
* No.1859.Sorting the Sentence

feat: update solutions to lc problems: No.0877,1859

---

solution/0800-0899/0898.Bitwise ORs of Subarrays/README.md
solution/0800-0899/0898.Bitwise ORs of Subarrays/README_EN.md
solution/0800-0899/0898.Bitwise ORs of Subarrays/Solution.cpp
solution/0800-0899/0898.Bitwise ORs of Subarrays/Solution.go
solution/0800-0899/0898.Bitwise ORs of Subarrays/Solution.java
solution/0800-0899/0898.Bitwise ORs of Subarrays/Solution.py
solution/0800-0899/0898.Bitwise ORs of Subarrays/Solution.ts

No.0898.Bitwise ORs of Subarrays

feat: update solutions to lc problem: No.0898

---

solution/1700-1799/1717.Maximum Score From Removing Substrings/README.md
solution/1700-1799/1717.Maximum Score From Removing Substrings/README_EN.md
solution/1700-1799/1717.Maximum Score From Removing Substrings/Solution.cpp
solution/1700-1799/1717.Maximum Score From Removing Substrings/Solution.go
solution/1700-1799/1717.Maximum Score From Removing Substrings/Solution.java
solution/1700-1799/1717.Maximum Score From Removing Substrings/Solution.py
solution/1700-1799/1717.Maximum Score From Removing Substrings/Solution.ts

No.1717.Maximum Score From Removing Substrings

feat: add solutions to lc problem: No.1717

---

solution/0800-0899/0807.Max Increase to Keep City Skyline/README.md
solution/0800-0899/0807.Max Increase to Keep City Skyline/README_EN.md
solution/0800-0899/0807.Max Increase to Keep City Skyline/Solution.cpp
solution/0800-0899/0807.Max Increase to Keep City Skyline/Solution.go
solution/0800-0899/0807.Max Increase to Keep City Skyline/Solution.java
solution/0800-0899/0807.Max Increase to Keep City Skyline/Solution.py
solution/0800-0899/0807.Max Increase to Keep City Skyline/Solution.ts
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/README.md
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/README_EN.md
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/Solution.cpp
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/Solution.go
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/Solution.java
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/Solution.py
solution/2100-2199/2170.Minimum Operations to Make the Array Alternating/Solution.ts

* No.0807.Max Increase to Keep City Skyline
* No.2170.Minimum Operations to Make the Array Alternating

feat: add solutions to lc problems: No.0807,2170

---

solution/2700-2799/2740.Find the Value of the Partition/README.md
solution/2700-2799/2740.Find the Value of the Partition/README_EN.md
solution/2700-2799/2740.Find the Value of the Partition/Solution.rs
solution/2700-2799/2740.Find the Value of the Partition/Solution.ts

No.2740.Find the Value of the Partition

feat: add solutions to lc problem: No.2740

---

solution/0300-0399/0332.Reconstruct Itinerary/README.md
solution/0300-0399/0332.Reconstruct Itinerary/README_EN.md
solution/0300-0399/0332.Reconstruct Itinerary/Solution.cpp
solution/0300-0399/0332.Reconstruct Itinerary/Solution.go
solution/0300-0399/0332.Reconstruct Itinerary/Solution.java
solution/0300-0399/0332.Reconstruct Itinerary/Solution.py
solution/0300-0399/0332.Reconstruct Itinerary/Solution.ts

feat: add solutions to lc problem: No.0332

---

solution/2100-2199/2149.Rearrange Array Elements by Sign/README.md
solution/2100-2199/2149.Rearrange Array Elements by Sign/README_EN.md
solution/2100-2199/2149.Rearrange Array Elements by Sign/Solution.cpp
solution/2100-2199/2149.Rearrange Array Elements by Sign/Solution.go
solution/2100-2199/2149.Rearrange Array Elements by Sign/Solution.java
solution/2100-2199/2149.Rearrange Array Elements by Sign/Solution.py
solution/2100-2199/2149.Rearrange Array Elements by Sign/Solution.ts
solution/2100-2199/2150.Find All Lonely Numbers in the Array/README.md
solution/2100-2199/2150.Find All Lonely Numbers in the Array/README_EN.md
solution/2100-2199/2150.Find All Lonely Numbers in the Array/Solution.cpp
solution/2100-2199/2150.Find All Lonely Numbers in the Array/Solution.go
solution/2100-2199/2150.Find All Lonely Numbers in the Array/Solution.java
solution/2100-2199/2150.Find All Lonely Numbers in the Array/Solution.py
solution/2100-2199/2150.Find All Lonely Numbers in the Array/Solution.ts

* No.2149.Rearrange Array Elements by Sign
* No.2150.Find All Lonely Numbers in the Array

feat: update solutions to lc problems: No.2149,2150

---

solution/2100-2199/2154.Keep Multiplying Found Values by Two/README.md
solution/2100-2199/2154.Keep Multiplying Found Values by Two/README_EN.md
solution/2100-2199/2154.Keep Multiplying Found Values by Two/Solution.cpp
solution/2100-2199/2154.Keep Multiplying Found Values by Two/Solution.go
solution/2100-2199/2154.Keep Multiplying Found Values by Two/Solution.ts
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/README.md
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/README_EN.md
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/Solution.cpp
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/Solution.go
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/Solution.java
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/Solution.py
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/Solution.rs
solution/2100-2199/2155.All Divisions With the Highest Score of a Binary Array/Solution.ts

* No.2154.Keep Multiplying Found Values by Two
* No.2155.All Divisions With the Highest Score of a Binary Array

feat: add solutions to lc problems: No.2154,2155

---

solution/2900-2999/2959.Number of Possible Sets of Closing Branches/README.md
solution/2900-2999/2959.Number of Possible Sets of Closing Branches/README_EN.md
solution/2900-2999/2959.Number of Possible Sets of Closing Branches/Solution.py
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/README.md
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/README_EN.md
solution/3100-3199/3112.Minimum Time to Visit Disappearing Nodes/Solution.py
solution/3200-3299/3220.Odd and Even Transactions/README.md
solution/3200-3299/3220.Odd and Even Transactions/README_EN.md
solution/3200-3299/3220.Odd and Even Transactions/Solution.py
solution/3200-3299/3220.Odd and Even Transactions/Solution.sql
solution/3200-3299/3221.Maximum Array Hopping Score II/README.md
solution/3200-3299/3221.Maximum Array Hopping Score II/README_EN.md
solution/3200-3299/3221.Maximum Array Hopping Score II/Solution.cpp
solution/3200-3299/3221.Maximum Array Hopping Score II/Solution.go
solution/3200-3299/3221.Maximum Array Hopping Score II/Solution.java
solution/3200-3299/3221.Maximum Array Hopping Score II/Solution.py
solution/3200-3299/3221.Maximum Array Hopping Score II/Solution.ts
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md
solution/main.py

* No.3220.Odd and Even Transactions
* No.3221.Maximum Array Hopping Score II

feat: add solutions to lc problems: No.3220,3221

---

solution/0900-0999/0945.Minimum Increment to Make Array Unique/README.md
solution/0900-0999/0945.Minimum Increment to Make Array Unique/README_EN.md
solution/0900-0999/0945.Minimum Increment to Make Array Unique/Solution.cpp
solution/0900-0999/0945.Minimum Increment to Make Array Unique/Solution.go
solution/0900-0999/0945.Minimum Increment to Make Array Unique/Solution.java
solution/0900-0999/0945.Minimum Increment to Make Array Unique/Solution.py
solution/0900-0999/0945.Minimum Increment to Make Array Unique/Solution.ts

No.0945.Minimum Increment to Make Array Unique

feat: update solutions to lc problem: No.0945

---

solution/0900-0999/0946.Validate Stack Sequences/README.md
solution/0900-0999/0946.Validate Stack Sequences/README_EN.md
solution/0900-0999/0946.Validate Stack Sequences/Solution.cpp
solution/0900-0999/0946.Validate Stack Sequences/Solution.cs
solution/0900-0999/0946.Validate Stack Sequences/Solution.go
solution/0900-0999/0946.Validate Stack Sequences/Solution.java
solution/0900-0999/0946.Validate Stack Sequences/Solution.js
solution/0900-0999/0946.Validate Stack Sequences/Solution.py
solution/0900-0999/0946.Validate Stack Sequences/Solution.rs
solution/0900-0999/0946.Validate Stack Sequences/Solution.ts

No.0946.Validate Stack Sequences

feat: add solutions to lc problem: No.0946

---

solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/README.md
solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/README_EN.md
solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/Solution.cpp
solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/Solution.go
solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/Solution.java
solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/Solution.py
solution/3200-3299/3226.Number of Bit Changes to Make Two Integers Equal/Solution.ts
solution/3200-3299/3227.Vowels Game in a String/README.md
solution/3200-3299/3227.Vowels Game in a String/README_EN.md
solution/3200-3299/3227.Vowels Game in a String/Solution.cpp
solution/3200-3299/3227.Vowels Game in a String/Solution.go
solution/3200-3299/3227.Vowels Game in a String/Solution.java
solution/3200-3299/3227.Vowels Game in a String/Solution.py
solution/3200-3299/3227.Vowels Game in a String/Solution.ts

* No.3226.Number of Bit Changes to Make Two Integers Equal
* No.3227.Vowels Game in a String

feat: add solutions to lc problems: No.3226,3227

---

solution/1600-1699/1674.Minimum Moves to Make Array Complementary/README.md
solution/1600-1699/1674.Minimum Moves to Make Array Complementary/README_EN.md
solution/1600-1699/1674.Minimum Moves to Make Array Complementary/Solution.cpp
solution/1600-1699/1674.Minimum Moves to Make Array Complementary/Solution.go
solution/1600-1699/1674.Minimum Moves to Make Array Complementary/Solution.java
solution/1600-1699/1674.Minimum Moves to Make Array Complementary/Solution.py
solution/1600-1699/1674.Minimum Moves to Make Array Complementary/Solution.ts
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/README.md
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/README_EN.md
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/Solution.cpp
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/Solution.go
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/Solution.java
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/Solution.py
solution/3200-3299/3224.Minimum Array Changes to Make Differences Equal/Solution.ts
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/README.md
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/README_EN.md
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/Solution.cpp
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/Solution.go
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/Solution.java
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/Solution.py
solution/3200-3299/3228.Maximum Number of Operations to Move Ones to the End/Solution.ts

* No.3224.Minimum Array Changes to Make Differences Equal
* No.3228.Maximum Number of Operations to Move Ones to the End

feat: add solutions to lc problems: No.3224,3228

---

solution/1500-1599/1526.Minimum Number of Increments on Subarrays to Form a Target Array/README.md
solution/1500-1599/1526.Minimum Number of Increments on Subarrays to Form a Target Array/README_EN.md
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/README.md
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/README_EN.md
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/Solution.cpp
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/Solution.go
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/Solution.java
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/Solution.py
solution/3200-3299/3229.Minimum Operations to Make Array Equal to Target/Solution.ts

No.3229.Minimum Operations to Make Array Equal to Target

feat: add solutions to lc problem: No.3229

---

solution/3200-3299/3230.Customer Purchasing Behavior Analysis/README.md
solution/3200-3299/3230.Customer Purchasing Behavior Analysis/README_EN.md
solution/3200-3299/3230.Customer Purchasing Behavior Analysis/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3230.Customer Purchasing Behavior Analysis

feat: add solutions to lc problem: No.3230

---

solution/0500-0599/0545.Boundary of Binary Tree/README.md
solution/0500-0599/0545.Boundary of Binary Tree/README_EN.md
solution/0500-0599/0545.Boundary of Binary Tree/Solution.cpp
solution/0500-0599/0545.Boundary of Binary Tree/Solution.go
solution/0500-0599/0545.Boundary of Binary Tree/Solution.java
solution/0500-0599/0545.Boundary of Binary Tree/Solution.py
solution/0500-0599/0545.Boundary of Binary Tree/Solution.ts

No.0545.Boundary of Binary Tree

feat: add solutions to lc problem: No.0545

---

solution/0500-0599/0544.Output Contest Matches/README.md
solution/0500-0599/0544.Output Contest Matches/README_EN.md
solution/0500-0599/0544.Output Contest Matches/Solution.cpp
solution/0500-0599/0544.Output Contest Matches/Solution.go
solution/0500-0599/0544.Output Contest Matches/Solution.java
solution/0500-0599/0544.Output Contest Matches/Solution.py
solution/0500-0599/0544.Output Contest Matches/Solution.ts

No.0544.Output Contest Matches

feat: add solutions to lc problem: No.0544

---

solution/0500-0599/0530.Minimum Absolute Difference in BST/README.md
solution/0500-0599/0530.Minimum Absolute Difference in BST/README_EN.md
solution/0500-0599/0530.Minimum Absolute Difference in BST/Solution.cpp
solution/0500-0599/0530.Minimum Absolute Difference in BST/Solution.go
solution/0500-0599/0530.Minimum Absolute Difference in BST/Solution.java
solution/0500-0599/0530.Minimum Absolute Difference in BST/Solution.js
solution/0500-0599/0530.Minimum Absolute Difference in BST/Solution.py
solution/0500-0599/0537.Complex Number Multiplication/README.md
solution/0500-0599/0537.Complex Number Multiplication/README_EN.md
solution/0500-0599/0537.Complex Number Multiplication/Solution.cpp
solution/0500-0599/0537.Complex Number Multiplication/Solution.go
solution/0500-0599/0537.Complex Number Multiplication/Solution.java
solution/0500-0599/0537.Complex Number Multiplication/Solution.py
solution/0500-0599/0537.Complex Number Multiplication/Solution.ts
solution/0700-0799/0783.Minimum Distance Between BST Nodes/README.md
solution/0700-0799/0783.Minimum Distance Between BST Nodes/README_EN.md
solution/0700-0799/0783.Minimum Distance Between BST Nodes/Solution.cpp
solution/0700-0799/0783.Minimum Distance Between BST Nodes/Solution.go
solution/0700-0799/0783.Minimum Distance Between BST Nodes/Solution.java
solution/0700-0799/0783.Minimum Distance Between BST Nodes/Solution.py
solution/0700-0799/0783.Minimum Distance Between BST Nodes/Solution.rs
solution/0700-0799/0783.Minimum Distance Between BST Nodes/Solution.ts

No.0537.Complex Number Multiplication

feat: update solutions to lc problem: No.0537

---

solution/0500-0599/0545.Boundary of Binary Tree/README.md
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/README.md
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/README_EN.md
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/Solution.cpp
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/Solution.go
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/Solution.java
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/Solution.py
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/Solution.rs
solution/3200-3299/3231.Minimum Number of Increasing Subsequence to Be Removed/Solution.ts
solution/README.md
solution/README_EN.md

No.3231.Minimum Number of Increasing Subsequence to Be Removed

feat: add solutions to lc problem: No.3231

---

solution/0700-0799/0725.Split Linked List in Parts/README.md
solution/0700-0799/0725.Split Linked List in Parts/README_EN.md
solution/0700-0799/0725.Split Linked List in Parts/Solution.cpp
solution/0700-0799/0725.Split Linked List in Parts/Solution.go
solution/0700-0799/0725.Split Linked List in Parts/Solution.java
solution/0700-0799/0725.Split Linked List in Parts/Solution.py
solution/0700-0799/0725.Split Linked List in Parts/Solution.ts

No.0725.Split Linked List in Parts

feat: add solutions to lc problem: No.0725

---

solution/2500-2599/2531.Make Number of Distinct Characters Equal/README.md
solution/2500-2599/2531.Make Number of Distinct Characters Equal/README_EN.md
solution/2500-2599/2531.Make Number of Distinct Characters Equal/Solution.cpp
solution/2500-2599/2531.Make Number of Distinct Characters Equal/Solution.go
solution/2500-2599/2531.Make Number of Distinct Characters Equal/Solution.java
solution/2500-2599/2531.Make Number of Distinct Characters Equal/Solution.py
solution/2500-2599/2531.Make Number of Distinct Characters Equal/Solution.ts

No.2531.Make Number of Distinct Characters Equal

feat: add solutions to lc problem: No.2531

---

solution/0600-0699/0699.Falling Squares/README.md
solution/0600-0699/0699.Falling Squares/README_EN.md
solution/0600-0699/0699.Falling Squares/Solution.go
solution/0600-0699/0699.Falling Squares/Solution.ts

feat: add solutions to lc problem: No.0699

---

solution/0700-0799/0700.Search in a Binary Search Tree/README.md
solution/0700-0799/0700.Search in a Binary Search Tree/README_EN.md
solution/0700-0799/0700.Search in a Binary Search Tree/Solution.cpp
solution/0700-0799/0700.Search in a Binary Search Tree/Solution.go
solution/0700-0799/0700.Search in a Binary Search Tree/Solution.java
solution/0700-0799/0700.Search in a Binary Search Tree/Solution.py
solution/0700-0799/0700.Search in a Binary Search Tree/Solution.ts
solution/0700-0799/0701.Insert into a Binary Search Tree/README.md
solution/0700-0799/0701.Insert into a Binary Search Tree/README_EN.md
solution/0700-0799/0701.Insert into a Binary Search Tree/Solution.cpp
solution/0700-0799/0701.Insert into a Binary Search Tree/Solution.go
solution/0700-0799/0701.Insert into a Binary Search Tree/Solution.java
solution/0700-0799/0701.Insert into a Binary Search Tree/Solution.py

feat: update solutions to lc problems: No.0700,0701

---

.editorconfig
.husky/commit-msg
.husky/pre-commit

添加 [EditorConfig](https://editorconfig.org/) 的配置文件 [`.editorconfig`](https://spec.editorconfig.org/) 以在不同的编辑器和集成开发环境中保持一致的编码风格。
Add the [`.editorconfig`](https://spec.editorconfig.org/) configuration file for [EditorConfig](https://editorconfig.org/) to maintain a consistent coding style across different editors and IDEs.

chore: add `EditorConfig` configuration file `.editorconfig`

---

solution/3000-3099/3091.Apply Operations to Make Sum of Array Greater Than or Equal to k/README.md
solution/3000-3099/3091.Apply Operations to Make Sum of Array Greater Than or Equal to k/README_EN.md
solution/3000-3099/3091.Apply Operations to Make Sum of Array Greater Than or Equal to k/Solution.rs
solution/3100-3199/3111.Minimum Rectangles to Cover Points/README.md
solution/3100-3199/3111.Minimum Rectangles to Cover Points/README_EN.md
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.cpp
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.cs
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.go
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.java
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.py
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.rs
solution/3100-3199/3111.Minimum Rectangles to Cover Points/Solution.ts

* No.3091.Apply Operations to Make Sum of Array Greater Than or Equal to k
* No.3111.Minimum Rectangles to Cover Points

feat: add solutions to lc problems: No.3091,3111

---

solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/README.md
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/README_EN.md
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution.cpp
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution.go
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution.java
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution.py
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution.ts
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution2.cpp
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution2.go
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution2.java
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution2.py
solution/1400-1499/1461.Check If a String Contains All Binary Codes of Size K/Solution2.ts
solution/1400-1499/1462.Course Schedule IV/README.md
solution/1400-1499/1462.Course Schedule IV/README_EN.md

No.1461.Check If a String Contains All Binary Codes of Size K

feat: add solutions to lc problem: No.1461

---

solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/README.md
solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/README_EN.md
solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/Solution.cpp
solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/Solution.go
solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/Solution.java
solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/Solution.py
solution/1400-1499/1452.People Whose List of Favorite Companies Is Not a Subset of Another List/Solution.ts

No.1452.People Whose List of Favorite Companies Is Not a Subset of Another List

feat: add solutions to lc problem: No.1452

---

solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/README.md
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/README_EN.md
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.cpp
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.go
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.java
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.py
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.ts

No.0600.Non-negative Integers without Consecutive Ones

feat: add solutions to lc problem: No.0600

---

solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/README.md
solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/README_EN.md
solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/Solution.cpp
solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/Solution.go
solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/Solution.java
solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/Solution.py
solution/3200-3299/3244.Shortest Distance After Road Addition Queries II/Solution.ts

No.3244.Shortest Distance After Road Addition Queries II

feat: add solutions to lc problem: No.3244

---

solution/3200-3299/3246.Premier League Table Ranking/README.md
solution/3200-3299/3246.Premier League Table Ranking/README_EN.md
solution/3200-3299/3246.Premier League Table Ranking/Solution.py
solution/3200-3299/3246.Premier League Table Ranking/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3246.Premier League Table Ranking

feat: add solutions to lc problem: No.3246

---

solution/2000-2099/2047.Number of Valid Words in a Sentence/README.md
solution/2000-2099/2047.Number of Valid Words in a Sentence/README_EN.md
solution/2000-2099/2047.Number of Valid Words in a Sentence/Solution.cpp
solution/2000-2099/2047.Number of Valid Words in a Sentence/Solution.go
solution/2000-2099/2047.Number of Valid Words in a Sentence/Solution.java
solution/2000-2099/2047.Number of Valid Words in a Sentence/Solution.py
solution/2000-2099/2047.Number of Valid Words in a Sentence/Solution.ts

No.2047.Number of Valid Words in a Sentence

feat: add solutions to lc problem: No.2047

---

solution/2000-2099/2015.Average Height of Buildings in Each Segment/README.md
solution/2000-2099/2015.Average Height of Buildings in Each Segment/README_EN.md
solution/2000-2099/2015.Average Height of Buildings in Each Segment/Solution.cpp
solution/2000-2099/2015.Average Height of Buildings in Each Segment/Solution.go
solution/2000-2099/2015.Average Height of Buildings in Each Segment/Solution.java
solution/2000-2099/2015.Average Height of Buildings in Each Segment/Solution.py
solution/2000-2099/2015.Average Height of Buildings in Each Segment/Solution.ts
solution/2000-2099/2016.Maximum Difference Between Increasing Elements/README.md
solution/2000-2099/2016.Maximum Difference Between Increasing Elements/README_EN.md
solution/2000-2099/2016.Maximum Difference Between Increasing Elements/Solution.js
solution/2000-2099/2016.Maximum Difference Between Increasing Elements/Solution.rs
solution/2000-2099/2016.Maximum Difference Between Increasing Elements/Solution.ts

* No.2015.Average Height of Buildings in Each Segment
* No.2016.Maximum Difference Between Increasing Elements

feat: add solutions to lc problems: No.2015,2016

---

solution/0200-0299/0209.Minimum Size Subarray Sum/README.md
solution/0200-0299/0209.Minimum Size Subarray Sum/README_EN.md
solution/0200-0299/0209.Minimum Size Subarray Sum/Solution2.cpp
solution/0200-0299/0209.Minimum Size Subarray Sum/Solution2.go
solution/0200-0299/0209.Minimum Size Subarray Sum/Solution2.java
solution/0200-0299/0209.Minimum Size Subarray Sum/Solution2.py
solution/0200-0299/0209.Minimum Size Subarray Sum/Solution2.ts
solution/0200-0299/0266.Palindrome Permutation/README.md
solution/0200-0299/0266.Palindrome Permutation/README_EN.md
solution/0200-0299/0266.Palindrome Permutation/Solution.js
solution/0200-0299/0266.Palindrome Permutation/Solution.ts

* No.0209.Minimum Size Subarray Sum
* No.0266.Palindrome Permutation

feat: update solutions to lc problems: No.0209,0266

---

solution/2700-2799/2753.Count Houses in a Circular Street II/README.md
solution/2700-2799/2753.Count Houses in a Circular Street II/README_EN.md
solution/3200-3299/3247.Number of Subsequences with Odd Sum/README.md
solution/3200-3299/3247.Number of Subsequences with Odd Sum/README_EN.md
solution/3200-3299/3247.Number of Subsequences with Odd Sum/Solution.cpp
solution/3200-3299/3247.Number of Subsequences with Odd Sum/Solution.go
solution/3200-3299/3247.Number of Subsequences with Odd Sum/Solution.java
solution/3200-3299/3247.Number of Subsequences with Odd Sum/Solution.py
solution/3200-3299/3247.Number of Subsequences with Odd Sum/Solution.ts
solution/README.md
solution/README_EN.md
solution/util.py

No.3247.Number of Subsequences with Odd Sum

feat: add solutions to lc problem: No.3247

---

solution/0700-0799/0737.Sentence Similarity II/README.md
solution/0900-0999/0967.Numbers With Same Consecutive Differences/README.md
solution/0900-0999/0967.Numbers With Same Consecutive Differences/README_EN.md
solution/0900-0999/0967.Numbers With Same Consecutive Differences/Solution.cpp
solution/0900-0999/0967.Numbers With Same Consecutive Differences/Solution.go
solution/0900-0999/0967.Numbers With Same Consecutive Differences/Solution.java
solution/0900-0999/0967.Numbers With Same Consecutive Differences/Solution.js
solution/0900-0999/0967.Numbers With Same Consecutive Differences/Solution.py
solution/0900-0999/0967.Numbers With Same Consecutive Differences/Solution.ts
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/README_EN.md
solution/3200-3299/3242.Design Neighbor Sum Service/README_EN.md

No.0967.Numbers With Same Consecutive Differences

feat: update solutions to lc problem: No.0967

---

solution/1000-1099/1035.Uncrossed Lines/README.md
solution/1000-1099/1035.Uncrossed Lines/README_EN.md
solution/1000-1099/1035.Uncrossed Lines/Solution.cpp
solution/1000-1099/1035.Uncrossed Lines/Solution.go
solution/1000-1099/1035.Uncrossed Lines/Solution.java
solution/1000-1099/1035.Uncrossed Lines/Solution.js
solution/1000-1099/1035.Uncrossed Lines/Solution.py

feat: add solutions to lc problem: No.1035

---

solution/0800-0899/0813.Largest Sum of Averages/README.md
solution/0800-0899/0813.Largest Sum of Averages/README_EN.md
solution/0800-0899/0813.Largest Sum of Averages/Solution.cpp
solution/0800-0899/0813.Largest Sum of Averages/Solution.go
solution/0800-0899/0813.Largest Sum of Averages/Solution.java
solution/0800-0899/0813.Largest Sum of Averages/Solution.py
solution/0800-0899/0813.Largest Sum of Averages/Solution.ts
solution/0800-0899/0813.Largest Sum of Averages/Solution2.cpp
solution/0800-0899/0813.Largest Sum of Averages/Solution2.go
solution/0800-0899/0813.Largest Sum of Averages/Solution2.java
solution/0800-0899/0813.Largest Sum of Averages/Solution2.py
solution/0800-0899/0813.Largest Sum of Averages/Solution2.ts
solution/0800-0899/0814.Binary Tree Pruning/README.md
solution/0800-0899/0814.Binary Tree Pruning/README_EN.md
solution/0800-0899/0814.Binary Tree Pruning/Solution.cpp
solution/0800-0899/0814.Binary Tree Pruning/Solution.js
solution/0800-0899/0814.Binary Tree Pruning/Solution.py
solution/0800-0899/0814.Binary Tree Pruning/Solution.ts

* No.0813.Largest Sum of Averages
* No.0814.Binary Tree Pruning

feat: add solutions to lc problems: No.0813,0814

---

solution/1300-1399/1307.Verbal Arithmetic Puzzle/Solution.py

Again this was missing so gave mine code to help others.

feat: add python solution to lc problem: No.1307

---

solution/1300-1399/1310.XOR Queries of a Subarray/README.md
solution/1300-1399/1310.XOR Queries of a Subarray/README_EN.md
solution/1300-1399/1310.XOR Queries of a Subarray/Solution.js
solution/1300-1399/1310.XOR Queries of a Subarray/Solution.ts
solution/1300-1399/1311.Get Watched Videos by Your Friends/README.md
solution/1300-1399/1311.Get Watched Videos by Your Friends/README_EN.md
solution/1300-1399/1311.Get Watched Videos by Your Friends/Solution.cpp
solution/1300-1399/1311.Get Watched Videos by Your Friends/Solution.go
solution/1300-1399/1311.Get Watched Videos by Your Friends/Solution.java
solution/1300-1399/1311.Get Watched Videos by Your Friends/Solution.py
solution/1300-1399/1311.Get Watched Videos by Your Friends/Solution.ts

No.1311.Get Watched Videos by Your Friends

feat: add solutions to lc problem: No.1311

---

solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/README.md
solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/README_EN.md
solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/Solution.cpp
solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/Solution.go
solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/Solution.java
solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/Solution.py
solution/3200-3299/3253.Construct String with Minimum Cost (Easy)/Solution.ts
solution/README.md
solution/README_EN.md

No.3253.Construct String with Minimum Cost (Easy)

feat: add solutions to lc problem: No.3253

---

solution/0200-0299/0214.Shortest Palindrome/README.md
solution/0200-0299/0214.Shortest Palindrome/README_EN.md
solution/0200-0299/0214.Shortest Palindrome/Solution.cs
solution/0200-0299/0214.Shortest Palindrome/Solution2.cpp
solution/0200-0299/0214.Shortest Palindrome/Solution2.cs
solution/0200-0299/0214.Shortest Palindrome/Solution2.go
solution/0200-0299/0214.Shortest Palindrome/Solution2.java
solution/0200-0299/0214.Shortest Palindrome/Solution2.py
solution/0200-0299/0214.Shortest Palindrome/Solution2.ts

feat: add solutions to lc problem: No.0214

---

solution/3000-3099/3068.Find the Maximum Sum of Node Values/README.md
solution/3000-3099/3068.Find the Maximum Sum of Node Values/README_EN.md
solution/3000-3099/3068.Find the Maximum Sum of Node Values/Solution.cpp
solution/3000-3099/3068.Find the Maximum Sum of Node Values/Solution.cs
solution/3000-3099/3068.Find the Maximum Sum of Node Values/Solution.go
solution/3000-3099/3068.Find the Maximum Sum of Node Values/Solution.rs
solution/3000-3099/3068.Find the Maximum Sum of Node Values/Solution.ts

No.3068.Find the Maximum Sum of Node Values

feat: add solutions to lc problem: No.3068

---

solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/README.md
solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/README_EN.md
solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/Solution.cpp
solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/Solution.go
solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/Solution.java
solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/Solution.py
solution/1400-1499/1418.Display Table of Food Orders in a Restaurant/Solution.ts

No.1418.Display Table of Food Orders in a Restaurant

feat: add solutions to lc problem: No.1418

---

solution/3000-3099/3007.Maximum Number That Sum of the Prices Is Less Than or Equal to K/README.md
solution/3000-3099/3007.Maximum Number That Sum of the Prices Is Less Than or Equal to K/README_EN.md
solution/3000-3099/3007.Maximum Number That Sum of the Prices Is Less Than or Equal to K/Solution.cpp
solution/3000-3099/3007.Maximum Number That Sum of the Prices Is Less Than or Equal to K/Solution.ts

No.3007.Maximum Number That Sum of the Prices Is Less Than or Equal to K

feat: add solutions to lc problem: No.3007

---

solution/3200-3299/3262.Find Overlapping Shifts/README.md
solution/3200-3299/3262.Find Overlapping Shifts/README_EN.md
solution/3200-3299/3262.Find Overlapping Shifts/Solution.py
solution/3200-3299/3262.Find Overlapping Shifts/Solution.sql
solution/3200-3299/3263.Convert Doubly Linked List to Array I/README.md
solution/3200-3299/3263.Convert Doubly Linked List to Array I/README_EN.md
solution/3200-3299/3263.Convert Doubly Linked List to Array I/Solution.cpp
solution/3200-3299/3263.Convert Doubly Linked List to Array I/Solution.go
solution/3200-3299/3263.Convert Doubly Linked List to Array I/Solution.java
solution/3200-3299/3263.Convert Doubly Linked List to Array I/Solution.py
solution/3200-3299/3263.Convert Doubly Linked List to Array I/Solution.ts
solution/CONTEST_README.md
solution/CONTEST_README_EN.md
solution/DATABASE_README.md
solution/README.md
solution/README_EN.md

No.3263.Convert Doubly Linked List to Array I

feat: add solutions to lc problem: No.3263

---

solution/3100-3199/3145.Find Products of Elements of Big Array/README.md
solution/3100-3199/3145.Find Products of Elements of Big Array/README_EN.md
solution/3100-3199/3145.Find Products of Elements of Big Array/Solution.cpp
solution/3100-3199/3145.Find Products of Elements of Big Array/Solution.go
solution/3100-3199/3145.Find Products of Elements of Big Array/Solution.java
solution/3100-3199/3145.Find Products of Elements of Big Array/Solution.py

No.3145.Find Products of Elements of Big Array

feat: add solutions to lc problem: No.3145

---

solution/0600-0699/0698.Partition to K Equal Sum Subsets/README.md
solution/0600-0699/0698.Partition to K Equal Sum Subsets/README_EN.md
solution/0600-0699/0698.Partition to K Equal Sum Subsets/Solution.cpp
solution/0600-0699/0698.Partition to K Equal Sum Subsets/Solution.py
solution/0600-0699/0698.Partition to K Equal Sum Subsets/Solution.ts
solution/0600-0699/0698.Partition to K Equal Sum Subsets/Solution2.cpp
solution/0600-0699/0698.Partition to K Equal Sum Subsets/Solution2.ts
solution/0600-0699/0698.Partition to K Equal Sum Subsets/Solution3.ts

No.0698.Partition to K Equal Sum Subsets

feat: add solutions to lc problem: No.0698

---

solution/2000-2099/2096.Step-By-Step Directions From a Binary Tree Node to Another/README.md
solution/2000-2099/2096.Step-By-Step Directions From a Binary Tree Node to Another/README_EN.md
solution/2000-2099/2096.Step-By-Step Directions From a Binary Tree Node to Another/Solution.js
solution/2000-2099/2096.Step-By-Step Directions From a Binary Tree Node to Another/Solution.ts
solution/2200-2299/2205.The Number of Users That Are Eligible for Discount/README.md
solution/3200-3299/3278.Find Candidates for Data Scientist Position II/README.md
solution/3200-3299/3278.Find Candidates for Data Scientist Position II/README_EN.md
solution/3200-3299/3278.Find Candidates for Data Scientist Position II/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3278.Find Candidates for Data Scientist Position II

feat: add solutions to lc problem: No.3278

---

solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/README.md
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/README_EN.md
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.c
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.cpp
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.go
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.java
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.py
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.rs
solution/2400-2499/2414.Length of the Longest Alphabetical Continuous Substring/Solution.ts

No.2414.Length of the Longest Alphabetical Continuous Substring

feat: add solutions to lc problem: No.2414

---

.gitignore
solution/1300-1399/1313.Decompress Run-Length Encoded List/README.md
solution/1300-1399/1313.Decompress Run-Length Encoded List/README_EN.md
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.c
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.cpp
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.go
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.java
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.py
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.rs
solution/1300-1399/1313.Decompress Run-Length Encoded List/Solution.ts

No.1313.Decompress Run-Length Encoded List

feat: add solutions to lc problem: No.1313

---

solution/3200-3299/3283.Maximum Number of Moves to Kill All Pawns/README.md
solution/3200-3299/3283.Maximum Number of Moves to Kill All Pawns/README_EN.md
solution/3200-3299/3283.Maximum Number of Moves to Kill All Pawns/Solution.cpp
solution/3200-3299/3283.Maximum Number of Moves to Kill All Pawns/Solution.go
solution/3200-3299/3283.Maximum Number of Moves to Kill All Pawns/Solution.java
solution/3200-3299/3283.Maximum Number of Moves to Kill All Pawns/Solution.py

No.3283.Maximum Number of Moves to Kill All Pawns

feat: add solutions to lc problem: No.3283

---

solution/1200-1299/1228.Missing Number In Arithmetic Progression/README.md
solution/1200-1299/1228.Missing Number In Arithmetic Progression/README_EN.md
solution/1200-1299/1228.Missing Number In Arithmetic Progression/Solution.go
solution/1200-1299/1228.Missing Number In Arithmetic Progression/Solution.ts
solution/1200-1299/1228.Missing Number In Arithmetic Progression/Solution2.cpp
solution/1200-1299/1228.Missing Number In Arithmetic Progression/Solution2.go
solution/1200-1299/1228.Missing Number In Arithmetic Progression/Solution2.ts

No.1228.Missing Number In Arithmetic Progression

feat: add solutions to lc problem: No.1228

---

solution/1200-1299/1229.Meeting Scheduler/README.md
solution/1200-1299/1229.Meeting Scheduler/README_EN.md
solution/1200-1299/1229.Meeting Scheduler/Solution.rs
solution/1200-1299/1229.Meeting Scheduler/Solution.ts

feat: add solutions to lc problem: No.1229

---

solution/2800-2899/2848.Points That Intersect With Cars/README.md
solution/2800-2899/2848.Points That Intersect With Cars/README_EN.md
solution/2800-2899/2848.Points That Intersect With Cars/Solution.cpp
solution/2800-2899/2848.Points That Intersect With Cars/Solution.go
solution/2800-2899/2848.Points That Intersect With Cars/Solution.java
solution/2800-2899/2848.Points That Intersect With Cars/Solution.py
solution/2800-2899/2848.Points That Intersect With Cars/Solution.ts
solution/2800-2899/2848.Points That Intersect With Cars/Solution2.cpp
solution/2800-2899/2848.Points That Intersect With Cars/Solution2.go
solution/2800-2899/2848.Points That Intersect With Cars/Solution2.java
solution/2800-2899/2848.Points That Intersect With Cars/Solution2.py
solution/2800-2899/2848.Points That Intersect With Cars/Solution2.ts

No.2848.Points That Intersect With Cars

feat: add solutions to lc problem: No.2848

---

solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/README.md
solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/README_EN.md
solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/Solution.cpp
solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/Solution.go
solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/Solution.java
solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/Solution.py
solution/2100-2199/2148.Count Elements With Strictly Smaller and Greater Elements/Solution.ts

No.2148.Count Elements With Strictly Smaller and Greater Elements

feat: add solutions to lc problem: No.2148

---

solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/README.md
solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/README_EN.md
solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/Solution.cpp
solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/Solution.go
solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/Solution.java
solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/Solution.py
solution/2100-2199/2146.K Highest Ranked Items Within a Price Range/Solution.ts

No.2146.K Highest Ranked Items Within a Price Range

feat: add solutions to lc problem: No.2146

---

solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/README.md
solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/README_EN.md
solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/Solution.cpp
solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/Solution.go
solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/Solution.java
solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/Solution.py
solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/Solution.ts

No.2133.Check if Every Row and Column Contains All Numbers

feat: add solutions to lc problem: No.2133

---

solution/1900-1999/1925.Count Square Sum Triples/README.md
solution/1900-1999/1925.Count Square Sum Triples/README_EN.md
solution/1900-1999/1925.Count Square Sum Triples/Solution.cpp
solution/1900-1999/1925.Count Square Sum Triples/Solution.go
solution/1900-1999/1925.Count Square Sum Triples/Solution.java
solution/1900-1999/1925.Count Square Sum Triples/Solution.py
solution/1900-1999/1925.Count Square Sum Triples/Solution.ts

No.1925.Count Square Sum Triples

feat: add solutions to lc problem: No.1925

---

solution/2400-2499/2403.Minimum Time to Kill All Monsters/README.md
solution/2400-2499/2403.Minimum Time to Kill All Monsters/README_EN.md
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution.cpp
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution.go
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution.java
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution.py
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution.ts
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution2.cpp
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution2.go
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution2.java
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution2.py
solution/2400-2499/2403.Minimum Time to Kill All Monsters/Solution2.ts

No.2403.Minimum Time to Kill All Monsters

feat: add solutions to lc problem: No.2403

---

solution/2400-2499/2410.Maximum Matching of Players With Trainers/README.md
solution/2400-2499/2410.Maximum Matching of Players With Trainers/README_EN.md
solution/2400-2499/2410.Maximum Matching of Players With Trainers/Solution.cpp
solution/2400-2499/2410.Maximum Matching of Players With Trainers/Solution.go
solution/2400-2499/2410.Maximum Matching of Players With Trainers/Solution.java
solution/2400-2499/2410.Maximum Matching of Players With Trainers/Solution.py
solution/2400-2499/2410.Maximum Matching of Players With Trainers/Solution.ts

No.2410.Maximum Matching of Players With Trainers

feat: add solutions to lc problem: No.2410

---

solution/0200-0299/0233.Number of Digit One/README.md
solution/0200-0299/0233.Number of Digit One/README_EN.md
solution/0200-0299/0233.Number of Digit One/Solution.cpp
solution/0200-0299/0233.Number of Digit One/Solution.cs
solution/0200-0299/0233.Number of Digit One/Solution.go
solution/0200-0299/0233.Number of Digit One/Solution.java
solution/0200-0299/0233.Number of Digit One/Solution.py
solution/0200-0299/0233.Number of Digit One/Solution.ts

feat: add solutions to lc problem: No.0233

---

solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/README.md
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/README_EN.md
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.cpp
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.go
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.java
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.py
solution/0600-0699/0600.Non-negative Integers without Consecutive Ones/Solution.ts

No.0600.Non-negative Integers without Consecutive Ones

feat: update solutions to lc problem: No.0600

---

solution/0700-0799/0788.Rotated Digits/README.md
solution/0700-0799/0788.Rotated Digits/README_EN.md
solution/0700-0799/0788.Rotated Digits/Solution.cpp
solution/0700-0799/0788.Rotated Digits/Solution.ts
solution/0700-0799/0788.Rotated Digits/Solution2.cpp
solution/0700-0799/0788.Rotated Digits/Solution2.go
solution/0700-0799/0788.Rotated Digits/Solution2.java
solution/0700-0799/0788.Rotated Digits/Solution2.py
solution/0700-0799/0788.Rotated Digits/Solution2.ts

feat: add solutions to lc problem: No.0788

---

solution/2300-2399/2374.Node With Highest Edge Score/README.md
solution/2300-2399/2374.Node With Highest Edge Score/README_EN.md
solution/2300-2399/2374.Node With Highest Edge Score/Solution.cpp
solution/2300-2399/2374.Node With Highest Edge Score/Solution.go
solution/2300-2399/2374.Node With Highest Edge Score/Solution.java
solution/2300-2399/2374.Node With Highest Edge Score/Solution.py
solution/2300-2399/2374.Node With Highest Edge Score/Solution.rs
solution/2300-2399/2374.Node With Highest Edge Score/Solution.ts

No.2374.Node With Highest Edge Score

feat: add solutions to lc problem: No.2374

---

solution/1900-1999/1957.Delete Characters to Make Fancy String/README.md
solution/1900-1999/1957.Delete Characters to Make Fancy String/README_EN.md
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.cpp
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.go
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.java
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.php
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.py
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.ts

No.1957.Delete Characters to Make Fancy String

feat: add solutions to lc problem: No.1957

---

solution/1900-1999/1970.Last Day Where You Can Still Cross/README.md
solution/1900-1999/1970.Last Day Where You Can Still Cross/README_EN.md
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution.cpp
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution.go
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution.java
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution.py
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution.ts
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution2.cpp
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution2.go
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution2.java
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution2.py
solution/1900-1999/1970.Last Day Where You Can Still Cross/Solution2.ts

No.1970.Last Day Where You Can Still Cross

feat: add solutions to lc problem: No.1970

---

solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/README.md
solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/README_EN.md
solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/Solution.cpp
solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/Solution.go
solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/Solution.java
solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/Solution.py
solution/1200-1299/1239.Maximum Length of a Concatenated String with Unique Characters/Solution.ts

No.1239.Maximum Length of a Concatenated String with Unique Characters

feat: add solutions to lc problem: No.1239

---

solution/1500-1599/1559.Detect Cycles in 2D Grid/README.md
solution/1500-1599/1559.Detect Cycles in 2D Grid/README_EN.md
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution.cpp
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution.go
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution.java
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution.py
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution.rs
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution.ts
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution2.cpp
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution2.go
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution2.java
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution2.py
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution2.rs
solution/1500-1599/1559.Detect Cycles in 2D Grid/Solution2.ts

No.1559.Detect Cycles in 2D Grid

feat: add solutions to lc problem: No.1559

---

solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/README.md
solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/README_EN.md
solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/Solution.cpp
solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/Solution.go
solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/Solution.java
solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/Solution.py
solution/1500-1599/1566.Detect Pattern of Length M Repeated K or More Times/Solution.ts

No.1566.Detect Pattern of Length M Repeated K or More Times

feat: update solutions to lc problem: No.1566

---

solution/3200-3299/3299.Sum of Consecutive Subsequences/README.md
solution/3200-3299/3299.Sum of Consecutive Subsequences/README_EN.md
solution/3200-3299/3299.Sum of Consecutive Subsequences/Solution.cpp
solution/3200-3299/3299.Sum of Consecutive Subsequences/Solution.go
solution/3200-3299/3299.Sum of Consecutive Subsequences/Solution.java
solution/3200-3299/3299.Sum of Consecutive Subsequences/Solution.py

No.3299.Sum of Consecutive Subsequences

feat: add solutions to lc problem: No.3299

---

solution/2200-2299/2286.Booking Concert Tickets in Groups/README.md
solution/2200-2299/2286.Booking Concert Tickets in Groups/README_EN.md
solution/2200-2299/2286.Booking Concert Tickets in Groups/Solution.py
solution/2200-2299/2286.Booking Concert Tickets in Groups/Solution.ts

No.2286.Booking Concert Tickets in Groups

feat: add solutions to lc problem: No.2286

---

solution/0500-0599/0508.Most Frequent Subtree Sum/README.md
solution/0500-0599/0508.Most Frequent Subtree Sum/README_EN.md
solution/0500-0599/0508.Most Frequent Subtree Sum/Solution.cpp
solution/0500-0599/0508.Most Frequent Subtree Sum/Solution.go
solution/0500-0599/0508.Most Frequent Subtree Sum/Solution.java
solution/0500-0599/0508.Most Frequent Subtree Sum/Solution.py
solution/0500-0599/0508.Most Frequent Subtree Sum/Solution.rs
solution/0500-0599/0508.Most Frequent Subtree Sum/Solution.ts

No.0508.Most Frequent Subtree Sum

feat: add solutions to lc problem: No.0508

---

solution/1800-1899/1845.Seat Reservation Manager/README.md
solution/1800-1899/1845.Seat Reservation Manager/README_EN.md
solution/1800-1899/1845.Seat Reservation Manager/Solution.cs
solution/1800-1899/1845.Seat Reservation Manager/Solution.py
solution/1800-1899/1845.Seat Reservation Manager/Solution.ts

No.1845.Seat Reservation Manager

feat: add solutions to lc problem: No.1845

---

solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/README.md
solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/README_EN.md
solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/Solution.cpp
solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/Solution.go
solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/Solution.java
solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/Solution.py
solution/1800-1899/1849.Splitting a String Into Descending Consecutive Values/Solution.ts

No.1849.Splitting a String Into Descending Consecutive Values

feat: add solutions to lc problem: No.1849

---

solution/3300-3399/3302.Find the Lexicographically Smallest Valid Sequence/README_EN.md
solution/3300-3399/3303.Find the Occurrence of First Almost Equal Substring/README_EN.md
solution/3300-3399/3308.Find Top Performing Driver/README.md
solution/3300-3399/3308.Find Top Performing Driver/README_EN.md
solution/3300-3399/3308.Find Top Performing Driver/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3308.Find Top Performing Driver

feat: add solutions to lc problem: No.3308

---

solution/1500-1599/1583.Count Unhappy Friends/README.md
solution/1500-1599/1583.Count Unhappy Friends/README_EN.md
solution/1500-1599/1583.Count Unhappy Friends/Solution.cpp
solution/1500-1599/1583.Count Unhappy Friends/Solution.go
solution/1500-1599/1583.Count Unhappy Friends/Solution.java
solution/1500-1599/1583.Count Unhappy Friends/Solution.py
solution/1500-1599/1583.Count Unhappy Friends/Solution.ts

feat: add solutions to lc problem: No.1583

---

solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/README.md
solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/README_EN.md
solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/Solution.cpp
solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/Solution.go
solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/Solution.php
solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/Solution.py
solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/Solution.ts

No.1876.Substrings of Size Three with Distinct Characters

feat: add solutions to lc problem: No.1876

---

solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/README.md
solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/README_EN.md
solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/Solution.cpp
solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/Solution.go
solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/Solution.java
solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/Solution.py
solution/1900-1999/1928.Minimum Cost to Reach Destination in Time/Solution.ts

No.1928.Minimum Cost to Reach Destination in Time

feat: add solutions to lc problem: No.1928

---

solution/1200-1299/1227.Airplane Seat Assignment Probability/README.md
solution/1200-1299/1227.Airplane Seat Assignment Probability/README_EN.md
solution/1200-1299/1227.Airplane Seat Assignment Probability/Solution.rs
solution/1200-1299/1227.Airplane Seat Assignment Probability/Solution.ts

No.1227.Airplane Seat Assignment Probability

feat: add solutions to lc problem: No.1227

---

solution/0800-0899/0871.Minimum Number of Refueling Stops/README.md
solution/0800-0899/0871.Minimum Number of Refueling Stops/README_EN.md
solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.cpp
solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.go
solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.java
solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.py
solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.rs
solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.ts

No.0871.Minimum Number of Refueling Stops

feat: add solutions to lc problem: No.0871

---

solution/3300-3399/3312.Sorted GCD Pair Queries/README.md
solution/3300-3399/3312.Sorted GCD Pair Queries/README_EN.md
solution/3300-3399/3312.Sorted GCD Pair Queries/Solution.cpp
solution/3300-3399/3312.Sorted GCD Pair Queries/Solution.go
solution/3300-3399/3312.Sorted GCD Pair Queries/Solution.java
solution/3300-3399/3312.Sorted GCD Pair Queries/Solution.py

No.3312.Sorted GCD Pair Queries

feat: add solutions to lc problem: No.3312

---

solution/1200-1299/1296.Divide Array in Sets of K Consecutive Numbers/README.md
solution/1200-1299/1296.Divide Array in Sets of K Consecutive Numbers/README_EN.md
solution/1200-1299/1296.Divide Array in Sets of K Consecutive Numbers/Solution.java
solution/1200-1299/1296.Divide Array in Sets of K Consecutive Numbers/Solution2.cpp
solution/1200-1299/1296.Divide Array in Sets of K Consecutive Numbers/Solution2.java

No.1296.Divide Array in Sets of K Consecutive Numbers

feat: update solutions to lc problem: No.1296

---

solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/README.md
solution/3300-3399/3318.Find X-Sum of All K-Long Subarrays I/README.md
solution/3300-3399/3318.Find X-Sum of All K-Long Subarrays I/README_EN.md
solution/3300-3399/3318.Find X-Sum of All K-Long Subarrays I/Solution.cpp
solution/3300-3399/3318.Find X-Sum of All K-Long Subarrays I/Solution.java
solution/3300-3399/3318.Find X-Sum of All K-Long Subarrays I/Solution.py
solution/3300-3399/3321.Find X-Sum of All K-Long Subarrays II/README.md
solution/3300-3399/3321.Find X-Sum of All K-Long Subarrays II/README_EN.md
solution/3300-3399/3321.Find X-Sum of All K-Long Subarrays II/Solution.cpp
solution/3300-3399/3321.Find X-Sum of All K-Long Subarrays II/Solution.java
solution/3300-3399/3321.Find X-Sum of All K-Long Subarrays II/Solution.py

* No.3318.Find X-Sum of All K-Long Subarrays I
* No.3321.Find X-Sum of All K-Long Subarrays II

feat: add solutions to lc problems: No.3318,3321

---

solution/3300-3399/3317.Find the Number of Possible Ways for an Event/README.md
solution/3300-3399/3317.Find the Number of Possible Ways for an Event/README_EN.md
solution/3300-3399/3317.Find the Number of Possible Ways for an Event/Solution.cpp
solution/3300-3399/3317.Find the Number of Possible Ways for an Event/Solution.go
solution/3300-3399/3317.Find the Number of Possible Ways for an Event/Solution.java
solution/3300-3399/3317.Find the Number of Possible Ways for an Event/Solution.py
solution/3300-3399/3317.Find the Number of Possible Ways for an Event/Solution.ts

No.3317.Find the Number of Possible Ways for an Event

feat: add solutions to lc problem: No.3317

---

.prettierignore
solution/3300-3399/3328.Find Cities in Each State II/README.md
solution/3300-3399/3328.Find Cities in Each State II/README_EN.md
solution/3300-3399/3328.Find Cities in Each State II/Solution.py
solution/3300-3399/3328.Find Cities in Each State II/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3328.Find Cities in Each State II

feat: add solution to lc problem: No.3328

---

solution/3300-3399/3327.Check if DFS Strings Are Palindromes/README.md
solution/3300-3399/3327.Check if DFS Strings Are Palindromes/README_EN.md
solution/3300-3399/3327.Check if DFS Strings Are Palindromes/Solution.cpp
solution/3300-3399/3327.Check if DFS Strings Are Palindromes/Solution.go
solution/3300-3399/3327.Check if DFS Strings Are Palindromes/Solution.java
solution/3300-3399/3327.Check if DFS Strings Are Palindromes/Solution.py

No.3327.Check if DFS Strings Are Palindromes

feat: update solutions to lc problem: No.3327

---

solution/3300-3399/3314.Construct the Minimum Bitwise Array I/README.md
solution/3300-3399/3314.Construct the Minimum Bitwise Array I/README_EN.md
solution/3300-3399/3314.Construct the Minimum Bitwise Array I/Solution.cpp
solution/3300-3399/3314.Construct the Minimum Bitwise Array I/Solution.go
solution/3300-3399/3314.Construct the Minimum Bitwise Array I/Solution.java
solution/3300-3399/3314.Construct the Minimum Bitwise Array I/Solution.py
solution/3300-3399/3314.Construct the Minimum Bitwise Array I/Solution.ts
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/README.md
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/README_EN.md
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/Solution.cpp
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/Solution.go
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/Solution.java
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/Solution.py
solution/3300-3399/3315.Construct the Minimum Bitwise Array II/Solution.ts
solution/3300-3399/3316.Find Maximum Removals From Source String/README.md
solution/3300-3399/3316.Find Maximum Removals From Source String/README_EN.md
solution/3300-3399/3316.Find Maximum Removals From Source String/Solution.cpp
solution/3300-3399/3316.Find Maximum Removals From Source String/Solution.go
solution/3300-3399/3316.Find Maximum Removals From Source String/Solution.java
solution/3300-3399/3316.Find Maximum Removals From Source String/Solution.py
solution/3300-3399/3316.Find Maximum Removals From Source String/Solution.ts

* No.3314.Construct the Minimum Bitwise Array I
* No.3315.Construct the Minimum Bitwise Array II
* No.3316.Find Maximum Removals From Source String

feat: add solutions to lc problems: No.3314~3316

---

solution/0600-0699/0684.Redundant Connection/README.md
solution/0600-0699/0684.Redundant Connection/README_EN.md
solution/0600-0699/0684.Redundant Connection/Solution.cpp
solution/0600-0699/0684.Redundant Connection/Solution.go
solution/0600-0699/0684.Redundant Connection/Solution.java
solution/0600-0699/0684.Redundant Connection/Solution.py
solution/0600-0699/0684.Redundant Connection/Solution.ts
solution/0600-0699/0684.Redundant Connection/Solution2.cpp
solution/0600-0699/0684.Redundant Connection/Solution2.go
solution/0600-0699/0684.Redundant Connection/Solution2.java
solution/0600-0699/0684.Redundant Connection/Solution2.js
solution/0600-0699/0684.Redundant Connection/Solution2.py
solution/0600-0699/0684.Redundant Connection/Solution2.ts
solution/1200-1299/1258.Synonymous Sentences/Solution.java

feat: add solutions to lc problem: No.0684

---

solution/0600-0699/0687.Longest Univalue Path/README.md
solution/0600-0699/0687.Longest Univalue Path/README_EN.md
solution/0600-0699/0687.Longest Univalue Path/Solution.c
solution/0600-0699/0687.Longest Univalue Path/Solution.cpp
solution/0600-0699/0687.Longest Univalue Path/Solution.go
solution/0600-0699/0687.Longest Univalue Path/Solution.java
solution/0600-0699/0687.Longest Univalue Path/Solution.js
solution/0600-0699/0687.Longest Univalue Path/Solution.py
solution/0600-0699/0687.Longest Univalue Path/Solution.rs
solution/0600-0699/0687.Longest Univalue Path/Solution.ts

feat: update solutions to lc problem: No.0687

---

solution/3300-3399/3338.Second Highest Salary II/README.md
solution/3300-3399/3338.Second Highest Salary II/README_EN.md
solution/3300-3399/3338.Second Highest Salary II/Solution.py
solution/3300-3399/3338.Second Highest Salary II/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3338.Second Highest Salary II

feat: add solutions to lc problem: No.3338

---

solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/README.md
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/README_EN.md
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/Solution.cpp
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/Solution.go
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/Solution.java
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/Solution.py
solution/3200-3299/3235.Check if the Rectangle Corner Is Reachable/Solution.ts

No.3235.Check if the Rectangle Corner Is Reachable

feat: add solutions to lc problem: No.3235

---

solution/2500-2599/2532.Time to Cross a Bridge/README_EN.md
solution/2500-2599/2534.Time Taken to Cross the Door/README.md
solution/2500-2599/2534.Time Taken to Cross the Door/README_EN.md
solution/2500-2599/2534.Time Taken to Cross the Door/Solution.cpp
solution/2500-2599/2534.Time Taken to Cross the Door/Solution.go
solution/2500-2599/2534.Time Taken to Cross the Door/Solution.java
solution/2500-2599/2534.Time Taken to Cross the Door/Solution.py
solution/2500-2599/2534.Time Taken to Cross the Door/Solution.rs
solution/2500-2599/2534.Time Taken to Cross the Door/Solution.ts

No.2534.Time Taken to Cross the Door

feat: add solutions to lc problem: No.2534

---

solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/README.md
solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/README_EN.md
solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/Solution.cpp
solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/Solution.go
solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/Solution.java
solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/Solution.py
solution/2200-2299/2265.Count Nodes Equal to Average of Subtree/Solution.ts

No.2265.Count Nodes Equal to Average of Subtree

feat: add solutions to lc problem: No.2265

---

solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/README.md
solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/README_EN.md
solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/Solution.cpp
solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/Solution.go
solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/Solution.java
solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/Solution.py
solution/2200-2299/2267.Check if There Is a Valid Parentheses String Path/Solution.ts

No.2267.Check if There Is a Valid Parentheses String Path

feat: add solutions to lc problem: No.2267

---

solution/0600-0699/0636.Exclusive Time of Functions/README.md
solution/0600-0699/0636.Exclusive Time of Functions/README_EN.md
solution/0600-0699/0636.Exclusive Time of Functions/Solution.cpp
solution/0600-0699/0636.Exclusive Time of Functions/Solution.go
solution/0600-0699/0636.Exclusive Time of Functions/Solution.java
solution/0600-0699/0636.Exclusive Time of Functions/Solution.py
solution/0600-0699/0636.Exclusive Time of Functions/Solution.ts

No.0636.Exclusive Time of Functions

feat: add solutions to lc problem: No.0636

---

lcof/面试题11. 旋转数组的最小数字/README.md

numbers[mid] == numbers[r] 并不能断定 numbers[mid] 一定不是最小值。应该修改为： 无法确定最小值的位置，但可以简单地缩小搜索范围，

fix(Update README.md):numbers[mid] == numbers[r] 并不能断定 numbers[mid] 一定不是最小值

---

solution/3200-3299/3242.Design Neighbor Sum Service/README.md
solution/3200-3299/3242.Design Neighbor Sum Service/README_EN.md
solution/3200-3299/3242.Design Neighbor Sum Service/Solution.cpp
solution/3200-3299/3242.Design Neighbor Sum Service/Solution.go
solution/3200-3299/3242.Design Neighbor Sum Service/Solution.java
solution/3200-3299/3242.Design Neighbor Sum Service/Solution.py
solution/3200-3299/3242.Design Neighbor Sum Service/Solution.ts

No.3242.Design Neighbor Sum Service

chore: update solutions to lc problem: No.3242

---

solution/0500-0599/0540.Single Element in a Sorted Array/README.md
solution/0500-0599/0540.Single Element in a Sorted Array/README_EN.md
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.c
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.cpp
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.go
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.java
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.py
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.rs
solution/0500-0599/0540.Single Element in a Sorted Array/Solution.ts

No.0540.Single Element in a Sorted Array

feat: add solutions to lc problem: No.0540

---

solution/3300-3399/3348.Smallest Divisible Digit Product II/README.md
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/README.md
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/README_EN.md
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/Solution.cpp
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/Solution.go
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/Solution.java
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/Solution.py
solution/3300-3399/3349.Adjacent Increasing Subarrays Detection I/Solution.ts
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/README.md
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/README_EN.md
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/Solution.cpp
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/Solution.go
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/Solution.java
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/Solution.py
solution/3300-3399/3350.Adjacent Increasing Subarrays Detection II/Solution.ts

* No.3349.Adjacent Increasing Subarrays Detection I
* No.3350.Adjacent Increasing Subarrays Detection II

feat: add solutions to lc problems: No.3349,3350

---

lcof/面试题26. 树的子结构/README.md

函数 dfs(A,B) 的执行步骤第三条应该和下面的总结一致：
即，
如果其中有一个返回 true，则树 B 是树 A 的子结构，返回 true；否则，返回 false。

fix（Update README.md）：函数 dfs(A,B) 的执行步骤第三条应该和下面的总结一致

---

solution/2200-2299/2226.Maximum Candies Allocated to K Children/README.md
solution/2200-2299/2226.Maximum Candies Allocated to K Children/README_EN.md
solution/2200-2299/2226.Maximum Candies Allocated to K Children/Solution.cpp
solution/2200-2299/2226.Maximum Candies Allocated to K Children/Solution.go
solution/2200-2299/2226.Maximum Candies Allocated to K Children/Solution.java
solution/2200-2299/2226.Maximum Candies Allocated to K Children/Solution.py
solution/2200-2299/2226.Maximum Candies Allocated to K Children/Solution.ts

No.2226.Maximum Candies Allocated to K Children

feat: add solutions to lc problem: No.2226

---

solution/0600-0699/0692.Top K Frequent Words/README.md
solution/0600-0699/0692.Top K Frequent Words/README_EN.md
solution/0600-0699/0692.Top K Frequent Words/Solution.cpp
solution/0600-0699/0692.Top K Frequent Words/Solution.go
solution/0600-0699/0692.Top K Frequent Words/Solution.java
solution/0600-0699/0692.Top K Frequent Words/Solution.ts

feat: add solutions to lc problem: No.0692

---

solution/3300-3399/3361.Shift Distance Between Two Strings/README.md
solution/3300-3399/3361.Shift Distance Between Two Strings/README_EN.md
solution/3300-3399/3361.Shift Distance Between Two Strings/Solution.cpp
solution/3300-3399/3361.Shift Distance Between Two Strings/Solution.go
solution/3300-3399/3361.Shift Distance Between Two Strings/Solution.java
solution/3300-3399/3361.Shift Distance Between Two Strings/Solution.py
solution/3300-3399/3361.Shift Distance Between Two Strings/Solution.ts

No.3361.Shift Distance Between Two Strings

feat: add solutions to lc problem: No.3361

---

solution/3300-3399/3365.Rearrange K Substrings to Form Target String/README.md
solution/3300-3399/3365.Rearrange K Substrings to Form Target String/README_EN.md
solution/3300-3399/3365.Rearrange K Substrings to Form Target String/Solution.cpp
solution/3300-3399/3365.Rearrange K Substrings to Form Target String/Solution.go
solution/3300-3399/3365.Rearrange K Substrings to Form Target String/Solution.java
solution/3300-3399/3365.Rearrange K Substrings to Form Target String/Solution.py
solution/3300-3399/3365.Rearrange K Substrings to Form Target String/Solution.ts

No.3365.Rearrange K Substrings to Form Target String

feat: add solutions to lc problem: No.3365

---

solution/1800-1899/1840.Maximum Building Height/README.md
solution/1800-1899/1840.Maximum Building Height/README_EN.md
solution/1800-1899/1840.Maximum Building Height/Solution.cpp
solution/1800-1899/1840.Maximum Building Height/Solution.ts

No.1840.Maximum Building Height

feat: add solutions to lc problem: No.1840

---

solution/0900-0999/0935.Knight Dialer/README.md
solution/0900-0999/0935.Knight Dialer/README_EN.md
solution/0900-0999/0935.Knight Dialer/Solution.cpp
solution/0900-0999/0935.Knight Dialer/Solution.cs
solution/0900-0999/0935.Knight Dialer/Solution.go
solution/0900-0999/0935.Knight Dialer/Solution.java
solution/0900-0999/0935.Knight Dialer/Solution.py
solution/0900-0999/0935.Knight Dialer/Solution2.cpp
solution/0900-0999/0935.Knight Dialer/Solution2.cs
solution/0900-0999/0935.Knight Dialer/Solution2.go
solution/0900-0999/0935.Knight Dialer/Solution2.java
solution/0900-0999/0935.Knight Dialer/Solution2.py
solution/0900-0999/0935.Knight Dialer/Solution2.ts
solution/0900-0999/0935.Knight Dialer/solution.ts

feat: add solutions to lc problem: No.0935

---

solution/1300-1399/1305.All Elements in Two Binary Search Trees/README.md
solution/1300-1399/1305.All Elements in Two Binary Search Trees/README_EN.md
solution/1300-1399/1305.All Elements in Two Binary Search Trees/Solution.cpp
solution/1300-1399/1305.All Elements in Two Binary Search Trees/Solution.go
solution/1300-1399/1305.All Elements in Two Binary Search Trees/Solution.java
solution/1300-1399/1305.All Elements in Two Binary Search Trees/Solution.py
solution/1300-1399/1305.All Elements in Two Binary Search Trees/Solution.rs
solution/1300-1399/1305.All Elements in Two Binary Search Trees/Solution.ts

No.1305.All Elements in Two Binary Search Trees

feat: add solutions to lc problem: No.1305

---

solution/2000-2099/2057.Smallest Index With Equal Value/README.md
solution/2000-2099/2057.Smallest Index With Equal Value/README_EN.md
solution/2000-2099/2057.Smallest Index With Equal Value/Solution.cj
solution/2000-2099/2057.Smallest Index With Equal Value/Solution.cpp
solution/2000-2099/2057.Smallest Index With Equal Value/Solution.go
solution/2000-2099/2057.Smallest Index With Equal Value/Solution.py
solution/2000-2099/2057.Smallest Index With Equal Value/Solution.rs
solution/2000-2099/2057.Smallest Index With Equal Value/Solution.ts

No.2057.Smallest Index With Equal Value

feat: add solutions to lc problem: No.2057

---

solution/1300-1399/1385.Find the Distance Value Between Two Arrays/README.md
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/README_EN.md
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/Solution.cpp
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/Solution.go
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/Solution.java
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/Solution.py
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/Solution.rs
solution/1300-1399/1385.Find the Distance Value Between Two Arrays/Solution.ts

No.1385.Find the Distance Value Between Two Arrays

feat: add solutions to lc problem: No.1385

---

solution/1000-1099/1009.Complement of Base 10 Integer/README.md
solution/1000-1099/1009.Complement of Base 10 Integer/README_EN.md
solution/1000-1099/1009.Complement of Base 10 Integer/Solution.cpp
solution/1000-1099/1009.Complement of Base 10 Integer/Solution.go
solution/1000-1099/1009.Complement of Base 10 Integer/Solution.java
solution/1000-1099/1009.Complement of Base 10 Integer/Solution.py
solution/1000-1099/1009.Complement of Base 10 Integer/Solution.rs
solution/1000-1099/1009.Complement of Base 10 Integer/Solution.ts

No.1009.Complement of Base 10 Integer

feat: add solutions to lc problem: No.1009

---

solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/README.md
solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/README_EN.md
solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/Solution.cpp
solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/Solution.go
solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/Solution.java
solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/Solution.py
solution/3300-3399/3380.Maximum Area Rectangle With Point Constraints I/Solution.ts

No.3380.Maximum Area Rectangle With Point Constraints I

feat: add solutions to lc problem: No.3380

---

solution/3300-3399/3376.Minimum Time to Break Locks I/README.md
solution/3300-3399/3376.Minimum Time to Break Locks I/README_EN.md
solution/3300-3399/3376.Minimum Time to Break Locks I/Solution.cpp
solution/3300-3399/3376.Minimum Time to Break Locks I/Solution.go
solution/3300-3399/3376.Minimum Time to Break Locks I/Solution.java
solution/3300-3399/3376.Minimum Time to Break Locks I/Solution.py
solution/3300-3399/3376.Minimum Time to Break Locks I/Solution.ts

No.3376.Minimum Time to Break Locks I

feat: add solutions to lc problem: No.3376

---

solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/README.md
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/README_EN.md
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/Solution.cpp
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/Solution.go
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/Solution.java
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/Solution.py
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/Solution.rs
solution/1800-1899/1897.Redistribute Characters to Make All Strings Equal/Solution.ts

No.1897.Redistribute Characters to Make All Strings Equal

feat: add solutions to lc problem: No.1897

---

solution/0300-0399/0354.Russian Doll Envelopes/README.md
solution/0300-0399/0354.Russian Doll Envelopes/README_EN.md
solution/0300-0399/0354.Russian Doll Envelopes/Solution.py

Remove confusing and unecessary lines.
Since h is not bigger than the last element in the d array, it is not possible that bisect_left(d, h) will return the index that is equal to the length of the array d. The maximum value of the return value is len(d)-1.
I also tested it in the leetcode and it works.

fix: remove unused lines of no.354

---

solution/0900-0999/0974.Subarray Sums Divisible by K/README_EN.md

Adding english explanation for question 0974

feat: readme update for lc problem: 0974

---

solution/1900-1999/1979.Find Greatest Common Divisor of Array/README.md
solution/1900-1999/1979.Find Greatest Common Divisor of Array/README_EN.md
solution/1900-1999/1979.Find Greatest Common Divisor of Array/Solution.cpp
solution/1900-1999/1979.Find Greatest Common Divisor of Array/Solution.rs
solution/1900-1999/1979.Find Greatest Common Divisor of Array/Solution.ts

No.1979.Find Greatest Common Divisor of Array

feat: add solutions to lc problem: No.1979

---

solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/README.md
solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/README_EN.md
solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/Solution.cpp
solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/Solution.go
solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/Solution.java
solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/Solution.py
solution/3300-3399/3397.Maximum Number of Distinct Elements After Operations/Solution.ts

No.3397.Maximum Number of Distinct Elements After Operations

feat: add solutions to lc problem: No.3397

---

solution/1500-1599/1592.Rearrange Spaces Between Words/README.md
solution/1500-1599/1592.Rearrange Spaces Between Words/README_EN.md
solution/1500-1599/1592.Rearrange Spaces Between Words/Solution.cpp
solution/1500-1599/1592.Rearrange Spaces Between Words/Solution.java
solution/1500-1599/1592.Rearrange Spaces Between Words/Solution.py
solution/1500-1599/1592.Rearrange Spaces Between Words/Solution.rs
solution/1500-1599/1592.Rearrange Spaces Between Words/Solution.ts

No.1592.Rearrange Spaces Between Words

feat: add solutions to lc problem: No.1592

---

solution/1500-1599/1565.Unique Orders and Customers Per Month/README.md
solution/1500-1599/1565.Unique Orders and Customers Per Month/README_EN.md
solution/1500-1599/1565.Unique Orders and Customers Per Month/Solution.py
solution/1500-1599/1565.Unique Orders and Customers Per Month/Solution.sql

No.1565.Unique Orders and Customers Per Month

feat: add solutions to lc problem: No.1565

---

solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/README.md
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/README_EN.md
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution.cpp
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution.go
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution.java
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution.py
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution.ts
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution2.cpp
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution2.go
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution2.java
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution2.py
solution/1500-1599/1567.Maximum Length of Subarray With Positive Product/Solution2.ts

No.1567.Maximum Length of Subarray With Positive Product

feat: add solutions to lc problem: No.1567

---

solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/README.md
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/README_EN.md
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution.cpp
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution.go
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution.java
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution.py
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution.ts
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution2.cpp
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution2.go
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution2.java
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution2.py
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/Solution2.ts

No.1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers

feat: add solutions to lc problem: No.1577

---

solution/1500-1599/1585.Check If String Is Transformable With Substring Sort Operations/README_EN.md
solution/1500-1599/1588.Sum of All Odd Length Subarrays/README.md
solution/1500-1599/1588.Sum of All Odd Length Subarrays/README_EN.md
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.c
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.cpp
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.go
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.java
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.py
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.rs
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution.ts
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.c
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.cpp
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.go
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.java
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.py
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.rs
solution/1500-1599/1588.Sum of All Odd Length Subarrays/Solution2.ts

No.1588.Sum of All Odd Length Subarrays

feat: add solutions to lc problem: No.1588

---

solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/README.md
solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/README_EN.md
solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/Solution.cpp
solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/Solution.go
solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/Solution.java
solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/Solution.py
solution/1500-1599/1593.Split a String Into the Max Number of Unique Substrings/Solution.ts

No.1593.Split a String Into the Max Number of Unique Substrings

feat: add solutions to lc problem: No.1593

---

solution/1500-1599/1565.Unique Orders and Customers Per Month/README_EN.md
solution/1500-1599/1577.Number of Ways Where Square of Number Is Equal to Product of Two Numbers/README_EN.md
solution/1500-1599/1589.Maximum Sum Obtained of Any Permutation/README_EN.md
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/README.md
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/README_EN.md
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/Solution.cpp
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/Solution.go
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/Solution.java
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/Solution.py
solution/3400-3499/3400.Maximum Number of Matching Indices After Right Shifts/Solution.ts
solution/README.md
solution/README_EN.md

No.3400.Maximum Number of Matching Indices After Right Shifts

feat: add solutions to lc problem: No.3400

---

solution/0000-0099/0001.Two Sum/README.md
solution/0000-0099/0001.Two Sum/README_EN.md
solution/0000-0099/0001.Two Sum/Solution.py
solution/0100-0199/0128.Longest Consecutive Sequence/README.md
solution/0100-0199/0128.Longest Consecutive Sequence/README_EN.md
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.cpp
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.go
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.java
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.js
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.py
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.rs
solution/0100-0199/0128.Longest Consecutive Sequence/Solution.ts
solution/0100-0199/0128.Longest Consecutive Sequence/Solution2.cpp
solution/0100-0199/0128.Longest Consecutive Sequence/Solution2.go
solution/0100-0199/0128.Longest Consecutive Sequence/Solution2.java
solution/0100-0199/0128.Longest Consecutive Sequence/Solution2.py
solution/0100-0199/0128.Longest Consecutive Sequence/Solution2.rs
solution/0100-0199/0128.Longest Consecutive Sequence/Solution2.ts

No.0128.Longest Consecutive Sequence

feat: add solutions to lc problem: No.0128

---

solution/0000-0099/0019.Remove Nth Node From End of List/README.md
solution/0000-0099/0019.Remove Nth Node From End of List/README_EN.md
solution/0000-0099/0019.Remove Nth Node From End of List/Solution.php
solution/0000-0099/0019.Remove Nth Node From End of List/Solution.swift

No.0019.Remove Nth Node From End of List

feat: add solutions to lc problem: No.0019

---

solution/0100-0199/0148.Sort List/README.md
solution/0100-0199/0148.Sort List/README_EN.md
solution/0100-0199/0148.Sort List/Solution.cpp
solution/0100-0199/0148.Sort List/Solution.cs
solution/0100-0199/0148.Sort List/Solution.go
solution/0100-0199/0148.Sort List/Solution.java
solution/0100-0199/0148.Sort List/Solution.js
solution/0100-0199/0148.Sort List/Solution.py
solution/0100-0199/0148.Sort List/Solution.ts

feat: add solutions to lc problem: No.0148

---

solution/0100-0199/0199.Binary Tree Right Side View/README.md
solution/0100-0199/0199.Binary Tree Right Side View/README_EN.md
solution/0100-0199/0199.Binary Tree Right Side View/Solution.cpp
solution/0100-0199/0199.Binary Tree Right Side View/Solution.go
solution/0100-0199/0199.Binary Tree Right Side View/Solution.java
solution/0100-0199/0199.Binary Tree Right Side View/Solution.js
solution/0100-0199/0199.Binary Tree Right Side View/Solution.py
solution/0100-0199/0199.Binary Tree Right Side View/Solution.rs
solution/0100-0199/0199.Binary Tree Right Side View/Solution.ts
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.cpp
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.go
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.java
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.js
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.py
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.rs
solution/0100-0199/0199.Binary Tree Right Side View/Solution2.ts

No.0199.Binary Tree Right Side View

feat: add solutions to lc problem: No.0199

---

solution/0900-0999/0994.Rotting Oranges/README.md
solution/0900-0999/0994.Rotting Oranges/README_EN.md
solution/0900-0999/0994.Rotting Oranges/Solution.cpp
solution/0900-0999/0994.Rotting Oranges/Solution.go
solution/0900-0999/0994.Rotting Oranges/Solution.java
solution/0900-0999/0994.Rotting Oranges/Solution.js
solution/0900-0999/0994.Rotting Oranges/Solution.py
solution/0900-0999/0994.Rotting Oranges/Solution.rs

feat: add solutions to lc problem: No.0994

---

solution/0700-0799/0729.My Calendar I/README.md
solution/0700-0799/0729.My Calendar I/README_EN.md
solution/0700-0799/0729.My Calendar I/Solution.cpp
solution/0700-0799/0729.My Calendar I/Solution.go
solution/0700-0799/0729.My Calendar I/Solution.java
solution/0700-0799/0729.My Calendar I/Solution.js
solution/0700-0799/0729.My Calendar I/Solution.py
solution/0700-0799/0729.My Calendar I/Solution.rs
solution/0700-0799/0729.My Calendar I/Solution.ts

feat: add solutions to lc problem: No.0729

---

solution/0700-0799/0732.My Calendar III/README.md
solution/0700-0799/0732.My Calendar III/README_EN.md
solution/0700-0799/0732.My Calendar III/Solution.cpp
solution/0700-0799/0732.My Calendar III/Solution.py
solution/0700-0799/0732.My Calendar III/Solution.ts

feat: add solutions to lc problem: No.0732

---

solution/3000-3099/3019.Number of Changing Keys/README.md
solution/3000-3099/3019.Number of Changing Keys/README_EN.md
solution/3000-3099/3019.Number of Changing Keys/Solution.py

No.3019.Number of Changing Keys

perf: update python solution to lc problem: No.3019

---

solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/README.md
solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/README_EN.md
solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/Solution.cpp
solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/Solution.go
solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/Solution.java
solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/Solution.py
solution/3400-3499/3418.Maximum Amount of Money Robot Can Earn/Solution.ts

No.3418.Maximum Amount of Money Robot Can Earn

feat: add solutions to lc problem: No.3418

---

solution/0500-0599/0573.Squirrel Simulation/README.md
solution/0500-0599/0573.Squirrel Simulation/README_EN.md
solution/0500-0599/0573.Squirrel Simulation/Solution.cpp
solution/0500-0599/0573.Squirrel Simulation/Solution.cs
solution/0500-0599/0573.Squirrel Simulation/Solution.go
solution/0500-0599/0573.Squirrel Simulation/Solution.java
solution/0500-0599/0573.Squirrel Simulation/Solution.py
solution/0500-0599/0573.Squirrel Simulation/Solution.rs
solution/0500-0599/0573.Squirrel Simulation/Solution.ts

feat: add solutions to lc problem: No.0573

---

solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/README.md
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/README_EN.md
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/Solution.cpp
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/Solution.go
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/Solution.java
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/Solution.py
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/Solution.rs
solution/3000-3099/3066.Minimum Operations to Exceed Threshold Value II/Solution.ts

No.3066.Minimum Operations to Exceed Threshold Value II

feat: add solutions to lc problem: No.3066

---

solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/README.md
solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/README_EN.md
solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/Solution.cpp
solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/Solution.java
solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/Solution.py
solution/README.md
solution/README_EN.md

No.3422.Minimum Operations to Make Subarray Elements Equal

feat: add solutions to lc problem: No.3422

---

solution/0000-0099/0086.Partition List/README.md
solution/0000-0099/0086.Partition List/README_EN.md
solution/0000-0099/0086.Partition List/Solution.cpp
solution/0000-0099/0086.Partition List/Solution.cs
solution/0000-0099/0086.Partition List/Solution.go
solution/0000-0099/0086.Partition List/Solution.java
solution/0000-0099/0086.Partition List/Solution.py
solution/0000-0099/0086.Partition List/Solution.rs
solution/0000-0099/0086.Partition List/Solution.ts

feat: add solutions to lc problem: No.0086

---

solution/3200-3299/3287.Find the Maximum Sequence Value of Array/README.md
solution/3200-3299/3287.Find the Maximum Sequence Value of Array/README_EN.md
solution/3200-3299/3287.Find the Maximum Sequence Value of Array/Solution.cpp
solution/3200-3299/3287.Find the Maximum Sequence Value of Array/Solution.go
solution/3200-3299/3287.Find the Maximum Sequence Value of Array/Solution.java
solution/3200-3299/3287.Find the Maximum Sequence Value of Array/Solution.py
solution/3200-3299/3287.Find the Maximum Sequence Value of Array/Solution.ts

No.3287.Find the Maximum Sequence Value of Array

feat: add solutions to lc problem: No.3287

---

solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/README.md
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/README_EN.md
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/Solution.cs
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/Solution.go
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/Solution.java
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/Solution.py
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/Solution.rs
solution/1900-1999/1909.Remove One Element to Make the Array Strictly Increasing/Solution.ts

No.1909.Remove One Element to Make the Array Strictly Increasing

feat: add solutions to lc problem: No.1909

---

solution/0500-0599/0547.Number of Provinces/README.md
solution/0500-0599/0547.Number of Provinces/README_EN.md
solution/0500-0599/0547.Number of Provinces/Solution.cpp
solution/0500-0599/0547.Number of Provinces/Solution.ts
solution/0500-0599/0547.Number of Provinces/Solution2.cpp
solution/0500-0599/0547.Number of Provinces/Solution2.ts

feat: update solutions to lc problem: No.0547

---

solution/2200-2299/2218.Maximum Value of K Coins From Piles/README.md
solution/2200-2299/2218.Maximum Value of K Coins From Piles/README_EN.md
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution.cpp
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution.go
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution.java
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution.py
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution.ts
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution2.cpp
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution2.go
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution2.java
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution2.py
solution/2200-2299/2218.Maximum Value of K Coins From Piles/Solution2.ts

No.2218.Maximum Value of K Coins From Piles

feat: add solutions to lc problem: No.2218

---

solution/2200-2299/2220.Minimum Bit Flips to Convert Number/README.md
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/README_EN.md
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.c
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.cpp
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.go
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.java
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.js
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.py
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution.rs
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution2.js
solution/2200-2299/2220.Minimum Bit Flips to Convert Number/Solution2.ts

No.2220.Minimum Bit Flips to Convert Number

feat: add solutions to lc problem: No.2220

---

solution/2200-2299/2206.Divide Array Into Equal Pairs/README.md
solution/2200-2299/2206.Divide Array Into Equal Pairs/README_EN.md
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.cpp
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.go
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.js
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.rs
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.ts

No.2206.Divide Array Into Equal Pairs

feat: add solutions to lc problem: No.2206

---

solution/2100-2199/2190.Most Frequent Number Following Key In an Array/README.md
solution/2100-2199/2190.Most Frequent Number Following Key In an Array/README_EN.md
solution/2100-2199/2190.Most Frequent Number Following Key In an Array/Solution.js
solution/2100-2199/2190.Most Frequent Number Following Key In an Array/Solution.php

No.2190.Most Frequent Number Following Key In an Array

feat: add solutions to lc problem: No.2190

---

solution/2100-2199/2165.Smallest Value of the Rearranged Number/README.md
solution/2100-2199/2165.Smallest Value of the Rearranged Number/README_EN.md
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.cpp
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.go
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.java
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.js
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.py
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.rs
solution/2100-2199/2165.Smallest Value of the Rearranged Number/Solution.ts
solution/2100-2199/2169.Count Operations to Obtain Zero/README.md
solution/2100-2199/2169.Count Operations to Obtain Zero/README_EN.md
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution.cpp
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution.go
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution.java
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution.js
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution.py
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution.rs
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.cpp
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.go
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.java
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.js
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.py
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.rs
solution/2100-2199/2169.Count Operations to Obtain Zero/Solution2.ts

* No.2165.Smallest Value of the Rearranged Number
* No.2169.Count Operations to Obtain Zero

feat: add solutions to lc problems: No.2165,2169

---

solution/2100-2199/2178.Maximum Split of Positive Even Integers/README.md
solution/2100-2199/2178.Maximum Split of Positive Even Integers/README_EN.md
solution/2100-2199/2178.Maximum Split of Positive Even Integers/Solution.cpp
solution/2100-2199/2178.Maximum Split of Positive Even Integers/Solution.py
solution/2100-2199/2178.Maximum Split of Positive Even Integers/Solution.rs

No.2178.Maximum Split of Positive Even Integers

feat: add solutions to lc problem: No.2178

---

solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/README.md
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/README_EN.md
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.cpp
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.go
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.java
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.php
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.py
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.ts
solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution2.ts

No.1941.Check if All Characters Have Equal Number of Occurrences

feat: add solutions to lc problem: No.1941

---

solution/1900-1999/1926.Nearest Exit from Entrance in Maze/README.md
solution/1900-1999/1926.Nearest Exit from Entrance in Maze/README_EN.md
solution/1900-1999/1926.Nearest Exit from Entrance in Maze/Solution.cpp
solution/1900-1999/1926.Nearest Exit from Entrance in Maze/Solution.go
solution/1900-1999/1926.Nearest Exit from Entrance in Maze/Solution.java
solution/1900-1999/1926.Nearest Exit from Entrance in Maze/Solution.py
solution/1900-1999/1926.Nearest Exit from Entrance in Maze/Solution.ts
solution/1900-1999/1927.Sum Game/README_EN.md

* No.1926.Nearest Exit from Entrance in Maze
* No.1927.Sum Game

feat: add solutions to lc problems: No.1926,1927

---

solution/2400-2499/2412.Minimum Money Required Before Transactions/README.md
solution/2400-2499/2412.Minimum Money Required Before Transactions/README_EN.md
solution/2400-2499/2412.Minimum Money Required Before Transactions/Solution.js
solution/2400-2499/2412.Minimum Money Required Before Transactions/Solution.rs
solution/2400-2499/2412.Minimum Money Required Before Transactions/Solution.ts

No.2412.Minimum Money Required Before Transactions

feat: add solutions to lc problem: No.2412

---

solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/README.md
solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/README_EN.md
solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/Solution.cpp
solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/Solution.go
solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/Solution.js
solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/Solution.rs
solution/2300-2399/2323.Find Minimum Time to Finish All Jobs II/Solution.ts

No.2323.Find Minimum Time to Finish All Jobs II

feat: add solutions to lc problem: No.2323

---

solution/1500-1599/1590.Make Sum Divisible by P/README.md
solution/1500-1599/1590.Make Sum Divisible by P/README_EN.md
solution/1500-1599/1590.Make Sum Divisible by P/Solution.js
solution/1500-1599/1590.Make Sum Divisible by P/Solution.rs

No.1590.Make Sum Divisible by P

feat: add solutions to lc problem: No.1590

---

solution/0200-0299/0219.Contains Duplicate II/README.md
solution/0200-0299/0219.Contains Duplicate II/README_EN.md
solution/0200-0299/0219.Contains Duplicate II/Solution.php

feat: update solutions to lc problem: No.0219

---

solution/3400-3499/3436.Find Valid Emails/README.md
solution/3400-3499/3436.Find Valid Emails/README_EN.md
solution/3400-3499/3436.Find Valid Emails/Solution.py
solution/3400-3499/3436.Find Valid Emails/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

feat: add solutions to lc problem: No.3436

---

solution/3400-3499/3433.Count Mentions Per User/README.md
solution/3400-3499/3433.Count Mentions Per User/README_EN.md
solution/3400-3499/3433.Count Mentions Per User/Solution.cpp
solution/3400-3499/3433.Count Mentions Per User/Solution.go
solution/3400-3499/3433.Count Mentions Per User/Solution.java
solution/3400-3499/3433.Count Mentions Per User/Solution.py
solution/3400-3499/3433.Count Mentions Per User/Solution.ts

No.3433.Count Mentions Per User

feat: add solutions to lc problem: No.3433

---

solution/3400-3499/3437.Permutations III/README.md
solution/3400-3499/3437.Permutations III/README_EN.md
solution/3400-3499/3437.Permutations III/Solution.cpp
solution/3400-3499/3437.Permutations III/Solution.go
solution/3400-3499/3437.Permutations III/Solution.java
solution/3400-3499/3437.Permutations III/Solution.py
solution/3400-3499/3437.Permutations III/Solution.ts
solution/README.md
solution/README_EN.md

feat: add solutions to lc problem: No.3437

---

solution/0500-0599/0598.Range Addition II/README.md
solution/0500-0599/0598.Range Addition II/README_EN.md
solution/0500-0599/0598.Range Addition II/Solution.cpp
solution/0500-0599/0598.Range Addition II/Solution.js
solution/0500-0599/0598.Range Addition II/Solution.rs
solution/0500-0599/0598.Range Addition II/Solution.ts

feat: add solutions to lc problem: No.0598

---

solution/0900-0999/0922.Sort Array By Parity II/README.md
solution/0900-0999/0922.Sort Array By Parity II/README_EN.md
solution/0900-0999/0922.Sort Array By Parity II/Solution.rs

No.0922.Sort Array By Parity II

feat: add solutions to lc problem: No.0922

---

solution/2300-2399/2389.Longest Subsequence With Limited Sum/README.md
solution/2300-2399/2389.Longest Subsequence With Limited Sum/README_EN.md
solution/2300-2399/2389.Longest Subsequence With Limited Sum/Solution.cpp
solution/2300-2399/2389.Longest Subsequence With Limited Sum/Solution.cs
solution/2300-2399/2389.Longest Subsequence With Limited Sum/Solution.java
solution/2300-2399/2389.Longest Subsequence With Limited Sum/Solution.js
solution/2300-2399/2389.Longest Subsequence With Limited Sum/Solution.rs

No.2389.Longest Subsequence With Limited Sum

feat: add solutions to lc problem: No.2389

---

solution/1900-1999/1946.Largest Number After Mutating Substring/README.md
solution/1900-1999/1946.Largest Number After Mutating Substring/README_EN.md
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.cpp
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.go
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.java
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.js
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.py
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.rs
solution/1900-1999/1946.Largest Number After Mutating Substring/Solution.ts

No.1946.Largest Number After Mutating Substring

feat: add solutions to lc problem: No.1946

---

solution/0000-0099/0016.3Sum Closest/README.md
solution/0000-0099/0016.3Sum Closest/README_EN.md
solution/0000-0099/0016.3Sum Closest/Solution.cs

feat: add csharp solution to lc problem: No.0016

---

solution/1900-1999/1920.Build Array from Permutation/README.md
solution/1900-1999/1920.Build Array from Permutation/README_EN.md
solution/1900-1999/1920.Build Array from Permutation/Solution.js
solution/1900-1999/1920.Build Array from Permutation/Solution.ts
solution/1900-1999/1996.The Number of Weak Characters in the Game/README_EN.md

No.1920.Build Array from Permutation

feat: add solutions to lc problem: No.1920

---

solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/README.md
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/README_EN.md
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/Solution.cpp
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/Solution.cs
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/Solution.go
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/Solution.java
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/Solution.js
solution/1900-1999/1930.Unique Length-3 Palindromic Subsequences/Solution.ts

No.1930.Unique Length-3 Palindromic Subsequences

feat: add solutions to lc problem: No.1930

---

solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/README.md
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/README_EN.md
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/Solution.cpp
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/Solution.go
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/Solution.java
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/Solution.js
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/Solution.py
solution/1900-1999/1942.The Number of the Smallest Unoccupied Chair/Solution.ts

No.1942.The Number of the Smallest Unoccupied Chair

feat: add solutions to lc problem: No.1942

---

solution/0000-0099/0019.Remove Nth Node From End of List/README.md
solution/0000-0099/0019.Remove Nth Node From End of List/README_EN.md
solution/0000-0099/0019.Remove Nth Node From End of List/Solution.cs

No.0019.Remove Nth Node From End of List

feat: add csharp solution to lc problem: No.0019

---

solution/0000-0099/0021.Merge Two Sorted Lists/README.md
solution/0000-0099/0021.Merge Two Sorted Lists/README_EN.md
solution/0000-0099/0021.Merge Two Sorted Lists/Solution.cs
solution/0000-0099/0021.Merge Two Sorted Lists/Solution.php
solution/0000-0099/0021.Merge Two Sorted Lists/Solution.rb
solution/0000-0099/0021.Merge Two Sorted Lists/Solution2.cs
solution/0000-0099/0021.Merge Two Sorted Lists/Solution2.php
solution/0000-0099/0021.Merge Two Sorted Lists/Solution2.rb

No.0021.Merge Two Sorted Lists

feat: update solutions to lc problem: No.0021

---

solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/README.md
solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/README_EN.md
solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/Solution.cpp
solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/Solution.go
solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/Solution.java
solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/Solution.py
solution/1800-1899/1864.Minimum Number of Swaps to Make the Binary String Alternating/Solution.ts

No.1864.Minimum Number of Swaps to Make the Binary String Alternating

feat: add solutions to lc problem: No.1864

---

solution/1800-1899/1865.Finding Pairs With a Certain Sum/README.md
solution/1800-1899/1865.Finding Pairs With a Certain Sum/README_EN.md
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.cpp
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.cs
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.go
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.java
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.js
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.py
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.ts

No.1865.Finding Pairs With a Certain Sum

feat: add solutions to lc problem: No.1865

---

solution/0000-0099/0022.Generate Parentheses/README.md
solution/0000-0099/0022.Generate Parentheses/README_EN.md
solution/0000-0099/0022.Generate Parentheses/Solution.cs

feat: add solution to lc problem: No.0022

---

solution/1800-1899/1882.Process Tasks Using Servers/README.md
solution/1800-1899/1882.Process Tasks Using Servers/README_EN.md
solution/1800-1899/1882.Process Tasks Using Servers/Solution.cpp
solution/1800-1899/1882.Process Tasks Using Servers/Solution.go
solution/1800-1899/1882.Process Tasks Using Servers/Solution.java
solution/1800-1899/1882.Process Tasks Using Servers/Solution.py
solution/1800-1899/1882.Process Tasks Using Servers/Solution.ts

No.1882.Process Tasks Using Servers

feat: add solutions to lc problem: No.1882

---

solution/1800-1899/1885.Count Pairs in Two Arrays/README.md
solution/1800-1899/1885.Count Pairs in Two Arrays/README_EN.md
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.cpp
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.go
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.java
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.js
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.py
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.rs
solution/1800-1899/1885.Count Pairs in Two Arrays/Solution.ts

No.1885.Count Pairs in Two Arrays

feat: add solutions to lc problem: No.1885

---

solution/1700-1799/1760.Minimum Limit of Balls in a Bag/README.md
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/README_EN.md
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.cpp
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.cs
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.go
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.java
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.js
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.py
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.rs
solution/1700-1799/1760.Minimum Limit of Balls in a Bag/Solution.ts

No.1760.Minimum Limit of Balls in a Bag

feat: add solutions to lc problem: No.1760

---

solution/1700-1799/1760.Minimum Limit of Balls in a Bag/README_EN.md
solution/1800-1899/1887.Reduction Operations to Make the Array Elements Equal/README.md
solution/3400-3499/3450.Maximum Students on a Single Bench/README.md
solution/3400-3499/3450.Maximum Students on a Single Bench/README_EN.md
solution/3400-3499/3450.Maximum Students on a Single Bench/Solution.cpp
solution/3400-3499/3450.Maximum Students on a Single Bench/Solution.go
solution/3400-3499/3450.Maximum Students on a Single Bench/Solution.java
solution/3400-3499/3450.Maximum Students on a Single Bench/Solution.py
solution/3400-3499/3450.Maximum Students on a Single Bench/Solution.rs
solution/3400-3499/3450.Maximum Students on a Single Bench/Solution.ts
solution/README.md
solution/README_EN.md

No.3450.Maximum Students on a Single Bench

feat: add solutions to lc problem: No.3450

---

.prettierignore
solution/3400-3499/3451.Find Invalid IP Addresses/README.md
solution/3400-3499/3451.Find Invalid IP Addresses/README_EN.md
solution/3400-3499/3451.Find Invalid IP Addresses/Solution.py
solution/3400-3499/3451.Find Invalid IP Addresses/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3451.Find Invalid IP Addresses

feat: add sql solution to lc problem: No.3451

---

lcci/17.15.Longest Word/README.md
lcci/17.15.Longest Word/README_EN.md
lcci/17.15.Longest Word/Solution.cpp
lcci/17.15.Longest Word/Solution.go
lcci/17.15.Longest Word/Solution.java
lcci/17.15.Longest Word/Solution.py
lcci/17.15.Longest Word/Solution.rs
lcci/17.15.Longest Word/Solution.swift
lcci/17.15.Longest Word/Solution.ts

feat: add solutions to lcci problem: No.17.15

---

solution/1700-1799/1706.Where Will the Ball Fall/README.md
solution/1700-1799/1706.Where Will the Ball Fall/README_EN.md
solution/1700-1799/1706.Where Will the Ball Fall/Solution.js
solution/1700-1799/1706.Where Will the Ball Fall/Solution.rs

No.1706.Where Will the Ball Fall

feat: add solutions to lc problem: No.1706

---

solution/1200-1299/1289.Minimum Falling Path Sum II/README_EN.md
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/README.md
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/README_EN.md
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.cpp
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.go
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.java
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.js
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.py
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.rs
solution/3400-3499/3460.Longest Common Prefix After at Most One Removal/Solution.ts
solution/README.md
solution/README_EN.md

No.3460.Longest Common Prefix After at Most One Removal

feat: add solutions to lc problem: No.3460

---

solution/2000-2099/2080.Range Frequency Queries/README.md
solution/2000-2099/2080.Range Frequency Queries/README_EN.md
solution/2000-2099/2080.Range Frequency Queries/Solution.cs
solution/2000-2099/2080.Range Frequency Queries/Solution.js
solution/2000-2099/2080.Range Frequency Queries/Solution.rs
solution/2000-2099/2080.Range Frequency Queries/Solution.ts

No.2080.Range Frequency Queries

feat: add solutions to lc problem: No.2080

---

solution/2200-2299/2211.Count Collisions on a Road/README.md
solution/2200-2299/2211.Count Collisions on a Road/README_EN.md
solution/2200-2299/2211.Count Collisions on a Road/Solution.cpp
solution/2200-2299/2211.Count Collisions on a Road/Solution.go
solution/2200-2299/2211.Count Collisions on a Road/Solution.java
solution/2200-2299/2211.Count Collisions on a Road/Solution.js
solution/2200-2299/2211.Count Collisions on a Road/Solution.py

No.2211.Count Collisions on a Road

feat: add solutions to lc problem: No.2211

---

solution/0700-0799/0784.Letter Case Permutation/README.md
solution/0700-0799/0784.Letter Case Permutation/README_EN.md
solution/0700-0799/0784.Letter Case Permutation/Solution.cpp
solution/0700-0799/0784.Letter Case Permutation/Solution.java
solution/0700-0799/0784.Letter Case Permutation/Solution.py
solution/0700-0799/0784.Letter Case Permutation/Solution.rs
solution/0700-0799/0784.Letter Case Permutation/Solution.ts
solution/0700-0799/0784.Letter Case Permutation/Solution2.cpp
solution/0700-0799/0784.Letter Case Permutation/Solution2.rs
solution/0700-0799/0784.Letter Case Permutation/Solution2.ts

No.0784.Letter Case Permutation

feat: add solutions to lc problem: No.0784

---

solution/1200-1299/1206.Design Skiplist/README.md
solution/1200-1299/1206.Design Skiplist/README_EN.md
solution/1200-1299/1206.Design Skiplist/Solution.ts

feat: add solutions to lc problem: No.1206

---

solution/0700-0799/0779.K-th Symbol in Grammar/README.md
solution/0700-0799/0779.K-th Symbol in Grammar/README_EN.md
solution/0700-0799/0779.K-th Symbol in Grammar/Solution.ts
solution/0700-0799/0779.K-th Symbol in Grammar/Solution2.ts

No.0779.K-th Symbol in Grammar

feat: add solutions to lc problem: No.0779

---

solution/2500-2599/2502.Design Memory Allocator/README.md
solution/2500-2599/2502.Design Memory Allocator/README_EN.md
solution/2500-2599/2502.Design Memory Allocator/Solution.cpp
solution/2500-2599/2502.Design Memory Allocator/Solution.go
solution/2500-2599/2502.Design Memory Allocator/Solution.java
solution/2500-2599/2502.Design Memory Allocator/Solution.py
solution/2500-2599/2502.Design Memory Allocator/Solution.ts
solution/2500-2599/2502.Design Memory Allocator/Solution2.cpp
solution/2500-2599/2502.Design Memory Allocator/Solution2.go
solution/2500-2599/2502.Design Memory Allocator/Solution2.java
solution/2500-2599/2502.Design Memory Allocator/Solution2.py

No.2502.Design Memory Allocator

feat: add solutions to lc problem: No.2502

---

solution/1700-1799/1745.Palindrome Partitioning IV/README.md
solution/1700-1799/1745.Palindrome Partitioning IV/README_EN.md
solution/1700-1799/1745.Palindrome Partitioning IV/Solution.cpp
solution/1700-1799/1745.Palindrome Partitioning IV/Solution.go
solution/1700-1799/1745.Palindrome Partitioning IV/Solution.java
solution/1700-1799/1745.Palindrome Partitioning IV/Solution.py
solution/1700-1799/1745.Palindrome Partitioning IV/Solution.ts

No.1745.Palindrome Partitioning IV

feat: add solutions to lc problem: No.1745

---

solution/1500-1599/1524.Number of Sub-arrays With Odd Sum/README.md
solution/1500-1599/1524.Number of Sub-arrays With Odd Sum/README_EN.md
solution/1500-1599/1524.Number of Sub-arrays With Odd Sum/Solution.rs

No.1524.Number of Sub-arrays With Odd Sum

feat: add solutions to lc problem: No.1524

---

solution/0800-0899/0888.Fair Candy Swap/README.md
solution/0800-0899/0888.Fair Candy Swap/README_EN.md
solution/0800-0899/0888.Fair Candy Swap/Solution.cpp
solution/0800-0899/0888.Fair Candy Swap/Solution.go
solution/0800-0899/0888.Fair Candy Swap/Solution.java
solution/0800-0899/0888.Fair Candy Swap/Solution.py
solution/0800-0899/0888.Fair Candy Swap/Solution.ts

feat: add solutions to lc problem: No.0888

---

solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/README.md
solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/README_EN.md
solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/Solution.cpp
solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/Solution.go
solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/Solution.java
solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/Solution.py
solution/1900-1999/1974.Minimum Time to Type Word Using Special Typewriter/Solution.ts
solution/1900-1999/1977.Number of Ways to Separate Numbers/README_EN.md

No.1974.Minimum Time to Type Word Using Special Typewriter

feat: add solutions to lc problem: No.1974

---

solution/1200-1299/1278.Palindrome Partitioning III/README.md
solution/1200-1299/1278.Palindrome Partitioning III/README_EN.md
solution/1200-1299/1278.Palindrome Partitioning III/Solution.rs
solution/1200-1299/1278.Palindrome Partitioning III/Solution.ts

No.1278.Palindrome Partitioning III

feat: add solutions to lc problem: No.1278

---

solution/3400-3499/3470.Permutations IV/README.md
solution/3400-3499/3475.DNA Pattern Recognition/README.md
solution/3400-3499/3476.Maximize Profit from Task Assignment/README.md
solution/3400-3499/3476.Maximize Profit from Task Assignment/README_EN.md
solution/3400-3499/3476.Maximize Profit from Task Assignment/Solution.cpp
solution/3400-3499/3476.Maximize Profit from Task Assignment/Solution.go
solution/3400-3499/3476.Maximize Profit from Task Assignment/Solution.java
solution/3400-3499/3476.Maximize Profit from Task Assignment/Solution.py
solution/3400-3499/3476.Maximize Profit from Task Assignment/Solution.ts
solution/CONTEST_README.md
solution/DATABASE_README.md
solution/README.md
solution/README_EN.md

No.3476.Maximize Profit from Task Assignment

feat: add solutions to lc problem: No.3476

---

solution/0900-0999/0937.Reorder Data in Log Files/README.md
solution/0900-0999/0937.Reorder Data in Log Files/README_EN.md
solution/0900-0999/0937.Reorder Data in Log Files/Solution.cpp
solution/0900-0999/0937.Reorder Data in Log Files/Solution.go
solution/0900-0999/0937.Reorder Data in Log Files/Solution.java
solution/0900-0999/0937.Reorder Data in Log Files/Solution.py
solution/0900-0999/0937.Reorder Data in Log Files/Solution.rs
solution/0900-0999/0937.Reorder Data in Log Files/Solution.ts

No.0937.Reorder Data in Log Files

feat: add solutions to lc problem: No.0937

---

solution/0900-0999/0985.Sum of Even Numbers After Queries/README.md
solution/0900-0999/0985.Sum of Even Numbers After Queries/README_EN.md
solution/0900-0999/0985.Sum of Even Numbers After Queries/Solution.cs
solution/0900-0999/0985.Sum of Even Numbers After Queries/Solution.js
solution/0900-0999/0985.Sum of Even Numbers After Queries/Solution.rs
solution/0900-0999/0985.Sum of Even Numbers After Queries/Solution.ts

No.0985.Sum of Even Numbers After Queries

feat: add solutions to lc problem: No.0985

---

solution/1200-1299/1257.Smallest Common Region/README.md
solution/1200-1299/1257.Smallest Common Region/README_EN.md
solution/1200-1299/1257.Smallest Common Region/Solution.cpp
solution/1200-1299/1257.Smallest Common Region/Solution.go
solution/1200-1299/1257.Smallest Common Region/Solution.java
solution/1200-1299/1257.Smallest Common Region/Solution.py
solution/1200-1299/1257.Smallest Common Region/Solution.rs
solution/1200-1299/1257.Smallest Common Region/Solution.ts

No.1257.Smallest Common Region

feat: add solutions to lc problem: No.1257

---

solution/3400-3499/3478.Choose K Elements With Maximum Sum/README.md
solution/3400-3499/3478.Choose K Elements With Maximum Sum/README_EN.md
solution/3400-3499/3478.Choose K Elements With Maximum Sum/Solution.cpp
solution/3400-3499/3478.Choose K Elements With Maximum Sum/Solution.go
solution/3400-3499/3478.Choose K Elements With Maximum Sum/Solution.java
solution/3400-3499/3478.Choose K Elements With Maximum Sum/Solution.py
solution/3400-3499/3478.Choose K Elements With Maximum Sum/Solution.ts

No.3478.Choose K Elements With Maximum Sum

feat: add solutions to lc problem: No.3478

---

solution/3400-3499/3481.Apply Substitutions/README.md
solution/3400-3499/3481.Apply Substitutions/README_EN.md
solution/3400-3499/3481.Apply Substitutions/Solution.cpp
solution/3400-3499/3481.Apply Substitutions/Solution.go
solution/3400-3499/3481.Apply Substitutions/Solution.java
solution/3400-3499/3481.Apply Substitutions/Solution.py
solution/3400-3499/3481.Apply Substitutions/Solution.ts

feat: add solutions to lc problem: No.3481

---

solution/3400-3499/3482.Analyze Organization Hierarchy/README.md
solution/3400-3499/3482.Analyze Organization Hierarchy/README_EN.md
solution/3400-3499/3482.Analyze Organization Hierarchy/Solution.py
solution/3400-3499/3482.Analyze Organization Hierarchy/Solution.sql

No.3482.Analyze Organization Hierarchy

feat: add solutions to lc problem: No.3482

---

solution/3300-3399/3305.Count of Substrings Containing Every Vowel and K Consonants I/README.md
solution/3300-3399/3305.Count of Substrings Containing Every Vowel and K Consonants I/README_EN.md
solution/3300-3399/3305.Count of Substrings Containing Every Vowel and K Consonants I/Solution.py
solution/3300-3399/3305.Count of Substrings Containing Every Vowel and K Consonants I/Solution.rs
solution/3300-3399/3306.Count of Substrings Containing Every Vowel and K Consonants II/README.md
solution/3300-3399/3306.Count of Substrings Containing Every Vowel and K Consonants II/README_EN.md
solution/3300-3399/3306.Count of Substrings Containing Every Vowel and K Consonants II/Solution.rs

No.3305.Count of Substrings Containing Every Vowel and K Consonants I

feat: add solutions to lc problem: No.3305

---

solution/1900-1999/1959.Minimum Total Space Wasted With K Resizing Operations/README.md
solution/1900-1999/1959.Minimum Total Space Wasted With K Resizing Operations/README_EN.md
solution/1900-1999/1959.Minimum Total Space Wasted With K Resizing Operations/Solution.rs
solution/1900-1999/1959.Minimum Total Space Wasted With K Resizing Operations/Solution.ts

No.1959.Minimum Total Space Wasted With K Resizing Operations

feat: add solutions to lc problem: No.1959

---

solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/README.md
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/README_EN.md
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/Solution.cpp
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/Solution.go
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/Solution.java
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/Solution.py
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/Solution.rs
solution/2800-2899/2829.Determine the Minimum Sum of a k-avoiding Array/Solution.ts

No.2829.Determine the Minimum Sum of a k-avoiding Array

feat: add solutions to lc problem: No.2829

---

solution/0700-0799/0766.Toeplitz Matrix/README.md
solution/0700-0799/0766.Toeplitz Matrix/README_EN.md
solution/0700-0799/0766.Toeplitz Matrix/Solution.py
solution/0700-0799/0766.Toeplitz Matrix/Solution.rs
solution/0700-0799/0766.Toeplitz Matrix/Solution.ts

feat: add solutions to lc problem: No.0766

---

solution/1000-1099/1062.Longest Repeating Substring/README.md
solution/1000-1099/1062.Longest Repeating Substring/README_EN.md
solution/1000-1099/1062.Longest Repeating Substring/Solution.cpp
solution/1000-1099/1062.Longest Repeating Substring/Solution.go
solution/1000-1099/1062.Longest Repeating Substring/Solution.java
solution/1000-1099/1062.Longest Repeating Substring/Solution.py
solution/1000-1099/1062.Longest Repeating Substring/Solution.rs
solution/1000-1099/1062.Longest Repeating Substring/Solution.ts

No.1062.Longest Repeating Substring

feat: add solutions to lc problem: No.1062

---

solution/3100-3199/3110.Score of a String/README.md
solution/3100-3199/3110.Score of a String/README_EN.md
solution/3100-3199/3110.Score of a String/Solution.cs
solution/3100-3199/3110.Score of a String/Solution.php
solution/3100-3199/3110.Score of a String/Solution.rs

feat: add solutions to lc problem: No.3110

---

solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/README.md
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/README_EN.md
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.c
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.cpp
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.go
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.java
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.js
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.py
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.rs
solution/0100-0199/0109.Convert Sorted List to Binary Search Tree/Solution.ts

No.0109.Convert Sorted List to Binary Search Tree

feat: add solutions to lc problem: No.0109

---

solution/0500-0599/0532.K-diff Pairs in an Array/README.md
solution/0500-0599/0532.K-diff Pairs in an Array/README_EN.md
solution/0500-0599/0532.K-diff Pairs in an Array/Solution.cpp
solution/0500-0599/0532.K-diff Pairs in an Array/Solution.go
solution/0500-0599/0532.K-diff Pairs in an Array/Solution.java
solution/0500-0599/0532.K-diff Pairs in an Array/Solution.py
solution/0500-0599/0532.K-diff Pairs in an Array/Solution.rs
solution/0500-0599/0532.K-diff Pairs in an Array/Solution.ts

No.0532.K-diff Pairs in an Array

feat: add solutions to lc problem: No.0532

---

solution/2700-2799/2712.Minimum Cost to Make All Characters Equal/README.md
solution/2700-2799/2712.Minimum Cost to Make All Characters Equal/README_EN.md
solution/2700-2799/2712.Minimum Cost to Make All Characters Equal/Solution.rs
solution/2700-2799/2716.Minimize String Length/README.md
solution/2700-2799/2716.Minimize String Length/README_EN.md
solution/2700-2799/2716.Minimize String Length/Solution.cpp
solution/2700-2799/2716.Minimize String Length/Solution.cs

* No.2712.Minimum Cost to Make All Characters Equal
* No.2716.Minimize String Length

feat: add solutions to lc problems: No.2712,2716

---

solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/README.md
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/README_EN.md
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/Solution.cpp
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/Solution.go
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/Solution.java
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/Solution.py
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/Solution.rs
solution/2800-2899/2873.Maximum Value of an Ordered Triplet I/Solution.ts
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/README.md
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/README_EN.md
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/Solution.cpp
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/Solution.go
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/Solution.java
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/Solution.py
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/Solution.rs
solution/2800-2899/2874.Maximum Value of an Ordered Triplet II/Solution.ts

* No.2873.Maximum Value of an Ordered Triplet I
* No.2874.Maximum Value of an Ordered Triplet II

feat: add solutions to lc problems: No.2873,2874

---

solution/2200-2299/2206.Divide Array Into Equal Pairs/README.md
solution/2200-2299/2206.Divide Array Into Equal Pairs/README_EN.md
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.js
solution/2200-2299/2206.Divide Array Into Equal Pairs/Solution.ts

Almost the same solution, but 30-35% faster

feat: update solutions to lc problem: No.2206

---

solution/0200-0299/0235.Lowest Common Ancestor of a Binary Search Tree/README.md
solution/0200-0299/0235.Lowest Common Ancestor of a Binary Search Tree/README_EN.md
solution/0200-0299/0235.Lowest Common Ancestor of a Binary Search Tree/Solution.cs
solution/0200-0299/0235.Lowest Common Ancestor of a Binary Search Tree/Solution.go
solution/0200-0299/0235.Lowest Common Ancestor of a Binary Search Tree/Solution2.cs
solution/0200-0299/0235.Lowest Common Ancestor of a Binary Search Tree/Solution2.ts

No.0235.Lowest Common Ancestor of a Binary Search Tree

feat: add solutions to lc problem: No.0235

---

solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/README.md
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/README_EN.md
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/Solution.cpp
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/Solution.go
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/Solution.java
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/Solution.py
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/Solution.rs
solution/1400-1499/1442.Count Triplets That Can Form Two Arrays of Equal XOR/Solution.ts

No.1442.Count Triplets That Can Form Two Arrays of Equal XOR

feat: add solutions to lc problem: No.1442

---

solution/1400-1499/1441.Build an Array With Stack Operations/README.md
solution/1400-1499/1441.Build an Array With Stack Operations/README_EN.md
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.c
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.cpp
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.go
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.java
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.py
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.rs
solution/1400-1499/1441.Build an Array With Stack Operations/Solution.ts

No.1441.Build an Array With Stack Operations

feat: add solutions to lc problem: No.1441

---

solution/0300-0399/0346.Moving Average from Data Stream/README.md
solution/0300-0399/0346.Moving Average from Data Stream/README_EN.md
solution/0300-0399/0346.Moving Average from Data Stream/Solution.cpp
solution/0300-0399/0346.Moving Average from Data Stream/Solution.go
solution/0300-0399/0346.Moving Average from Data Stream/Solution.java
solution/0300-0399/0346.Moving Average from Data Stream/Solution.py
solution/0300-0399/0346.Moving Average from Data Stream/Solution.ts
solution/0300-0399/0346.Moving Average from Data Stream/Solution2.ts

No.0346.Moving Average from Data Stream

feat: add solutions to lc problem: No.0346

---

solution/0500-0599/0568.Maximum Vacation Days/README.md
solution/0500-0599/0568.Maximum Vacation Days/README_EN.md
solution/0500-0599/0568.Maximum Vacation Days/Solution.rs
solution/0500-0599/0568.Maximum Vacation Days/Solution.ts

feat: add solutions to lc problem: No.0568

---

solution/0600-0699/0676.Implement Magic Dictionary/README.md
solution/0600-0699/0676.Implement Magic Dictionary/README_EN.md
solution/0600-0699/0676.Implement Magic Dictionary/Solution.cs
solution/0600-0699/0676.Implement Magic Dictionary/Solution.rs
solution/0600-0699/0677.Map Sum Pairs/README.md
solution/0600-0699/0677.Map Sum Pairs/README_EN.md
solution/0600-0699/0677.Map Sum Pairs/Solution.js

No.0676.Implement Magic Dictionary

feat: add solutions to lc problem: No.0676

---

solution/2600-2699/2643.Row With Maximum Ones/README.md
solution/2600-2699/2643.Row With Maximum Ones/README_EN.md
solution/2600-2699/2643.Row With Maximum Ones/Solution.cpp
solution/2600-2699/2643.Row With Maximum Ones/Solution.cs
solution/2600-2699/2643.Row With Maximum Ones/Solution.go
solution/2600-2699/2643.Row With Maximum Ones/Solution.java
solution/2600-2699/2643.Row With Maximum Ones/Solution.py
solution/2600-2699/2643.Row With Maximum Ones/Solution.rs
solution/2600-2699/2643.Row With Maximum Ones/Solution.ts

feat: add solutions to lc problem: No.2643

---

solution/0200-0299/0252.Meeting Rooms/README.md
solution/0200-0299/0252.Meeting Rooms/README_EN.md
solution/0200-0299/0252.Meeting Rooms/Solution.cpp
solution/0200-0299/0252.Meeting Rooms/Solution.java
solution/0200-0299/0252.Meeting Rooms/Solution.rs
solution/0200-0299/0253.Meeting Rooms II/README.md
solution/0200-0299/0253.Meeting Rooms II/README_EN.md
solution/0200-0299/0253.Meeting Rooms II/Solution.go
solution/0200-0299/0253.Meeting Rooms II/Solution.java
solution/0200-0299/0253.Meeting Rooms II/Solution.rs
solution/0200-0299/0253.Meeting Rooms II/Solution.ts
solution/0200-0299/0253.Meeting Rooms II/Solution2.cpp
solution/0200-0299/0253.Meeting Rooms II/Solution2.go
solution/0200-0299/0253.Meeting Rooms II/Solution2.java
solution/0200-0299/0253.Meeting Rooms II/Solution2.py
solution/0200-0299/0253.Meeting Rooms II/Solution2.rs
solution/0200-0299/0253.Meeting Rooms II/Solution2.ts

* No.0252.Meeting Rooms
* No.0253.Meeting Rooms II

feat: add solutions to lc problems: No.0252,0253

---

solution/0300-0399/0325.Maximum Size Subarray Sum Equals k/README.md
solution/0300-0399/0325.Maximum Size Subarray Sum Equals k/README_EN.md
solution/0300-0399/0325.Maximum Size Subarray Sum Equals k/Solution.cs
solution/0300-0399/0325.Maximum Size Subarray Sum Equals k/Solution.js
solution/0300-0399/0325.Maximum Size Subarray Sum Equals k/Solution.rs

No.0325.Maximum Size Subarray Sum Equals k

feat: add solutions to lc problem: No.0325

---

solution/3400-3499/3493.Properties Graph/README.md
solution/3400-3499/3493.Properties Graph/README_EN.md
solution/3400-3499/3493.Properties Graph/Solution.cpp
solution/3400-3499/3493.Properties Graph/Solution.go
solution/3400-3499/3493.Properties Graph/Solution.java
solution/3400-3499/3493.Properties Graph/Solution.py
solution/3400-3499/3493.Properties Graph/Solution.ts

feat: add solutions to lc problem: No.3493

---

solution/0900-0999/0960.Delete Columns to Make Sorted III/README.md
solution/0900-0999/0960.Delete Columns to Make Sorted III/README_EN.md
solution/0900-0999/0960.Delete Columns to Make Sorted III/Solution.cpp
solution/0900-0999/0960.Delete Columns to Make Sorted III/Solution.go
solution/0900-0999/0960.Delete Columns to Make Sorted III/Solution.java
solution/0900-0999/0960.Delete Columns to Make Sorted III/Solution.py
solution/0900-0999/0960.Delete Columns to Make Sorted III/Solution.rs
solution/0900-0999/0960.Delete Columns to Make Sorted III/Solution.ts
solution/2600-2699/2600.K Items With the Maximum Sum/README.md
solution/2600-2699/2600.K Items With the Maximum Sum/README_EN.md

No.0960.Delete Columns to Make Sorted III

feat: add solutions to lc problem: No.0960

---

solution/2300-2399/2360.Longest Cycle in a Graph/README.md
solution/2300-2399/2360.Longest Cycle in a Graph/README_EN.md
solution/2300-2399/2360.Longest Cycle in a Graph/Solution.rs
solution/2300-2399/2360.Longest Cycle in a Graph/Solution.ts

No.2360.Longest Cycle in a Graph

feat: add solutions to lc problem: No.2360

---

solution/3300-3399/3394.Check if Grid can be Cut into Sections/README.md

Solution for the question 3394 using sweep line algorithm

leetcode 3394 solution with java c++ python and go languages

---

solution/3300-3399/3394.Check if Grid can be Cut into Sections/README.md
solution/3300-3399/3394.Check if Grid can be Cut into Sections/README_EN.md
solution/3300-3399/3394.Check if Grid can be Cut into Sections/Solution.cpp
solution/3300-3399/3394.Check if Grid can be Cut into Sections/Solution.go
solution/3300-3399/3394.Check if Grid can be Cut into Sections/Solution.java
solution/3300-3399/3394.Check if Grid can be Cut into Sections/Solution.py

No.3394.Check if Grid can be Cut into Sections

feat: add solutions to lc problem: No.3394

---

solution/2000-2099/2033.Minimum Operations to Make a Uni-Value Grid/README.md
solution/2000-2099/2033.Minimum Operations to Make a Uni-Value Grid/README_EN.md
solution/3400-3499/3497.Analyze Subscription Conversion/README.md
solution/3400-3499/3497.Analyze Subscription Conversion/README_EN.md
solution/3400-3499/3497.Analyze Subscription Conversion/Solution.py
solution/3400-3499/3497.Analyze Subscription Conversion/Solution.sql
solution/DATABASE_README.md
solution/DATABASE_README_EN.md
solution/README.md
solution/README_EN.md

No.3497.Analyze Subscription Conversion

feat: add solutions to lc problem: No.3497

---

solution/3400-3499/3499.Maximize Active Section with Trade I/README.md
solution/3400-3499/3499.Maximize Active Section with Trade I/README_EN.md
solution/3400-3499/3499.Maximize Active Section with Trade I/Solution.cpp
solution/3400-3499/3499.Maximize Active Section with Trade I/Solution.go
solution/3400-3499/3499.Maximize Active Section with Trade I/Solution.java
solution/3400-3499/3499.Maximize Active Section with Trade I/Solution.py
solution/3400-3499/3499.Maximize Active Section with Trade I/Solution.ts

No.3499.Maximize Active Section with Trade I

feat: add solutions to lc problem: No.3499

---

solution/3500-3599/3502.Minimum Cost to Reach Every Position/README.md
solution/3500-3599/3502.Minimum Cost to Reach Every Position/README_EN.md
solution/3500-3599/3502.Minimum Cost to Reach Every Position/Solution.cpp
solution/3500-3599/3502.Minimum Cost to Reach Every Position/Solution.go
solution/3500-3599/3502.Minimum Cost to Reach Every Position/Solution.java
solution/3500-3599/3502.Minimum Cost to Reach Every Position/Solution.py
solution/3500-3599/3502.Minimum Cost to Reach Every Position/Solution.ts

No.3502.Minimum Cost to Reach Every Position

feat: add solutions to lc problem: No.3502

---

solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/README.md
solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/README_EN.md
solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/Solution.cpp
solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/Solution.go
solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/Solution.java
solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/Solution.py
solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/Solution.ts
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/README.md
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/README_EN.md
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/Solution.cpp
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/Solution.go
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/Solution.java
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/Solution.py
solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/Solution.ts

* No.3503.Longest Palindrome After Substring Concatenation I
* No.3504.Longest Palindrome After Substring Concatenation II

feat: add solutions to lc problems: No.3503,3504

---

solution/1100-1199/1199.Minimum Time to Build Blocks/README.md
solution/1100-1199/1199.Minimum Time to Build Blocks/README_EN.md
solution/1100-1199/1199.Minimum Time to Build Blocks/Solution.ts
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/README.md
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/README_EN.md
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/Solution.cpp
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/Solution.go
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/Solution.java
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/Solution.py
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/Solution.rs
solution/3500-3599/3506.Find Time Required to Eliminate Bacterial Strains II/Solution.ts

No.3506.Find Time Required to Eliminate Bacterial Strains II

feat: add solutions to lc problem: No.3506

---

solution/2800-2899/2850.Minimum Moves to Spread Stones Over Grid/README.md
solution/2800-2899/2850.Minimum Moves to Spread Stones Over Grid/README_EN.md
solution/2800-2899/2850.Minimum Moves to Spread Stones Over Grid/Solution.cpp
solution/2800-2899/2850.Minimum Moves to Spread Stones Over Grid/Solution.go
solution/2800-2899/2850.Minimum Moves to Spread Stones Over Grid/Solution.ts

No.2850.Minimum Moves to Spread Stones Over Grid

feat: add solutions to lc problem: No.2850

---

solution/3200-3299/3272.Find the Count of Good Integers/README.md
solution/3200-3299/3272.Find the Count of Good Integers/README_EN.md
solution/3200-3299/3272.Find the Count of Good Integers/Solution.js
solution/3200-3299/3272.Find the Count of Good Integers/Solution.rs

No.3272.Find the Count of Good Integers

feat: add solutions to lc problem: No.3272

---

solution/1800-1899/1899.Merge Triplets to Form Target Triplet/README.md
solution/1800-1899/1899.Merge Triplets to Form Target Triplet/README_EN.md
solution/1800-1899/1899.Merge Triplets to Form Target Triplet/Solution.rs
solution/1800-1899/1899.Merge Triplets to Form Target Triplet/Solution.scala
solution/1900-1999/1918.Kth Smallest Subarray Sum/README.md
solution/1900-1999/1918.Kth Smallest Subarray Sum/README_EN.md
solution/1900-1999/1918.Kth Smallest Subarray Sum/Solution.rs
solution/1900-1999/1918.Kth Smallest Subarray Sum/Solution.scala
solution/1900-1999/1918.Kth Smallest Subarray Sum/Solution.ts

* No.1899.Merge Triplets to Form Target Triplet
* No.1918.Kth Smallest Subarray Sum

feat: add solutions to lc problems: No.1899,1918

---

solution/0400-0499/0437.Path Sum III/README.md
solution/0400-0499/0437.Path Sum III/README_EN.md
solution/0400-0499/0437.Path Sum III/Solution.cpp
solution/0400-0499/0437.Path Sum III/Solution.cs
solution/0400-0499/0437.Path Sum III/Solution.js
solution/0400-0499/0437.Path Sum III/Solution.rs

feat: add solutions to lc problems: No.0437

---

solution/0600-0699/0604.Design Compressed String Iterator/README.md
solution/0600-0699/0604.Design Compressed String Iterator/README_EN.md
solution/0600-0699/0604.Design Compressed String Iterator/Solution.ts

No.604.Design Compressed String Iterator

feat: add solutions to lc problem: No.0604

---

solution/1100-1199/1123.Lowest Common Ancestor of Deepest Leaves/README.md
solution/1100-1199/1123.Lowest Common Ancestor of Deepest Leaves/README_EN.md
solution/1100-1199/1123.Lowest Common Ancestor of Deepest Leaves/Solution.cpp
solution/1100-1199/1123.Lowest Common Ancestor of Deepest Leaves/Solution.cs

No.1123.Lowest Common Ancestor of Deepest Leaves

feat: add solutions to lc problem: No.1123

---

solution/0100-0199/0184.Department Highest Salary/README.md
solution/0100-0199/0184.Department Highest Salary/README_EN.md
solution/0100-0199/0184.Department Highest Salary/Solution.py
solution/0100-0199/0184.Department Highest Salary/solution.py

This PR adds a working Pandas solution for Leetcode Problem 184: Department Highest Salary.
- Implemented a Pandas-based solution using `merge`, `groupby().transform('max')`, and filtering.
- Ensures compatibility with Leetcode's pandas environment.
- Returns the department name, employee name, and highest salary per department.
Employee and Department tables as provided in the problem statement.
+------------+----------+--------+
| Department | Employee | Salary |
+------------+----------+--------+
| IT         | Jim      | 90000  |
| IT         | Max      | 90000  |
| Sales      | Henry    | 80000  |
+------------+----------+--------+
- The solution is optimized and tested.
- Follows Leetcode’s expected return format.
- Ready for review and merge.
---
Closes #184

Add Pandas solution for 184. Department Highest Salary

---

solution/0800-0899/0857.Minimum Cost to Hire K Workers/README.md
solution/0800-0899/0857.Minimum Cost to Hire K Workers/README_EN.md
solution/0800-0899/0857.Minimum Cost to Hire K Workers/Solution.cpp
solution/0800-0899/0857.Minimum Cost to Hire K Workers/Solution.go
solution/0800-0899/0857.Minimum Cost to Hire K Workers/Solution.java

previous it was giving wrong asnwer, I have tested and the new code works

fix: update solution to lc problem: No.0857

---

solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/README.md
solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/README_EN.md
solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/Solution3.cpp
solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/Solution3.go
solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/Solution3.java
solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/Solution3.py
solution/2600-2699/2657.Find the Prefix Common Array of Two Arrays/Solution3.ts

No.2657.Find the Prefix Common Array of Two Arrays

feat: add solutions to lc problem: No.2657

---

solution/3300-3399/3375.Minimum Operations to Make Array Values Equal to K/README.md
solution/3300-3399/3375.Minimum Operations to Make Array Values Equal to K/README_EN.md
solution/3300-3399/3375.Minimum Operations to Make Array Values Equal to K/Solution.rs

No.3375.Minimum Operations to Make Array Values Equal to K

feat: add solutions to lc problem: No.3375

---

solution/3400-3499/3485.Longest Common Prefix of K Strings After Removal/README.md
solution/3400-3499/3485.Longest Common Prefix of K Strings After Removal/README_EN.md
solution/3400-3499/3485.Longest Common Prefix of K Strings After Removal/Solution.cpp
solution/3400-3499/3485.Longest Common Prefix of K Strings After Removal/Solution.java

i have make changes in readme for ccp program for this solution

feat: add solution to lc problem: No.3485

---

solution/2500-2599/2537.Count the Number of Good Subarrays/README.md
solution/2500-2599/2537.Count the Number of Good Subarrays/README_EN.md
solution/2500-2599/2537.Count the Number of Good Subarrays/Solution.java
solution/2500-2599/2537.Count the Number of Good Subarrays/Solution.rs
solution/2500-2599/2537.Count the Number of Good Subarrays/Solution.ts

No.2537.Count the Number of Good Subarrays

feat: add solutions to lc problem: No.2537

---

solution/1900-1999/1943.Describe the Painting/README.md
solution/1900-1999/1943.Describe the Painting/README_EN.md
solution/1900-1999/1943.Describe the Painting/Solution.go

feat: add solutions to lc problem: No.1943 (#4354)

---

solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/README.md
solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/README_EN.md
solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/Solution.cpp
solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/Solution.go
solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/Solution.java
solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/Solution.py
solution/3500-3599/3512.Minimum Operations to Make Array Sum Divisible by K/Solution.ts

No.3512.Minimum Operations to Make Array Sum Divisible by K

feat: add solutions to lc problem: No.3512

---

solution/3500-3599/3523.Make Array Non-decreasing/README.md
solution/3500-3599/3523.Make Array Non-decreasing/README_EN.md
solution/3500-3599/3523.Make Array Non-decreasing/Solution.cpp
solution/3500-3599/3523.Make Array Non-decreasing/Solution.go
solution/3500-3599/3523.Make Array Non-decreasing/Solution.java
solution/3500-3599/3523.Make Array Non-decreasing/Solution.py
solution/3500-3599/3523.Make Array Non-decreasing/Solution.ts

No.3523.Make Array Non-decreasing

feat: add solutions to lc problem: No.3523

---

solution/3500-3599/3528.Unit Conversion I/README.md
solution/3500-3599/3528.Unit Conversion I/README_EN.md
solution/3500-3599/3528.Unit Conversion I/Solution.cpp
solution/3500-3599/3528.Unit Conversion I/Solution.go
solution/3500-3599/3528.Unit Conversion I/Solution.java
solution/3500-3599/3528.Unit Conversion I/Solution.py
solution/3500-3599/3528.Unit Conversion I/Solution.ts

feat: add solutions to lc problem: No.3528

---

solution/3500-3599/3527.Find the Most Common Response/README.md
solution/3500-3599/3527.Find the Most Common Response/README_EN.md
solution/3500-3599/3527.Find the Most Common Response/Solution.cpp
solution/3500-3599/3527.Find the Most Common Response/Solution.go
solution/3500-3599/3527.Find the Most Common Response/Solution.java
solution/3500-3599/3527.Find the Most Common Response/Solution.py
solution/3500-3599/3527.Find the Most Common Response/Solution.ts

No.3527.Find the Most Common Response

feat: add solutions to lc problem: No.3527

---

solution/2000-2099/2071.Maximum Number of Tasks You Can Assign/README.md
solution/2000-2099/2071.Maximum Number of Tasks You Can Assign/README_EN.md
solution/2000-2099/2071.Maximum Number of Tasks You Can Assign/Solution.ts

No.2071.Maximum Number of Tasks You Can Assign

feat: add solutions to lc problem: No.2071

---

solution/0800-0899/0838.Push Dominoes/README.md
solution/0800-0899/0838.Push Dominoes/README_EN.md
solution/0800-0899/0838.Push Dominoes/Solution.ts

feat: add solutions to lc problem: No.0838

---

solution/1100-1199/1128.Number of Equivalent Domino Pairs/README.md
solution/1100-1199/1128.Number of Equivalent Domino Pairs/README_EN.md
solution/1100-1199/1128.Number of Equivalent Domino Pairs/Solution.rs
solution/1100-1199/1128.Number of Equivalent Domino Pairs/Solution.ts

No.1128.Number of Equivalent Domino Pairs

feat: add solutions to lc problem: No.1128

---

solution/3500-3599/3531.Count Covered Buildings/README.md
solution/3500-3599/3531.Count Covered Buildings/README_EN.md
solution/3500-3599/3531.Count Covered Buildings/Solution.cpp
solution/3500-3599/3531.Count Covered Buildings/Solution.go
solution/3500-3599/3531.Count Covered Buildings/Solution.java
solution/3500-3599/3531.Count Covered Buildings/Solution.py
solution/3500-3599/3531.Count Covered Buildings/Solution.ts

No.3531.Count Covered Buildings

feat: add solutions to lc problem: No.3531

---

solution/3500-3599/3532.Path Existence Queries in a Graph I/README.md
solution/3500-3599/3532.Path Existence Queries in a Graph I/README_EN.md
solution/3500-3599/3532.Path Existence Queries in a Graph I/Solution.cpp
solution/3500-3599/3532.Path Existence Queries in a Graph I/Solution.go
solution/3500-3599/3532.Path Existence Queries in a Graph I/Solution.java
solution/3500-3599/3532.Path Existence Queries in a Graph I/Solution.py
solution/3500-3599/3532.Path Existence Queries in a Graph I/Solution.ts

No.3532.Path Existence Queries in a Graph I

feat: add solutions to lc problem: No.3532

---

solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/README.md
solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/README_EN.md
solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/Solution.cpp
solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/Solution.go
solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/Solution.java
solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/Solution.py
solution/3500-3599/3541.Find Most Frequent Vowel and Consonant/Solution.ts

No.3541.Find Most Frequent Vowel and Consonant

feat: add solutions to lc problem: No.3541

---

solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/README.md
solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/README_EN.md
solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/Solution.cpp
solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/Solution.go
solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/Solution.java
solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/Solution.py
solution/3500-3599/3545.Minimum Deletions for At Most K Distinct Characters/Solution.ts

No.3545.Minimum Deletions for At Most K Distinct Characters

feat: add solutions to lc problem: No.4545

---

solution/3300-3399/3337.Total Characters in String After Transformations II/README.md
solution/3300-3399/3337.Total Characters in String After Transformations II/README_EN.md
solution/3300-3399/3337.Total Characters in String After Transformations II/Solution.cpp
solution/3300-3399/3337.Total Characters in String After Transformations II/Solution.go
solution/3300-3399/3337.Total Characters in String After Transformations II/Solution.ts

No.3337.Total Characters in String After Transformations II

feat: add solutions to lc problem: No.3337

---

solution/1400-1499/1477.Find Two Non-overlapping Sub-arrays Each With Target Sum/README.md
solution/1400-1499/1477.Find Two Non-overlapping Sub-arrays Each With Target Sum/README_EN.md
solution/1400-1499/1477.Find Two Non-overlapping Sub-arrays Each With Target Sum/Solution.ts
solution/1400-1499/1487.Making File Names Unique/README_EN.md

No.1477.Find Two Non-overlapping Sub-arrays Each With Target Sum

feat: add solutions to lc problem: No.1477

---

solution/3500-3599/3552.Grid Teleportation Traversal/README.md
solution/3500-3599/3552.Grid Teleportation Traversal/README_EN.md
solution/3500-3599/3552.Grid Teleportation Traversal/Solution.cpp
solution/3500-3599/3552.Grid Teleportation Traversal/Solution.go
solution/3500-3599/3552.Grid Teleportation Traversal/Solution.java
solution/3500-3599/3552.Grid Teleportation Traversal/Solution.py
solution/3500-3599/3552.Grid Teleportation Traversal/Solution.ts

No.3552.Grid Teleportation Traversal

feat: add solutions to lc problem: No.3552

---

solution/3300-3399/3356.Zero Array Transformation II/README.md
solution/3300-3399/3356.Zero Array Transformation II/README_EN.md
solution/3300-3399/3356.Zero Array Transformation II/Solution.rs

No.3356.Zero Array Transformation II

feat: add solutions to lc problem: No.3356

---

solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/README.md
solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/README_EN.md
solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/Solution.cpp
solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/Solution.go
solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/Solution.java
solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/Solution.py
solution/3500-3599/3555.Smallest Subarray to Sort in Every Sliding Window/Solution.ts

No.3555.Smallest Subarray to Sort in Every Sliding Window

feat: add solutions to lc problem: No.3555

---

solution/3500-3599/3554.Find Category Recommendation Pairs/README.md
solution/3500-3599/3554.Find Category Recommendation Pairs/README_EN.md
solution/3500-3599/3554.Find Category Recommendation Pairs/Solution.py
solution/3500-3599/3554.Find Category Recommendation Pairs/Solution.sql

No.3554.Find Category Recommendation Pairs

feat: add solutions to lc problem: No.3554

---

solution/3300-3399/3362.Zero Array Transformation III/README.md
solution/3300-3399/3362.Zero Array Transformation III/README_EN.md
solution/3300-3399/3362.Zero Array Transformation III/Solution.cpp
solution/3300-3399/3362.Zero Array Transformation III/Solution.go
solution/3300-3399/3362.Zero Array Transformation III/Solution.java
solution/3300-3399/3362.Zero Array Transformation III/Solution.py
solution/3300-3399/3362.Zero Array Transformation III/Solution.ts

No.3362.Zero Array Transformation III

feat: add solutions to lc problem: No.3362

---

solution/3500-3599/3556.Sum of Largest Prime Substrings/README.md
solution/3500-3599/3556.Sum of Largest Prime Substrings/README_EN.md
solution/3500-3599/3556.Sum of Largest Prime Substrings/Solution.cpp
solution/3500-3599/3556.Sum of Largest Prime Substrings/Solution.go
solution/3500-3599/3556.Sum of Largest Prime Substrings/Solution.java
solution/3500-3599/3556.Sum of Largest Prime Substrings/Solution.py
solution/3500-3599/3556.Sum of Largest Prime Substrings/Solution.ts

No.3556.Sum of Largest Prime Substrings

feat: add solutions to lc problem: No.3556

---

solution/1800-1899/1857.Largest Color Value in a Directed Graph/README.md
solution/1800-1899/1857.Largest Color Value in a Directed Graph/README_EN.md
solution/1800-1899/1857.Largest Color Value in a Directed Graph/Solution.ts

No.1857.Largest Color Value in a Directed Graph

feat: add solutions to lc problem: No.1857

---

solution/0200-0299/0245.Shortest Word Distance III/README.md
solution/0200-0299/0245.Shortest Word Distance III/README_EN.md
solution/0200-0299/0245.Shortest Word Distance III/Solution.ts

No.0245.Shortest Word Distance III

feat: add solutions to lc problem: No.0245

---

solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/README.md
solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/README_EN.md
solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/Solution.cpp
solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/Solution.go
solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/Solution.java
solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/Solution.py
solution/3400-3499/3403.Find the Lexicographically Largest String From the Box I/Solution.ts

No.3403.Find the Lexicographically Largest String From the Box I

feat: add solutions to lc problem: No.3403

---

solution/0100-0199/0147.Insertion Sort List/README.md
solution/0100-0199/0147.Insertion Sort List/README_EN.md
solution/0100-0199/0147.Insertion Sort List/Solution.go

feat: add solutions to lc problem: No.0147

---

solution/0200-0299/0269.Alien Dictionary/README.md
solution/0200-0299/0269.Alien Dictionary/README_EN.md
solution/0200-0299/0269.Alien Dictionary/Solution.go

feat: add solutions to lc problem: No.0269

---

solution/3500-3599/3561.Resulting String After Adjacent Removals/README.md
solution/3500-3599/3561.Resulting String After Adjacent Removals/README_EN.md
solution/3500-3599/3561.Resulting String After Adjacent Removals/Solution.cpp
solution/3500-3599/3561.Resulting String After Adjacent Removals/Solution.go
solution/3500-3599/3561.Resulting String After Adjacent Removals/Solution.java
solution/3500-3599/3561.Resulting String After Adjacent Removals/Solution.py
solution/3500-3599/3561.Resulting String After Adjacent Removals/Solution.ts

No.3561.Resulting String After Adjacent Removals

feat: add solutions to lc problem: No.3561

---

solution/3500-3599/3568.Minimum Moves to Clean the Classroom/README.md
solution/3500-3599/3568.Minimum Moves to Clean the Classroom/README_EN.md
solution/3500-3599/3568.Minimum Moves to Clean the Classroom/Solution.cpp
solution/3500-3599/3568.Minimum Moves to Clean the Classroom/Solution.go
solution/3500-3599/3568.Minimum Moves to Clean the Classroom/Solution.java
solution/3500-3599/3568.Minimum Moves to Clean the Classroom/Solution.py

No.3568.Minimum Moves to Clean the Classroom

feat: add solutions to lc problem: No.3568

---

solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/README.md
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/README_EN.md
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/Solution.cpp
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/Solution.go
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/Solution.java
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/Solution.py
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/Solution.rs
solution/1200-1299/1298.Maximum Candies You Can Get from Boxes/Solution.ts

No.1298.Maximum Candies You Can Get from Boxes

feat: add solutions to lc problem: No.1298

---

solution/1000-1099/1061.Lexicographically Smallest Equivalent String/README.md
solution/1000-1099/1061.Lexicographically Smallest Equivalent String/README_EN.md
solution/1000-1099/1061.Lexicographically Smallest Equivalent String/Solution.cs
solution/1000-1099/1061.Lexicographically Smallest Equivalent String/Solution.rs

No.1061.Lexicographically Smallest Equivalent String

feat: add solutions to lc problem: No.1061

---

solution/3500-3599/3573.Best Time to Buy and Sell Stock V/README.md
solution/3500-3599/3573.Best Time to Buy and Sell Stock V/README_EN.md
solution/3500-3599/3573.Best Time to Buy and Sell Stock V/Solution.cpp
solution/3500-3599/3573.Best Time to Buy and Sell Stock V/Solution.go
solution/3500-3599/3573.Best Time to Buy and Sell Stock V/Solution.java
solution/3500-3599/3573.Best Time to Buy and Sell Stock V/Solution.py
solution/3500-3599/3573.Best Time to Buy and Sell Stock V/Solution.ts

No.3573.Best Time to Buy and Sell Stock V

feat: add solutions to lc problem: No.3573

---

solution/0400-0499/0440.K-th Smallest in Lexicographical Order/README.md
solution/0400-0499/0440.K-th Smallest in Lexicographical Order/README_EN.md
solution/0400-0499/0440.K-th Smallest in Lexicographical Order/Solution.rs
solution/0400-0499/0440.K-th Smallest in Lexicographical Order/Solution.ts

No.0440.K-th Smallest in Lexicographical Order

feat: add solutions to lc problem: No.0440

---

solution/3400-3499/3423.Maximum Difference Between Adjacent Elements in a Circular Array/README.md
solution/3400-3499/3423.Maximum Difference Between Adjacent Elements in a Circular Array/README_EN.md
solution/3400-3499/3423.Maximum Difference Between Adjacent Elements in a Circular Array/Solution.cs
solution/3400-3499/3423.Maximum Difference Between Adjacent Elements in a Circular Array/Solution.py
solution/3400-3499/3423.Maximum Difference Between Adjacent Elements in a Circular Array/Solution.rs

No.3423.Maximum Difference Between Adjacent Elements in a Circular Array

feat: add solutions to lc problem: No.3423

---

solution/3500-3599/3581.Count Odd Letters from Number/README.md
solution/3500-3599/3581.Count Odd Letters from Number/README_EN.md
solution/3500-3599/3581.Count Odd Letters from Number/Solution.cpp
solution/3500-3599/3581.Count Odd Letters from Number/Solution.go
solution/3500-3599/3581.Count Odd Letters from Number/Solution.java
solution/3500-3599/3581.Count Odd Letters from Number/Solution.py
solution/3500-3599/3581.Count Odd Letters from Number/Solution.ts

No.3581.Count Odd Letters from Number

feat: add solutions to lc problem: No.3581

---

solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/README.md
solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/README_EN.md
solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/Solution.rs

No.3405.Count the Number of Arrays with K Matching Adjacent Elements

feat: add solutions to lc problem: No.3405

---

solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/README.md
solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/README_EN.md
solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/Solution.cpp
solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/Solution.go
solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/Solution.java
solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/Solution.py
solution/3500-3599/3587.Minimum Adjacent Swaps to Alternate Parity/Solution.ts

No.3587.Minimum Adjacent Swaps to Alternate Parity

feat: add solutions to lc problem: No.3587

---

solution/2000-2099/2081.Sum of k-Mirror Numbers/README.md
solution/2000-2099/2081.Sum of k-Mirror Numbers/README_EN.md
solution/2000-2099/2081.Sum of k-Mirror Numbers/Solution.cpp
solution/2000-2099/2081.Sum of k-Mirror Numbers/Solution.go
solution/2000-2099/2081.Sum of k-Mirror Numbers/Solution.py
solution/2000-2099/2081.Sum of k-Mirror Numbers/Solution.ts

No.2081.Sum of k-Mirror Numbers

feat: add solutions to lc problem: No.2081

---

solution/3500-3599/3590.Kth Smallest Path XOR Sum/README.md
solution/3500-3599/3590.Kth Smallest Path XOR Sum/README_EN.md
solution/3500-3599/3590.Kth Smallest Path XOR Sum/Solution.py

Provided a python3 solution for problem 3590. Kth Smallest Path XOR Sum. With Time: O(n log A) where A is the max value of path XOR (since we store numbers in tries, bit by bit).
Space: O(n log A) for all tries, possibly merged.

feat: add python solution to lc problem: No.3590

---

solution/3300-3399/3330.Find the Original Typed String I/README.md
solution/3300-3399/3330.Find the Original Typed String I/README_EN.md
solution/3300-3399/3330.Find the Original Typed String I/Solution.rs

No.3330.Find the Original Typed String I

feat: add rust solution to lc problem: No.3330

---

solution/2000-2099/2014.Longest Subsequence Repeated k Times/README.md
solution/2000-2099/2014.Longest Subsequence Repeated k Times/README_EN.md
solution/2000-2099/2014.Longest Subsequence Repeated k Times/Solution.cpp
solution/2000-2099/2014.Longest Subsequence Repeated k Times/Solution.go
solution/2000-2099/2014.Longest Subsequence Repeated k Times/Solution.java
solution/2000-2099/2014.Longest Subsequence Repeated k Times/Solution.py
solution/2000-2099/2014.Longest Subsequence Repeated k Times/Solution.ts

No.2014.Longest Subsequence Repeated k Times

feat: add solutions to lc problem: No.2014

---

solution/2000-2099/2099.Find Subsequence of Length K With the Largest Sum/README.md
solution/2000-2099/2099.Find Subsequence of Length K With the Largest Sum/README_EN.md
solution/2000-2099/2099.Find Subsequence of Length K With the Largest Sum/Solution.cpp
solution/2000-2099/2099.Find Subsequence of Length K With the Largest Sum/Solution.go
solution/2000-2099/2099.Find Subsequence of Length K With the Largest Sum/Solution.java
solution/2000-2099/2099.Find Subsequence of Length K With the Largest Sum/Solution.rs

No.2099.Find Subsequence of Length K With the Largest Sum

feat: add solutions to lc problem: No.2099

---

solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/README.md
solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/README_EN.md
solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/Solution.cpp
solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/Solution.go
solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/Solution.java
solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/Solution.py
solution/3500-3599/3596.Minimum Cost Path with Alternating Directions I/Solution.ts
solution/README.md
solution/README_EN.md

No.3596.Minimum Cost Path with Alternating Directions I

feat: add solutions to lc problem: No.3696

---

solution/3500-3599/3597.Partition String/README.md
solution/3500-3599/3597.Partition String/README_EN.md
solution/3500-3599/3597.Partition String/Solution.cpp
solution/3500-3599/3597.Partition String/Solution.go
solution/3500-3599/3597.Partition String/Solution.java
solution/3500-3599/3597.Partition String/Solution.py
solution/3500-3599/3597.Partition String/Solution.ts
solution/3500-3599/3597.Partition String/Solution2.cpp
solution/3500-3599/3597.Partition String/Solution2.go
solution/3500-3599/3597.Partition String/Solution2.java
solution/3500-3599/3597.Partition String/Solution2.py
solution/3500-3599/3597.Partition String/Solution2.ts

feat: add solutions to lc problem: No.3597

---

solution/3600-3699/3601.Find Drivers with Improved Fuel Efficiency/README.md
solution/3600-3699/3601.Find Drivers with Improved Fuel Efficiency/README_EN.md
solution/3600-3699/3601.Find Drivers with Improved Fuel Efficiency/Solution.py
solution/3600-3699/3601.Find Drivers with Improved Fuel Efficiency/Solution.sql

No.3601.Find Drivers with Improved Fuel Efficiency

feat: add solutions to lc problem: No.3601

---

solution/3300-3399/3307.Find the K-th Character in String Game II/README.md
solution/3300-3399/3307.Find the K-th Character in String Game II/README_EN.md
solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.cs
solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.php
solution/3600-3699/3601.Find Drivers with Improved Fuel Efficiency/README.md
solution/DATABASE_README.md
solution/README.md

No.3307.Find the K-th Character in String Game II

feat: add solutions to lc problem: No.3307

---

solution/1800-1899/1865.Finding Pairs With a Certain Sum/README.md
solution/1800-1899/1865.Finding Pairs With a Certain Sum/README_EN.md
solution/1800-1899/1865.Finding Pairs With a Certain Sum/Solution.rs

No.1865.Finding Pairs With a Certain Sum

feat: add rust solution to lc problem: No.1865

---

solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/README.md
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/README_EN.md
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/Solution.cpp
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/Solution.go
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/Solution.java
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/Solution.py
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/Solution.rs
solution/1300-1399/1353.Maximum Number of Events That Can Be Attended/Solution.ts

No.1353.Maximum Number of Events That Can Be Attended

feat: add solutions to lc problem: No.1353

---

solution/3600-3699/3606.Coupon Code Validator/README.md
solution/3600-3699/3606.Coupon Code Validator/README_EN.md
solution/3600-3699/3606.Coupon Code Validator/Solution.cpp
solution/3600-3699/3606.Coupon Code Validator/Solution.go
solution/3600-3699/3606.Coupon Code Validator/Solution.java
solution/3600-3699/3606.Coupon Code Validator/Solution.py
solution/3600-3699/3606.Coupon Code Validator/Solution.ts

feat: add solutions to lc problem: No.3606

---

solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/README.md
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/README_EN.md
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/Solution.cpp
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/Solution.go
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/Solution.java
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/Solution.py
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/Solution.rs
solution/3400-3499/3440.Reschedule Meetings for Maximum Free Time II/Solution.ts

No.3440.Reschedule Meetings for Maximum Free Time II

feat: add solutions to lc problem: No.3440

---

solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/README.md
solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/README_EN.md
solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/Solution.cpp
solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/Solution.go
solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/Solution.java
solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/Solution.py
solution/1900-1999/1900.The Earliest and Latest Rounds Where Players Compete/Solution.ts

No.1900.The Earliest and Latest Rounds Where Players Compete

feat: add solutions to lc problem: No.1900

---

solution/3600-3699/3612.Process String with Special Operations I/README.md
solution/3600-3699/3612.Process String with Special Operations I/README_EN.md
solution/3600-3699/3612.Process String with Special Operations I/Solution.cpp
solution/3600-3699/3612.Process String with Special Operations I/Solution.go
solution/3600-3699/3612.Process String with Special Operations I/Solution.java
solution/3600-3699/3612.Process String with Special Operations I/Solution.py
solution/3600-3699/3612.Process String with Special Operations I/Solution.ts
solution/3600-3699/3613.Minimize Maximum Component Cost/README.md
solution/3600-3699/3613.Minimize Maximum Component Cost/README_EN.md
solution/3600-3699/3613.Minimize Maximum Component Cost/Solution.cpp
solution/3600-3699/3613.Minimize Maximum Component Cost/Solution.go
solution/3600-3699/3613.Minimize Maximum Component Cost/Solution.java
solution/3600-3699/3613.Minimize Maximum Component Cost/Solution.py
solution/3600-3699/3613.Minimize Maximum Component Cost/Solution.ts

* No.3612.Process String with Special Operations I
* No.3613.Minimize Maximum Component Cost

feat: add solutions to lc problems: No.3612,3613 

---

solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/README.md
solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/README_EN.md
solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/Solution.cs
solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/Solution.php
solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/Solution.rs

No.1290.Convert Binary Number in a Linked List to Integer

feat: add solutions to lc problem: No.1290

---

solution/3100-3199/3136.Valid Word/README.md
solution/3100-3199/3136.Valid Word/README_EN.md
solution/3100-3199/3136.Valid Word/Solution.cs
solution/3100-3199/3136.Valid Word/Solution.rs

feat: add solutions to lc problem: No.3136

---

solution/3200-3299/3203.Find Minimum Diameter After Merging Two Trees/README.md
solution/3200-3299/3203.Find Minimum Diameter After Merging Two Trees/README_EN.md
solution/3200-3299/3203.Find Minimum Diameter After Merging Two Trees/Solution.cs
solution/3200-3299/3203.Find Minimum Diameter After Merging Two Trees/Solution.go
solution/3200-3299/3203.Find Minimum Diameter After Merging Two Trees/Solution.rs

No.3203.Find Minimum Diameter After Merging Two Trees

feat: add solutions to lc problem: No.3203

---

solution/1900-1999/1957.Delete Characters to Make Fancy String/README.md
solution/1900-1999/1957.Delete Characters to Make Fancy String/README_EN.md
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.cpp
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.go
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.java
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.js
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.php
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.py
solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.ts

No.1957.Delete Characters to Make Fancy String

feat: update solutions to lc problem: No.1957

---

solution/1600-1699/1695.Maximum Erasure Value/README.md
solution/1600-1699/1695.Maximum Erasure Value/README_EN.md
solution/1600-1699/1695.Maximum Erasure Value/Solution.py
solution/1600-1699/1695.Maximum Erasure Value/Solution.rs
solution/1600-1699/1695.Maximum Erasure Value/Solution2.rs

feat: add rust solutions to lc problem: No.1695

---

solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/README.md
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/README_EN.md
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/Solution.cpp
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/Solution.go
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/Solution.java
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/Solution.py
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/Solution.rs
solution/3400-3499/3480.Maximize Subarrays After Removing One Conflicting Pair/Solution.ts

No.3480.Maximize Subarrays After Removing One Conflicting Pair

feat: add solutions to lc problem: No.3480

---

solution/0100-0199/0118.Pascal's Triangle/README.md
solution/0100-0199/0118.Pascal's Triangle/README_EN.md
solution/0100-0199/0118.Pascal's Triangle/Solution.cpp
solution/0100-0199/0118.Pascal's Triangle/Solution.cs
solution/0100-0199/0118.Pascal's Triangle/Solution.go
solution/0100-0199/0118.Pascal's Triangle/Solution.java
solution/0100-0199/0118.Pascal's Triangle/Solution.js
solution/0100-0199/0118.Pascal's Triangle/Solution.rs
solution/0100-0199/0118.Pascal's Triangle/Solution.ts

feat: add solutions to lc problem: No.0118

---

solution/3600-3699/3631.Sort Threats by Severity and Exploitability/README.md
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/README_EN.md
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/Solution.cpp
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/Solution.go
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/Solution.java
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/Solution.py
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/Solution.rs
solution/3600-3699/3631.Sort Threats by Severity and Exploitability/Solution.ts

No.3631.Sort Threats by Severity and Exploitability

feat: add solutions to lc problem: No.3631

---

solution/3600-3699/3634.Minimum Removals to Balance Array/README.md
solution/3600-3699/3634.Minimum Removals to Balance Array/README_EN.md
solution/3600-3699/3634.Minimum Removals to Balance Array/Solution.cpp
solution/3600-3699/3634.Minimum Removals to Balance Array/Solution.go
solution/3600-3699/3634.Minimum Removals to Balance Array/Solution.java
solution/3600-3699/3634.Minimum Removals to Balance Array/Solution.py
solution/3600-3699/3634.Minimum Removals to Balance Array/Solution.ts

No.3634.Minimum Removals to Balance Array

feat: add solutions to lc problem: No.3634

---

solution/3600-3699/3637.Trionic Array I/README.md
solution/3600-3699/3637.Trionic Array I/README_EN.md
solution/3600-3699/3637.Trionic Array I/Solution.cpp
solution/3600-3699/3637.Trionic Array I/Solution.go
solution/3600-3699/3637.Trionic Array I/Solution.java
solution/3600-3699/3637.Trionic Array I/Solution.py
solution/3600-3699/3637.Trionic Array I/Solution.ts

feat: add solutions to lc problem: No.3637

---

solution/3600-3699/3638.Maximum Balanced Shipments/README.md
solution/3600-3699/3638.Maximum Balanced Shipments/README_EN.md
solution/3600-3699/3638.Maximum Balanced Shipments/Solution.cpp
solution/3600-3699/3638.Maximum Balanced Shipments/Solution.go
solution/3600-3699/3638.Maximum Balanced Shipments/Solution.java
solution/3600-3699/3638.Maximum Balanced Shipments/Solution.py
solution/3600-3699/3638.Maximum Balanced Shipments/Solution.ts

No.3638.Maximum Balanced Shipments

feat: add solutions to lc problem: No.3638

---

solution/0900-0999/0904.Fruit Into Baskets/README.md
solution/0900-0999/0904.Fruit Into Baskets/README_EN.md
solution/0900-0999/0904.Fruit Into Baskets/Solution.cs
solution/0900-0999/0904.Fruit Into Baskets/Solution2.cs

feat: add solutions to lc problem: No.0904

---

solution/0200-0299/0231.Power of Two/README.md
solution/0200-0299/0231.Power of Two/README_EN.md
solution/0200-0299/0231.Power of Two/Solution.rs
solution/0200-0299/0231.Power of Two/Solution2.js
solution/0200-0299/0231.Power of Two/Solution2.rs
solution/0200-0299/0231.Power of Two/Solution2.ts

feat: add solutions to lc problem: No.0231

---

solution/0800-0899/0869.Reordered Power of 2/README.md
solution/0800-0899/0869.Reordered Power of 2/README_EN.md
solution/0800-0899/0869.Reordered Power of 2/Solution.cpp
solution/0800-0899/0869.Reordered Power of 2/Solution.go
solution/0800-0899/0869.Reordered Power of 2/Solution.java
solution/0800-0899/0869.Reordered Power of 2/Solution.py
solution/0800-0899/0869.Reordered Power of 2/Solution.rs
solution/0800-0899/0869.Reordered Power of 2/Solution.ts

feat: add solutions to lc problem: No.0869

---

solution/0300-0399/0326.Power of Three/README.md
solution/0300-0399/0326.Power of Three/README_EN.md
solution/0300-0399/0326.Power of Three/Solution.js
solution/0300-0399/0326.Power of Three/Solution.rs
solution/0300-0399/0326.Power of Three/Solution.ts
solution/0300-0399/0326.Power of Three/Solution2.js
solution/0300-0399/0326.Power of Three/Solution2.rs
solution/0300-0399/0326.Power of Three/Solution2.ts

feat: add solutions to lc problem: No.0326

---

solution/1300-1399/1323.Maximum 69 Number/README.md
solution/1300-1399/1323.Maximum 69 Number/README_EN.md
solution/1300-1399/1323.Maximum 69 Number/Solution.c
solution/1300-1399/1323.Maximum 69 Number/Solution.go

feat: add solutions to lc problem: No.1323

---

solution/2300-2399/2348.Number of Zero-Filled Subarrays/README.md
solution/2300-2399/2348.Number of Zero-Filled Subarrays/README_EN.md
solution/2300-2399/2348.Number of Zero-Filled Subarrays/Solution.cpp
solution/2300-2399/2348.Number of Zero-Filled Subarrays/Solution.go
solution/2300-2399/2348.Number of Zero-Filled Subarrays/Solution.java
solution/2300-2399/2348.Number of Zero-Filled Subarrays/Solution.py
solution/2300-2399/2348.Number of Zero-Filled Subarrays/Solution.rs
solution/2300-2399/2348.Number of Zero-Filled Subarrays/Solution.ts

No.2348.2348.Number of Zero-Filled Subarrays

feat: add solutions to lc problem: No.2348

---

solution/1700-1799/1733.Minimum Number of People to Teach/README.md
solution/1700-1799/1733.Minimum Number of People to Teach/README_EN.md
solution/1700-1799/1733.Minimum Number of People to Teach/Solution.cpp
solution/1700-1799/1733.Minimum Number of People to Teach/Solution.py
solution/1700-1799/1733.Minimum Number of People to Teach/Solution.rs
solution/1700-1799/1733.Minimum Number of People to Teach/Solution.ts
solution/2700-2799/2785.Sort Vowels in a String/README.md
solution/2700-2799/2785.Sort Vowels in a String/README_EN.md
solution/2700-2799/2785.Sort Vowels in a String/Solution.cpp

No.1733.Minimum Number of People to Teach

feat: add solutions to lc problem: No.1733

---

solution/3500-3599/3588.Find Maximum Area of a Triangle/README.md
solution/3500-3599/3588.Find Maximum Area of a Triangle/README_EN.md
solution/3500-3599/3588.Find Maximum Area of a Triangle/Solution.cpp
solution/3500-3599/3588.Find Maximum Area of a Triangle/Solution.go
solution/3500-3599/3588.Find Maximum Area of a Triangle/Solution.java
solution/3500-3599/3588.Find Maximum Area of a Triangle/Solution.py
solution/3500-3599/3588.Find Maximum Area of a Triangle/Solution.ts

No.3588.Find Maximum Area of a Triangle

feat: add solutions to lc problem: No.3588

---

solution/1900-1999/1912.Design Movie Rental System/README.md
solution/1900-1999/1912.Design Movie Rental System/README_EN.md
solution/1900-1999/1912.Design Movie Rental System/Solution.cpp
solution/1900-1999/1912.Design Movie Rental System/Solution.go
solution/1900-1999/1912.Design Movie Rental System/Solution.java
solution/1900-1999/1912.Design Movie Rental System/Solution.py

No.1912.Design Movie Rental System

feat: add solutions to lc problem: No.1912
