solution/021.Merge Two Sorted Lists/Solution.py
=> Update solution 021 [Python3]

solution/019.Remove Nth Node From End of List/Solution.py
=> Update Solution 019 [Python3]

solution/007.Reverse Integer/Solution.py
=> Update solution 007 [Python3]

solution/046.Permutations/Solution.cpp
=> Permutations CPP

solution/047.Permutations II/Solution.cpp
=> Add C++ solution to 047

solution/001.Two Sum/Solution2.py
=> Solution2.py

solution/007.Reverse Integer/Solution2.py, solution/009.Palindrome Number/Solution.py
=> add two solutions with python

solution/198.House Robber/Solution.cpp
198.House Robber cpp version (0ms)
=> 198.House Robber cpp version (0ms)

solution/167.Two Sum II - Input array is sorted/Solution.cpp, solution/438.Find All Anagrams in a String/Solution.cpp, solution/443.String Compression/Solution.cpp, solution/605.Can Place Flowers/Solution.cpp, solution/836.Rectangle Overlap/Solution.cpp, solution/874.Walking Robot Simulation/Solution.cpp
=> add 438 folder & cpp version(24ms)

solution/004.Median of Two Sorted Arrays/Solution.cpp
=> Add solution 004[CPP]

solution/387.First Unique Character in a String/Solution.cpp
=> add 387 folder & cpp

solution/007.Reverse Integer/Solution2.py, solution/009.Palindrome Number/Solution.py
=> Revert "add two solutions with python"

solution/142.Linked List Cycle II/README.md, solution/142.Linked List Cycle II/Solution.cpp
=> Add solution 142[CPP]

solution/002.Add Two Numbers/Solution.js
=> Standard Code Solution 002 Solution.js [JavaScript]

solution/029.Divide Two Integers/README.md, solution/029.Divide Two Integers/Solution.java
Not the best Solution using Java,just  47ms.
=> Add Solution 029[Java]

solution/268.Missing Number/Solution.js, solution/326.Power of Three/Solution.js, solution/412.Fizz Buzz/Solution.js
=> add javascript solutions

solution/028.Implement strStr()/Solution.cpp
=> add 028 cpp version(4ms)

.github/CONTRIBUTING.md, solution/024.Swap Nodes in Pairs/Solution.cpp
=> Update solution 024 in cpp version with recursion

solution/027.Remove Element/README.md, solution/027.Remove Element/Solution.cpp
=> Add Solution 027[CPP]

solution/006.ZigZag Conversion/Solution.java
=> 6. ZigZag Conversion (java)

solution/013.Roman to Integer/Solution.js, solution/118.Pascal's Triangle/Solution.js, solution/155.Min Stack/README.md, solution/155.Min Stack/Solution.js, solution/384.Shuffle an Array/Solution.js, solution/929.Unique Email Addresses/Solution.js, solution/930.Binary Subarrays With Sum/Solution.js
=> add solutions in javascript

Solution2.py, solution/001.Two Sum/Solution2.py, solution/007.Reverse Integer/Solution2.py, solution/013.Roman to Integer/Solution2.py
=> Update solution 014 [Python2]-20ms

solution/008. String to Integer (atoi)/Solution.java
=> 008. String to Integer (atoi) (java)

solution/054.Spiral Matrix/Solution.cpp
=> Update solution 054 with cpp version

solution/020.Valid Parentheses/Solution2.py
=> Update Solution 020 [python2] - 24ms

solution/053.Maximum Subarray/Solution.js, solution/070.Climbing Stairs/Solution.js, solution/121.Best Time to Buy and Sell Stock/Solution.js, solution/122.Best Time to Buy and Sell Stock II/Solution.js
=> add js solutions

solution/021.Merge Two Sorted Lists/Solution.cpp, solution/070.Climbing Stairs/Solution.cpp
=> Update solution 070 and 021 with cpp version

solution/014.Longest Common Prefix/Solution.cpp, solution/062.Unique Paths/Solution.cpp
=> Update Solution 014  and 062 with cpp version

solution/075.Sort Colors/Solution2.py
=> 075 Sort colors - Python (Solution2)

solution/032.Longest Valid Parentheses/Solution.py
=> 032 Longest Valid Parentheses - Python

solution/022. Generate Parentheses/Solution.java
=> 022. Generate Parentheses (java)

solution/021.Merge Two Sorted Lists/Solution2.py, solution/026.Remove Duplicates from Sorted Array/Solution.py
=>  Update Solution to 026[python2] - 48ms

solution/0027.Remove Element/Solution.py
=> Create Solution with python2 to 0027-20ms

solution/0038.Count and Say/Solution.py
=> Create Solution.py to 0038 with python2 -24ms

solution/0028.Implement strStr()/Solution.py
=> 0028 Implement strStr() - Python

solution/0150.Evaluate Reverse Polish Notation/Solution.py
=> 0150 Evaluate Reverse Polish Notation - Python

solution/0054.Spiral Matrix/Solution.py
=> 0054 Spiral Matrix - Python

solution/0035.Search Insert Position/Solution.py
=> 0035 Search Insert Position - Python

solution/0789.Escape The Ghosts/Solution.py
=> add the solution 0789

solution/0041.First Missing Positive/Solution.py
Can i add __C__ code for this question? _(there are no C codes for any solution so i thought of asking before including it in the PR)_
=> 0041 First Missing Positive - Python

solution/0889.Construct Binary Tree from Preorder and Postorder Traversal/README.md, solution/0889.Construct Binary Tree from Preorder and Postorder Traversal/Solution.py
=> add the solution of 0889.

solution/0041.First Missing Positive/Solution.c, solution/0066.Plus One/Solution.py, solution/0066.Plus One/Solution2.py
=> 0066 Plus One - Python / 0041 First Missing Positive - C

solution/0412.Fizz Buzz/Solution.cpp, solution/0412.Fizz Buzz/Solution.py
=> 0412 Fizz Buzz

solution/0938.Range Sum of BST/README.md, solution/0938.Range Sum of BST/Solution.py
=> add the solution of problem 0938-python

solution/0701.Insert into a Binary Search Tree/README.md, solution/0701.Insert into a Binary Search Tree/Solution.py
=> add the solution of problem 0701-python.

solution/0190.Reverse Bits/Solution.py
=> 0190 Reverse Bits - Python

solution/0011.Container With Most Water/Solution.cpp
=> 0011 Container With Most Water - Cpp

solution/0929.Unique Email Addresses/Solution.py
=> 0929 Unique Email Addresses - Python

solution/0657.Robot Return to Origin/Solution.py, solution/0804.Unique Morse Code Words/Solution.py
0804 Unique Morse Code Words
0657 Robot Return to Origin
=> 0804 & 0657 - Python

solution/0953.Verifying an Alien Dictionary/Solution.cpp
=> add 0953 folder & cpp(4ms) version

solution/0147.Insertion Sort List/README.md, solution/0147.Insertion Sort List/Solution.java
我删了旧的仓库，重新fork并提交，修改了if else 和 while 的格式
=> Add 147 Solution.java and README.md

solution/1024.Video Stitching/Solution.cpp, solution/1025.Divisor Game/Solution.cpp, solution/1026.Maximum Difference Between Node and Ancestor/Solution.cpp, solution/1027.Longest Arithmetic Sequence/Solution.cpp, solution/1028.Recover a Tree From Preorder Traversal/Solution.cpp
Add cpp solution for problem 1024 Video Stitching.
Add cpp solution for problem 1025 Divisor Game.
Add cpp solution for problem 1026 Maximum Difference Between Node and Ancestor.
Add cpp solution for problem 1027 Longest Arithmetic Sequence.
Add cpp solution for problem 1028 Recover a Tree From Preorder Traversal.
=> Add cpp solution for problem 1024-1028

solution/0027.Remove Element/Solution.js, solution/0058.Length of Last Word/Solution.js, solution/0234.Palindrome Linked List/Solution.js
=> add JS solution for 0027,0058,0234

solution/1114.Print in Order/README.md, solution/1114.Print in Order/solution.cpp, solution/1115.Print FooBar Alternately/README.md, solution/1115.Print FooBar Alternately/Solution.cpp, solution/1116.Print Zero Even Odd/README.md, solution/1116.Print Zero Even Odd/Solution.cpp, solution/1117.Building H2O/README.md, solution/1117.Building H2O/Solution.cpp
Update to the new topic: Concurrency
=> New theme:Concurrency. update

solution/0760.Find Anagram Mappings/Solution.java, solution/0771.Jewels and Stones/Solution.java
update  based on requested changes
=> Jewels and stones

solution/1171.Remove Zero Sum Consecutive Nodes from Linked List/README_EN.md, solution/1171.Remove Zero Sum Consecutive Nodes from Linked List/Solution.java
=> Add Solution.java for 1171.Remove Zero Sum Consecutive Nodes from Linked List

solution/1275.Find Winner on a Tic Tac Toe Game/Solution.cpp, solution/1276.Number of Burgers with No Waste of Ingredients/Solution.cpp, solution/1277.Count Squre Submatrices with All Ones/Solution.cpp, solution/1278.Palindrome Partitioning III/Solution.cpp
added cpp solutions for these problems:
- 1275 Find Winner on a Tic Tac Toe Game
- 1276 Number of Burgers with No Waste of Ingredients
- 1277 Count Square Submatrices with All Ones
- 1278 Palindrome Partitioning III
=> add cpp solutions for weekly contest 165 problems (1275-1278)

solution/0342.Power of Four/README.md, solution/0342.Power of Four/Solution.js, solution/README.md
=> Power of four

solution/0500-0599/0502.IPO/Solution.java, solution/1100-1199/1117.Building H2O/Solution.java, solution/1100-1199/1195.Fizz Buzz Multithreaded/Solution.java
add solution for '0502','1117','1195'
=> feat:add solution for '0502','1117','1195'

solution/0500-0599/0515.Find Largest Value in Each Tree Row/Solution.java
=> add 515 solution for java

lcof/面试题03. 数组中重复的数字/README.md, lcof/面试题03. 数组中重复的数字/Solution.go, lcof/面试题04. 二维数组中的查找/README.md, lcof/面试题04. 二维数组中的查找/Solution.go, lcof/面试题05. 替换空格/README.md, lcof/面试题05. 替换空格/Solution.go
quite a good project. notice that few solutions writing in Golang,  just create a PR to enrich it. 
btw, problems 05 replace space. it's not designed to call the library funtions or any other Strings API to complete the job.
=> feat:add golang solutions for lcof problems 03-05

solution/1200-1299/1295.Find Numbers with Even Number of Digits/README.md, solution/1200-1299/1295.Find Numbers with Even Number of Digits/Solution.java
=> feat: add java solutions to problem: 1295

solution/0100-0199/0175.Combine Two Tables/Solution.sql
=> leetcode 0175

solution/0000-0099/0089.Gray Code/Solution.cpp
Add Solution.cpp for 0089.Gray Code
=> feat: add Solution.cpp for 0089.Gray Code

lcof/面试题32 - I. 从上到下打印二叉树/README.md
=> 更新了lcof-cpp中[从上到下打印二叉树]中README.md内容

lcof/面试题48. 最长不含重复字符的子字符串/README.md, lcof/面试题48. 最长不含重复字符的子字符串/Solution.cpp, lcof/面试题61. 扑克牌中的顺子/README.md, lcof/面试题61. 扑克牌中的顺子/Solution.cpp
增加了[lcof-48.最长不含重复字符的子字符串]和[lcof-61.扑克牌中的顺子]的cpp写法,基本双优
=> 剑指offer题目cpp版本提供

basic/sorting/BubbleSort/BubbleSort.js, basic/sorting/BubbleSort/README.md, basic/sorting/InsertionSort/InsertionSort.js, basic/sorting/InsertionSort/README.md, basic/sorting/MergeSort/MergeSort.js, basic/sorting/MergeSort/README.md, basic/sorting/QuickSort/QuickSort.js, basic/sorting/QuickSort/README.md, basic/sorting/SelectionSort/README.md, basic/sorting/SelectionSort/SelectionSort.js
add sorting algorithms in javascript
=> add sorting algorithms in javascript

solution/0400-0499/0403.Frog Jump/README.md, solution/0400-0499/0403.Frog Jump/README_EN.md, solution/0400-0499/0403.Frog Jump/Solution.java, solution/0400-0499/0403.Frog Jump/Solution.py
=> feat: add solutions to leetcode problem: No.0403. Frog Jump

solution/0300-0399/0377.Combination Sum IV/README.md, solution/0300-0399/0377.Combination Sum IV/README_EN.md, solution/0300-0399/0377.Combination Sum IV/Solution.java, solution/0300-0399/0377.Combination Sum IV/Solution.py
=> feat: add solutions to leetcode problem: No.0377. Combination Sum IV

solution/0000-0099/0001.Two Sum/README.md, solution/0000-0099/0001.Two Sum/README_EN.md, solution/0000-0099/0001.Two Sum/Solution.swift
This pull request, when merged, will add a Swift solution to the Two Sum problem
=> add a Two Sum solution in Swift language

solution/0000-0099/0001.Two Sum/README.md, solution/0000-0099/0001.Two Sum/README_EN.md, solution/0000-0099/0001.Two Sum/Solution.nim
=> feat: adds two sum in nim, minor fix in readme_en

lcof2/剑指 Offer II 006. 排序数组中两个数字之和/README.md, lcof2/剑指 Offer II 006. 排序数组中两个数字之和/Solution.cpp
feat: add cpp solution to lcof2 problem: NO.006
=> feat: add cpp solution to lcof2 problem: NO.006

lcof2/剑指 Offer II 045. 二叉树最底层最左边的值/README.md, lcof2/剑指 Offer II 045. 二叉树最底层最左边的值/Solution.cpp
feat: add cpp solution to lcof2 problem: NO.045
=> feat: add cpp solution to lcof2 problem: NO.045

solution/2000-2099/2049.Count Nodes With the Highest Score/README.md, solution/2000-2099/2049.Count Nodes With the Highest Score/README_EN.md, solution/2000-2099/2049.Count Nodes With the Highest Score/Solution.ts
=> feat: add typescript solution to lc problem: No.2049

solution/2000-2099/2059.Minimum Operations to Convert Number/README.md, solution/2000-2099/2059.Minimum Operations to Convert Number/README_EN.md, solution/2000-2099/2059.Minimum Operations to Convert Number/Solution.ts
=> feat: add typescript solution to lc problem: No.2059

solution/1100-1199/1124.Longest Well-Performing Interval/README.md, solution/1100-1199/1124.Longest Well-Performing Interval/README_EN.md, solution/1100-1199/1124.Longest Well-Performing Interval/Solution.py
1124.Longest Well-Performing Interval
=> feat: add solutions to lc problem: No.1124

solution/0800-0899/0860.Lemonade Change/README.md, solution/0800-0899/0860.Lemonade Change/README_EN.md, solution/0800-0899/0860.Lemonade Change/Solution.py
=> feat: add solutions to lc problem: No.0860

solution/2000-2099/2062.Count Vowel Substrings of a String/README.md, solution/2000-2099/2062.Count Vowel Substrings of a String/README_EN.md, solution/2000-2099/2062.Count Vowel Substrings of a String/Solution.ts
No.2062.Count Vowel Substrings of a String
=> feat: add typescript solution to lc problem: No.2062

solution/2000-2099/2064.Minimized Maximum of Products Distributed to Any Store/README.md, solution/2000-2099/2064.Minimized Maximum of Products Distributed to Any Store/README_EN.md, solution/2000-2099/2064.Minimized Maximum of Products Distributed to Any Store/Solution.ts
Minimized Maximum of Products Distributed to Any Store
=> feat: add typescript solution to locf problem: No.2064.

solution/2000-2099/2065.Maximum Path Quality of a Graph/README.md, solution/2000-2099/2065.Maximum Path Quality of a Graph/README_EN.md, solution/2000-2099/2065.Maximum Path Quality of a Graph/Solution.ts
Maximum Path Quality of a Graph
=> feat: add typescript solution to locf problem: No.2065.

solution/2000-2099/2091.Removing Minimum and Maximum From Array/README.md, solution/2000-2099/2091.Removing Minimum and Maximum From Array/README_EN.md, solution/2000-2099/2091.Removing Minimum and Maximum From Array/Solution.ts
Removing Minimum and Maximum From Array
=> feat: add typescript solution to lc problem: No.2091

solution/0400-0499/0419.Battleships in a Board/README.md, solution/0400-0499/0419.Battleships in a Board/README_EN.md, solution/0400-0499/0419.Battleships in a Board/Solution.java, solution/0400-0499/0419.Battleships in a Board/Solution.py
=> feat: add solutions to lc problem: No.0419

solution/1500-1599/1590.Make Sum Divisible by P/README.md, solution/1500-1599/1590.Make Sum Divisible by P/README_EN.md, solution/1500-1599/1590.Make Sum Divisible by P/Solution.ts
No.1590.Make Sum Divisible by P
=> feat: add typescript solution to lc problem: No.1590

solution/1700-1799/1737.Change Minimum Characters to Satisfy One of Three Conditions/README.md, solution/1700-1799/1737.Change Minimum Characters to Satisfy One of Three Conditions/README_EN.md, solution/1700-1799/1737.Change Minimum Characters to Satisfy One of Three Conditions/Solution.ts
No.1737.Change Minimum Characters to Satisfy One of Three Conditions
=> feat: add typescript solution to lc problem: No.1737

solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/README.md, solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/README_EN.md, solution/2100-2199/2133.Check if Every Row and Column Contains All Numbers/Solution.ts
No.2133.Check if Every Row and Column Contains All Numbers
=> feat: add typescript solution to lc problem: No.2133

solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/README.md, solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/README_EN.md, solution/2100-2199/2134.Minimum Swaps to Group All 1's Together II/Solution.ts
No.2134.Minimum Swaps to Group All 1's Together II
=> feat: add typescript solution to lc problem: No.2134

solution/0800-0899/0837.New 21 Game/README.md, solution/0800-0899/0837.New 21 Game/README_EN.md, solution/0800-0899/0837.New 21 Game/Solution.ts
=> feat: add typescript solution to lc problem: No.0837

solution/0900-0999/0983.Minimum Cost For Tickets/README.md, solution/0900-0999/0983.Minimum Cost For Tickets/README_EN.md, solution/0900-0999/0983.Minimum Cost For Tickets/Solution.ts
No.0983.Minimum Cost For Tickets
=> feat: add typescript solution to lc problem: No.0983

solution/0100-0199/0136.Single Number/README.md, solution/0100-0199/0136.Single Number/README_EN.md, solution/0100-0199/0136.Single Number/Solution.rs
=> feat: add rust solution to lc problem: No.0136

solution/0500-0599/0539.Minimum Time Difference/README.md, solution/0500-0599/0539.Minimum Time Difference/README_EN.md, solution/0500-0599/0539.Minimum Time Difference/Solution.ts
No.0539. Minimum Time Difference
=> feat: add typescript solution to lc problem: No.0539

lcof/面试题06. 从尾到头打印链表/README.md
=>  feat: add rust solution to lcof problem: No.06

lcof/面试题05. 替换空格/README.md, lcof/面试题05. 替换空格/Solution.rs
=> feat: add rust solution to lcof problem: No.05

basic/sorting/BubbleSort/BubbleSort.cs, basic/sorting/BubbleSort/README.md
add c# bubble in BubbleSort and improve the algorithm.
=> add c# bubble and improve the algorithm

basic/sorting/InsertionSort/InsertionSort.cs, basic/sorting/InsertionSort/README.md
add c# insert in InsertionSort, sorry for the last ps witout check my git operation. :(
=> add c# insert in InsertionSort

solution/0000-0099/0069.Sqrt(x)/README.md, solution/0000-0099/0069.Sqrt(x)/README_EN.md
=> docs: update description to lc problem No.0069

lcof/面试题25. 合并两个排序的链表/README.md, lcof/面试题25. 合并两个排序的链表/Solution.js
=> feat: update js solution to lcof problem: No.25

solution/0100-0199/0167.Two Sum II - Input array is sorted/README.md, solution/0100-0199/0167.Two Sum II - Input array is sorted/README_EN.md, solution/0100-0199/0167.Two Sum II - Input array is sorted/Solution.js, solution/0100-0199/0189.Rotate Array/README.md, solution/0100-0199/0189.Rotate Array/README_EN.md, solution/0200-0299/0283.Move Zeroes/README.md, solution/0200-0299/0283.Move Zeroes/README_EN.md
+ add a js solution of  167
+ add a js solution of  283
+ format 189 files
=> Add js solution of 167 and 283

lcof/面试题68 - I. 二叉搜索树的最近公共祖先/README.md
=> docs: update description to lcof problem No.68 - |

lcof/面试题68 - II. 二叉树的最近公共祖先/README.md
=> docs: remove unnecessary labels from lcof problem: No.68 - ||

solution/1600-1699/1679.Max Number of K-Sum Pairs/README.md, solution/1600-1699/1679.Max Number of K-Sum Pairs/README_EN.md, solution/1600-1699/1679.Max Number of K-Sum Pairs/Solution.java, solution/1600-1699/1679.Max Number of K-Sum Pairs/Solution.py
1679.Max Number of K-Sum Pairs
=> feat: add solutions to lc problem: No.1679

solution/1000-1099/1031.Maximum Sum of Two Non-Overlapping Subarrays/README.md, solution/1000-1099/1031.Maximum Sum of Two Non-Overlapping Subarrays/README_EN.md, solution/1000-1099/1031.Maximum Sum of Two Non-Overlapping Subarrays/Solution.java, solution/1000-1099/1031.Maximum Sum of Two Non-Overlapping Subarrays/Solution.py
1031.Maximum Sum of Two Non-Overlapping Subarrays
=> feat: add solutions to lc problem: No.1031

lcci/02.03.Delete Middle Node/README.md
=> docs: update a description of the solution to lcci problem: No.02.03

solution/2100-2199/2100.Find Good Days to Rob the Bank/README.md, solution/2100-2199/2100.Find Good Days to Rob the Bank/README_EN.md, solution/2100-2199/2100.Find Good Days to Rob the Bank/Solution.cpp, solution/2100-2199/2100.Find Good Days to Rob the Bank/Solution.go, solution/2100-2199/2100.Find Good Days to Rob the Bank/Solution.java
No.2100.Find Good Days to Rob the Bank
=> perf: optimize solutions to lc problem: No.2100

solution/0000-0099/0068.Text Justification/README.md, solution/0000-0099/0068.Text Justification/README_EN.md, solution/0000-0099/0068.Text Justification/Solution.cpp
=> add cpp solution to lc problem no:68

solution/1300-1399/1322.Ads Performance/README.md, solution/1300-1399/1322.Ads Performance/README_EN.md, solution/1300-1399/1322.Ads Performance/Solution.sql
=> added solution to lc:1322

solution/0600-0699/0603.Consecutive Available Seats/README.md, solution/0600-0699/0603.Consecutive Available Seats/README_EN.md, solution/0600-0699/0603.Consecutive Available Seats/Solution.sql
=> added solution to lc:603

solution/1400-1499/1435.Create a Session Bar Chart/README.md, solution/1400-1499/1435.Create a Session Bar Chart/README_EN.md, solution/1400-1499/1435.Create a Session Bar Chart/Solution.sql
=> added solution to lc:1435

solution/0500-0599/0586.Customer Placing the Largest Number of Orders/README.md, solution/0500-0599/0586.Customer Placing the Largest Number of Orders/README_EN.md, solution/0500-0599/0586.Customer Placing the Largest Number of Orders/Solution.sql
✅ Update readme 
✅ Added Solution file
=> added solution to lc:586

solution/0500-0599/0580.Count Student Number in Departments/README.md, solution/0500-0599/0580.Count Student Number in Departments/README_EN.md, solution/0500-0599/0580.Count Student Number in Departments/Solution.sql
=> added solution to lc:580

solution/0000-0099/0076.Minimum Window Substring/README.md, solution/0000-0099/0076.Minimum Window Substring/README_EN.md, solution/0000-0099/0076.Minimum Window Substring/Solution.cpp, solution/0000-0099/0076.Minimum Window Substring/Solution.java
✅ added java and cpp solution files
=> added solution to lc:76

solution/0500-0599/0577.Employee Bonus/README.md, solution/0500-0599/0577.Employee Bonus/README_EN.md, solution/0500-0599/0577.Employee Bonus/Solution.sql
=> added solution to lc:577

solution/0500-0599/0584.Find Customer Referee/README.md, solution/0500-0599/0584.Find Customer Referee/README_EN.md, solution/0500-0599/0584.Find Customer Referee/Solution.sql
=> added solution to lc:584

solution/0500-0599/0597.Friend Requests I Overall Acceptance Rate/README.md, solution/0500-0599/0597.Friend Requests I Overall Acceptance Rate/README_EN.md, solution/0500-0599/0597.Friend Requests I Overall Acceptance Rate/Solution.sql
=> added solution to :lc 597

solution/0500-0599/0511.Game Play Analysis I/README.md, solution/0500-0599/0511.Game Play Analysis I/README_EN.md, solution/0500-0599/0511.Game Play Analysis I/Solution.sql
=> added solution to lc:511

solution/0200-0299/0238.Product of Array Except Self/README.md
No.0238.Product of Array Except Self
=> docs: add a description of the solution to lc problem: No.0238

solution/1400-1499/1484.Group Sold Products By The Date/README.md, solution/1400-1499/1484.Group Sold Products By The Date/README_EN.md, solution/1400-1499/1484.Group Sold Products By The Date/Solution.sql
=> added solution to lc:1484

solution/1200-1299/1285.Find the Start and End Number of Continuous Ranges/README.md, solution/1200-1299/1285.Find the Start and End Number of Continuous Ranges/README_EN.md, solution/1200-1299/1285.Find the Start and End Number of Continuous Ranges/Solution.sql
=> added solution to lc:1285

solution/0600-0699/0602.Friend Requests II Who Has the Most Friends/README.md, solution/0600-0699/0602.Friend Requests II Who Has the Most Friends/README_EN.md, solution/0600-0699/0602.Friend Requests II Who Has the Most Friends/Solution.sql
=> added solution to lc:602

solution/0000-0099/0031.Next Permutation/README.md, solution/0000-0099/0031.Next Permutation/README_EN.md, solution/0000-0099/0031.Next Permutation/Solution.cpp
=> added solution to lc:31

solution/0100-0199/0191.Number of 1 Bits/README.md, solution/0100-0199/0191.Number of 1 Bits/README_EN.md, solution/0100-0199/0191.Number of 1 Bits/Solution.rs
=> feat: add rust solution to lc problem: No.0191

solution/1700-1799/1721.Swapping Nodes in a Linked List/README.md, solution/1700-1799/1721.Swapping Nodes in a Linked List/README_EN.md, solution/1700-1799/1721.Swapping Nodes in a Linked List/Solution.cpp
=> added cpp solution to lc:1721

solution/0900-0999/0923.3Sum With Multiplicity/README.md, solution/0900-0999/0923.3Sum With Multiplicity/README_EN.md, solution/0900-0999/0923.3Sum With Multiplicity/Solution.cpp
=> added cpp solution to lc:923

solution/1000-1099/1046.Last Stone Weight/README.md, solution/1000-1099/1046.Last Stone Weight/README_EN.md, solution/1000-1099/1046.Last Stone Weight/Solution.cpp, solution/1000-1099/1046.Last Stone Weight/Solution.java
✅ added java and c++ solution files
=> added solution to lc:1046

solution/0800-0899/0845.Longest Mountain in Array/README.md, solution/0800-0899/0845.Longest Mountain in Array/README_EN.md, solution/0800-0899/0845.Longest Mountain in Array/Solution.java, solution/0800-0899/0845.Longest Mountain in Array/Solution.py
0845.Longest Mountain in Array
=> feat: add solutions to lc problem: No.0845

index.html
- 统一风格
- 去除不必要的标签
- 更换最新的 CDN src
=> refactor: unified style

lcof2/剑指 Offer II 001. 整数除法/README.md
=> update example data

solution/0500-0599/0578.Get Highest Answer Rate Question/README.md, solution/0500-0599/0578.Get Highest Answer Rate Question/README_EN.md, solution/0500-0599/0578.Get Highest Answer Rate Question/Solution.sql
=> added solution to lc:578

solution/1300-1399/1369.Get the Second Most Recent Activity/README.md, solution/1300-1399/1369.Get the Second Most Recent Activity/README_EN.md, solution/1300-1399/1369.Get the Second Most Recent Activity/Solution.sql
=> added solution to lc:1369

solution/1100-1199/1112.Highest Grade For Each Student/README.md, solution/1100-1199/1112.Highest Grade For Each Student/README_EN.md, solution/1100-1199/1112.Highest Grade For Each Student/Solution.sql
=> added solution to lc:1112

solution/0700-0799/0706.Design HashMap/README.md, solution/0700-0799/0706.Design HashMap/README_EN.md, solution/0700-0799/0706.Design HashMap/Solution.cpp
=> added cpp solution to lc:706

solution/1700-1799/1712.Ways to Split Array Into Three Subarrays/README.md, solution/1700-1799/1712.Ways to Split Array Into Three Subarrays/README_EN.md, solution/1700-1799/1712.Ways to Split Array Into Three Subarrays/Solution.java, solution/1700-1799/1712.Ways to Split Array Into Three Subarrays/Solution.py
1712.Ways to Split Array Into Three Subarrays
=> feat: add solutions to lc problem: No.1712

solution/1600-1699/1679.Max Number of K-Sum Pairs/README.md, solution/1600-1699/1679.Max Number of K-Sum Pairs/README_EN.md, solution/1600-1699/1679.Max Number of K-Sum Pairs/Solution.cpp
=> added cpp solution to lc:1679

vercel.json
https://vercel.com/support/articles/how-to-prevent-vercel-github-comments
=> chore: disable vercel comments

solution/0000-0099/0048.Rotate Image/README.md, solution/0000-0099/0048.Rotate Image/README_EN.md, solution/0000-0099/0048.Rotate Image/Solution.go
=> feat: add go solution to lc problem:No0048

solution/0000-0099/0059.Spiral Matrix II/README.md, solution/0000-0099/0059.Spiral Matrix II/README_EN.md, solution/0000-0099/0059.Spiral Matrix II/Solution.go
=> feat: add go solution to lc problem:No.0059

solution/0500-0599/0567.Permutation in String/README.md, solution/0500-0599/0567.Permutation in String/README_EN.md, solution/0500-0599/0567.Permutation in String/Solution.go, solution/0500-0599/0567.Permutation in String/Solution.py
No.0567 [Permutation in String](https://leetcode.com/problems/permutation-in-string/)
=> feat: add solutions to lc problem:No.0567

solution/0100-0199/0116.Populating Next Right Pointers in Each Node/README.md, solution/0100-0199/0116.Populating Next Right Pointers in Each Node/README_EN.md, solution/0100-0199/0116.Populating Next Right Pointers in Each Node/Solution.go
No.0114.Populating Next Right Pointers in Each Node
=> feat: add go solution to lc problem: No.0116

lcof/面试题37. 序列化二叉树/README.md, lcof/面试题37. 序列化二叉树/Solution.cpp
=> feat: add cpp solution to lcof problem: No.037

solution/0300-0399/0341.Flatten Nested List Iterator/README.md, solution/0300-0399/0341.Flatten Nested List Iterator/README_EN.md, solution/0300-0399/0341.Flatten Nested List Iterator/Solution.go
No.0341.Flatten Nested List Iterator
=> feat: add go solution to lc problem: No.0341

solution/0300-0399/0313.Super Ugly Number/README.md, solution/0300-0399/0313.Super Ugly Number/README_EN.md, solution/0300-0399/0313.Super Ugly Number/Solution.go, solution/0300-0399/0313.Super Ugly Number/Solution.py
=> feat: add solutions to lc problem: No.0313

solution/0200-0299/0218.The Skyline Problem/README.md, solution/0200-0299/0218.The Skyline Problem/README_EN.md, solution/0200-0299/0218.The Skyline Problem/Solution.go, solution/0200-0299/0218.The Skyline Problem/Solution.py
=> feat: add solutions to lc problem: No.0218

solution/0600-0699/0621.Task Scheduler/README.md, solution/0600-0699/0621.Task Scheduler/README_EN.md, solution/0600-0699/0621.Task Scheduler/Solution.cs
Add C# solution to lc problem: No.621
=> add C# solution to lc problem: No.621

solution/0400-0499/0403.Frog Jump/README.md, solution/0400-0499/0403.Frog Jump/README_EN.md, solution/0400-0499/0403.Frog Jump/Solution.go
=> feat: add go solution to lc problem: No.0403

solution/1200-1299/1262.Greatest Sum Divisible by Three/README.md, solution/1200-1299/1262.Greatest Sum Divisible by Three/README_EN.md, solution/1200-1299/1262.Greatest Sum Divisible by Three/Solution.java, solution/1200-1299/1262.Greatest Sum Divisible by Three/Solution.py
1262.Greatest Sum Divisible by Three
=> feat: add solutions to lc problem: No.1262

solution/2000-2099/2086.Minimum Number of Buckets Required to Collect Rainwater from Houses/README.md, solution/2000-2099/2086.Minimum Number of Buckets Required to Collect Rainwater from Houses/README_EN.md, solution/2000-2099/2086.Minimum Number of Buckets Required to Collect Rainwater from Houses/Solution.java, solution/2000-2099/2086.Minimum Number of Buckets Required to Collect Rainwater from Houses/Solution.py
2086.Minimum Number of Buckets Required to Collect Rainwater from Houses
=> feat: add solutions to lc problem: No.2086

solution/0000-0099/0007.Reverse Integer/README.md, solution/0000-0099/0007.Reverse Integer/README_EN.md, solution/0000-0099/0007.Reverse Integer/Solution.cpp, solution/0000-0099/0007.Reverse Integer/Solution.go
=> feat: update solutions to lc problem: No.0007

solution/0000-0099/0010.Regular Expression Matching/README.md, solution/0000-0099/0010.Regular Expression Matching/README_EN.md, solution/0000-0099/0010.Regular Expression Matching/Solution.go
No.0010.Regular Expression Matching
=> feat: update solution to lc problem: No.0010

solution/0600-0699/0628.Maximum Product of Three Numbers/README.md, solution/0600-0699/0628.Maximum Product of Three Numbers/README_EN.md, solution/0600-0699/0628.Maximum Product of Three Numbers/Solution.go
No.0628.Maximum Product of Three Numbers
=> feat: add solutions to lc problem: No.0628

solution/0600-0699/0697.Degree of an Array/README.md, solution/0600-0699/0697.Degree of an Array/README_EN.md, solution/0600-0699/0697.Degree of an Array/Solution.go
=> feat: add golang solutions to lc problem: No.0697

solution/0100-0199/0136.Single Number/README.md, solution/0100-0199/0136.Single Number/README_EN.md, solution/0100-0199/0136.Single Number/Solution.swift
Hallo Teamleder,
thanks for offering us that we would code together. Here is my solution with **swift** to problem Nr.0136 at Leetcode.  I will keep contributing to Doosc and let us make **IT** bigger. 
Regards, 
Qiu
=> Leetcodebyqiu

solution/0800-0899/0876.Middle of the Linked List/README.md, solution/0800-0899/0876.Middle of the Linked List/README_EN.md, solution/0800-0899/0876.Middle of the Linked List/Solution.php, solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/README.md, solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/README_EN.md, solution/1200-1299/1290.Convert Binary Number in a Linked List to Integer/Solution.php
1290题许多语言的答案都很好了　按着解题思路写了php　
希望是可以给我们这里的也添个小砖和小瓦　
谢谢您们每天的更新
=> add PHP solution to lc problem No.1290 and No.876

solution/0200-0299/0217.Contains Duplicate/README.md, solution/0200-0299/0217.Contains Duplicate/README_EN.md, solution/0200-0299/0217.Contains Duplicate/Solution.php
=> add php solution to lc problem No.0217

solution/0000-0099/0027.Remove Element/README.md, solution/0000-0099/0027.Remove Element/README_EN.md, solution/0000-0099/0027.Remove Element/Solution.php
=> feat: add php soulution to lc problem:No.0027

solution/1500-1599/1523.Count Odd Numbers in an Interval Range/README.md, solution/1500-1599/1523.Count Odd Numbers in an Interval Range/README_EN.md, solution/1500-1599/1523.Count Odd Numbers in an Interval Range/Solution.php
=> feat:add php solution to lc problem:No.1523

solution/0000-0099/0088.Merge Sorted Array/README.md, solution/0000-0099/0088.Merge Sorted Array/README_EN.md, solution/0000-0099/0088.Merge Sorted Array/Solution.php
=> feat: add php solution to lc problem: No.0088

solution/0000-0099/0058.Length of Last Word/README.md, solution/0000-0099/0058.Length of Last Word/README_EN.md, solution/0000-0099/0058.Length of Last Word/Solution.php
=> feat: add php solution to lc problem: No.0058

solution/0000-0099/0028.Find the Index of the First Occurrence in a String/README.md, solution/0000-0099/0028.Find the Index of the First Occurrence in a String/README_EN.md, solution/0000-0099/0028.Find the Index of the First Occurrence in a String/Solution.php
=> feat: add php solution to lc problem: No.0028

solution/0000-0099/0070.Climbing Stairs/README.md, solution/0000-0099/0070.Climbing Stairs/README_EN.md, solution/0000-0099/0070.Climbing Stairs/Solution.php
=> feat: add php solution to lc problem: No.0070

solution/0100-0199/0121.Best Time to Buy and Sell Stock/README.md, solution/0100-0199/0121.Best Time to Buy and Sell Stock/README_EN.md, solution/0100-0199/0121.Best Time to Buy and Sell Stock/Solution.php
=> feat: add php solution to lc problem: No.0121

solution/0200-0299/0268.Missing Number/README.md, solution/0200-0299/0268.Missing Number/README_EN.md, solution/0200-0299/0268.Missing Number/Solution.php
=> feat: add php solution to lc problem: No.0268

solution/1100-1199/1137.N-th Tribonacci Number/README.md, solution/1100-1199/1137.N-th Tribonacci Number/README_EN.md, solution/1100-1199/1137.N-th Tribonacci Number/Solution.php
=> add php solution to lc problem: No.1137

solution/0500-0599/0557.Reverse Words in a String III/README.md, solution/0500-0599/0557.Reverse Words in a String III/README_EN.md, solution/0500-0599/0557.Reverse Words in a String III/Solution.php
=> feat: add php solution to lc problem: No.0557

solution/2000-2099/2000.Reverse Prefix of Word/README.md, solution/2000-2099/2000.Reverse Prefix of Word/README_EN.md, solution/2000-2099/2000.Reverse Prefix of Word/Solution.php
=> add php solution to lc problem: No.2000

solution/0200-0299/0263.Ugly Number/README.md, solution/0200-0299/0263.Ugly Number/README_EN.md, solution/0200-0299/0263.Ugly Number/Solution.php
=> feat: add php solution to lc problem: No.0263

solution/0000-0099/0013.Roman to Integer/README.md, solution/0000-0099/0013.Roman to Integer/README_EN.md, solution/0000-0099/0013.Roman to Integer/Solution.php
=> feat: add php solution to lc problem: No.0013

solution/0700-0799/0744.Find Smallest Letter Greater Than Target/README.md, solution/0700-0799/0744.Find Smallest Letter Greater Than Target/README_EN.md, solution/0700-0799/0744.Find Smallest Letter Greater Than Target/Solution.php
=> feat: add php solution to lc problem: No.0744

solution/0300-0399/0383.Ransom Note/README.md, solution/0300-0399/0383.Ransom Note/README_EN.md, solution/0300-0399/0383.Ransom Note/Solution.php
=> feat: add php solution to lc problem: No.0383

solution/0100-0199/0169.Majority Element/README.md, solution/0100-0199/0169.Majority Element/README_EN.md, solution/0100-0199/0169.Majority Element/Solution.php
=> feat: add php solution to lc problem: No.0169

solution/0700-0799/0796.Rotate String/README.md, solution/0700-0799/0796.Rotate String/README_EN.md, solution/0700-0799/0796.Rotate String/Solution.php
=> feat: add php solution to lc problem: No.0769

solution/1200-1299/1287.Element Appearing More Than 25% In Sorted Array/README.md, solution/1200-1299/1287.Element Appearing More Than 25% In Sorted Array/README_EN.md, solution/1200-1299/1287.Element Appearing More Than 25% In Sorted Array/Solution.php
=> feat: add php solution to lc problem: No.1287

solution/0000-0099/0014.Longest Common Prefix/README.md, solution/0000-0099/0014.Longest Common Prefix/README_EN.md, solution/0000-0099/0014.Longest Common Prefix/Solution.php
=> feat: add php solution to lc problem: No.0014

solution/0200-0299/0299.Bulls and Cows/README.md, solution/0200-0299/0299.Bulls and Cows/README_EN.md, solution/0200-0299/0299.Bulls and Cows/Solution.php
=> feat: add php solution to lc problem; No.0299

lcp/LCP 62. 交通枢纽/README.md
=> style: resize document image size

solution/0600-0699/0674.Longest Continuous Increasing Subsequence/README.md, solution/0600-0699/0674.Longest Continuous Increasing Subsequence/README_EN.md, solution/0600-0699/0674.Longest Continuous Increasing Subsequence/Solution.php
=> feat: add php solution to lc problem: No.0674

solution/1100-1199/1189.Maximum Number of Balloons/README.md, solution/1100-1199/1189.Maximum Number of Balloons/README_EN.md, solution/1100-1199/1189.Maximum Number of Balloons/Solution.php
=> feat: add php solution to lc problem: No.1189

solution/0000-0099/0026.Remove Duplicates from Sorted Array/README.md, solution/0000-0099/0026.Remove Duplicates from Sorted Array/README_EN.md, solution/0000-0099/0026.Remove Duplicates from Sorted Array/Solution.php
=> feat: add php solution to lc problem: No.0026

solution/0400-0499/0485.Max Consecutive Ones/README.md, solution/0400-0499/0485.Max Consecutive Ones/README_EN.md, solution/0400-0499/0485.Max Consecutive Ones/Solution.php
=> feat: add php solution lc problem: No.0485

solution/0600-0699/0643.Maximum Average Subarray I/README.md, solution/0600-0699/0643.Maximum Average Subarray I/README_EN.md, solution/0600-0699/0643.Maximum Average Subarray I/Solution.php
=> feat: add php solution to lc problem: No.0643

solution/1300-1399/1394.Find Lucky Integer in an Array/README.md, solution/1300-1399/1394.Find Lucky Integer in an Array/README_EN.md, solution/1300-1399/1394.Find Lucky Integer in an Array/Solution.php
=> feat: add php solution to lc problem: No.1394

solution/1700-1799/1704.Determine if String Halves Are Alike/README.md, solution/1700-1799/1704.Determine if String Halves Are Alike/README_EN.md, solution/1700-1799/1704.Determine if String Halves Are Alike/Solution.js
=> feat: add js solution to lc problem: No.1704

solution/1700-1799/1748.Sum of Unique Elements/README.md, solution/1700-1799/1748.Sum of Unique Elements/README_EN.md, solution/1700-1799/1748.Sum of Unique Elements/Solution.php
=> feat: add php solution to lc problem: No.1748

solution/0900-0999/0977.Squares of a Sorted Array/README.md, solution/0900-0999/0977.Squares of a Sorted Array/README_EN.md, solution/0900-0999/0977.Squares of a Sorted Array/Solution.php
=> feat: add php solution to lc problem: No.0977

solution/1600-1699/1672.Richest Customer Wealth/README.md, solution/1600-1699/1672.Richest Customer Wealth/README_EN.md, solution/1600-1699/1672.Richest Customer Wealth/Solution.php
=> feat: add php solution to lc problem: No.1672

solution/1900-1999/1945.Sum of Digits of String After Convert/README.md, solution/1900-1999/1945.Sum of Digits of String After Convert/README_EN.md, solution/1900-1999/1945.Sum of Digits of String After Convert/Solution.php
=> feat: add php solution to lc problem: No.1945

solution/1400-1499/1480.Running Sum of 1d Array/README.md, solution/1400-1499/1480.Running Sum of 1d Array/README_EN.md, solution/1400-1499/1480.Running Sum of 1d Array/Solution.php
=> feat: add php solution to lc problem: No.1480

solution/1400-1499/1491.Average Salary Excluding the Minimum and Maximum Salary/README.md, solution/1400-1499/1491.Average Salary Excluding the Minimum and Maximum Salary/README_EN.md, solution/1400-1499/1491.Average Salary Excluding the Minimum and Maximum Salary/Solution.php
=> feat add php solution to lc problemn: No.1491

solution/1300-1399/1323.Maximum 69 Number/README.md, solution/1300-1399/1323.Maximum 69 Number/README_EN.md, solution/1300-1399/1323.Maximum 69 Number/Solution.php
=> feat: add php solution to lc problem: No.1323

solution/1400-1499/1455.Check If a Word Occurs As a Prefix of Any Word in a Sentence/README.md, solution/1400-1499/1455.Check If a Word Occurs As a Prefix of Any Word in a Sentence/README_EN.md, solution/1400-1499/1455.Check If a Word Occurs As a Prefix of Any Word in a Sentence/Solution.php
=> feat: add php solution to lc problem: No.1455

solution/2000-2099/2068.Check Whether Two Strings are Almost Equivalent/README.md, solution/2000-2099/2068.Check Whether Two Strings are Almost Equivalent/README_EN.md, solution/2000-2099/2068.Check Whether Two Strings are Almost Equivalent/Solution.php
=> feat: add php solution to lc problem: No.2068

solution/1300-1399/1346.Check If N and Its Double Exist/README.md, solution/1300-1399/1346.Check If N and Its Double Exist/README_EN.md, solution/1300-1399/1346.Check If N and Its Double Exist/Solution.php
=> feat: add php solution to lc problem: No.1346

solution/2300-2399/2351.First Letter to Appear Twice/README.md, solution/2300-2399/2351.First Letter to Appear Twice/README_EN.md, solution/2300-2399/2351.First Letter to Appear Twice/Solution.php
=> feat: add php solution to lc problem: No.2351

solution/2400-2499/2418.Sort the People/README.md, solution/2400-2499/2418.Sort the People/README_EN.md, solution/2400-2499/2418.Sort the People/Solution.php
=> feat: add php solution to lc problem: No.2418

lcci/16.17.Contiguous Sequence/README.md, lcci/16.17.Contiguous Sequence/README_EN.md, lcci/16.17.Contiguous Sequence/Solution.php
=> feat: add php solution to lcci problem: No.16.17

solution/2300-2399/2390.Removing Stars From a String/README.md, solution/2300-2399/2390.Removing Stars From a String/README_EN.md, solution/2300-2399/2390.Removing Stars From a String/Solution.php
=> feat: add php solution to lc problem: No.2390

solution/1600-1699/1636.Sort Array by Increasing Frequency/README.md, solution/1600-1699/1636.Sort Array by Increasing Frequency/README_EN.md, solution/1600-1699/1636.Sort Array by Increasing Frequency/Solution.js
第1636题js做法 谢谢
刚才再local不小心删除 所以重新提交 打搅杨大大
=> feat: add js solution to lc problem: No.1636

solution/0400-0499/0451.Sort Characters By Frequency/README.md, solution/0400-0499/0451.Sort Characters By Frequency/README_EN.md, solution/0400-0499/0451.Sort Characters By Frequency/Solution.php
=> feat: add php solution to lc problem: No.0451

solution/2400-2499/2404.Most Frequent Even Element/README.md, solution/2400-2499/2404.Most Frequent Even Element/README_EN.md, solution/2400-2499/2404.Most Frequent Even Element/Solution.php
=> feat: add php solution to lc problem: No.2404

solution/0400-0499/0434.Number of Segments in a String/README.md, solution/0400-0499/0434.Number of Segments in a String/README_EN.md, solution/0400-0499/0434.Number of Segments in a String/Solution.php
=> feat: add php solution to lc problem: No.0434

solution/2200-2299/2215.Find the Difference of Two Arrays/README.md, solution/2200-2299/2215.Find the Difference of Two Arrays/README_EN.md, solution/2200-2299/2215.Find the Difference of Two Arrays/Solution.php
=> feat: add php solution to lc problem: No.2215

solution/2200-2299/2248.Intersection of Multiple Arrays/README.md, solution/2200-2299/2248.Intersection of Multiple Arrays/README_EN.md, solution/2200-2299/2248.Intersection of Multiple Arrays/Solution.php
=> feat: add php solution to lc problem: No.2248

solution/1200-1299/1213.Intersection of Three Sorted Arrays/README.md, solution/1200-1299/1213.Intersection of Three Sorted Arrays/README_EN.md, solution/1200-1299/1213.Intersection of Three Sorted Arrays/Solution.php
=> feat: add php solution to lc problem: No.1213

lcof/面试题05. 替换空格/README.md, lcof/面试题05. 替换空格/Solution.php
=> feat: add php solution to lcof problem: No.05

solution/1300-1399/1370.Increasing Decreasing String/README.md, solution/1300-1399/1370.Increasing Decreasing String/README_EN.md, solution/1300-1399/1370.Increasing Decreasing String/Solution.js
=> feat: add js solution to lc problem: No.1370

solution/1500-1599/1512.Number of Good Pairs/README.md, solution/1500-1599/1512.Number of Good Pairs/README_EN.md, solution/1500-1599/1512.Number of Good Pairs/Solution.php
=> feat: add php solution to lc problem: No.1512

solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/README.md, solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/README_EN.md, solution/1800-1899/1876.Substrings of Size Three with Distinct Characters/Solution.php
=> feat: add php solution to lc problem: No.1876

solution/1900-1999/1957.Delete Characters to Make Fancy String/README.md, solution/1900-1999/1957.Delete Characters to Make Fancy String/README_EN.md, solution/1900-1999/1957.Delete Characters to Make Fancy String/Solution.php
=> feat: add php solution to lc problem: No.1957

solution/1400-1499/1426.Counting Elements/README.md, solution/1400-1499/1426.Counting Elements/README_EN.md, solution/1400-1499/1426.Counting Elements/Solution.php
=> feat: add php solution to lc problem: No.1426

solution/1400-1499/1431.Kids With the Greatest Number of Candies/README.md, solution/1400-1499/1431.Kids With the Greatest Number of Candies/README_EN.md, solution/1400-1499/1431.Kids With the Greatest Number of Candies/Solution.php
=> feat: add php solution to lc problem: No.1431

solution/1400-1499/1464.Maximum Product of Two Elements in an Array/README.md, solution/1400-1499/1464.Maximum Product of Two Elements in an Array/README_EN.md, solution/1400-1499/1464.Maximum Product of Two Elements in an Array/Solution.php
=> feat: add php solution to lc problem: No.1464

solution/1400-1499/1451.Rearrange Words in a Sentence/README.md, solution/1400-1499/1451.Rearrange Words in a Sentence/README_EN.md, solution/1400-1499/1451.Rearrange Words in a Sentence/Solution.php
=> feat: add php solution to lc problem: No.1451

solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/README.md, solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/README_EN.md, solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/Solution.php
第1475题php做法 谢谢
PS：用的是枚举及原地修改做法 因单调栈使用不熟悉
=> feat:add php solution to lc problem: No.1475

solution/1400-1499/1451.Rearrange Words in a Sentence/README.md, solution/1400-1499/1451.Rearrange Words in a Sentence/README_EN.md, solution/1400-1499/1451.Rearrange Words in a Sentence/Solution.js
=> feat: add js solution to lc problem: No.1451

solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/README.md, solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/README_EN.md, solution/1400-1499/1475.Final Prices With a Special Discount in a Shop/Solution.js
=> feat: add js solution to lc problem: No.1475

solution/2200-2299/2259.Remove Digit From Number to Maximize Result/README.md, solution/2200-2299/2259.Remove Digit From Number to Maximize Result/README_EN.md, solution/2200-2299/2259.Remove Digit From Number to Maximize Result/Solution.php
=> feat: add php solution to lc problem: No.2259

solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/README.md, solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/README_EN.md, solution/1900-1999/1941.Check if All Characters Have Equal Number of Occurrences/Solution.php
=> feat: add php solution to lc problem: No.1941

solution/1000-1099/1056.Confusing Number/README.md, solution/1000-1099/1056.Confusing Number/README_EN.md, solution/1000-1099/1056.Confusing Number/Solution.php
=> feat: add php solution to lc problem: No.1056

solution/2700-2799/2742.Painting the Walls/README.md, solution/2700-2799/2742.Painting the Walls/README_EN.md, solution/2700-2799/2742.Painting the Walls/Solution.rs
=> feat: 2742 add rust solution

lcci/16.19.Pond Sizes/README.md, lcci/16.19.Pond Sizes/README_EN.md, lcci/16.19.Pond Sizes/Solution.cpp, lcci/16.19.Pond Sizes/Solution.go, lcci/16.19.Pond Sizes/Solution.java, lcci/16.19.Pond Sizes/Solution.py, lcci/16.19.Pond Sizes/Solution.ts, solution/0700-0799/0763.Partition Labels/Solution.java
=> feat: add solutions to lcci problem: No.16.19

solution/2400-2499/2490.Circular Sentence/README.md, solution/2400-2499/2490.Circular Sentence/README_EN.md, solution/2400-2499/2490.Circular Sentence/Solution.cpp, solution/2400-2499/2490.Circular Sentence/Solution.go, solution/2400-2499/2490.Circular Sentence/Solution.java, solution/2400-2499/2490.Circular Sentence/Solution.js, solution/2400-2499/2490.Circular Sentence/Solution.py, solution/2400-2499/2490.Circular Sentence/Solution.rs, solution/2400-2499/2490.Circular Sentence/Solution.ts
=> feat: add solutions to lc problem: No.2490

basic/sorting/BubbleSort/BubbleSort.py
按照题目的要求，增加`hasChange`标志表示上次循环是否有移动过元素。
=> 增加标志表示上次循环是否有元素移动

solution/2700-2799/2717.Semi-Ordered Permutation/README.md, solution/2700-2799/2717.Semi-Ordered Permutation/README_EN.md, solution/2700-2799/2717.Semi-Ordered Permutation/Solution.rs
=> feat: 2717 add rust solution

solution/1600-1699/1659.Maximize Grid Happiness/README.md, solution/1600-1699/1659.Maximize Grid Happiness/README_EN.md, solution/1600-1699/1659.Maximize Grid Happiness/Solution.cpp, solution/1600-1699/1659.Maximize Grid Happiness/Solution.go, solution/1600-1699/1659.Maximize Grid Happiness/Solution.java, solution/1600-1699/1659.Maximize Grid Happiness/Solution.py, solution/1600-1699/1659.Maximize Grid Happiness/Solution.ts
No.1659.Maximize Grid Happiness
=> feat: add solutions to lc problem: No.1659

solution/2700-2799/2743.Count Substrings Without Repeating Character/README.md, solution/2700-2799/2743.Count Substrings Without Repeating Character/README_EN.md, solution/2700-2799/2743.Count Substrings Without Repeating Character/Solution.cpp, solution/2700-2799/2743.Count Substrings Without Repeating Character/Solution.go, solution/2700-2799/2743.Count Substrings Without Repeating Character/Solution.java, solution/2700-2799/2743.Count Substrings Without Repeating Character/Solution.py, solution/2700-2799/2743.Count Substrings Without Repeating Character/Solution.ts
No.2743.Count Substrings Without Repeating Character
=> feat: add solutions to lc problem: No.2743

solution/2700-2799/2737.Find the Closest Marked Node/README.md, solution/2700-2799/2737.Find the Closest Marked Node/README_EN.md, solution/2700-2799/2737.Find the Closest Marked Node/Solution.cpp, solution/2700-2799/2737.Find the Closest Marked Node/Solution.go, solution/2700-2799/2737.Find the Closest Marked Node/Solution.java, solution/2700-2799/2737.Find the Closest Marked Node/Solution.py, solution/2700-2799/2737.Find the Closest Marked Node/Solution.ts
No.2737.Find the Closest Marked Node
=> feat: add solutions to lc problem: No.2737

solution/0200-0299/0219.Contains Duplicate II/README.md, solution/0200-0299/0219.Contains Duplicate II/README_EN.md, solution/0200-0299/0219.Contains Duplicate II/Solution.php
=> feat add php solution to lc problem No: 0219

solution/2700-2799/2716.Minimize String Length/README.md, solution/2700-2799/2716.Minimize String Length/README_EN.md, solution/2700-2799/2716.Minimize String Length/Solution.rs
=> feat: 2716 add rust solution

solution/2700-2799/2706.Buy Two Chocolates/README.md, solution/2700-2799/2706.Buy Two Chocolates/README_EN.md, solution/2700-2799/2706.Buy Two Chocolates/Solution.rs
=> feat: 2706 add rust solution

solution/2700-2799/2710.Remove Trailing Zeros From a String/README.md, solution/2700-2799/2710.Remove Trailing Zeros From a String/README_EN.md, solution/2700-2799/2710.Remove Trailing Zeros From a String/Solution.rs
=> feat: 2710 add rust solution

solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/README.md, solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/README_EN.md, solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/Solution.cpp, solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/Solution.go, solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/Solution.java, solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/Solution.py, solution/1500-1599/1557.Minimum Number of Vertices to Reach All Nodes/Solution.ts
No.1557.Minimum Number of Vertices to Reach All Nodes
=> feat: add solutions to lc problem: No.1557

solution/0800-0899/0861.Score After Flipping Matrix/README.md, solution/0800-0899/0861.Score After Flipping Matrix/README_EN.md, solution/0800-0899/0861.Score After Flipping Matrix/Solution.cs, solution/1500-1599/1551.Minimum Operations to Make Array Equal/README.md, solution/1500-1599/1551.Minimum Operations to Make Array Equal/README_EN.md, solution/1500-1599/1551.Minimum Operations to Make Array Equal/Solution.cpp, solution/1500-1599/1551.Minimum Operations to Make Array Equal/Solution.go, solution/1500-1599/1551.Minimum Operations to Make Array Equal/Solution.java, solution/1500-1599/1551.Minimum Operations to Make Array Equal/Solution.py, solution/1500-1599/1551.Minimum Operations to Make Array Equal/Solution.ts
* No.0861.Score After Flipping Matrix
* No.1551.Minimum Operations to Make Array Equal
=> feat: add solutions to lc problems: No.0861,1551

solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/README.md, solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/README_EN.md, solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/Solution.cpp, solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/Solution.go, solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/Solution.java, solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/Solution.py, solution/1800-1899/1877.Minimize Maximum Pair Sum in Array/Solution.ts
No.1877.Minimize Maximum Pair Sum in Array
=> feat: add solutions to lc problem: No.1877

solution/1500-1599/1581.Customer Who Visited but Did Not Make Any Transactions/README.md, solution/1500-1599/1581.Customer Who Visited but Did Not Make Any Transactions/README_EN.md, solution/1600-1699/1633.Percentage of Users Attended a Contest/README.md, solution/1600-1699/1633.Percentage of Users Attended a Contest/README_EN.md, solution/1600-1699/1633.Percentage of Users Attended a Contest/Solution.sql, solution/1700-1799/1731.The Number of Employees Which Report to Each Employee/README.md, solution/1700-1799/1731.The Number of Employees Which Report to Each Employee/README_EN.md, solution/1700-1799/1731.The Number of Employees Which Report to Each Employee/Solution.sql
* No.1581.Customer Who Visited but Did Not Make Any Transactions
* No.1633.Percentage of Users Attended a Contest
* No.1731.The Number of Employees Which Report to Each Employee
=> feat: add sql solutions to lc problems: No.1581,1633,1731

solution/1700-1799/1731.The Number of Employees Which Report to Each Employee/README.md, solution/1700-1799/1731.The Number of Employees Which Report to Each Employee/README_EN.md, solution/1700-1799/1731.The Number of Employees Which Report to Each Employee/Solution.sql, solution/1800-1899/1867.Orders With Maximum Quantity Above Average/README.md, solution/1800-1899/1867.Orders With Maximum Quantity Above Average/README_EN.md, solution/1800-1899/1867.Orders With Maximum Quantity Above Average/Solution.sql, solution/1900-1999/1988.Find Cutoff Score for Each School/README.md, solution/1900-1999/1988.Find Cutoff Score for Each School/README_EN.md, solution/1900-1999/1988.Find Cutoff Score for Each School/Solution.sql
* No.1731.The Number of Employees Which Report to Each Employee
* No.1867.Orders With Maximum Quantity Above Average
* No.1988.Find Cutoff Score for Each School
=> feat: add sql solutions to lc problems: No.1731,1867,1988

lcci/04.03.List of Depth/README.md, lcci/04.03.List of Depth/README_EN.md, lcci/04.03.List of Depth/Solution.cpp, lcci/04.03.List of Depth/Solution.go, lcci/04.03.List of Depth/Solution.java, lcci/04.03.List of Depth/Solution.py, lcci/04.03.List of Depth/Solution.ts, lcci/04.04.Check Balance/README.md, lcci/04.04.Check Balance/README_EN.md, lcci/04.04.Check Balance/Solution.cpp, lcci/04.04.Check Balance/Solution.go, lcci/04.04.Check Balance/Solution.java, lcci/04.04.Check Balance/Solution.py, lcci/04.04.Check Balance/Solution.ts
* No.04.03.List of Depth
* No.04.04.Check Balance
=> feat: add solutions to lcci problems: No.04.03,04.04

solution/2700-2799/2744.Find Maximum Number of String Pairs/README.md, solution/2700-2799/2744.Find Maximum Number of String Pairs/README_EN.md, solution/2700-2799/2744.Find Maximum Number of String Pairs/Solution.cpp, solution/2700-2799/2744.Find Maximum Number of String Pairs/Solution.go, solution/2700-2799/2744.Find Maximum Number of String Pairs/Solution.java, solution/2700-2799/2744.Find Maximum Number of String Pairs/Solution.py, solution/2700-2799/2744.Find Maximum Number of String Pairs/Solution.ts
No.2744.Find Maximum Number of String Pairs
=> feat: add solutions to lc problem: No.2744

solution/2300-2399/2379.Minimum Recolors to Get K Consecutive Black Blocks/README.md, solution/2300-2399/2379.Minimum Recolors to Get K Consecutive Black Blocks/README_EN.md, solution/2300-2399/2379.Minimum Recolors to Get K Consecutive Black Blocks/Solution.php
=> feat: add php solution to lc problem: No.2379

solution/2600-2699/2697.Lexicographically Smallest Palindrome/README.md, solution/2600-2699/2697.Lexicographically Smallest Palindrome/README_EN.md, solution/2600-2699/2697.Lexicographically Smallest Palindrome/Solution.rs
=> feat: 2697 add rust solution

solution/2700-2799/2745.Construct the Longest New String/README.md, solution/2700-2799/2745.Construct the Longest New String/README_EN.md, solution/2700-2799/2745.Construct the Longest New String/Solution.cpp, solution/2700-2799/2745.Construct the Longest New String/Solution.go, solution/2700-2799/2745.Construct the Longest New String/Solution.java, solution/2700-2799/2745.Construct the Longest New String/Solution.py, solution/2700-2799/2745.Construct the Longest New String/Solution.ts
No.2745.Construct the Longest New String
=> feat: add solutions to lc problem: No.2745

solution/2700-2799/2746.Decremental String Concatenation/README.md, solution/2700-2799/2746.Decremental String Concatenation/README_EN.md, solution/2700-2799/2746.Decremental String Concatenation/Solution.cpp, solution/2700-2799/2746.Decremental String Concatenation/Solution.go, solution/2700-2799/2746.Decremental String Concatenation/Solution.java, solution/2700-2799/2746.Decremental String Concatenation/Solution.py, solution/2700-2799/2746.Decremental String Concatenation/Solution.ts
No.2746.Decremental String Concatenation
=> feat: add solutions to lc problem: No.2746

solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/README.md, solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/README_EN.md, solution/1900-1999/1984.Minimum Difference Between Highest and Lowest of K Scores/Solution.php
=> feat: add php solution to lc problem: No.1984

solution/2700-2799/2749.Minimum Operations to Make the Integer Zero/README.md, solution/2700-2799/2749.Minimum Operations to Make the Integer Zero/README_EN.md, solution/2700-2799/2749.Minimum Operations to Make the Integer Zero/Solution.cpp, solution/2700-2799/2749.Minimum Operations to Make the Integer Zero/Solution.go, solution/2700-2799/2749.Minimum Operations to Make the Integer Zero/Solution.java, solution/2700-2799/2749.Minimum Operations to Make the Integer Zero/Solution.py
No.2749.Minimum Operations to Make the Integer Zero
=> feat: add solutions to lc problem: No.2749

solution/1200-1299/1241.Number of Comments per Post/README.md, solution/1200-1299/1241.Number of Comments per Post/README_EN.md, solution/1200-1299/1241.Number of Comments per Post/Solution.sql
No.1241.Number of Comments per Post
=> feat: add sql solution to lc problem: No.1241

.prettierrc, solution/1400-1499/1468.Calculate Salaries/README.md, solution/1400-1499/1468.Calculate Salaries/README_EN.md, solution/1400-1499/1468.Calculate Salaries/Solution.sql, solution/1500-1599/1543.Fix Product Name Format/README.md, solution/1500-1599/1543.Fix Product Name Format/README_EN.md, solution/1500-1599/1543.Fix Product Name Format/Solution.sql, solution/1500-1599/1555.Bank Account Summary/README.md, solution/1500-1599/1555.Bank Account Summary/README_EN.md, solution/1500-1599/1555.Bank Account Summary/Solution.sql
* No.1468.Calculate Salaries
* No.1543.Fix Product Name Format
* No.1555.Bank Account Summary
=> feat: add sql solutions to lc problems: No.1468,1543,1555

.prettierrc, solution/1400-1499/1479.Sales by Day of the Week/README.md, solution/1400-1499/1479.Sales by Day of the Week/README_EN.md, solution/1400-1499/1479.Sales by Day of the Week/Solution.sql
No.1479.Sales by Day of the Week
=> feat: add sql solution to lc problem: No.1479

solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/README.md, solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/README_EN.md, solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/Solution.php
=> feat: add php solution to lc problem: No.1456

solution/1400-1499/1456.Maximum Number of Vowels in a Substring of Given Length/README_EN.md, solution/1500-1599/1565.Unique Orders and Customers Per Month/README.md, solution/1500-1599/1565.Unique Orders and Customers Per Month/README_EN.md, solution/1500-1599/1565.Unique Orders and Customers Per Month/Solution.sql
No.1565.Unique Orders and Customers Per Month
=> feat: add sql solution to lc problem: No.1565

solution/2600-2699/2678.Number of Senior Citizens/README.md, solution/2600-2699/2678.Number of Senior Citizens/README_EN.md, solution/2600-2699/2678.Number of Senior Citizens/Solution.rs
=> feat: 2678 add rust solution

.prettierrc, solution/1000-1099/1097.Game Play Analysis V/README.md, solution/1000-1099/1097.Game Play Analysis V/README_EN.md, solution/1000-1099/1097.Game Play Analysis V/Solution.sql
=> feat: add sql solution to lc problem: No.1097

.prettierrc, solution/1100-1199/1127.User Purchase Platform/README.md, solution/1100-1199/1127.User Purchase Platform/README_EN.md, solution/1100-1199/1127.User Purchase Platform/Solution.sql
No.1127.User Purchase Platform
=> feat: add sql solution to lc problem: No.1127

solution/1300-1399/1327.List the Products Ordered in a Period/README.md, solution/1300-1399/1327.List the Products Ordered in a Period/README_EN.md, solution/1300-1399/1327.List the Products Ordered in a Period/Solution.sql
No.1327.List the Products Ordered in a Period
=> feat: add sql solution to lc problem: No.1327

solution/1300-1399/1364.Number of Trusted Contacts of a Customer/README.md, solution/1300-1399/1364.Number of Trusted Contacts of a Customer/README_EN.md, solution/1300-1399/1364.Number of Trusted Contacts of a Customer/Solution.sql
No.1364.Number of Trusted Contacts of a Customer
=> feat: add sql solution to lc problem: No.1364

solution/1300-1399/1355.Activity Participants/README.md, solution/1300-1399/1355.Activity Participants/README_EN.md, solution/1300-1399/1355.Activity Participants/Solution.sql
=> feat: add sql solution to lc problem: No.1355

solution/2600-2699/2670.Find the Distinct Difference Array/README.md, solution/2600-2699/2670.Find the Distinct Difference Array/README_EN.md, solution/2600-2699/2670.Find the Distinct Difference Array/Solution.rs
=> feat: 2670 add rust solution

solution/0600-0699/0601.Human Traffic of Stadium/README.md, solution/0600-0699/0601.Human Traffic of Stadium/README_EN.md, solution/0600-0699/0601.Human Traffic of Stadium/Solution.sql, solution/0600-0699/0615.Average Salary Departments VS Company/README.md, solution/0600-0699/0615.Average Salary Departments VS Company/README_EN.md, solution/0600-0699/0615.Average Salary Departments VS Company/Solution.sql
* No.0601.Human Traffic of Stadium
* No.0615.Average Salary Departments VS Company
=> feat: add sql solutions to lc problems: No.0601,0615

solution/1800-1899/1811.Find Interview Candidates/README.md, solution/1800-1899/1811.Find Interview Candidates/README_EN.md, solution/1800-1899/1811.Find Interview Candidates/Solution.sql
No.1811.Find Interview Candidates
=> feat: add sql solution to lc problem: No.1811

solution/1800-1899/1843.Suspicious Bank Accounts/README.md, solution/1800-1899/1843.Suspicious Bank Accounts/README_EN.md, solution/1800-1899/1843.Suspicious Bank Accounts/Solution.sql
No.1843.Suspicious Bank Accounts
=> feat: add sql solution to lc prolem: No.1843

solution/1100-1199/1100.Find K-Length Substrings With No Repeated Characters/README.md, solution/1100-1199/1100.Find K-Length Substrings With No Repeated Characters/README_EN.md, solution/1100-1199/1100.Find K-Length Substrings With No Repeated Characters/Solution.php
=> feat: add php solution to lc problem: No.1100

solution/2600-2699/2660.Determine the Winner of a Bowling Game/README.md, solution/2600-2699/2660.Determine the Winner of a Bowling Game/README_EN.md, solution/2600-2699/2660.Determine the Winner of a Bowling Game/Solution.rs
=> feat: 2660 add rust solution

.prettierignore, solution/0600-0699/0627.Swap Salary/README.md, solution/0600-0699/0627.Swap Salary/README_EN.md, solution/0600-0699/0627.Swap Salary/Solution.sql, solution/1600-1699/1661.Average Time of Process per Machine/README.md, solution/1600-1699/1661.Average Time of Process per Machine/README_EN.md, solution/1600-1699/1661.Average Time of Process per Machine/Solution.sql, solution/1600-1699/1677.Product's Worth Over Invoices/README.md, solution/1600-1699/1677.Product's Worth Over Invoices/README_EN.md, solution/1600-1699/1677.Product's Worth Over Invoices/Solution.sql
* No.0627.Swap Salary
* No.1661.Average Time of Process per Machine
* No.1677.Product's Worth Over Invoices
=> feat: add sql solutions to lc problems: No.0627,1661,1677

lcof2/剑指 Offer II 012. 左右两边子数组的和相等/README.md, lcof2/剑指 Offer II 012. 左右两边子数组的和相等/Solution.php
=> feat: add php solution to lcof2 problem: No.012

.prettierrc, solution/1700-1799/1777.Product's Price for Each Store/README.md, solution/1700-1799/1777.Product's Price for Each Store/README_EN.md, solution/1700-1799/1777.Product's Price for Each Store/Solution.sql, solution/2600-2699/2679.Sum in a Matrix/README.md, solution/2600-2699/2679.Sum in a Matrix/README_EN.md, solution/2600-2699/2679.Sum in a Matrix/Solution.py, solution/2600-2699/2679.Sum in a Matrix/Solution.ts
* No.1777.Product's Price for Each Store
* No.2679.Sum in a Matrix
=> feat: add solutions to lc problems: No.1777,2679

solution/1700-1799/1789.Primary Department for Each Employee/README.md, solution/1700-1799/1789.Primary Department for Each Employee/README_EN.md, solution/1700-1799/1789.Primary Department for Each Employee/Solution.sql, solution/1800-1899/1809.Ad-Free Sessions/README.md, solution/1800-1899/1809.Ad-Free Sessions/README_EN.md, solution/1800-1899/1809.Ad-Free Sessions/Solution.sql
* No.1789.Primary Department for Each Employee
* No.1809.Ad-Free Sessions
=> feat: add sql solutions to lc problems: No.1789,1809

solution/1900-1999/1907.Count Salary Categories/README.md, solution/1900-1999/1907.Count Salary Categories/README_EN.md, solution/1900-1999/1907.Count Salary Categories/Solution.sql, solution/1900-1999/1917.Leetcodify Friends Recommendations/README.md, solution/1900-1999/1917.Leetcodify Friends Recommendations/README_EN.md, solution/1900-1999/1917.Leetcodify Friends Recommendations/Solution.sql
* No.1907.Count Salary Categories
* No.1917.Leetcodify Friends Recommendations
=> feat: add solutions to lc problems: No.1907,1917

solution/2600-2699/2656.Maximum Sum With Exactly K Elements/README.md, solution/2600-2699/2656.Maximum Sum With Exactly K Elements/README_EN.md, solution/2600-2699/2656.Maximum Sum With Exactly K Elements/Solution.rs
=> feat: 2656 add rust solution

solution/2600-2699/2652.Sum Multiples/README.md, solution/2600-2699/2652.Sum Multiples/README_EN.md, solution/2600-2699/2652.Sum Multiples/Solution.rs
=> feat: 2652 add rust solution

.github/workflows/clang-format-lint.yml, solution/1800-1899/1892.Page Recommendations II/README.md, solution/1800-1899/1892.Page Recommendations II/README_EN.md, solution/1800-1899/1892.Page Recommendations II/Solution.sql
No.1892.Page Recommendations II
=> feat: add sql solution to lc problem: No.1892

solution/1300-1399/1336.Number of Transactions per Visit/README.md, solution/1300-1399/1336.Number of Transactions per Visit/README_EN.md, solution/1300-1399/1336.Number of Transactions per Visit/Solution.sql
No.1336.Number of Transactions per Visit/
=> feat: add sql solution to lc problem: No.1336

solution/2600-2699/2651.Calculate Delayed Arrival Time/README.md, solution/2600-2699/2651.Calculate Delayed Arrival Time/README_EN.md, solution/2600-2699/2651.Calculate Delayed Arrival Time/Solution.rs
=> feat: 2651 add rust solution

solution/2600-2699/2644.Find the Maximum Divisibility Score/README.md, solution/2600-2699/2644.Find the Maximum Divisibility Score/README_EN.md, solution/2600-2699/2644.Find the Maximum Divisibility Score/Solution.rs
=> feat: 2644 add rust solution

solution/2100-2199/2142.The Number of Passengers in Each Bus I/README.md, solution/2100-2199/2142.The Number of Passengers in Each Bus I/README_EN.md, solution/2100-2199/2142.The Number of Passengers in Each Bus I/Solution.sql, solution/2100-2199/2173.Longest Winning Streak/README.md, solution/2100-2199/2173.Longest Winning Streak/README_EN.md, solution/2100-2199/2173.Longest Winning Streak/Solution.sql
* No.2142.The Number of Passengers in Each Bus I
* No.2173.Longest Winning Streak
=> feat: add sql solutions to lc problems: No.2142,2173

solution/0000-0099/0004.Median of Two Sorted Arrays/README.md, solution/0000-0099/0004.Median of Two Sorted Arrays/README_EN.md, solution/0000-0099/0004.Median of Two Sorted Arrays/Solution.cpp, solution/0000-0099/0004.Median of Two Sorted Arrays/Solution.cs, solution/0000-0099/0004.Median of Two Sorted Arrays/Solution.go, solution/0000-0099/0004.Median of Two Sorted Arrays/Solution.java, solution/0000-0099/0004.Median of Two Sorted Arrays/Solution.py, solution/0000-0099/0004.Median of Two Sorted Arrays/Solution.ts
No.0004.Median of Two Sorted Arrays
=> feat: add solutions to lc problem: No.0004

solution/2600-2699/2643.Row With Maximum Ones/README.md, solution/2600-2699/2643.Row With Maximum Ones/README_EN.md, solution/2600-2699/2643.Row With Maximum Ones/Solution.rs
=> feat: 2643 add rust solution

.prettierrc, solution/1900-1999/1910.Remove All Occurrences of a Substring/README.md, solution/1900-1999/1910.Remove All Occurrences of a Substring/README_EN.md, solution/1900-1999/1910.Remove All Occurrences of a Substring/Solution.cpp, solution/1900-1999/1910.Remove All Occurrences of a Substring/Solution.go, solution/1900-1999/1910.Remove All Occurrences of a Substring/Solution.java, solution/1900-1999/1910.Remove All Occurrences of a Substring/Solution.py, solution/1900-1999/1910.Remove All Occurrences of a Substring/Solution.ts, solution/1900-1999/1934.Confirmation Rate/README.md, solution/1900-1999/1934.Confirmation Rate/README_EN.md, solution/1900-1999/1934.Confirmation Rate/Solution.sql, solution/1900-1999/1978.Employees Whose Manager Left the Company/README.md, solution/1900-1999/1978.Employees Whose Manager Left the Company/README_EN.md, solution/1900-1999/1978.Employees Whose Manager Left the Company/Solution.sql, solution/2000-2099/2026.Low-Quality Problems/README.md, solution/2000-2099/2026.Low-Quality Problems/README_EN.md, solution/2000-2099/2026.Low-Quality Problems/Solution.sql, solution/2100-2199/2175.The Change in Global Rankings/README.md, solution/2100-2199/2175.The Change in Global Rankings/README_EN.md, solution/2100-2199/2175.The Change in Global Rankings/Solution.sql, solution/2100-2199/2199.Finding the Topic of Each Post/README.md, solution/2100-2199/2199.Finding the Topic of Each Post/README_EN.md, solution/2100-2199/2199.Finding the Topic of Each Post/Solution.sql, solution/2200-2299/2230.The Users That Are Eligible for Discount/README.md, solution/2200-2299/2230.The Users That Are Eligible for Discount/README_EN.md, solution/2200-2299/2230.The Users That Are Eligible for Discount/Solution.sql, solution/2400-2499/2480.Form a Chemical Bond/README.md, solution/2400-2499/2480.Form a Chemical Bond/README_EN.md, solution/2400-2499/2480.Form a Chemical Bond/Solution.sql
* No.1910.Remove All Occurrences of a Substring
* No.1934.Confirmation Rate
* No.1978.Employees Whose Manager Left the Company
* No.2026.Low-Quality Problems
* No.2175.The Change in Global Rankings
* No.2199.Finding the Topic of Each Post
* No.2230.The Users That Are Eligible for Discount
* No.2480.Form a Chemical Bond
=> feat: add solutions to lc problems

solution/2600-2699/2639.Find the Width of Columns of a Grid/README.md, solution/2600-2699/2639.Find the Width of Columns of a Grid/README_EN.md, solution/2600-2699/2639.Find the Width of Columns of a Grid/Solution.rs
=> feat: 2639 add rust solution

solution/0400-0499/0445.Add Two Numbers II/README.md, solution/0400-0499/0445.Add Two Numbers II/README_EN.md, solution/0400-0499/0445.Add Two Numbers II/Solution.cpp, solution/0400-0499/0445.Add Two Numbers II/Solution.go, solution/0400-0499/0445.Add Two Numbers II/Solution.java, solution/0400-0499/0445.Add Two Numbers II/Solution.py, solution/0400-0499/0445.Add Two Numbers II/Solution.rs, solution/0400-0499/0445.Add Two Numbers II/Solution.ts
=> feat: update solutions to lc problem: No.0445

solution/2400-2499/2485.Find the Pivot Integer/README.md, solution/2400-2499/2485.Find the Pivot Integer/README_EN.md, solution/2400-2499/2485.Find the Pivot Integer/Solution.php
=> feat: add php solution to lc problem: No.2485

solution/2700-2799/2701.Consecutive Transactions with Increasing Amounts/README.md, solution/2700-2799/2701.Consecutive Transactions with Increasing Amounts/README_EN.md, solution/2700-2799/2701.Consecutive Transactions with Increasing Amounts/Solution.sql
No.2701.Consecutive Transactions with Increasing Amounts
=> feat: add sql solution to lc problem: No.2701

.prettierrc, solution/2400-2499/2494.Merge Overlapping Events in the Same Hall/README.md, solution/2400-2499/2494.Merge Overlapping Events in the Same Hall/README_EN.md, solution/2400-2499/2494.Merge Overlapping Events in the Same Hall/Solution.sql
No.2494.Merge Overlapping Events in the Same Hall
=> feat: add sql solution to lc problem: No.2494

solution/2300-2399/2388.Change Null Values in a Table to the Previous Value/README.md, solution/2300-2399/2388.Change Null Values in a Table to the Previous Value/README_EN.md, solution/2300-2399/2388.Change Null Values in a Table to the Previous Value/Solution.sql
No.2388.Change Null Values in a Table to the Previous Value
=> feat: add sql solution to lc problem: No.2388

solution/2300-2399/2362.Generate the Invoice/README.md, solution/2300-2399/2362.Generate the Invoice/README_EN.md, solution/2300-2399/2362.Generate the Invoice/Solution.sql, solution/2300-2399/2372.Calculate the Influence of Each Salesperson/README.md, solution/2300-2399/2372.Calculate the Influence of Each Salesperson/README_EN.md, solution/2300-2399/2372.Calculate the Influence of Each Salesperson/Solution.sql
* No.2362.Generate the Invoice
* No.2372.Calculate the Influence of Each Salesperson
=> feat: add sql solutions to lc problems: No.2362

solution/2300-2399/2346.Compute the Rank as a Percentage/README.md, solution/2300-2399/2346.Compute the Rank as a Percentage/README_EN.md, solution/2300-2399/2346.Compute the Rank as a Percentage/Solution.sql
No.2346.Compute the Rank as a Percentage
=> feat: add sql solution to lc problem: No.2346

solution/2600-2699/2609.Find the Longest Balanced Substring of a Binary String/README.md, solution/2600-2699/2609.Find the Longest Balanced Substring of a Binary String/README_EN.md, solution/2600-2699/2609.Find the Longest Balanced Substring of a Binary String/Solution.rs
=> feat: 2609 add rust solution

solution/2600-2699/2600.K Items With the Maximum Sum/README.md, solution/2600-2699/2600.K Items With the Maximum Sum/README_EN.md, solution/2600-2699/2600.K Items With the Maximum Sum/Solution.rs
=> feat: 2600 add rust solution

solution/2500-2599/2595.Number of Even and Odd Bits/README.md, solution/2500-2599/2595.Number of Even and Odd Bits/README_EN.md, solution/2500-2599/2595.Number of Even and Odd Bits/Solution.rs
请切换到 `Preview` 选项卡选择对应的模板：
> Please go the the `Preview` tab and select the appropriate sub-template:
* [中文模板](?quick_pull=1&template=template.md)
* [English Template](?quick_pull=1&template=template_en.md)
=> feat: add rust solution to lc problem: No.2595

solution/0200-0299/0231.Power of Two/README.md, solution/0200-0299/0231.Power of Two/README_EN.md, solution/0200-0299/0231.Power of Two/Solution.ts
[English Template](?quick_pull=1&template=template_en.md)
我们项目中各种编程语言代码（包括文档）所采用的格式化工具不同，提交 pr 之前必须确保代码、文档正确格式化。
-   .{md,js,ts,php,sql} 采用 prettier
-   .{c,cpp,java} 采用 clang-format
-   .{py} 采用 black
-   .{go} 采用 gofmt
-   其它待完善
我们项目遵循 [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#) 规范，我们希望你的提交信息尽可能与项目保持一致。
-   新增或修改题解：feat: add/update solution(s) to lc problem(s): No.xxxx
-   修复错误：fix: xxxx
-   日常维护：chore: xxx
新增题解及代码时，需要创建 Solution.xxx 源代码文件（如果已存在，请确认算法是否更优，是则覆盖已有算法代码），同时，需要在 README.md 以及 README_EN.md 中添加对应的代码片段（英文文件中不要出现中文注释）
另外，编码风格（比如变量、函数的命名），尽量跟项目已有代码保持一致。
=> feat: update ts solution to lc problem: No.0231

solution/0100-0199/0183.Customers Who Never Order/README.md, solution/0100-0199/0183.Customers Who Never Order/README_EN.md, solution/0100-0199/0183.Customers Who Never Order/Solution.sql, solution/0100-0199/0184.Department Highest Salary/README.md, solution/0100-0199/0184.Department Highest Salary/README_EN.md, solution/0100-0199/0184.Department Highest Salary/Solution.sql, solution/0100-0199/0185.Department Top Three Salaries/README.md, solution/0100-0199/0185.Department Top Three Salaries/README_EN.md, solution/0100-0199/0185.Department Top Three Salaries/Solution.sql, solution/0100-0199/0196.Delete Duplicate Emails/README.md, solution/0100-0199/0196.Delete Duplicate Emails/README_EN.md, solution/0100-0199/0196.Delete Duplicate Emails/Solution.sql, solution/0100-0199/0197.Rising Temperature/README.md, solution/0100-0199/0197.Rising Temperature/README_EN.md, solution/0100-0199/0197.Rising Temperature/Solution.sql
=> feat: update sql solutions to lc problems

solution/0000-0099/0015.3Sum/README.md, solution/0000-0099/0015.3Sum/README_EN.md, solution/0000-0099/0015.3Sum/Solution.ts
=> feat: update ts solution to lc problem: No.0015

solution/2500-2599/2591.Distribute Money to Maximum Children/README.md, solution/2500-2599/2591.Distribute Money to Maximum Children/README_EN.md, solution/2500-2599/2591.Distribute Money to Maximum Children/Solution.rs
请切换到 `Preview` 选项卡选择对应的模板：
> Please go the the `Preview` tab and select the appropriate sub-template:
* [中文模板](?quick_pull=1&template=template.md)
* [English Template](?quick_pull=1&template=template_en.md)
=> feat: add rust solution to lc problem: No.2591

solution/2500-2599/2586.Count the Number of Vowel Strings in Range/README.md, solution/2500-2599/2586.Count the Number of Vowel Strings in Range/README_EN.md, solution/2500-2599/2586.Count the Number of Vowel Strings in Range/Solution.rs
=> feat: add rust solution to lc problem: No.2586

solution/0500-0599/0574.Winning Candidate/README.md, solution/0500-0599/0574.Winning Candidate/README_EN.md, solution/0500-0599/0574.Winning Candidate/Solution.sql
=> feat: add sql solution to lc problem: No.0574

solution/2600-2699/2619.Array Prototype Last/README.md, solution/2600-2699/2619.Array Prototype Last/README_EN.md, solution/2600-2699/2619.Array Prototype Last/Solution.ts
2619.Array Prototype Last
当前版本无法通过新增测试用例 `[null]`
=> fix: update ts solution to lc problem: No.2619

solution/2800-2899/2810.Faulty Keyboard/README.md, solution/2800-2899/2810.Faulty Keyboard/README_EN.md, solution/2800-2899/2810.Faulty Keyboard/Solution.rs, solution/2800-2899/2811.Check if it is Possible to Split Array/README.md, solution/2800-2899/2811.Check if it is Possible to Split Array/README_EN.md, solution/2800-2899/2811.Check if it is Possible to Split Array/Solution.rs, solution/2800-2899/2812.Find the Safest Path in a Grid/README.md, solution/2800-2899/2812.Find the Safest Path in a Grid/README_EN.md, solution/2800-2899/2812.Find the Safest Path in a Grid/Solution.rs
- No.2810.Faulty Keyboard
- No.2811.Check if it is Possible to Split Array
- No.2812.Find the Safest Path in a Grid
=> feat: add solutions to lc problems: No.2810~2812

solution/0000-0099/0002.Add Two Numbers/README.md, solution/0000-0099/0002.Add Two Numbers/README_EN.md, solution/0000-0099/0002.Add Two Numbers/Solution.php, solution/0000-0099/0003.Longest Substring Without Repeating Characters/README.md, solution/0000-0099/0003.Longest Substring Without Repeating Characters/README_EN.md, solution/0000-0099/0003.Longest Substring Without Repeating Characters/Solution.php
Below are template for copilot to generate CR message.
Please DO NOT modify it.
Implemented PHP solutions for two LeetCode problems: Add Two Numbres and Longest Substring Without Repeating Characters.
Added a solution using with PHP
Passed all test cases successfully.
=> feat:add php solution to lc problems:No.0002,0003

solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/README.md, solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/README_EN.md, solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/Solution.cpp, solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/Solution.go, solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/Solution.java, solution/3000-3099/3013.Divide an Array Into Subarrays With Minimum Cost II/Solution.py
Updated the fully working and all test case passes code of Question No. 3013
Adding the code.
=> No.3013.Divide an Array Into Subarrays With Minimum Cost II

solution/3000-3099/3026.Maximum Good Subarray Sum/README.md, solution/3000-3099/3026.Maximum Good Subarray Sum/README_EN.md, solution/3000-3099/3026.Maximum Good Subarray Sum/Solution.cpp, solution/3000-3099/3026.Maximum Good Subarray Sum/Solution.go, solution/3000-3099/3026.Maximum Good Subarray Sum/Solution.java, solution/3000-3099/3026.Maximum Good Subarray Sum/Solution.py, solution/3000-3099/3026.Maximum Good Subarray Sum/Solution.ts
Updated the fully working and all test cases are passed for these codes for Question No. 3026
I am adding the code.
=> feat: add solutions to lc problem: No.3026

solution/2900-2999/2902.Count of Sub-Multisets With Bounded Sum/README.md, solution/2900-2999/2902.Count of Sub-Multisets With Bounded Sum/README_EN.md, solution/2900-2999/2902.Count of Sub-Multisets With Bounded Sum/Solution.cpp, solution/2900-2999/2902.Count of Sub-Multisets With Bounded Sum/Solution.go, solution/2900-2999/2902.Count of Sub-Multisets With Bounded Sum/Solution.ts
Updated the fully working and all test cases are passed for these codes for Question No. 2902
I am adding the code for cpp, goland and typescript.
=> feat: add solutions to lc problems: No.2902

solution/0000-0099/0011.Container With Most Water/README.md, solution/0000-0099/0011.Container With Most Water/README_EN.md, solution/0000-0099/0011.Container With Most Water/Solution.php, solution/0000-0099/0012.Integer to Roman/README.md, solution/0000-0099/0012.Integer to Roman/README_EN.md, solution/0000-0099/0012.Integer to Roman/Solution.php
Implemented PHP solutions for LeetCode problems 00011, 0012
Added a solution using with PHP
Passed all test cases successfully.
=> feat:add php solution to lc problems:No.0011,0012

lcci/04.01.Route Between Nodes/README.md, lcci/04.01.Route Between Nodes/README_EN.md, lcci/04.01.Route Between Nodes/Solution.cpp, lcci/04.01.Route Between Nodes/Solution.go, lcci/04.01.Route Between Nodes/Solution.java, lcci/04.01.Route Between Nodes/Solution.py, lcci/04.01.Route Between Nodes/Solution.ts, lcci/04.01.Route Between Nodes/Solution2.cpp, lcci/04.01.Route Between Nodes/Solution2.go, lcci/04.01.Route Between Nodes/Solution2.java, lcci/04.01.Route Between Nodes/Solution2.py, lcci/04.01.Route Between Nodes/Solution2.ts
=> feat: add solutions to lcci problem: No.04.01

solution/1400-1499/1483.Kth Ancestor of a Tree Node/README.md, solution/1400-1499/1483.Kth Ancestor of a Tree Node/README_EN.md, solution/1400-1499/1483.Kth Ancestor of a Tree Node/Solution.cs
No.1483.Kth Ancestor of a Tree Node
=> feat: add cs solution to lc problem: No.1483

solution/1600-1699/1600.Throne Inheritance/README.md, solution/1600-1699/1600.Throne Inheritance/README_EN.md, solution/1600-1699/1600.Throne Inheritance/Solution.cpp, solution/1600-1699/1600.Throne Inheritance/Solution.cs, solution/1600-1699/1600.Throne Inheritance/Solution.go, solution/1600-1699/1600.Throne Inheritance/Solution.java, solution/1600-1699/1600.Throne Inheritance/Solution.py, solution/1600-1699/1600.Throne Inheritance/Solution.ts
=> feat: add solutions to lc problem: No.1600

solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/README.md, solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/README_EN.md, solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/Solution.cpp, solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/Solution.go, solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/Solution.java, solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/Solution.py, solution/3100-3199/3105.Longest Strictly Increasing or Strictly Decreasing Subarray/Solution.ts, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/README.md, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/README_EN.md, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/Solution.cpp, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/Solution.go, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/Solution.java, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/Solution.py, solution/3100-3199/3106.Lexicographically Smallest String After Operations With Constraint/Solution.ts
* No.3105.Longest Strictly Increasing or Strictly Decreasing Subarray
* No.3106.Lexicographically Smallest String After Operations With Constraint
=> feat: add solutions to lc problems: No.3105,3106

solution/2200-2299/2269.Find the K-Beauty of a Number/README.md, solution/2200-2299/2269.Find the K-Beauty of a Number/README_EN.md, solution/2200-2299/2269.Find the K-Beauty of a Number/Solution2.cpp, solution/2200-2299/2269.Find the K-Beauty of a Number/Solution2.go, solution/2200-2299/2269.Find the K-Beauty of a Number/Solution2.java, solution/2200-2299/2269.Find the K-Beauty of a Number/Solution2.py, solution/2200-2299/2269.Find the K-Beauty of a Number/Solution2.ts
No.2269.Find the K-Beauty of a Number
=> feat: add solutions to lc problem: No.2269

solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/README.md, solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/README_EN.md, solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/Solution.cpp, solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/Solution.go, solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/Solution.java, solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/Solution.py, solution/1300-1399/1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold/Solution.ts, solution/2000-2099/2090.K Radius Subarray Averages/README.md, solution/2000-2099/2090.K Radius Subarray Averages/README_EN.md, solution/2000-2099/2090.K Radius Subarray Averages/Solution.cpp, solution/2000-2099/2090.K Radius Subarray Averages/Solution.go, solution/2000-2099/2090.K Radius Subarray Averages/Solution.java, solution/2000-2099/2090.K Radius Subarray Averages/Solution.py, solution/2000-2099/2090.K Radius Subarray Averages/Solution.ts
* No.1343.Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold
* No.2090.K Radius Subarray Averages
=> feat: update solutions to lc problems: No.1343,2090

solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/README.md, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/README_EN.md, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/Solution.cpp, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/Solution.cs, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/Solution.go, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/Solution.java, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/Solution.py, solution/2400-2499/2461.Maximum Sum of Distinct Subarrays With Length K/Solution.ts, solution/2800-2899/2841.Maximum Sum of Almost Unique Subarray/README.md, solution/2800-2899/2841.Maximum Sum of Almost Unique Subarray/README_EN.md, solution/2800-2899/2841.Maximum Sum of Almost Unique Subarray/Solution.cs, solution/2800-2899/2841.Maximum Sum of Almost Unique Subarray/Solution.java, solution/2800-2899/2841.Maximum Sum of Almost Unique Subarray/Solution.py
* No.2461.Maximum Sum of Distinct Subarrays With Length K
* No.2841.Maximum Sum of Almost Unique Subarray
=> feat: add solutions to lc problems: No.2461,2841

solution/1400-1499/1423.Maximum Points You Can Obtain from Cards/README.md, solution/1400-1499/1423.Maximum Points You Can Obtain from Cards/README_EN.md
No.1423.Maximum Points You Can Obtain from Cards
=> feat: add dart solution to lc problem: No.1423

solution/2600-2699/2653.Sliding Subarray Beauty/README.md, solution/2600-2699/2653.Sliding Subarray Beauty/README_EN.md, solution/2600-2699/2653.Sliding Subarray Beauty/Solution.py, solution/2600-2699/2653.Sliding Subarray Beauty/Solution2.cpp, solution/2600-2699/2653.Sliding Subarray Beauty/Solution2.go, solution/2600-2699/2653.Sliding Subarray Beauty/Solution2.java, solution/2600-2699/2653.Sliding Subarray Beauty/Solution2.py
No.2653.Sliding Subarray Beauty
=> feat: add solutions to lc problem: No.2653

solution/1700-1799/1702.Maximum Binary String After Change/README.md, solution/1700-1799/1702.Maximum Binary String After Change/README_EN.md, solution/1700-1799/1702.Maximum Binary String After Change/Solution.cpp, solution/1700-1799/1702.Maximum Binary String After Change/Solution.cs, solution/1700-1799/1702.Maximum Binary String After Change/Solution.rs, solution/1700-1799/1702.Maximum Binary String After Change/Solution.ts
No.1702.Maximum Binary String After Change
=> feat: add solutions to lc problem: No.1702

solution/0400-0499/0402.Remove K Digits/README.md, solution/0400-0499/0402.Remove K Digits/README_EN.md, solution/0400-0499/0402.Remove K Digits/Solution.ts
=> feat: update ts solutions to lc problem: No.0402

solution/2000-2099/2070.Most Beautiful Item for Each Query/README.md, solution/2000-2099/2070.Most Beautiful Item for Each Query/README_EN.md, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution.cpp, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution.go, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution.java, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution.py, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution.ts, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution2.cpp, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution2.go, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution2.java, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution2.py, solution/2000-2099/2070.Most Beautiful Item for Each Query/Solution2.ts
No.2070.Most Beautiful Item for Each Query
=> feat: add solutions to lc problem: No.2070

solution/0900-0999/0904.Fruit Into Baskets/README.md, solution/0900-0999/0904.Fruit Into Baskets/README_EN.md, solution/0900-0999/0904.Fruit Into Baskets/Solution.cpp, solution/0900-0999/0904.Fruit Into Baskets/Solution.java, solution/0900-0999/0904.Fruit Into Baskets/Solution.rs, solution/0900-0999/0904.Fruit Into Baskets/Solution.ts, solution/0900-0999/0904.Fruit Into Baskets/Solution2.cpp, solution/0900-0999/0904.Fruit Into Baskets/Solution2.java, solution/0900-0999/0904.Fruit Into Baskets/Solution2.rs, solution/0900-0999/0904.Fruit Into Baskets/Solution2.ts, solution/1600-1699/1695.Maximum Erasure Value/README.md, solution/1600-1699/1695.Maximum Erasure Value/README_EN.md, solution/1600-1699/1695.Maximum Erasure Value/Solution2.cpp, solution/1600-1699/1695.Maximum Erasure Value/Solution2.go, solution/1600-1699/1695.Maximum Erasure Value/Solution2.java, solution/1600-1699/1695.Maximum Erasure Value/Solution2.py, solution/1600-1699/1695.Maximum Erasure Value/Solution2.ts
* No.0904.Fruit Into Baskets
* No.1695.Maximum Erasure Value
=> feat: add solutions to lc problems: No.0904,1695

solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/README.md, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/README_EN.md, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution.go, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution.java, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution.py, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution.ts, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution2.cpp, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution2.go, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution2.java, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution2.py, solution/1400-1499/1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit/Solution2.ts
No.1438.Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit
=> feat: add solutions to lc problem: No.1438

solution/0900-0999/0924.Minimize Malware Spread/README.md, solution/0900-0999/0924.Minimize Malware Spread/README_EN.md, solution/0900-0999/0924.Minimize Malware Spread/Solution.cpp, solution/0900-0999/0924.Minimize Malware Spread/Solution.go, solution/0900-0999/0924.Minimize Malware Spread/Solution.java, solution/0900-0999/0924.Minimize Malware Spread/Solution.py, solution/0900-0999/0924.Minimize Malware Spread/Solution.ts
No.0924.Minimize Malware Spread
=> feat: add solutions to lc problem: No.0924

lcci/01.06.Compress String/README.md, lcci/01.06.Compress String/README_EN.md, lcci/01.06.Compress String/Solution.swift, lcci/01.07.Rotate Matrix/README.md, lcci/01.07.Rotate Matrix/README_EN.md, lcci/01.07.Rotate Matrix/Solution.swift
=> feat: update swift solutions to lc problem: No.01.06、No.01.07

.github/workflows/pr-labeled.yml
后续通过添加label 可以自动评论，antd社区在用的功能，后续对重复的review 都可以参照实现，方便管理
=> ci(supplement): auto comment tutorial

solution/0900-0999/0928.Minimize Malware Spread II/README.md, solution/0900-0999/0928.Minimize Malware Spread II/README_EN.md, solution/0900-0999/0928.Minimize Malware Spread II/Solution.cpp, solution/0900-0999/0928.Minimize Malware Spread II/Solution.go, solution/0900-0999/0928.Minimize Malware Spread II/Solution.java, solution/0900-0999/0928.Minimize Malware Spread II/Solution.py, solution/0900-0999/0928.Minimize Malware Spread II/Solution.ts
No.0928.Minimize Malware Spread II
=> feat: add solutions to lc problem: No.0928

solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/README.md, solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/README_EN.md, solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/Solution.cpp, solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/Solution.go, solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/Solution.java, solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/Solution.js, solution/2400-2499/2493.Divide Nodes Into the Maximum Number of Groups/Solution.py
No.2493.Divide Nodes Into the Maximum Number of Groups
=> feat: add solutions to lc problem: No.2493

solution/2000-2099/2076.Process Restricted Friend Requests/README.md, solution/2000-2099/2076.Process Restricted Friend Requests/README_EN.md, solution/2000-2099/2076.Process Restricted Friend Requests/Solution.cpp, solution/2000-2099/2076.Process Restricted Friend Requests/Solution.go, solution/2000-2099/2076.Process Restricted Friend Requests/Solution.java, solution/2000-2099/2076.Process Restricted Friend Requests/Solution.py, solution/2000-2099/2076.Process Restricted Friend Requests/Solution.ts
No.2076.Process Restricted Friend Requests
=> feat: add solutions to lc problem: No.2076

solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/README.md, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/README_EN.md, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.cpp, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.go, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.java, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.py, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.ts, solution/README.md, solution/README_EN.md
No.3119.Maximum Number of Potholes That Can Be Fixed
=> feat: add solutions to lc problem: No.3119

solution/1800-1899/1856.Maximum Subarray Min-Product/README.md, solution/1800-1899/1856.Maximum Subarray Min-Product/README_EN.md, solution/1800-1899/1856.Maximum Subarray Min-Product/Solution.ts, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/README.md, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/README_EN.md, solution/3100-3199/3119.Maximum Number of Potholes That Can Be Fixed/Solution.py
* No.1856.Maximum Subarray Min-Product
* No.3119.Maximum Number of Potholes That Can Be Fixed
=> feat: update solutions to lc problems: No.1856,3119

lcci/02.02.Kth Node From End of List/README.md, lcci/02.02.Kth Node From End of List/README_EN.md, lcci/02.02.Kth Node From End of List/Solution.swift
=> Swift implementation for LCCI 02.02

solution/1100-1199/1146.Snapshot Array/README.md, solution/1100-1199/1146.Snapshot Array/README_EN.md, solution/1100-1199/1146.Snapshot Array/Solution.cpp, solution/1100-1199/1146.Snapshot Array/Solution.go, solution/1100-1199/1146.Snapshot Array/Solution.java, solution/1100-1199/1146.Snapshot Array/Solution.py, solution/1100-1199/1146.Snapshot Array/Solution.ts, solution/2600-2699/2639.Find the Width of Columns of a Grid/README.md, solution/2600-2699/2639.Find the Width of Columns of a Grid/README_EN.md, solution/2600-2699/2639.Find the Width of Columns of a Grid/Solution.py, solution/2600-2699/2639.Find the Width of Columns of a Grid/Solution2.py, solution/2600-2699/2640.Find the Score of All Prefixes of an Array/README.md, solution/2600-2699/2640.Find the Score of All Prefixes of an Array/README_EN.md
* No.1146.Snapshot Array
* No.2639.Find the Width of Columns of a Grid
=> feat: update solutions to lc problems: No.1146,2639

lcci/05.08.Draw Line/README.md, lcci/05.08.Draw Line/README_EN.md, lcci/05.08.Draw Line/Solution.cpp, lcci/05.08.Draw Line/Solution.java, lcci/05.08.Draw Line/Solution.py
=> feat: add solutions to lcci problem: No.05.08

.github/workflows/black-lint.yml, .github/workflows/clang-format-lint.yml, .github/workflows/compress.yml, .github/workflows/deploy.yml, .github/workflows/pr-add-label.yml, solution/3100-3199/3133.Minimum Array End/README.md, solution/3100-3199/3133.Minimum Array End/README_EN.md, solution/3100-3199/3133.Minimum Array End/Solution.cpp, solution/3100-3199/3133.Minimum Array End/Solution.go, solution/3100-3199/3133.Minimum Array End/Solution.java, solution/3100-3199/3133.Minimum Array End/Solution.py, solution/3100-3199/3133.Minimum Array End/Solution.ts
=> feat: add solutions to lc problem: No.3133

solution/1300-1399/1329.Sort the Matrix Diagonally/README.md, solution/1300-1399/1329.Sort the Matrix Diagonally/README_EN.md, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.cpp, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.cs, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.go, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.java, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.py, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.rs, solution/1300-1399/1329.Sort the Matrix Diagonally/Solution.ts, solution/3100-3199/3126.Server Utilization Time/README.md, solution/3100-3199/3126.Server Utilization Time/README_EN.md, solution/3100-3199/3126.Server Utilization Time/Solution.sql
* No.1329.Sort the Matrix Diagonally
* No.3126.Server Utilization Time
=> feat: add solutions to lc problems: No.1329,3126

lcci/10.10.Rank from Stream/README.md, lcci/10.10.Rank from Stream/README_EN.md, lcci/10.10.Rank from Stream/Solution.cpp, lcci/10.10.Rank from Stream/Solution.go, lcci/10.10.Rank from Stream/Solution.java, lcci/10.10.Rank from Stream/Solution.py, lcci/10.10.Rank from Stream/Solution.ts
=> feat: add solutions to lcci problem: No.10.10

solution/0600-0699/0602.Friend Requests II Who Has the Most Friends/README.md, solution/0600-0699/0602.Friend Requests II Who Has the Most Friends/README_EN.md, solution/0600-0699/0602.Friend Requests II Who Has the Most Friends/Solution.sql
=> fix: update sql solution to lc problem: No.0602

solution/1600-1699/1652.Defuse the Bomb/README.md, solution/1600-1699/1652.Defuse the Bomb/README_EN.md, solution/1600-1699/1652.Defuse the Bomb/Solution2.ts
=> feat: add solutions to lc problem: No.1652

solution/0700-0799/0741.Cherry Pickup/README.md, solution/0700-0799/0741.Cherry Pickup/README_EN.md, solution/0700-0799/0741.Cherry Pickup/Solution.cpp, solution/0700-0799/0741.Cherry Pickup/Solution.go, solution/0700-0799/0741.Cherry Pickup/Solution.java, solution/0700-0799/0741.Cherry Pickup/Solution.py, solution/0700-0799/0741.Cherry Pickup/Solution.ts
=> feat: add solutions to lc problem: No.0741

solution/2500-2599/2521.Distinct Prime Factors of Product of Array/README.md, solution/2500-2599/2521.Distinct Prime Factors of Product of Array/README_EN.md, solution/2500-2599/2521.Distinct Prime Factors of Product of Array/Solution.ts, solution/2500-2599/2522.Partition String Into Substrings With Values at Most K/README_EN.md
No.2521.Distinct Prime Factors of Product of Array
=> feat: add ts solution to lc problem: No.2521

solution/2000-2099/2080.Range Frequency Queries/README.md, solution/2000-2099/2080.Range Frequency Queries/README_EN.md, solution/2000-2099/2080.Range Frequency Queries/Solution.cpp, solution/2000-2099/2080.Range Frequency Queries/Solution.go, solution/2000-2099/2080.Range Frequency Queries/Solution.java, solution/2000-2099/2080.Range Frequency Queries/Solution.py, solution/2000-2099/2080.Range Frequency Queries/Solution.ts
No.2080.Range Frequency Queries
=> feat: add solutions to lc problem: No.2080

solution/2100-2199/2195.Append K Integers With Minimal Sum/README.md, solution/2100-2199/2195.Append K Integers With Minimal Sum/README_EN.md, solution/2100-2199/2195.Append K Integers With Minimal Sum/Solution.cpp, solution/2100-2199/2195.Append K Integers With Minimal Sum/Solution.go, solution/2100-2199/2195.Append K Integers With Minimal Sum/Solution.java, solution/2100-2199/2195.Append K Integers With Minimal Sum/Solution.py, solution/2100-2199/2195.Append K Integers With Minimal Sum/Solution.ts
No.2195.Append K Integers With Minimal Sum
=> feat: add solutions to lc problem: No.2195

solution/2100-2199/2187.Minimum Time to Complete Trips/README.md, solution/2100-2199/2187.Minimum Time to Complete Trips/README_EN.md, solution/2100-2199/2187.Minimum Time to Complete Trips/Solution.cpp, solution/2100-2199/2187.Minimum Time to Complete Trips/Solution.go, solution/2100-2199/2187.Minimum Time to Complete Trips/Solution.ts
No.2187.Minimum Time to Complete Trips
=> feat: add solutions to lc problem: No.2187

solution/3100-3199/3146.Permutation Difference between Two Strings/README.md, solution/3100-3199/3146.Permutation Difference between Two Strings/README_EN.md, solution/3100-3199/3146.Permutation Difference between Two Strings/Solution.cpp, solution/3100-3199/3146.Permutation Difference between Two Strings/Solution.go, solution/3100-3199/3146.Permutation Difference between Two Strings/Solution.java, solution/3100-3199/3146.Permutation Difference between Two Strings/Solution.py, solution/3100-3199/3146.Permutation Difference between Two Strings/Solution.ts
No.3146.Permutation Difference between Two Strings
=> feat: add solutions to lc problem: No.3146

solution/3100-3199/3148.Maximum Difference Score in a Grid/README.md, solution/3100-3199/3148.Maximum Difference Score in a Grid/README_EN.md, solution/3100-3199/3148.Maximum Difference Score in a Grid/Solution.cpp, solution/3100-3199/3148.Maximum Difference Score in a Grid/Solution.go, solution/3100-3199/3148.Maximum Difference Score in a Grid/Solution.java, solution/3100-3199/3148.Maximum Difference Score in a Grid/Solution.py, solution/3100-3199/3148.Maximum Difference Score in a Grid/Solution.ts
No.3148.Maximum Difference Score in a Grid
=> feat: add solutions to lc problem: No.3148

lcci/17.22.Word Transformer/README.md, lcci/17.22.Word Transformer/README_EN.md, lcci/17.22.Word Transformer/Solution.cpp, lcci/17.22.Word Transformer/Solution.go, lcci/17.22.Word Transformer/Solution.java, lcci/17.22.Word Transformer/Solution.py, lcci/17.22.Word Transformer/Solution.ts, lcci/17.23.Max Black Square/README.md, lcci/17.23.Max Black Square/README_EN.md, lcci/17.23.Max Black Square/Solution.ts
=> feat: add solutions to lcci problem: No.17.22

solution/2600-2699/2622.Cache With Time Limit/README.md, solution/2600-2699/2622.Cache With Time Limit/README_EN.md, solution/2600-2699/2622.Cache With Time Limit/Solution.ts
> [Once the duration has elapsed, the key should be inaccessible.](https://leetcode.com/problems/cache-with-time-limit/description/)
Replaced `removeExpire()` with checking with `isExist`
=> refactor: refactor solution to lc problem: No.2622

lcp/LCP 80. 生物进化录/README.md, lcp/LCP 80. 生物进化录/Solution.cpp, lcp/LCP 80. 生物进化录/Solution.go, lcp/LCP 80. 生物进化录/Solution.java, lcp/LCP 80. 生物进化录/Solution.py
=> feat: add solutions to lcp problem: No.80

.github/workflows/deploy.yml, solution/2800-2899/2831.Find the Longest Equal Subarray/README.md, solution/2800-2899/2831.Find the Longest Equal Subarray/README_EN.md, solution/2800-2899/2831.Find the Longest Equal Subarray/Solution2.cpp, solution/2800-2899/2831.Find the Longest Equal Subarray/Solution2.go, solution/2800-2899/2831.Find the Longest Equal Subarray/Solution2.java, solution/2800-2899/2831.Find the Longest Equal Subarray/Solution2.py, solution/2800-2899/2831.Find the Longest Equal Subarray/Solution2.ts
No.2831.Find the Longest Equal Subarray
=> feat: add solutions to lc problem: No.2831

solution/0200-0299/0270.Closest Binary Search Tree Value/README.md, solution/0200-0299/0270.Closest Binary Search Tree Value/README_EN.md, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution.cpp, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution.go, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution.java, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution.js, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution.py, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution2.cpp, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution2.go, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution2.java, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution2.js, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution2.py, solution/0200-0299/0270.Closest Binary Search Tree Value/Solution2.ts
No.0270.Closest Binary Search Tree Value
=> feat: add solutions to lc problem: No.270

solution/0600-0699/0690.Employee Importance/README.md, solution/0600-0699/0690.Employee Importance/README_EN.md, solution/0600-0699/0690.Employee Importance/Solution.cpp, solution/0600-0699/0690.Employee Importance/Solution.go, solution/0600-0699/0690.Employee Importance/Solution.java, solution/0600-0699/0690.Employee Importance/Solution.js, solution/0600-0699/0690.Employee Importance/Solution.py, solution/0600-0699/0690.Employee Importance/Solution.ts
=> feat: add solutions to lc problem: No.690

lcof/面试题60. n个骰子的点数/README.md, lcof/面试题60. n个骰子的点数/Solution.cpp, lcof/面试题60. n个骰子的点数/Solution.cs, lcof/面试题60. n个骰子的点数/Solution.java, lcof/面试题60. n个骰子的点数/Solution.py, lcof/面试题60. n个骰子的点数/Solution2.cpp, lcof/面试题60. n个骰子的点数/Solution2.cs, lcof/面试题60. n个骰子的点数/Solution2.go, lcof/面试题60. n个骰子的点数/Solution2.java, lcof/面试题60. n个骰子的点数/Solution2.js
=> feat: add solutions to lcof problem: No.60

solution/2200-2299/2213.Longest Substring of One Repeating Character/README.md, solution/2200-2299/2213.Longest Substring of One Repeating Character/README_EN.md, solution/2200-2299/2213.Longest Substring of One Repeating Character/Solution.cpp, solution/2200-2299/2213.Longest Substring of One Repeating Character/Solution.go, solution/2200-2299/2213.Longest Substring of One Repeating Character/Solution.java, solution/2200-2299/2213.Longest Substring of One Repeating Character/Solution.py, solution/2200-2299/2213.Longest Substring of One Repeating Character/Solution.ts
No.2213.Longest Substring of One Repeating Character
=> feat: add solutions to lc problem: No.2213

solution/1100-1199/1129.Shortest Path with Alternating Colors/README.md, solution/1100-1199/1129.Shortest Path with Alternating Colors/README_EN.md, solution/1100-1199/1129.Shortest Path with Alternating Colors/Solution.ts
Unfortunately, the solution is quite slow.
I will appreciate any help to make it better.
=> feat: add TS solution to lc problem: No.1129

solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/README.md, solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/README_EN.md, solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/Solution3.cpp, solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/Solution3.go, solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/Solution3.java, solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/Solution3.py, solution/0300-0399/0323.Number of Connected Components in an Undirected Graph/Solution3.ts
No.323.Number of Connected Components in an Undirected Graph
=> feat: add solutions to lc problem: No.323

solution/0300-0399/0348.Design Tic-Tac-Toe/README.md, solution/0300-0399/0348.Design Tic-Tac-Toe/README_EN.md, solution/0300-0399/0348.Design Tic-Tac-Toe/Solution.cpp, solution/0300-0399/0348.Design Tic-Tac-Toe/Solution.go, solution/0300-0399/0348.Design Tic-Tac-Toe/Solution.py, solution/0300-0399/0348.Design Tic-Tac-Toe/Solution.ts
=> feat: add solutions to lc problem: No.0348

solution/0500-0599/0575.Distribute Candies/README.md, solution/0500-0599/0575.Distribute Candies/README_EN.md, solution/0500-0599/0575.Distribute Candies/Solution.cpp, solution/0500-0599/0575.Distribute Candies/Solution.ts, solution/0700-0799/0752.Open the Lock/Solution.ts
=> feat: add solutions to lc problem: No.0575

solution/0300-0399/0366.Find Leaves of Binary Tree/README.md, solution/0300-0399/0366.Find Leaves of Binary Tree/README_EN.md, solution/0300-0399/0366.Find Leaves of Binary Tree/Solution.cpp, solution/0300-0399/0366.Find Leaves of Binary Tree/Solution.cs, solution/0300-0399/0366.Find Leaves of Binary Tree/Solution.go, solution/0300-0399/0366.Find Leaves of Binary Tree/Solution.java, solution/0300-0399/0366.Find Leaves of Binary Tree/Solution.py, solution/0300-0399/0366.Find Leaves of Binary Tree/Solution.ts
No.0366.Find Leaves of Binary Tree
=> feat: add solutions to lc problem: No.366

solution/0400-0499/0467.Unique Substrings in Wraparound String/README.md, solution/0400-0499/0467.Unique Substrings in Wraparound String/README_EN.md, solution/0400-0499/0467.Unique Substrings in Wraparound String/Solution.cpp, solution/0400-0499/0467.Unique Substrings in Wraparound String/Solution.go, solution/0400-0499/0467.Unique Substrings in Wraparound String/Solution.java, solution/0400-0499/0467.Unique Substrings in Wraparound String/Solution.py, solution/0400-0499/0467.Unique Substrings in Wraparound String/Solution.rs, solution/0400-0499/0467.Unique Substrings in Wraparound String/Solution.ts
No.0467.Unique Substrings in Wraparound String
=> feat: add solutions to lc problem: No.467

solution/0400-0499/0468.Validate IP Address/README.md, solution/0400-0499/0468.Validate IP Address/README_EN.md, solution/0400-0499/0468.Validate IP Address/Solution.cpp, solution/0400-0499/0468.Validate IP Address/Solution.go, solution/0400-0499/0468.Validate IP Address/Solution.java, solution/0400-0499/0468.Validate IP Address/Solution.py, solution/0400-0499/0468.Validate IP Address/Solution.rs, solution/0400-0499/0468.Validate IP Address/Solution.ts
=> feat: add solutions to lc problem: No.468

lcof2/剑指 Offer II 037. 小行星碰撞/README.md, lcof2/剑指 Offer II 038. 每日温度/README.md, lcof2/剑指 Offer II 041. 滑动窗口的平均值/README.md, lcof2/剑指 Offer II 042. 最近请求次数/README.md, solution/1000-1099/1006.Clumsy Factorial/README.md, solution/1000-1099/1006.Clumsy Factorial/README_EN.md, solution/1000-1099/1006.Clumsy Factorial/Solution.cpp, solution/1000-1099/1006.Clumsy Factorial/Solution.go, solution/1000-1099/1006.Clumsy Factorial/Solution.java, solution/1000-1099/1006.Clumsy Factorial/Solution.py, solution/1000-1099/1006.Clumsy Factorial/Solution.ts, solution/3100-3199/3173.Bitwise OR of Adjacent Elements/README.md, solution/README.md, solution/main.py
=> feat: add solutions to lc problem: No.1006

solution/0300-0399/0312.Burst Balloons/README.md, solution/0300-0399/0312.Burst Balloons/README_EN.md, solution/0300-0399/0312.Burst Balloons/Solution.cpp, solution/0300-0399/0312.Burst Balloons/Solution.go, solution/0300-0399/0312.Burst Balloons/Solution.java, solution/0300-0399/0312.Burst Balloons/Solution.py, solution/0300-0399/0312.Burst Balloons/Solution.rs, solution/0300-0399/0312.Burst Balloons/Solution.ts
=> feat: add solutions to lc problem: No.312

solution/1000-1099/1051.Height Checker/README.md, solution/1000-1099/1051.Height Checker/README_EN.md, solution/1000-1099/1051.Height Checker/Solution.cpp, solution/1000-1099/1051.Height Checker/Solution.go, solution/1000-1099/1051.Height Checker/Solution2.ts
=> feat: update solutions to lc problem: No.1051

solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/README.md, solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/README_EN.md, solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/Solution.cpp, solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/Solution.go, solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/Solution.java, solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/Solution.py, solution/3100-3199/3176.Find the Maximum Length of a Good Subsequence I/Solution.ts, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/README.md, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/README_EN.md, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/Solution.cpp, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/Solution.go, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/Solution.java, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/Solution.py, solution/3100-3199/3177.Find the Maximum Length of a Good Subsequence II/Solution.ts
* No.3176.Find the Maximum Length of a Good Subsequence I
* No.3177.Find the Maximum Length of a Good Subsequence II
=> feat: add solutions to lc problems: No.3176,3177

solution/3100-3199/3180.Maximum Total Reward Using Operations I/README.md, solution/3100-3199/3180.Maximum Total Reward Using Operations I/README_EN.md, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution.cpp, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution.go, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution.java, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution.py, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution.ts
No.3180.Maximum Total Reward Using Operations I
=> feat: add solutions to lc problem: No.3180

solution/3100-3199/3180.Maximum Total Reward Using Operations I/README.md, solution/3100-3199/3180.Maximum Total Reward Using Operations I/README_EN.md, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution2.cpp, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution2.go, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution2.java, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution2.py, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution2.ts, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution3.cpp, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution3.go, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution3.java, solution/3100-3199/3180.Maximum Total Reward Using Operations I/Solution3.py, solution/3100-3199/3181.Maximum Total Reward Using Operations II/README.md, solution/3100-3199/3181.Maximum Total Reward Using Operations II/README_EN.md, solution/3100-3199/3181.Maximum Total Reward Using Operations II/Solution.cpp, solution/3100-3199/3181.Maximum Total Reward Using Operations II/Solution.go, solution/3100-3199/3181.Maximum Total Reward Using Operations II/Solution.java, solution/3100-3199/3181.Maximum Total Reward Using Operations II/Solution.py
* No.3180.Maximum Total Reward Using Operations I
* No.3181.Maximum Total Reward Using Operations II
=> feat: add solutions to lc problems: No.3180,3181

solution/0100-0199/0121.Best Time to Buy and Sell Stock/README.md, solution/0100-0199/0121.Best Time to Buy and Sell Stock/README_EN.md, solution/0100-0199/0121.Best Time to Buy and Sell Stock/Solution.php, solution/0100-0199/0121.Best Time to Buy and Sell Stock/Solution.rs
No.0121.Best Time to Buy and Sell Stock
=> chore: update solutions to lcp problem: No.0121

solution/2700-2799/2732.Find a Good Subset of the Matrix/README.md, solution/2700-2799/2732.Find a Good Subset of the Matrix/README_EN.md, solution/2700-2799/2732.Find a Good Subset of the Matrix/Solution.cpp, solution/2700-2799/2732.Find a Good Subset of the Matrix/Solution.go, solution/2700-2799/2732.Find a Good Subset of the Matrix/Solution.java, solution/2700-2799/2732.Find a Good Subset of the Matrix/Solution.py, solution/2700-2799/2732.Find a Good Subset of the Matrix/Solution.rs, solution/2700-2799/2732.Find a Good Subset of the Matrix/Solution.ts
No.2732.Find a Good Subset of the Matrix
=> feat: add solutions to lc problem: No.2732

solution/1700-1799/1720.Decode XORed Array/README.md, solution/1700-1799/1720.Decode XORed Array/README_EN.md, solution/1700-1799/1720.Decode XORed Array/Solution.cpp, solution/1700-1799/1720.Decode XORed Array/Solution.go, solution/1700-1799/1720.Decode XORed Array/Solution.py, solution/1700-1799/1720.Decode XORed Array/Solution.ts
=> feat: add solutions to lc problem: No.1720

solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/README.md, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/README_EN.md, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution.cpp, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution.go, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution.java, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution.py, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution.ts, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution2.cpp, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution2.go, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution2.java, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution2.py, solution/3100-3199/3196.Maximize Total Cost of Alternating Subarrays/Solution2.ts
No.3196.Maximize Total Cost of Alternating Subarrays
=> feat: add solutions to lc problem: No.3196

solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/README.md, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/README_EN.md, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/Solution.cpp, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/Solution.go, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/Solution.java, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/Solution.py, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/Solution.ts
No.3197.Find the Minimum Area to Cover All Ones II
=> feat: add solutions to lc problem: No.3197

solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/README.md, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/README_EN.md, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/Solution.go, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/Solution.js, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/Solution.py, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/Solution.rs, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/Solution.ts, solution/1200-1299/1283.Find the Smallest Divisor Given a Threshold/Solution2.py
No.1283.Find the Smallest Divisor Given a Threshold
=> feat: add solutions to lc problem: No.1283

solution/2000-2099/2073.Time Needed to Buy Tickets/README.md, solution/2000-2099/2073.Time Needed to Buy Tickets/README_EN.md, solution/2000-2099/2073.Time Needed to Buy Tickets/Solution.cpp, solution/2000-2099/2073.Time Needed to Buy Tickets/Solution.go, solution/2000-2099/2073.Time Needed to Buy Tickets/Solution.java, solution/2000-2099/2073.Time Needed to Buy Tickets/Solution.py, solution/2000-2099/2073.Time Needed to Buy Tickets/Solution.ts
No.2073.Time Needed to Buy Tickets
=> feat: update solutions to lc problem: No.2073

solution/3100-3199/3100.Water Bottles II/README.md, solution/3100-3199/3100.Water Bottles II/README_EN.md, solution/3100-3199/3100.Water Bottles II/Solution.rs
=> feat: add rust solution to lc problem: No.3100

solution/1800-1899/1823.Find the Winner of the Circular Game/README.md, solution/1800-1899/1823.Find the Winner of the Circular Game/README_EN.md, solution/1800-1899/1823.Find the Winner of the Circular Game/Solution.rs
0ms Runtime
2.04 mb Memory space
=> feat: add rust solution to lc problem: No.1823

solution/1500-1599/1562.Find Latest Group of Size M/README.md, solution/1500-1599/1562.Find Latest Group of Size M/README_EN.md, solution/1500-1599/1562.Find Latest Group of Size M/Solution.js
feat: add JS solution to lc problem: No.1562
This time using 'Union' technique and also run through prettier on my codesandbox.io Cloud Development Environment
=> feat: add js solution to lc problem: No.1562

solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/README.md, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/README_EN.md, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/Solution.cpp, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/Solution.go, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/Solution.java, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/Solution.py, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/Solution.rs, solution/0800-0899/0873.Length of Longest Fibonacci Subsequence/Solution.ts
No.0873.Length of Longest Fibonacci Subsequence
=> feat: add solutions to lc problem: No.0873

solution/0900-0999/0909.Snakes and Ladders/README.md, solution/0900-0999/0909.Snakes and Ladders/README_EN.md, solution/0900-0999/0909.Snakes and Ladders/Solution.cpp, solution/0900-0999/0909.Snakes and Ladders/Solution.go, solution/0900-0999/0909.Snakes and Ladders/Solution.java, solution/0900-0999/0909.Snakes and Ladders/Solution.py, solution/0900-0999/0909.Snakes and Ladders/Solution.ts
=> feat: add solutions to lc problem: No.0909

solution/0700-0799/0726.Number of Atoms/README.md, solution/0700-0799/0726.Number of Atoms/README_EN.md, solution/0700-0799/0726.Number of Atoms/Solution.java
=> feat: add java solution to lc problem: No.0726

solution/0900-0999/0948.Bag of Tokens/README.md, solution/0900-0999/0948.Bag of Tokens/README_EN.md, solution/0900-0999/0948.Bag of Tokens/Solution.cpp, solution/0900-0999/0948.Bag of Tokens/Solution.go, solution/0900-0999/0948.Bag of Tokens/Solution.java, solution/0900-0999/0948.Bag of Tokens/Solution.py, solution/0900-0999/0948.Bag of Tokens/Solution.ts
=> feat: add solutions to lc problem: No.0948

solution/0600-0699/0682.Baseball Game/README.md, solution/0600-0699/0682.Baseball Game/README_EN.md, solution/0600-0699/0682.Baseball Game/Solution.cpp, solution/0600-0699/0682.Baseball Game/Solution.go, solution/0600-0699/0682.Baseball Game/Solution.java, solution/0600-0699/0682.Baseball Game/Solution.py, solution/0600-0699/0682.Baseball Game/Solution.rs, solution/0600-0699/0682.Baseball Game/Solution.ts
=> feat: update solutions to lc problem: No.0682

solution/2600-2699/2621.Sleep/README.md, solution/2600-2699/2621.Sleep/README_EN.md, solution/2600-2699/2621.Sleep/Solution.js
added js solution for 2621 , https://leetcode.com/problems/sleep/
=> feat: add js solution to lc problem: No.2621

solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/README.md, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/README_EN.md, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/Solution.cpp, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/Solution.ts, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/Solution2.cpp, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/Solution2.java, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/Solution2.py, solution/3100-3199/3129.Find All Possible Stable Binary Arrays I/Solution2.ts, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/README.md, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/README_EN.md, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/Solution.cpp, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/Solution2.cpp, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/Solution2.java, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/Solution2.py, solution/3100-3199/3130.Find All Possible Stable Binary Arrays II/Solution2.ts
* No.3129.Find All Possible Stable Binary Arrays I
* No.3130.Find All Possible Stable Binary Arrays II
=> feat: add solutions to lc problems: No.3129,3130

solution/1400-1499/1458.Max Dot Product of Two Subsequences/README.md, solution/1400-1499/1458.Max Dot Product of Two Subsequences/README_EN.md, solution/1400-1499/1458.Max Dot Product of Two Subsequences/Solution.cpp, solution/1400-1499/1458.Max Dot Product of Two Subsequences/Solution.go, solution/1400-1499/1458.Max Dot Product of Two Subsequences/Solution.java, solution/1400-1499/1458.Max Dot Product of Two Subsequences/Solution.py, solution/1400-1499/1458.Max Dot Product of Two Subsequences/Solution.rs, solution/1400-1499/1458.Max Dot Product of Two Subsequences/Solution.ts
No.1458.Max Dot Product of Two Subsequences
=> feat: add solutions to lc problem: No.1458

solution/0800-0899/0839.Similar String Groups/README.md, solution/0800-0899/0839.Similar String Groups/README_EN.md, solution/0800-0899/0839.Similar String Groups/Solution.cpp, solution/0800-0899/0839.Similar String Groups/Solution.go, solution/0800-0899/0839.Similar String Groups/Solution.java, solution/0800-0899/0839.Similar String Groups/Solution.py, solution/0800-0899/0839.Similar String Groups/Solution.ts, solution/0800-0899/0840.Magic Squares In Grid/README.md, solution/0800-0899/0840.Magic Squares In Grid/README_EN.md, solution/0800-0899/0840.Magic Squares In Grid/Solution.ts, solution/3100-3199/3132.Find the Integer Added to Array II/README.md, solution/3100-3199/3132.Find the Integer Added to Array II/README_EN.md, solution/3100-3199/3132.Find the Integer Added to Array II/Solution.py
=> feat: add solutions to lc problem: No.0839

solution/1300-1399/1307.Verbal Arithmetic Puzzle/Solution.java
This solution was missing so i gave mine. Hope it helps.
=> feat: add java solution to lc problem: No.1307

solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/README.md, solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/README_EN.md, solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/Solution.cpp, solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/Solution.go, solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/Solution.java, solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/Solution.py, solution/3200-3299/3259.Maximum Energy Boost From Two Drinks/Solution.ts
No.3259.Maximum Energy Boost From Two Drinks
=> feat: add solutions to lc problem: No.3259

solution/2300-2399/2398.Maximum Number of Robots Within Budget/README.md, solution/2300-2399/2398.Maximum Number of Robots Within Budget/README_EN.md, solution/2300-2399/2398.Maximum Number of Robots Within Budget/Solution.cpp, solution/2300-2399/2398.Maximum Number of Robots Within Budget/Solution.go, solution/2300-2399/2398.Maximum Number of Robots Within Budget/Solution.java, solution/2300-2399/2398.Maximum Number of Robots Within Budget/Solution.py, solution/2300-2399/2398.Maximum Number of Robots Within Budget/Solution.ts
No.2398.Maximum Number of Robots Within Budget
=> feat: add solutions to lc problem: No.2398

solution/2100-2199/2145.Count the Hidden Sequences/README.md, solution/2100-2199/2145.Count the Hidden Sequences/README_EN.md, solution/2100-2199/2145.Count the Hidden Sequences/Solution.cpp, solution/2100-2199/2145.Count the Hidden Sequences/Solution.go, solution/2100-2199/2145.Count the Hidden Sequences/Solution.java, solution/2100-2199/2145.Count the Hidden Sequences/Solution.py, solution/2100-2199/2145.Count the Hidden Sequences/Solution.ts
No.2145.Count the Hidden Sequences
=> feat: add solutions to lc problem: No.2145

solution/2400-2499/2401.Longest Nice Subarray/README.md, solution/2400-2499/2401.Longest Nice Subarray/README_EN.md, solution/2400-2499/2401.Longest Nice Subarray/Solution.cpp, solution/2400-2499/2401.Longest Nice Subarray/Solution.cs, solution/2400-2499/2401.Longest Nice Subarray/Solution.go, solution/2400-2499/2401.Longest Nice Subarray/Solution.java, solution/2400-2499/2401.Longest Nice Subarray/Solution.py, solution/2400-2499/2401.Longest Nice Subarray/Solution.rs, solution/2400-2499/2401.Longest Nice Subarray/Solution.ts
=> feat: update solutions to lc problem: No.2401

solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/README.md, solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/README_EN.md, solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/Solution.cpp, solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/Solution.go, solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/Solution.java, solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/Solution.py, solution/3200-3299/3291.Minimum Number of Valid Strings to Form Target I/Solution.ts
No.3291.Minimum Number of Valid Strings to Form Target I
=> feat: add solutions to lc problem: No.3291

solution/2200-2299/2207.Maximize Number of Subsequences in a String/README.md, solution/2200-2299/2207.Maximize Number of Subsequences in a String/README_EN.md, solution/2200-2299/2207.Maximize Number of Subsequences in a String/Solution.cpp, solution/2200-2299/2207.Maximize Number of Subsequences in a String/Solution.go, solution/2200-2299/2207.Maximize Number of Subsequences in a String/Solution.java, solution/2200-2299/2207.Maximize Number of Subsequences in a String/Solution.py, solution/2200-2299/2207.Maximize Number of Subsequences in a String/Solution.ts
No.2207.Maximize Number of Subsequences in a String
=> feat: add solutions to lc problem: No.2207

solution/0700-0799/0728.Self Dividing Numbers/README.md, solution/0700-0799/0728.Self Dividing Numbers/README_EN.md, solution/0700-0799/0728.Self Dividing Numbers/Solution.cpp, solution/0700-0799/0728.Self Dividing Numbers/Solution.go, solution/0700-0799/0728.Self Dividing Numbers/Solution.java, solution/0700-0799/0728.Self Dividing Numbers/Solution.py, solution/0700-0799/0728.Self Dividing Numbers/Solution.rs, solution/0700-0799/0728.Self Dividing Numbers/Solution.ts
=> feat: add solutions to lc problem: No.0728

solution/3300-3399/3307.Find the K-th Character in String Game II/README.md, solution/3300-3399/3307.Find the K-th Character in String Game II/README_EN.md, solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.cpp, solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.go, solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.java, solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.py, solution/3300-3399/3307.Find the K-th Character in String Game II/Solution.ts
No.3307.Find the K-th Character in String Game II
=> feat: add solutions to lc problem: No.3307

solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/README.md, solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/README_EN.md, solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/Solution.cpp, solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/Solution.go, solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/Solution.java, solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/Solution.py, solution/3300-3399/3309.Maximum Possible Number by Binary Concatenation/Solution.ts, solution/3300-3399/3310.Remove Methods From Project/README.md, solution/3300-3399/3310.Remove Methods From Project/README_EN.md, solution/3300-3399/3310.Remove Methods From Project/Solution.cpp, solution/3300-3399/3310.Remove Methods From Project/Solution.go, solution/3300-3399/3310.Remove Methods From Project/Solution.java, solution/3300-3399/3310.Remove Methods From Project/Solution.py, solution/3300-3399/3310.Remove Methods From Project/Solution.ts
* No.3309.Maximum Possible Number by Binary Concatenation
* No.3310.Remove Methods From Project
=> feat: add solutions to lc problems: No.3309,3310

solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/README.md, solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/README_EN.md, solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/Solution.cpp, solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/Solution.go, solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/Solution.java, solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/Solution.py, solution/3300-3399/3311.Construct 2D Grid Matching Graph Layout/Solution.ts
No.3311.Construct 2D Grid Matching Graph Layout
=> feat: add solutions to lc problem: No.3311

solution/3300-3399/3313.Find the Last Marked Nodes in Tree/README.md, solution/3300-3399/3313.Find the Last Marked Nodes in Tree/README_EN.md, solution/3300-3399/3313.Find the Last Marked Nodes in Tree/Solution.cpp, solution/3300-3399/3313.Find the Last Marked Nodes in Tree/Solution.js
No.3313.Find the Last Marked Nodes in Tree
=> feat: add solutions to lc problem: No.3313

solution/3300-3399/3320.Count The Number of Winning Sequences/README.md, solution/3300-3399/3320.Count The Number of Winning Sequences/README_EN.md, solution/3300-3399/3320.Count The Number of Winning Sequences/Solution.cpp, solution/3300-3399/3320.Count The Number of Winning Sequences/Solution.go, solution/3300-3399/3320.Count The Number of Winning Sequences/Solution.java, solution/3300-3399/3320.Count The Number of Winning Sequences/Solution.py
No.3320.Count The Number of Winning Sequences
=> feat: add solutions to lc problem: No.3320

solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/README.md, solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/README_EN.md, solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/Solution.cpp, solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/Solution.go, solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/Solution.java, solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/Solution.py, solution/3100-3199/3165.Maximum Sum of Subsequence With Non-adjacent Elements/Solution.ts
No.3165.Maximum Sum of Subsequence With Non-adjacent Elements
=> feat: add solutions to lc problem: No.3165

solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/README.md, solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/README_EN.md, solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/Solution.cpp, solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/Solution.go, solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/Solution.java, solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/Solution.py, solution/3300-3399/3326.Minimum Division Operations to Make Array Non Decreasing/Solution.ts
No.3326.Minimum Division Operations to Make Array Non Decreasing
=> feat: add solutions to lc problem: No.3326

solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/README.md, solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/README_EN.md, solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/Solution.cpp, solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/Solution.go, solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/Solution.java, solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/Solution.py, solution/3300-3399/3329.Count Substrings With K-Frequency Characters II/Solution.ts, solution/README.md, solution/README_EN.md
No.3329.Count Substrings With K-Frequency Characters II
=> feat: add solutions to lc problem: No.3329

solution/3300-3399/3332.Maximum Points Tourist Can Earn/README.md, solution/3300-3399/3332.Maximum Points Tourist Can Earn/README_EN.md, solution/3300-3399/3332.Maximum Points Tourist Can Earn/Solution.cpp, solution/3300-3399/3332.Maximum Points Tourist Can Earn/Solution.go, solution/3300-3399/3332.Maximum Points Tourist Can Earn/Solution.java, solution/3300-3399/3332.Maximum Points Tourist Can Earn/Solution.py, solution/3300-3399/3332.Maximum Points Tourist Can Earn/Solution.ts, solution/3300-3399/3334.Find the Maximum Factor Score of Array/README.md, solution/3300-3399/3334.Find the Maximum Factor Score of Array/README_EN.md, solution/3300-3399/3334.Find the Maximum Factor Score of Array/Solution.cpp, solution/3300-3399/3334.Find the Maximum Factor Score of Array/Solution.go, solution/3300-3399/3334.Find the Maximum Factor Score of Array/Solution.java, solution/3300-3399/3334.Find the Maximum Factor Score of Array/Solution.py, solution/3300-3399/3334.Find the Maximum Factor Score of Array/Solution.ts
* No.3332.Maximum Points Tourist Can Earn
* No.3334.Find the Maximum Factor Score of Array
=> feat: add solutions to lc problems: No.3332,3334

solution/3300-3399/3341.Find Minimum Time to Reach Last Room I/README.md, solution/3300-3399/3341.Find Minimum Time to Reach Last Room I/README_EN.md, solution/3300-3399/3342.Find Minimum Time to Reach Last Room II/README.md, solution/3300-3399/3342.Find Minimum Time to Reach Last Room II/README_EN.md, solution/3300-3399/3343.Count Number of Balanced Permutations/README.md, solution/3300-3399/3343.Count Number of Balanced Permutations/README_EN.md, solution/3300-3399/3343.Count Number of Balanced Permutations/Solution.cpp, solution/3300-3399/3343.Count Number of Balanced Permutations/Solution.go, solution/3300-3399/3343.Count Number of Balanced Permutations/Solution.java, solution/3300-3399/3343.Count Number of Balanced Permutations/Solution.py, solution/3300-3399/3343.Count Number of Balanced Permutations/Solution.ts
No.3343.Count Number of Balanced Permutations
=> feat: add solutions to lc problem: No.3343

solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/README.md, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/README_EN.md, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/Solution.cpp, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/Solution.go, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/Solution.java, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/Solution.py, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/Solution.rs, solution/3200-3299/3258.Count Substrings That Satisfy K-Constraint I/Solution.ts
No.3258.Count Substrings That Satisfy K-Constraint I
=> feat: add solutions to lc problem: No.3258

solution/2200-2299/2270.Number of Ways to Split Array/README.md, solution/2200-2299/2270.Number of Ways to Split Array/README_EN.md, solution/2200-2299/2270.Number of Ways to Split Array/Solution.cpp, solution/2200-2299/2270.Number of Ways to Split Array/Solution.go, solution/2200-2299/2270.Number of Ways to Split Array/Solution.java, solution/2200-2299/2270.Number of Ways to Split Array/Solution.py, solution/2200-2299/2270.Number of Ways to Split Array/Solution.ts
No.2270.Number of Ways to Split Array
=> feat: add solutions to lc problem: No.2270

solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/README.md, solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/README_EN.md, solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/Solution.cpp, solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/Solution.go, solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/Solution.java, solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/Solution.py, solution/3200-3299/3240.Minimum Number of Flips to Make Binary Grid Palindromic II/Solution.ts
No.3240.Minimum Number of Flips to Make Binary Grid Palindromic II
=> feat: add solutions to lc problem: No.3240

solution/0500-0599/0515.Find Largest Value in Each Tree Row/README.md, solution/0500-0599/0515.Find Largest Value in Each Tree Row/README_EN.md, solution/0500-0599/0515.Find Largest Value in Each Tree Row/Solution.cpp, solution/0500-0599/0515.Find Largest Value in Each Tree Row/Solution.go, solution/0500-0599/0515.Find Largest Value in Each Tree Row/Solution.py, solution/0500-0599/0515.Find Largest Value in Each Tree Row/Solution.rs, solution/0500-0599/0515.Find Largest Value in Each Tree Row/Solution.ts
No.0515.Find Largest Value in Each Tree Row
=> feat: add solutions to lc problem: No.0515

solution/1800-1899/1898.Maximum Number of Removable Characters/README.md, solution/1800-1899/1898.Maximum Number of Removable Characters/README_EN.md, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.cpp, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.go, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.java, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.js, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.kt, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.py, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.rs, solution/1800-1899/1898.Maximum Number of Removable Characters/Solution.ts
No.1898.Maximum Number of Removable Characters
=> feat: add solutions to lc problem: No.1898

solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/README.md, solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/README_EN.md, solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/Solution.cpp, solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/Solution.go, solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/Solution.java, solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/Solution.py, solution/2000-2099/2056.Number of Valid Move Combinations On Chessboard/Solution.ts
No.2056.Number of Valid Move Combinations On Chessboard
=> feat: add solutions to lc problem: No.2056

solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/README.md, solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/README_EN.md, solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/Solution.cpp, solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/Solution.go, solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/Solution.java, solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/Solution.py, solution/3300-3399/3367.Maximize Sum of Weights after Edge Removals/Solution.ts
No.3367.Maximize Sum of Weights after Edge Removals
=> feat: add solutions to lc problem: No.3367

solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/README.md, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/README_EN.md, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/Solution.cpp, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/Solution.go, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/Solution.java, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/Solution.py, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/Solution.rs, solution/1000-1099/1013.Partition Array Into Three Parts With Equal Sum/Solution.ts
No.1013.Partition Array Into Three Parts With Equal Sum
=> feat: add solutions to lc problem: No.1013

solution/3300-3399/3379.Transformed Array/README.md, solution/3300-3399/3379.Transformed Array/README_EN.md, solution/3300-3399/3379.Transformed Array/Solution.cpp, solution/3300-3399/3379.Transformed Array/Solution.go, solution/3300-3399/3379.Transformed Array/Solution.java, solution/3300-3399/3379.Transformed Array/Solution.py, solution/3300-3399/3379.Transformed Array/Solution.ts
=> feat: add solutions to lc problem: No.3379

solution/0900-0999/0929.Unique Email Addresses/README.md, solution/0900-0999/0929.Unique Email Addresses/README_EN.md, solution/0900-0999/0929.Unique Email Addresses/Solution.cpp, solution/0900-0999/0929.Unique Email Addresses/Solution.go, solution/0900-0999/0929.Unique Email Addresses/Solution.java, solution/0900-0999/0929.Unique Email Addresses/Solution.js, solution/0900-0999/0929.Unique Email Addresses/Solution.py, solution/0900-0999/0929.Unique Email Addresses/Solution.rs, solution/0900-0999/0929.Unique Email Addresses/Solution.ts
No.0929.Unique Email Addresses
=> feat: add solutions to lc problem: No.0929

solution/3300-3399/3388.Count Beautiful Splits in an Array/README.md, solution/3300-3399/3388.Count Beautiful Splits in an Array/README_EN.md, solution/3300-3399/3388.Count Beautiful Splits in an Array/Solution.cpp, solution/3300-3399/3388.Count Beautiful Splits in an Array/Solution.go, solution/3300-3399/3388.Count Beautiful Splits in an Array/Solution.java, solution/3300-3399/3388.Count Beautiful Splits in an Array/Solution.py, solution/3300-3399/3388.Count Beautiful Splits in an Array/Solution.ts
No.3388.Count Beautiful Splits in an Array
=> feat: add solutions to lc problem: No.3388

solution/3300-3399/3388.Count Beautiful Splits in an Array/Solution.cpp, solution/3300-3399/3390.Longest Team Pass Streak/README.md, solution/3300-3399/3390.Longest Team Pass Streak/README_EN.md, solution/3300-3399/3390.Longest Team Pass Streak/Solution.sql, solution/DATABASE_README.md, solution/DATABASE_README_EN.md, solution/README.md, solution/README_EN.md
No.3390.Longest Team Pass Streak
=> feat: add solutions to lc problem: No.3390

solution/3200-3299/3292.Minimum Number of Valid Strings to Form Target II/README.md, solution/3200-3299/3292.Minimum Number of Valid Strings to Form Target II/README_EN.md, solution/3200-3299/3292.Minimum Number of Valid Strings to Form Target II/Solution.cpp, solution/3200-3299/3292.Minimum Number of Valid Strings to Form Target II/Solution.go, solution/3200-3299/3292.Minimum Number of Valid Strings to Form Target II/Solution.java, solution/3200-3299/3292.Minimum Number of Valid Strings to Form Target II/Solution.py
No.3292.Minimum Number of Valid Strings to Form Target II
=> feat: add solutions to lc problem: No.3292

solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/README.md, solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/README_EN.md, solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/Solution.cpp, solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/Solution.go, solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/Solution.java, solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/Solution.py, solution/1300-1399/1371.Find the Longest Substring Containing Vowels in Even Counts/Solution.ts
No.1371.Find the Longest Substring Containing Vowels in Even Counts
=> feat: add solutions to lc problem: No.1371

solution/0900-0999/0977.Squares of a Sorted Array/README.md, solution/1800-1899/1891.Cutting Ribbons/README.md, solution/3300-3399/3369.Design an Array Statistics Tracker/README.md, solution/3300-3399/3369.Design an Array Statistics Tracker/README_EN.md, solution/3300-3399/3376.Minimum Time to Break Locks I/README_EN.md, solution/3300-3399/3385.Minimum Time to Break Locks II/README.md, solution/3300-3399/3385.Minimum Time to Break Locks II/README_EN.md, solution/3300-3399/3386.Button with Longest Push Time/README.md, solution/3300-3399/3386.Button with Longest Push Time/README_EN.md, solution/3300-3399/3387.Maximize Amount After Two Days of Conversions/README.md, solution/3300-3399/3387.Maximize Amount After Two Days of Conversions/README_EN.md, solution/3300-3399/3388.Count Beautiful Splits in an Array/README.md, solution/3300-3399/3388.Count Beautiful Splits in an Array/README_EN.md, solution/3300-3399/3389.Minimum Operations to Make Character Frequencies Equal/README.md, solution/3300-3399/3389.Minimum Operations to Make Character Frequencies Equal/README_EN.md, solution/3300-3399/3391.Design a 3D Binary Matrix with Efficient Layer Tracking/README.md, solution/3300-3399/3391.Design a 3D Binary Matrix with Efficient Layer Tracking/README_EN.md, solution/3300-3399/3391.Design a 3D Binary Matrix with Efficient Layer Tracking/Solution.cpp, solution/3300-3399/3391.Design a 3D Binary Matrix with Efficient Layer Tracking/Solution.java, solution/3300-3399/3391.Design a 3D Binary Matrix with Efficient Layer Tracking/Solution.py, solution/DATABASE_README.md, solution/DATABASE_README_EN.md, solution/README.md, solution/README_EN.md
No.3391.Design a 3D Binary Matrix with Efficient Layer Tracking
=> feat: add solutions to lc problem: No.3391

solution/1300-1399/1387.Sort Integers by The Power Value/README.md, solution/1300-1399/1387.Sort Integers by The Power Value/README_EN.md, solution/1300-1399/1387.Sort Integers by The Power Value/Solution.rs
No.1387.Sort Integers by The Power Value
=> feat: add solutions to lc problem: No.1387

solution/1500-1599/1563.Stone Game V/README.md, solution/1500-1599/1563.Stone Game V/README_EN.md, solution/1500-1599/1563.Stone Game V/Solution.cpp, solution/1500-1599/1563.Stone Game V/Solution.go, solution/1500-1599/1563.Stone Game V/Solution.java, solution/1500-1599/1563.Stone Game V/Solution.py, solution/1500-1599/1563.Stone Game V/Solution.ts
=> feat: add solutions to lc problem: No.1563

solution/0000-0099/0048.Rotate Image/README.md, solution/0000-0099/0048.Rotate Image/README_EN.md, solution/0200-0299/0240.Search a 2D Matrix II/README.md, solution/0200-0299/0240.Search a 2D Matrix II/README_EN.md, solution/0200-0299/0240.Search a 2D Matrix II/Solution.js, solution/0200-0299/0240.Search a 2D Matrix II/Solution.ts, solution/0200-0299/0240.Search a 2D Matrix II/Solution2.rs
=> feat: add solutions to lc problem: No.240

solution/0100-0199/0160.Intersection of Two Linked Lists/README.md, solution/0100-0199/0160.Intersection of Two Linked Lists/README_EN.md, solution/0100-0199/0160.Intersection of Two Linked Lists/Solution.js, solution/0100-0199/0160.Intersection of Two Linked Lists/Solution.ts, solution/1300-1399/1366.Rank Teams by Votes/README.md, solution/1300-1399/1366.Rank Teams by Votes/README_EN.md, solution/1300-1399/1366.Rank Teams by Votes/Solution.cpp, solution/1300-1399/1366.Rank Teams by Votes/Solution.go, solution/1300-1399/1366.Rank Teams by Votes/Solution.java, solution/1300-1399/1366.Rank Teams by Votes/Solution.py, solution/1300-1399/1366.Rank Teams by Votes/Solution.rs, solution/1300-1399/1366.Rank Teams by Votes/Solution.ts
=> feat: add solutions to lc problem: No.1366

solution/0000-0099/0026.Remove Duplicates from Sorted Array/README.md, solution/0000-0099/0026.Remove Duplicates from Sorted Array/README_EN.md, solution/0000-0099/0026.Remove Duplicates from Sorted Array/Solution2.cpp, solution/0100-0199/0138.Copy List with Random Pointer/README.md, solution/0100-0199/0138.Copy List with Random Pointer/README_EN.md, solution/0100-0199/0138.Copy List with Random Pointer/Solution.cpp, solution/0100-0199/0138.Copy List with Random Pointer/Solution.cs, solution/0100-0199/0138.Copy List with Random Pointer/Solution.go, solution/0100-0199/0138.Copy List with Random Pointer/Solution.java, solution/0100-0199/0138.Copy List with Random Pointer/Solution.js, solution/0100-0199/0138.Copy List with Random Pointer/Solution.py, solution/0100-0199/0138.Copy List with Random Pointer/Solution.ts, solution/0100-0199/0138.Copy List with Random Pointer/Solution2.cpp, solution/0100-0199/0138.Copy List with Random Pointer/Solution2.cs, solution/0100-0199/0138.Copy List with Random Pointer/Solution2.go, solution/0100-0199/0138.Copy List with Random Pointer/Solution2.java, solution/0100-0199/0138.Copy List with Random Pointer/Solution2.py, solution/0100-0199/0138.Copy List with Random Pointer/Solution2.ts
No.0138.Copy List with Random Pointer
=> feat: add solutions to lc problem: No.0138

solution/0000-0099/0023.Merge k Sorted Lists/README.md, solution/0000-0099/0023.Merge k Sorted Lists/README_EN.md, solution/0000-0099/0023.Merge k Sorted Lists/Solution.js, solution/0000-0099/0023.Merge k Sorted Lists/Solution.ts, solution/0100-0199/0146.LRU Cache/README.md, solution/0100-0199/0146.LRU Cache/README_EN.md, solution/0100-0199/0146.LRU Cache/Solution.cpp, solution/0100-0199/0146.LRU Cache/Solution.cs, solution/0100-0199/0146.LRU Cache/Solution.go, solution/0100-0199/0146.LRU Cache/Solution.java, solution/0100-0199/0146.LRU Cache/Solution.js, solution/0100-0199/0146.LRU Cache/Solution.py, solution/0100-0199/0146.LRU Cache/Solution.ts, solution/0600-0699/0649.Dota2 Senate/README_EN.md
=> feat: add solutions to lc problem: No.0146

solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/README.md, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/README_EN.md, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.cpp, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.cs, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.go, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.java, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.js, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.py, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.rs, solution/0100-0199/0108.Convert Sorted Array to Binary Search Tree/Solution.ts
No.0108.Convert Sorted Array to Binary Search Tree
=> feat: add solutions to lc problem: No.0108

solution/0200-0299/0207.Course Schedule/README.md, solution/0200-0299/0207.Course Schedule/README_EN.md, solution/0200-0299/0207.Course Schedule/Solution.cpp, solution/0200-0299/0207.Course Schedule/Solution.cs, solution/0200-0299/0207.Course Schedule/Solution.go, solution/0200-0299/0207.Course Schedule/Solution.java, solution/0200-0299/0207.Course Schedule/Solution.py, solution/0200-0299/0207.Course Schedule/Solution.rs, solution/0200-0299/0207.Course Schedule/Solution.ts
=> feat: add solutions to lc problem: No.0207

solution/2200-2299/2241.Design an ATM Machine/README.md, solution/2200-2299/2241.Design an ATM Machine/README_EN.md, solution/2200-2299/2241.Design an ATM Machine/Solution.cpp, solution/2200-2299/2241.Design an ATM Machine/Solution.go, solution/2200-2299/2241.Design an ATM Machine/Solution.java, solution/2200-2299/2241.Design an ATM Machine/Solution.py, solution/2200-2299/2241.Design an ATM Machine/Solution.ts
=> feat: update solutions to lc problem: No.2241

solution/3400-3499/3411.Maximum Subarray With Equal Products/README.md, solution/3400-3499/3411.Maximum Subarray With Equal Products/README_EN.md, solution/3400-3499/3411.Maximum Subarray With Equal Products/Solution.cpp, solution/3400-3499/3411.Maximum Subarray With Equal Products/Solution.go, solution/3400-3499/3411.Maximum Subarray With Equal Products/Solution.java, solution/3400-3499/3411.Maximum Subarray With Equal Products/Solution.py
No.3411.Maximum Subarray With Equal Products
=> feat: add solutions to lc problem: No.3411

solution/3400-3499/3412.Find Mirror Score of a String/README.md, solution/3400-3499/3412.Find Mirror Score of a String/README_EN.md, solution/3400-3499/3412.Find Mirror Score of a String/Solution.cpp, solution/3400-3499/3412.Find Mirror Score of a String/Solution.go, solution/3400-3499/3412.Find Mirror Score of a String/Solution.java, solution/3400-3499/3412.Find Mirror Score of a String/Solution.py, solution/3400-3499/3412.Find Mirror Score of a String/Solution.ts
No.3412.Find Mirror Score of a String
=> feat: add solutions to lc problem: No.3412

solution/3300-3399/3377.Digit Operations to Make Two Integers Equal/README.md, solution/3300-3399/3377.Digit Operations to Make Two Integers Equal/README_EN.md, solution/3300-3399/3377.Digit Operations to Make Two Integers Equal/Solution.cpp, solution/3300-3399/3377.Digit Operations to Make Two Integers Equal/Solution.go, solution/3300-3399/3377.Digit Operations to Make Two Integers Equal/Solution.java, solution/3300-3399/3377.Digit Operations to Make Two Integers Equal/Solution.py
feat: add solution to lc problem: No. 3377
=> feat: add solution to lc problem: No. 3377

solution/2200-2299/2237.Count Positions on Street With Required Brightness/README.md, solution/2200-2299/2237.Count Positions on Street With Required Brightness/README_EN.md, solution/2200-2299/2237.Count Positions on Street With Required Brightness/Solution.cpp, solution/2200-2299/2237.Count Positions on Street With Required Brightness/Solution.go, solution/2200-2299/2237.Count Positions on Street With Required Brightness/Solution.java, solution/2200-2299/2237.Count Positions on Street With Required Brightness/Solution.py, solution/2200-2299/2237.Count Positions on Street With Required Brightness/Solution.ts, solution/2200-2299/2239.Find Closest Number to Zero/README_EN.md
No.2237.Count Positions on Street With Required Brightness
=> feat: add solutions to lc problem: No.2237

solution/0700-0799/0753.Cracking the Safe/README.md, solution/0700-0799/0753.Cracking the Safe/README_EN.md, solution/0700-0799/0753.Cracking the Safe/Solution.ts, solution/0700-0799/0754.Reach a Number/README.md, solution/0700-0799/0754.Reach a Number/README_EN.md, solution/0700-0799/0755.Pour Water/README_EN.md
=> feat: add solutions to lc problem: No.0753

solution/0500-0599/0563.Binary Tree Tilt/README_EN.md, solution/3400-3499/3421.Find Students Who Improved/README.md, solution/3400-3499/3421.Find Students Who Improved/README_EN.md, solution/3400-3499/3421.Find Students Who Improved/Solution.sql, solution/DATABASE_README.md, solution/DATABASE_README_EN.md, solution/README.md, solution/README_EN.md
No.3421.Find Students Who Improved
=> feat: add solutions to lc problem: No.3421

solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/README.md, solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/README_EN.md, solution/3400-3499/3422.Minimum Operations to Make Subarray Elements Equal/Solution.go
No.3422.Minimum Operations to Make Subarray Elements Equal
=> feat: add solutions to lc problem: No.3422

solution/0600-0699/0622.Design Circular Queue/README.md, solution/0600-0699/0622.Design Circular Queue/README_EN.md, solution/0600-0699/0622.Design Circular Queue/Solution.py, solution/0600-0699/0622.Design Circular Queue/Solution.rs, solution/0600-0699/0628.Maximum Product of Three Numbers/README.md, solution/0600-0699/0628.Maximum Product of Three Numbers/README_EN.md, solution/0600-0699/0629.K Inverse Pairs Array/README.md, solution/0600-0699/0629.K Inverse Pairs Array/README_EN.md, solution/0600-0699/0629.K Inverse Pairs Array/Solution.ts
=> feat: add solutions to lc problem: No.0622

solution/0500-0599/0554.Brick Wall/README.md, solution/0500-0599/0554.Brick Wall/README_EN.md, solution/0500-0599/0554.Brick Wall/Solution.cpp, solution/0500-0599/0554.Brick Wall/Solution.go, solution/0500-0599/0554.Brick Wall/Solution.java, solution/0500-0599/0554.Brick Wall/Solution.py, solution/0500-0599/0554.Brick Wall/Solution.ts
=> feat: add solutions to lc problem: No.0554

solution/0500-0599/0583.Delete Operation for Two Strings/README.md, solution/0500-0599/0583.Delete Operation for Two Strings/README_EN.md, solution/0500-0599/0583.Delete Operation for Two Strings/Solution.cpp, solution/0500-0599/0583.Delete Operation for Two Strings/Solution.go, solution/0500-0599/0583.Delete Operation for Two Strings/Solution.java, solution/0500-0599/0583.Delete Operation for Two Strings/Solution.py, solution/0500-0599/0583.Delete Operation for Two Strings/Solution.rs, solution/0500-0599/0583.Delete Operation for Two Strings/Solution.ts
No.0583.Delete Operation for Two Strings
=> feat: add solutions to lc problem: No.0583

solution/2200-2299/2219.Maximum Sum Score of Array/README.md, solution/2200-2299/2219.Maximum Sum Score of Array/README_EN.md, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.cpp, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.go, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.java, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.js, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.py, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.rs, solution/2200-2299/2219.Maximum Sum Score of Array/Solution.ts
No.2219.Maximum Sum Score of Array
=> feat: add solutions to lc problem: No.2219

solution/2200-2299/2229.Check if an Array Is Consecutive/README.md, solution/2200-2299/2229.Check if an Array Is Consecutive/README_EN.md, solution/2200-2299/2229.Check if an Array Is Consecutive/Solution.cpp, solution/2200-2299/2229.Check if an Array Is Consecutive/Solution.go, solution/2200-2299/2229.Check if an Array Is Consecutive/Solution.java, solution/2200-2299/2229.Check if an Array Is Consecutive/Solution.js, solution/2200-2299/2229.Check if an Array Is Consecutive/Solution.py, solution/2200-2299/2229.Check if an Array Is Consecutive/Solution.ts
No.2229.Check if an Array Is Consecutive
=> feat: add solutions to lc problem: No.2229

solution/2000-2099/2011.Final Value of Variable After Performing Operations/README.md, solution/2000-2099/2011.Final Value of Variable After Performing Operations/README_EN.md, solution/2000-2099/2011.Final Value of Variable After Performing Operations/Solution.cpp, solution/2000-2099/2011.Final Value of Variable After Performing Operations/Solution.js, solution/2000-2099/2011.Final Value of Variable After Performing Operations/Solution.ts, solution/2000-2099/2011.Final Value of Variable After Performing Operations/Solution2.ts, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/README.md, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/README_EN.md, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.cpp, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.go, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.java, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.js, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.py, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.rs, solution/2400-2499/2419.Longest Subarray With Maximum Bitwise AND/Solution.ts
No.2419.Longest Subarray With Maximum Bitwise AND
=> feat: add solutions to lc problem: No.2419

solution/1900-1999/1975.Maximum Matrix Sum/README.md, solution/1900-1999/1975.Maximum Matrix Sum/README_EN.md, solution/1900-1999/1975.Maximum Matrix Sum/Solution.cpp, solution/1900-1999/1975.Maximum Matrix Sum/Solution.go, solution/1900-1999/1975.Maximum Matrix Sum/Solution.java, solution/1900-1999/1975.Maximum Matrix Sum/Solution.py, solution/1900-1999/1975.Maximum Matrix Sum/Solution.rs, solution/1900-1999/1975.Maximum Matrix Sum/Solution.ts
=> feat: add solutions to lc problem: No.1975

solution/0600-0699/0680.Valid Palindrome II/README.md, solution/0600-0699/0680.Valid Palindrome II/README_EN.md, solution/0600-0699/0680.Valid Palindrome II/Solution.cpp, solution/0600-0699/0680.Valid Palindrome II/Solution.java, solution/0600-0699/0680.Valid Palindrome II/Solution.js, solution/0600-0699/0680.Valid Palindrome II/Solution.ts
=> feat: update solutions to lc problem: No.0680

solution/0000-0099/0009.Palindrome Number/README.md, solution/0000-0099/0009.Palindrome Number/README_EN.md, solution/0000-0099/0009.Palindrome Number/Solution.cs
=> feat: add csharp solution to lc problem: No.0009

solution/0700-0799/0729.My Calendar I/README_EN.md, solution/0700-0799/0734.Sentence Similarity/README.md, solution/0700-0799/0734.Sentence Similarity/README_EN.md, solution/0700-0799/0734.Sentence Similarity/Solution.cpp, solution/0700-0799/0734.Sentence Similarity/Solution.go, solution/0700-0799/0734.Sentence Similarity/Solution.java, solution/0700-0799/0734.Sentence Similarity/Solution.js, solution/0700-0799/0734.Sentence Similarity/Solution.py, solution/0700-0799/0734.Sentence Similarity/Solution.rs, solution/0700-0799/0734.Sentence Similarity/Solution.ts
=> feat: add solutions to lc problem: No.0734

lcp/LCP 67. 装饰树/README.md, lcp/LCP 67. 装饰树/Solution.swift
@yanglbme Please I sent you a couple of emails. I'd appreciate it if you can check and respond. Thanks
=> feat: add swift implementation to lcp problem: No.67

solution/1900-1999/1947.Maximum Compatibility Score Sum/README.md, solution/1900-1999/1947.Maximum Compatibility Score Sum/README_EN.md, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.cpp, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.go, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.java, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.js, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.py, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.rs, solution/1900-1999/1947.Maximum Compatibility Score Sum/Solution.ts
No.1947.Maximum Compatibility Score Sum
=> feat: add solutions to lc problem: No.1947

solution/0000-0099/0005.Longest Palindromic Substring/README.md, solution/0000-0099/0005.Longest Palindromic Substring/README_EN.md, solution/0000-0099/0005.Longest Palindromic Substring/Solution2.cs
No.0005.Longest Palindromic Substring
=> feat: add solution to lc problem: No.0005

solution/0000-0099/0024.Swap Nodes in Pairs/README.md, solution/0000-0099/0024.Swap Nodes in Pairs/README_EN.md, solution/0000-0099/0024.Swap Nodes in Pairs/Solution.cs, solution/0000-0099/0024.Swap Nodes in Pairs/Solution2.cs
=> feat: add solution to lc problem: No.0024

solution/1700-1799/1728.Cat and Mouse II/README.md, solution/1700-1799/1728.Cat and Mouse II/README_EN.md, solution/1700-1799/1728.Cat and Mouse II/Solution.cpp, solution/1700-1799/1728.Cat and Mouse II/Solution.go, solution/1700-1799/1728.Cat and Mouse II/Solution.java, solution/1700-1799/1728.Cat and Mouse II/Solution.py
=> feat: add solutions to lc problem: No.1728

solution/0000-0099/0027.Remove Element/README.md, solution/0000-0099/0027.Remove Element/README_EN.md, solution/0000-0099/0027.Remove Element/Solution.cs
=> feat: add solution to lc problem: No.0027

solution/1700-1799/1742.Maximum Number of Balls in a Box/README.md, solution/1700-1799/1742.Maximum Number of Balls in a Box/README_EN.md, solution/1700-1799/1742.Maximum Number of Balls in a Box/Solution.cs, solution/1700-1799/1742.Maximum Number of Balls in a Box/Solution.js, solution/1700-1799/1742.Maximum Number of Balls in a Box/Solution.rs
No.1742.Maximum Number of Balls in a Box
=> feat: add solutions to lc problem: No.1742

solution/1500-1599/1534.Count Good Triplets/README.md, solution/1500-1599/1534.Count Good Triplets/README_EN.md, solution/1500-1599/1534.Count Good Triplets/Solution.ts, solution/1500-1599/1552.Magnetic Force Between Two Balls/README.md, solution/1500-1599/1552.Magnetic Force Between Two Balls/README_EN.md, solution/1500-1599/1552.Magnetic Force Between Two Balls/Solution.cpp
No.1552.Magnetic Force Between Two Balls
=> feat: add solutions to lc problem: No.1552

solution/1200-1299/1288.Remove Covered Intervals/README.md, solution/1200-1299/1288.Remove Covered Intervals/README_EN.md, solution/1200-1299/1288.Remove Covered Intervals/Solution.cpp, solution/1200-1299/1288.Remove Covered Intervals/Solution.go, solution/1200-1299/1288.Remove Covered Intervals/Solution.java, solution/1200-1299/1288.Remove Covered Intervals/Solution.js, solution/1200-1299/1288.Remove Covered Intervals/Solution.py, solution/1200-1299/1288.Remove Covered Intervals/Solution.ts
No.1288.Remove Covered Intervals
=> feat: add solutions to lc problem: No.1288

solution/2000-2099/2063.Vowels of All Substrings/README.md, solution/2000-2099/2063.Vowels of All Substrings/README_EN.md, solution/2000-2099/2063.Vowels of All Substrings/Solution.js, solution/2000-2099/2063.Vowels of All Substrings/Solution.rs
No.2063.Vowels of All Substrings
=> feat: add solutions to lc problem: No.2063

solution/0000-0099/0034.Find First and Last Position of Element in Sorted Array/README.md, solution/0000-0099/0034.Find First and Last Position of Element in Sorted Array/README_EN.md, solution/0000-0099/0034.Find First and Last Position of Element in Sorted Array/Solution.cs
No.0034.Find First and Last Position of Element in Sorted Array
=> feat: add solution to lc problem: No.0034

solution/0700-0799/0720.Longest Word in Dictionary/README.md, solution/0700-0799/0720.Longest Word in Dictionary/README_EN.md, solution/0700-0799/0720.Longest Word in Dictionary/Solution.cpp, solution/0700-0799/0720.Longest Word in Dictionary/Solution.go, solution/0700-0799/0720.Longest Word in Dictionary/Solution.java, solution/0700-0799/0720.Longest Word in Dictionary/Solution.js, solution/0700-0799/0720.Longest Word in Dictionary/Solution.py, solution/0700-0799/0720.Longest Word in Dictionary/Solution.rs, solution/0700-0799/0720.Longest Word in Dictionary/Solution.ts
No.0720.Longest Word in Dictionary
=> feat: add solutions to lc problem: No.0720

solution/2900-2999/2992.Number of Self-Divisible Permutations/README.md, solution/2900-2999/2992.Number of Self-Divisible Permutations/README_EN.md, solution/2900-2999/2992.Number of Self-Divisible Permutations/Solution.py, solution/2900-2999/2992.Number of Self-Divisible Permutations/Solution2.py
如果对于每个 1 <= i <= n，满足 gcd(a[i], i) == 1，数组 nums 就是 自整除 的。
=> feat: update python3 solution to lc problem: No.2992

solution/0700-0799/0785.Is Graph Bipartite/README.md, solution/0700-0799/0785.Is Graph Bipartite/README_EN.md, solution/0700-0799/0785.Is Graph Bipartite/Solution.cpp, solution/0700-0799/0785.Is Graph Bipartite/Solution.go, solution/0700-0799/0785.Is Graph Bipartite/Solution.java, solution/0700-0799/0785.Is Graph Bipartite/Solution.py, solution/0700-0799/0785.Is Graph Bipartite/Solution.rs, solution/0700-0799/0785.Is Graph Bipartite/Solution.ts, solution/0700-0799/0785.Is Graph Bipartite/Solution2.cpp, solution/0700-0799/0785.Is Graph Bipartite/Solution2.go, solution/0700-0799/0785.Is Graph Bipartite/Solution2.java, solution/0700-0799/0785.Is Graph Bipartite/Solution2.py, solution/0700-0799/0785.Is Graph Bipartite/Solution2.rs, solution/0700-0799/0785.Is Graph Bipartite/Solution2.ts
=> feat: add solutions to lc problem: No.0785

solution/2300-2399/2353.Design a Food Rating System/README.md, solution/2300-2399/2353.Design a Food Rating System/README_EN.md, solution/2300-2399/2353.Design a Food Rating System/Solution.cpp, solution/2300-2399/2353.Design a Food Rating System/Solution.go, solution/2300-2399/2353.Design a Food Rating System/Solution.java, solution/2300-2399/2353.Design a Food Rating System/Solution.py
No.2353.Design a Food Rating System
=> feat: add solutions to lc problem: No.2353

solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/README.md, solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/README_EN.md, solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/Solution.cpp, solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/Solution.go, solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/Solution.java, solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/Solution.py, solution/3400-3499/3472.Longest Palindromic Subsequence After at Most K Operations/Solution.ts
No.3472.Longest Palindromic Subsequence After at Most K Operations
=> feat: add solutions to lc problem: No.3472

solution/1300-1399/1328.Break a Palindrome/README.md, solution/1300-1399/1328.Break a Palindrome/README_EN.md, solution/1300-1399/1328.Break a Palindrome/Solution.java, solution/1300-1399/1328.Break a Palindrome/Solution.rs
=> feat: add solutions to lc problem: No.1328

solution/3400-3499/3477.Fruits Into Baskets II/README.md, solution/3400-3499/3477.Fruits Into Baskets II/README_EN.md, solution/3400-3499/3477.Fruits Into Baskets II/Solution.cpp, solution/3400-3499/3477.Fruits Into Baskets II/Solution.go, solution/3400-3499/3477.Fruits Into Baskets II/Solution.java, solution/3400-3499/3477.Fruits Into Baskets II/Solution.py, solution/3400-3499/3477.Fruits Into Baskets II/Solution.ts
No.3477.Fruits Into Baskets II
=> feat: add solutions to lc problem: No.3477

solution/0200-0299/0278.First Bad Version/README.md, solution/0200-0299/0278.First Bad Version/README_EN.md, solution/0200-0299/0278.First Bad Version/Solution.cpp, solution/0200-0299/0278.First Bad Version/Solution.go, solution/0200-0299/0278.First Bad Version/Solution.java, solution/0200-0299/0278.First Bad Version/Solution.js, solution/0200-0299/0278.First Bad Version/Solution.py, solution/0200-0299/0278.First Bad Version/Solution.rs, solution/0200-0299/0278.First Bad Version/Solution.ts
=> feat: add solutions to lc problem: No.0278

solution/2200-2299/2272.Substring With Largest Variance/README.md, solution/2200-2299/2272.Substring With Largest Variance/README_EN.md, solution/2200-2299/2272.Substring With Largest Variance/Solution.cpp, solution/2200-2299/2272.Substring With Largest Variance/Solution.ts
No.2272.Substring With Largest Variance
=> feat: add solutions to lc problem: No.2272

solution/3300-3399/3340.Check Balanced String/README.md, solution/3300-3399/3340.Check Balanced String/README_EN.md, solution/3300-3399/3340.Check Balanced String/Solution.cs, solution/3300-3399/3340.Check Balanced String/Solution.js, solution/3300-3399/3340.Check Balanced String/Solution.php, solution/3300-3399/3340.Check Balanced String/Solution.rs, solution/3300-3399/3340.Check Balanced String/Solution.scala
=> feat: add solutions to lc problem: No.3340

solution/3400-3499/3488.Closest Equal Element Queries/README.md, solution/3400-3499/3488.Closest Equal Element Queries/README_EN.md, solution/3400-3499/3488.Closest Equal Element Queries/Solution.cpp, solution/3400-3499/3488.Closest Equal Element Queries/Solution.go, solution/3400-3499/3488.Closest Equal Element Queries/Solution.java, solution/3400-3499/3488.Closest Equal Element Queries/Solution.py, solution/3400-3499/3488.Closest Equal Element Queries/Solution.ts
No.3488.Closest Equal Element Queries
=> feat: add solutions to lc problem: No.3488

solution/3400-3499/3492.Maximum Containers on a Ship/README.md, solution/3400-3499/3492.Maximum Containers on a Ship/README_EN.md, solution/3400-3499/3492.Maximum Containers on a Ship/Solution.cpp, solution/3400-3499/3492.Maximum Containers on a Ship/Solution.go, solution/3400-3499/3492.Maximum Containers on a Ship/Solution.java, solution/3400-3499/3492.Maximum Containers on a Ship/Solution.py, solution/3400-3499/3492.Maximum Containers on a Ship/Solution.ts
No.3492.Maximum Containers on a Ship
=> feat: add solutions to lc problem: No.3492

solution/2200-2299/2255.Count Prefixes of a Given String/README.md, solution/2200-2299/2255.Count Prefixes of a Given String/README_EN.md, solution/2200-2299/2255.Count Prefixes of a Given String/Solution.cs, solution/2200-2299/2255.Count Prefixes of a Given String/Solution.rs
No.2255.Count Prefixes of a Given String
=> feat: add solutions to lc problem: No.2255

solution/3400-3499/3498.Reverse Degree of a String/README.md, solution/3400-3499/3498.Reverse Degree of a String/README_EN.md, solution/3400-3499/3498.Reverse Degree of a String/Solution.cpp, solution/3400-3499/3498.Reverse Degree of a String/Solution.go, solution/3400-3499/3498.Reverse Degree of a String/Solution.java, solution/3400-3499/3498.Reverse Degree of a String/Solution.py, solution/3400-3499/3498.Reverse Degree of a String/Solution.ts
No.3498.Reverse Degree of a String
=> feat: add solutions to lc problem: No.3498

solution/3500-3599/3500.Minimum Cost to Divide Array Into Subarrays/README_EN.md, solution/3500-3599/3501.Maximize Active Section with Trade II/README_EN.md, solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/README.md, solution/3500-3599/3503.Longest Palindrome After Substring Concatenation I/README_EN.md, solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/README.md, solution/3500-3599/3504.Longest Palindrome After Substring Concatenation II/README_EN.md, solution/3500-3599/3505.Minimum Operations to Make Elements Within K Subarrays Equal/README_EN.md
* No.3503.Longest Palindrome After Substring Concatenation I
* No.3504.Longest Palindrome After Substring Concatenation II
=> feat: update solutions to lc problems: No.3503,3504

solution/1100-1199/1137.N-th Tribonacci Number/README.md, solution/1100-1199/1137.N-th Tribonacci Number/README_EN.md, solution/1100-1199/1137.N-th Tribonacci Number/Solution.php, solution/1100-1199/1137.N-th Tribonacci Number/Solution.ts, solution/1100-1199/1137.N-th Tribonacci Number/Solution2.php, solution/1100-1199/1137.N-th Tribonacci Number/Solution2.ts
No.1137.N-th Tribonacci Number
=> feat: add solutions to lc problem: No.1137

solution/2900-2999/2999.Count the Number of Powerful Integers/README.md, solution/2900-2999/2999.Count the Number of Powerful Integers/README_EN.md, solution/2900-2999/2999.Count the Number of Powerful Integers/Solution.rs
No.2999.Count the Number of Powerful Integers
=> feat: add rust solution to lc problem: No.2999

solution/3500-3599/3511.Make a Positive Array/README.md, solution/3500-3599/3511.Make a Positive Array/README_EN.md, solution/3500-3599/3511.Make a Positive Array/Solution.cpp, solution/3500-3599/3511.Make a Positive Array/Solution.go, solution/3500-3599/3511.Make a Positive Array/Solution.java, solution/3500-3599/3511.Make a Positive Array/Solution.py, solution/3500-3599/3511.Make a Positive Array/Solution.ts
=> feat: add solutions to lc problem: No.3511

solution/1900-1999/1922.Count Good Numbers/README.md, solution/1900-1999/1922.Count Good Numbers/README_EN.md, solution/1900-1999/1922.Count Good Numbers/Solution.cpp, solution/1900-1999/1922.Count Good Numbers/Solution.java, solution/1900-1999/1922.Count Good Numbers/Solution.ts
=> feat: add solutions to lc problem: No.1922

solution/1500-1599/1534.Count Good Triplets/README.md, solution/1500-1599/1534.Count Good Triplets/README_EN.md, solution/1500-1599/1534.Count Good Triplets/Solution.cs, solution/1500-1599/1534.Count Good Triplets/Solution.rs
=> feat: add solutions to lc problem: No.1534

solution/3500-3599/3516.Find Closest Person/README.md, solution/3500-3599/3516.Find Closest Person/README_EN.md, solution/3500-3599/3516.Find Closest Person/Solution.cpp, solution/3500-3599/3516.Find Closest Person/Solution.go, solution/3500-3599/3516.Find Closest Person/Solution.java, solution/3500-3599/3516.Find Closest Person/Solution.py, solution/3500-3599/3516.Find Closest Person/Solution.ts
=> feat: add solutions to lc problem: No.3516

solution/2100-2199/2179.Count Good Triplets in an Array/README.md, solution/2100-2199/2179.Count Good Triplets in an Array/README_EN.md, solution/2100-2199/2179.Count Good Triplets in an Array/Solution.ts, solution/2100-2199/2179.Count Good Triplets in an Array/Solution2.go, solution/2100-2199/2179.Count Good Triplets in an Array/Solution2.py, solution/2100-2199/2179.Count Good Triplets in an Array/Solution2.ts
No.2179.Count Good Triplets in an Array
=> feat: add solutions to lc problem: No.2179

solution/3300-3399/3392.Count Subarrays of Length Three With a Condition/README.md, solution/3300-3399/3392.Count Subarrays of Length Three With a Condition/README_EN.md, solution/3300-3399/3392.Count Subarrays of Length Three With a Condition/Solution.rs
No.3392.Count Subarrays of Length Three With a Condition
=> feat: add rust solution to lc problem: No.3392

solution/2300-2399/2300.Successful Pairs of Spells and Potions/README.md, solution/2300-2399/2300.Successful Pairs of Spells and Potions/README_EN.md, solution/2300-2399/2300.Successful Pairs of Spells and Potions/Solution.rs
No.2300.Successful Pairs of Spells and Potions
=> feat: add rust solution to lc problem: No.2300

solution/1200-1299/1295.Find Numbers with Even Number of Digits/README.md, solution/1200-1299/1295.Find Numbers with Even Number of Digits/README_EN.md, solution/1200-1299/1295.Find Numbers with Even Number of Digits/Solution.rs, solution/1200-1299/1295.Find Numbers with Even Number of Digits/Soluton.cs
No.1295.Find Numbers with Even Number of Digits
=> feat: add solutions to lc problem: No.1295

solution/0700-0799/0790.Domino and Tromino Tiling/README.md, solution/0700-0799/0790.Domino and Tromino Tiling/README_EN.md, solution/0700-0799/0790.Domino and Tromino Tiling/Solution.cpp, solution/0700-0799/0790.Domino and Tromino Tiling/Solution.rs, solution/0700-0799/0790.Domino and Tromino Tiling/Solution.ts
No.0790.Domino and Tromino Tiling
=> feat: add solutions to lc problem: No.0790

solution/3300-3399/3335.Total Characters in String After Transformations I/README.md, solution/3300-3399/3335.Total Characters in String After Transformations I/README_EN.md, solution/3300-3399/3335.Total Characters in String After Transformations I/Solution.cpp, solution/3300-3399/3335.Total Characters in String After Transformations I/Solution.go, solution/3300-3399/3335.Total Characters in String After Transformations I/Solution.java, solution/3300-3399/3335.Total Characters in String After Transformations I/Solution.py, solution/3300-3399/3335.Total Characters in String After Transformations I/Solution.ts
No.3335.Total Characters in String After Transformations I
=> feat: add solutions to lc problem: No.3335

solution/3300-3399/3337.Total Characters in String After Transformations II/README.md, solution/3300-3399/3337.Total Characters in String After Transformations II/README_EN.md, solution/3300-3399/3337.Total Characters in String After Transformations II/Solution.java, solution/3300-3399/3337.Total Characters in String After Transformations II/Solution.py
No.3337.Total Characters in String After Transformations II
=> feat: add solutions to lc problem: No.3337

solution/0500-0599/0581.Shortest Unsorted Continuous Subarray/README.md, solution/0500-0599/0581.Shortest Unsorted Continuous Subarray/README_EN.md, solution/0500-0599/0581.Shortest Unsorted Continuous Subarray/Solution.rs, solution/0500-0599/0581.Shortest Unsorted Continuous Subarray/Solution2.rs
No.0581.Shortest Unsorted Continuous Subarray
=> feat: add rust solution to lc problem: No.0581

solution/2000-2099/2009.Minimum Number of Operations to Make Array Continuous/README.md, solution/2000-2099/2009.Minimum Number of Operations to Make Array Continuous/README_EN.md, solution/2000-2099/2009.Minimum Number of Operations to Make Array Continuous/Solution.ts, solution/2000-2099/2009.Minimum Number of Operations to Make Array Continuous/Solution2.rs, solution/2000-2099/2009.Minimum Number of Operations to Make Array Continuous/Solution2.ts
No.2009.Minimum Number of Operations to Make Array Continuous
=> feat: add solutions to lc problem: No.2009

solution/0000-0099/0002.Add Two Numbers/README.md, solution/0000-0099/0002.Add Two Numbers/README_EN.md, solution/0000-0099/0002.Add Two Numbers/Solution.c
I have  added the code in c language for problem 0002 
and also updated the readme file there
=> Solution of  0002 in c language and Readme file updated with all the terms

solution/3400-3499/3442.Maximum Difference Between Even and Odd Frequency I/README.md, solution/3400-3499/3442.Maximum Difference Between Even and Odd Frequency I/README_EN.md, solution/3400-3499/3442.Maximum Difference Between Even and Odd Frequency I/Solution.cs, solution/3400-3499/3442.Maximum Difference Between Even and Odd Frequency I/Solution.rs
No.3442.Maximum Difference Between Even and Odd Frequency I
=> feat: add solutions to lc problem: No.3442

solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/README.md, solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/README_EN.md, solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/Solution.cpp, solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/Solution.go, solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/Solution.java, solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/Solution.py, solution/3400-3499/3405.Count the Number of Arrays with K Matching Adjacent Elements/Solution.ts
No.3405.Count the Number of Arrays with K Matching Adjacent Elements
=> feat: add solutions to lc problem: No.3405

solution/3500-3599/3576.Transform Array to All Equal Elements/README.md, solution/3500-3599/3576.Transform Array to All Equal Elements/README_EN.md, solution/3500-3599/3576.Transform Array to All Equal Elements/Solution.cpp, solution/3500-3599/3576.Transform Array to All Equal Elements/Solution.go, solution/3500-3599/3576.Transform Array to All Equal Elements/Solution.java, solution/3500-3599/3576.Transform Array to All Equal Elements/Solution.py, solution/3500-3599/3576.Transform Array to All Equal Elements/Solution.ts
No.3576.Transform Array to All Equal Elements
=> feat: add solutions to lc problem: No.3576

solution/3500-3599/3580.Find Consistently Improving Employees/README.md, solution/3500-3599/3580.Find Consistently Improving Employees/README_EN.md, solution/3500-3599/3580.Find Consistently Improving Employees/Solution.py, solution/3500-3599/3580.Find Consistently Improving Employees/Solution.sql
No.3580.Find Consistently Improving Employees
=> feat: update solution to lc problem: No.3580

solution/3500-3599/3574.Maximize Subarray GCD Score/README.md, solution/3500-3599/3574.Maximize Subarray GCD Score/README_EN.md, solution/3500-3599/3574.Maximize Subarray GCD Score/Solution.cpp, solution/3500-3599/3574.Maximize Subarray GCD Score/Solution.go, solution/3500-3599/3574.Maximize Subarray GCD Score/Solution.java, solution/3500-3599/3574.Maximize Subarray GCD Score/Solution.py, solution/3500-3599/3574.Maximize Subarray GCD Score/Solution.ts
No.3574.Maximize Subarray GCD Score
=> feat: add solutions to lc problem: No.3574

solution/2600-2699/2616.Minimize the Maximum Difference of Pairs/README.md, solution/2600-2699/2616.Minimize the Maximum Difference of Pairs/README_EN.md, solution/2600-2699/2616.Minimize the Maximum Difference of Pairs/Solution.cs, solution/2600-2699/2616.Minimize the Maximum Difference of Pairs/Solution.php, solution/2600-2699/2616.Minimize the Maximum Difference of Pairs/Solution.swift
No.2616.Minimize the Maximum Difference of Pairs
=> feat: add solutions to lc problem: No.2616

solution/2600-2699/2614.Prime In Diagonal/README.md, solution/2600-2699/2614.Prime In Diagonal/README_EN.md, solution/2600-2699/2614.Prime In Diagonal/Solution.js, solution/2600-2699/2614.Prime In Diagonal/Solution.ts
=> feat: add solutions to lc problem: No.2614

solution/1500-1599/1517.Find Users With Valid E-Mails/README.md, solution/1500-1599/1517.Find Users With Valid E-Mails/README_EN.md, solution/1500-1599/1517.Find Users With Valid E-Mails/Solution.py, solution/1500-1599/1517.Find Users With Valid E-Mails/Solution.sql
=> fix: correct case-sensitivity issue in lc problem No.1517

solution/1400-1499/1432.Max Difference You Can Get From Changing an Integer/README.md, solution/1400-1499/1432.Max Difference You Can Get From Changing an Integer/README_EN.md, solution/1400-1499/1432.Max Difference You Can Get From Changing an Integer/Solution.rs, solution/1400-1499/1432.Max Difference You Can Get From Changing an Integer/Solution.ts
No.1432.Max Difference You Can Get From Changing an Integer
=> feat: add solutions to lc problem: No.1432

solution/2900-2999/2967.Minimum Cost to Make Array Equalindromic/README.md, solution/2900-2999/2967.Minimum Cost to Make Array Equalindromic/README_EN.md, solution/2900-2999/2967.Minimum Cost to Make Array Equalindromic/Solution.rs
No.2967.Minimum Cost to Make Array Equalindromic
=> feat: add rust solution to lc problem: No.2967

solution/3400-3499/3443.Maximum Manhattan Distance After K Changes/README.md, solution/3400-3499/3443.Maximum Manhattan Distance After K Changes/README_EN.md, solution/3400-3499/3443.Maximum Manhattan Distance After K Changes/Solution.rs
No.3443.Maximum Manhattan Distance After K Changes
=> feat: add rust solution to lc problem: No.3443

solution/0000-0099/0010.Regular Expression Matching/README.md, solution/0000-0099/0010.Regular Expression Matching/README_EN.md, solution/0000-0099/0010.Regular Expression Matching/Solution.php, solution/0000-0099/0010.Regular Expression Matching/Solution2.php
No.0010.Regular Expression Matching
=> feat: add php solution to lc problem: No.0010

solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/README.md, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/README_EN.md, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/Solution.cpp, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/Solution.ts, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/Solution2.ts
No.1751.Maximum Number of Events That Can Be Attended II
=> feat: add solutions to lc problem: No.1751

solution/2200-2299/2200.Find All K-Distant Indices in an Array/README.md, solution/2200-2299/2200.Find All K-Distant Indices in an Array/README_EN.md, solution/2200-2299/2200.Find All K-Distant Indices in an Array/Solution.rs, solution/2200-2299/2200.Find All K-Distant Indices in an Array/Solution2.rs, solution/2200-2299/2200.Find All K-Distant Indices in an Array/Solution3.rs
No.2200.Find All K-Distant Indices in an Array
=> feat: add rust solutions to lc problem: No.2200

solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/README.md, solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/README_EN.md, solution/2000-2099/2040.Kth Smallest Product of Two Sorted Arrays/Solution.rs
No.2040.Kth Smallest Product of Two Sorted Arrays
=> feat: add rust solution to lc problem: No.2040

solution/3500-3599/3598.Longest Common Prefix Between Adjacent Strings After Removals/README.md, solution/3500-3599/3598.Longest Common Prefix Between Adjacent Strings After Removals/README_EN.md, solution/3500-3599/3598.Longest Common Prefix Between Adjacent Strings After Removals/Solution.cpp, solution/3500-3599/3598.Longest Common Prefix Between Adjacent Strings After Removals/Solution.go, solution/3500-3599/3598.Longest Common Prefix Between Adjacent Strings After Removals/Solution.java, solution/3500-3599/3598.Longest Common Prefix Between Adjacent Strings After Removals/Solution.py
No.3598.Longest Common Prefix Between Adjacent Strings After Removals
=> feat: add solutions to lc problem: No.3598

solution/0500-0599/0594.Longest Harmonious Subsequence/README.md, solution/0500-0599/0594.Longest Harmonious Subsequence/README_EN.md, solution/0500-0599/0594.Longest Harmonious Subsequence/Solution.rs
No.0594.Longest Harmonious Subsequence
=> feat: add rust solution to lc problem: No.0594

solution/3300-3399/3304.Find the K-th Character in String Game I/README.md, solution/3300-3399/3304.Find the K-th Character in String Game I/README_EN.md, solution/3300-3399/3304.Find the K-th Character in String Game I/Solution.rs
No.3304.Find the K-th Character in String Game I
=> feat: add rust solution to lc problem: No.3304

solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/README.md, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/README_EN.md, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/Solution.rs, solution/1700-1799/1751.Maximum Number of Events That Can Be Attended II/Solution2.rs
No.1751.Maximum Number of Events That Can Be Attended II
=> feat: add rust solution to lc problem: No.1751

solution/0800-0899/0871.Minimum Number of Refueling Stops/README.md, solution/0800-0899/0871.Minimum Number of Refueling Stops/README_EN.md, solution/0800-0899/0871.Minimum Number of Refueling Stops/Solution.ts, solution/2100-2199/2163.Minimum Difference in Sums After Removal of Elements/README.md, solution/2100-2199/2163.Minimum Difference in Sums After Removal of Elements/README_EN.md, solution/2100-2199/2163.Minimum Difference in Sums After Removal of Elements/Solution.rs, solution/2100-2199/2163.Minimum Difference in Sums After Removal of Elements/Solution.ts
No.2163.Minimum Difference in Sums After Removal of Elements
=> feat: add solutions to lc problem: No.2163

solution/1000-1099/1046.Last Stone Weight/README.md, solution/1000-1099/1046.Last Stone Weight/README_EN.md, solution/1000-1099/1046.Last Stone Weight/Solution.js, solution/1000-1099/1046.Last Stone Weight/Solution.ts, solution/1300-1399/1354.Construct Target Array With Multiple Sums/README.md, solution/1300-1399/1354.Construct Target Array With Multiple Sums/README_EN.md, solution/1300-1399/1354.Construct Target Array With Multiple Sums/Solution.ts
* No.1046.Last Stone Weight
* No.1354.Construct Target Array With Multiple Sums
=> fix: update solutions to lc problems: No.1046,1354

solution/3600-3699/3619.Count Islands With Total Value Divisible by K/README.md, solution/3600-3699/3619.Count Islands With Total Value Divisible by K/README_EN.md, solution/3600-3699/3619.Count Islands With Total Value Divisible by K/Solution.cpp, solution/3600-3699/3619.Count Islands With Total Value Divisible by K/Solution.go, solution/3600-3699/3619.Count Islands With Total Value Divisible by K/Solution.java, solution/3600-3699/3619.Count Islands With Total Value Divisible by K/Solution.py, solution/3600-3699/3619.Count Islands With Total Value Divisible by K/Solution.ts
No.3619.Count Islands With Total Value Divisible by K
=> feat: add solutions to lc problem: No.3619

solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/README.md, solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/README_EN.md, solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/Solution.cpp, solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/Solution.go, solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/Solution.java, solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/Solution.py, solution/3600-3699/3622.Check Divisibility by Digit Sum and Product/Solution.ts
No.3622.Check Divisibility by Digit Sum and Product
=> feat: add solutions to lc problem: No.3622

solution/2600-2699/2683.Neighboring Bitwise XOR/README.md, solution/2600-2699/2683.Neighboring Bitwise XOR/README_EN.md, solution/2600-2699/2683.Neighboring Bitwise XOR/Solution.cs, solution/2600-2699/2683.Neighboring Bitwise XOR/Solution.js, solution/2600-2699/2683.Neighboring Bitwise XOR/Solution.rs
No.2683.Neighboring Bitwise XOR
=> feat: add solutions to lc problem: No.2683

solution/3400-3499/3479.Fruits Into Baskets III/README.md, solution/3400-3499/3479.Fruits Into Baskets III/README_EN.md, solution/3400-3499/3479.Fruits Into Baskets III/Solution.cpp, solution/3400-3499/3479.Fruits Into Baskets III/Solution.go, solution/3400-3499/3479.Fruits Into Baskets III/Solution.java, solution/3400-3499/3479.Fruits Into Baskets III/Solution.py, solution/3400-3499/3479.Fruits Into Baskets III/Solution.rs, solution/3400-3499/3479.Fruits Into Baskets III/Solution.ts
No.3479.Fruits Into Baskets III
=> feat: add solutions to lc problem: No.3479

solution/2700-2799/2787.Ways to Express an Integer as Sum of Powers/README.md, solution/2700-2799/2787.Ways to Express an Integer as Sum of Powers/README_EN.md, solution/2700-2799/2787.Ways to Express an Integer as Sum of Powers/Solution.rs, solution/2700-2799/2787.Ways to Express an Integer as Sum of Powers/Solution.ts
No.2787.Ways to Express an Integer as Sum of Powers
=> feat: add solutions to lc problem: No.2787

solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/README.md, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/README_EN.md, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/Solution.cpp, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/Solution.go, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/Solution.java, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/Solution.py, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/Solution.rs, solution/3300-3399/3363.Find the Maximum Number of Fruits Collected/Solution.ts
No.3363.Find the Maximum Number of Fruits Collected
=> feat: add solutions to lc problem: No.3363

solution/0800-0899/0808.Soup Servings/README.md, solution/0800-0899/0808.Soup Servings/README_EN.md, solution/0800-0899/0808.Soup Servings/Solution.cpp, solution/0800-0899/0808.Soup Servings/Solution.cs, solution/0800-0899/0808.Soup Servings/Solution.rs, solution/0800-0899/0808.Soup Servings/Solution.ts
=> feat: add solutions to lc problem: No.0808

solution/3600-3699/3644.Maximum K to Sort a Permutation/README.md, solution/3600-3699/3644.Maximum K to Sort a Permutation/README_EN.md, solution/3600-3699/3644.Maximum K to Sort a Permutation/Solution.cpp, solution/3600-3699/3644.Maximum K to Sort a Permutation/Solution.go, solution/3600-3699/3644.Maximum K to Sort a Permutation/Solution.java, solution/3600-3699/3644.Maximum K to Sort a Permutation/Solution.py, solution/3600-3699/3644.Maximum K to Sort a Permutation/Solution.ts
No.3644.Maximum K to Sort a Permutation
=> feat: add solutions to lc problem: No.3644

solution/3600-3699/3645.Maximum Total from Optimal Activation Order/README.md, solution/3600-3699/3645.Maximum Total from Optimal Activation Order/README_EN.md, solution/3600-3699/3645.Maximum Total from Optimal Activation Order/Solution.cpp, solution/3600-3699/3645.Maximum Total from Optimal Activation Order/Solution.go, solution/3600-3699/3645.Maximum Total from Optimal Activation Order/Solution.java, solution/3600-3699/3645.Maximum Total from Optimal Activation Order/Solution.py, solution/3600-3699/3645.Maximum Total from Optimal Activation Order/Solution.ts
No.3645.Maximum Total from Optimal Activation Order
=> feat: add solutions to lc problem: No.3645

solution/1700-1799/1780.Check if Number is a Sum of Powers of Three/README.md, solution/1700-1799/1780.Check if Number is a Sum of Powers of Three/README_EN.md, solution/1700-1799/1780.Check if Number is a Sum of Powers of Three/Solution.cs, solution/1700-1799/1780.Check if Number is a Sum of Powers of Three/Solution.rs
No.1780.Check if Number is a Sum of Powers of Three
=> feat: add solutions to lc problem: No.1780

solution/1700-1799/1781.Sum of Beauty of All Substrings/README.md, solution/1700-1799/1781.Sum of Beauty of All Substrings/README_EN.md, solution/1700-1799/1781.Sum of Beauty of All Substrings/Solution.rs, solution/1700-1799/1781.Sum of Beauty of All Substrings/Solution.ts
No.1781.Sum of Beauty of All Substrings
=> feat: add solutions to lc problem: No.1781

solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/README.md, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/README_EN.md, solution/3100-3199/3197.Find the Minimum Area to Cover All Ones II/Solution.cs
No.3197.Find the Minimum Area to Cover All Ones II
=> feat: add csharp solution to lc problem: No.3197

solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/README.md, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/README_EN.md, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution.rs, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution2.rs, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution3.cpp, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution3.go, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution3.java, solution/1400-1499/1493.Longest Subarray of 1's After Deleting One Element/Solution3.rs
No.1493.Longest Subarray of 1's After Deleting One Element
=> feat: add solutions to lc problem: No.1493

solution/3600-3699/3660.Jump Game IX/README.md, solution/3600-3699/3660.Jump Game IX/README_EN.md, solution/3600-3699/3660.Jump Game IX/Solution.cpp, solution/3600-3699/3660.Jump Game IX/Solution.go, solution/3600-3699/3660.Jump Game IX/Solution.java, solution/3600-3699/3660.Jump Game IX/Solution.py, solution/3600-3699/3660.Jump Game IX/Solution.ts
=> feat: add solutions to lc problem: No.3660

solution/3600-3699/3661.Maximum Walls Destroyed by Robots/README.md, solution/3600-3699/3661.Maximum Walls Destroyed by Robots/README_EN.md, solution/3600-3699/3661.Maximum Walls Destroyed by Robots/Solution.cpp, solution/3600-3699/3661.Maximum Walls Destroyed by Robots/Solution.go, solution/3600-3699/3661.Maximum Walls Destroyed by Robots/Solution.java, solution/3600-3699/3661.Maximum Walls Destroyed by Robots/Solution.py, solution/3600-3699/3661.Maximum Walls Destroyed by Robots/Solution.ts
No.3661.Maximum Walls Destroyed by Robots
=> feat: add solutions to lc problem: No.3661

solution/0400-0499/0498.Diagonal Traverse/README.md, solution/0400-0499/0498.Diagonal Traverse/README_EN.md, solution/0400-0499/0498.Diagonal Traverse/Solution.cpp, solution/0400-0499/0498.Diagonal Traverse/Solution.cs, solution/0400-0499/0498.Diagonal Traverse/Solution.go, solution/0400-0499/0498.Diagonal Traverse/Solution.rs, solution/0400-0499/0498.Diagonal Traverse/Solution.ts
=> feat: add solutions to lc problem: No.0498

solution/0000-0099/0036.Valid Sudoku/README.md, solution/0000-0099/0036.Valid Sudoku/README_EN.md, solution/0000-0099/0036.Valid Sudoku/Solution.cs, solution/0000-0099/0036.Valid Sudoku/Solution.php, solution/0000-0099/0036.Valid Sudoku/Solution.rs
=> feat: add solutions to lc problem: No.0036

solution/1700-1799/1792.Maximum Average Pass Ratio/README.md, solution/1700-1799/1792.Maximum Average Pass Ratio/README_EN.md, solution/1700-1799/1792.Maximum Average Pass Ratio/Solution.rs, solution/1700-1799/1792.Maximum Average Pass Ratio/Solution.ts, solution/3200-3299/3264.Final Array State After K Multiplication Operations I/README.md, solution/3200-3299/3264.Final Array State After K Multiplication Operations I/README_EN.md, solution/3200-3299/3264.Final Array State After K Multiplication Operations I/Solution.ts
No.1792.Maximum Average Pass Ratio
=> feat: add solutions to lc problem: No.1792

solution/0400-0499/0412.Fizz Buzz/README.md, solution/0400-0499/0412.Fizz Buzz/README_EN.md, solution/0400-0499/0412.Fizz Buzz/Solution.go
- improved solution added for 412
=> fix: solution of 412

solution/3400-3499/3408.Design Task Manager/README.md, solution/3400-3499/3408.Design Task Manager/README_EN.md, solution/3400-3499/3408.Design Task Manager/Solution.go, solution/3400-3499/3408.Design Task Manager/Solution.ts
=> feat: add solutions to lc problem: No.3408
